apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:kWoDPjlSVaNmURtq4L2RMESwcOPxp+EGKzZGduS4UAGLIDMbuu7De8E2AkJtXFWGc0dPevRf5Eh0MP+uGXmNOImeh4adWuIHq/7a5IAO6qB87xadHn19mOGmCxeHPavrWcr+UiHGWiJQAoQ/JnWXw+VuL6rljFLREEp8k74Y1tw=,iv:NG452N9NUvSyjd2IegLcSvlNDH3v/ck41TrZhLWCX5M=,tag:zcErIr6qgxUtDitydBpJ0w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFb0YyakI1MitteVVBNzBC
            YlVVMENmZlhweTJqQ2pGZi82OG5yblNsYmdVCkFEbCsxZGt2TzRFSTJtKzlFdEdz
            L0xJd3RnVXRIeU1DVWVqeUlZVUp3UmsKLS0tIENJaGMxUWhkQ2lQUWZkblRaNVdC
            NEVVM21CeWtWNlJQaW5scTJDN0tQWXcKz3OxFxt118m2OnvAxu5X9B+qn9W8RhtM
            6Cod5GTkZf1pDUGyE1FXXUugMx/I+fvmPvChMn3Bbo6qbBT/3+LA3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T07:41:41Z"
    mac: ENC[AES256_GCM,data:LEguzZoo5a7wffM4zuRaE2X/wxzXtBs+79INo/FIq6g+/4M/mqQyIn71Z07MZ4jD9hEp5QMA4DVpCvzrErp1cNZ2tsnXkne2Ym/J2Ck9C5Hp4RKjHeeKb55sjgLehKbi/QLGi0PELY0URirVP/i0aRGs6Df7AvfG/6bAwGOgZig=,iv:A9gjdf4/an9vrSDKWQgjTAAIM+cqYxA919nMpJQzg5c=,tag:2UcnM8wj4NJ+cvsEnrgxqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
