apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:SlJj4/zvhSefHlfxT1lOAlVsjiJnr8Ymg99bCEbrD2xzMB3jJJbK9nCh7LKGZ8K2T6IuIb2P7SabpxXh2a1ODwreUYGUEtktUjMiGCOyVptJu4G4WUwRNYidOCves7FMlpbMPzmsxUASWhf06365DpQPbM934w4lOcuktVoIQoM=,iv:WsMgWA6CXcXXPKztlwPJ0LYj8iFlywBQAuINyHeFDMw=,tag:UxpKwU5yqhIBee+0+xVbgg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZ20zUS8vYVpESDl3VlFM
            ZVlxMUZtUFZhSUF0aUU5Z2d3b1FvU0NRVGxRCmk1c0QxQUFkNElRQWora0xaN1pI
            bUtjZGZQcTl5dy9LT3NtT1lwSWdzbDQKLS0tIGNkcFpyRWpwWlM1eld4bXd0WWQ1
            TTkvWlFqU3VLSmpUYkJiUnRWNDh4ckkKMAz8hIi0Q3NYEnYPlslMzYgwpH1EpuKK
            82KElaJn+lNC05BawfPE/M+QN3UY40P3P+fSsvnVQ1O8M7Ep6v1LzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T09:08:48Z"
    mac: ENC[AES256_GCM,data:0EK+bHs75eYArNJz9QblsjuEUayBuLlNn0wrpl9w7BGDh/vaNsB+bHDys8qSjKqJJRUJUQ/aHsub0mJ0oaAvEmZqPoTcnSTnD1kWlcAzcb4hylX9Om23L7XlPqnL0LEe8k6fwwmsbNiZG9MUH2W6tzCJWPFoZZcxvLl6bboEsyA=,iv:qTHQ8we5ZyyRo1gmYnJTwBKc6odNaiL6qifaSlx2p9o=,tag:9OiKdHmHHhAqiQG4gUceGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
