apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:kbgL2cVcoeKxeg+8fkLACm0ot14Jb5yvEujCIdJJ0zrWgwIie4OhY2ivPUUSzGtvbYU2/9IXiIKEAnlAIz7K/wslaXt0Av2KEbC1DaQK+MnbPAjg5xok6VPXMOThxHOnam6SW/eT1YDcBweF8cwJfN+brj4kyV5Am1Tys2wPQPQ=,iv:ULJvYrEt/Nyjidqr9YIM/7hrqzCuMn3Vakvmb8XpiR8=,tag:X5oSvQXQuFN6U30DAgMAYQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubTlzZjk1TC84YmplYmVz
            TVpTVlVBc2VNVlQ4MjFnTktZTndRSlcrRGpjCmFLMHZOczFvNGVZS0dLSGlCd2tq
            VnVYamhqZXlTVW1Bb1hmZTJYcUJTVmsKLS0tIHdibnl6SHh1NStKaEdLVWNGRUtW
            SUMxTTR5OU54eFZUaVJSMHQ4TU9wNDgKioA68mTcI8Uz8QfnJ7pq0hnVkySmc/hp
            tdlZod3K/e8+ZM7RL0Uo6yBwi8ZO1u2uJyUqTAruLfY+nPcyO0/tTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T21:23:37Z"
    mac: ENC[AES256_GCM,data:NSP5AJKywTurseTfgAveNCk82gulbmWiUHuwUeF1EZDvnrjzBJtrfqmBTHWEmNnS1H4r9vKfsV/L4q2TAwcbOqUtJa8LhRBkZ4ZJ6PWbkby0grEA/p9xtqyQPFGCsoorgAkOdmJjFRagKrIuRekkEvVXtF56xDNVwmonMh2YY1s=,iv:hqX6VB4LzNtMsI8PpjB26shJFftyiTRsdadNFX2km+4=,tag:R3UQEofa5WNKJRXSNJkVFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
