apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:CkKIxK3HNuaDtUuSrUqc6k66WJqfQwJsq2jGPCqf/SCeSzwfzWhGV6o0jAqx6HcU+4X0nTf/wZQZC4Z+i6vyxZR/zyZD7WmzSAcC4peNsz3dDIFH8DztWlRv4l+nZQzD0KViYj24EsW2FK+ctF4f6JhS9cHACVwv5hHLUg4svQ8=,iv:6go9UisvcE5wCl9bNqdg0TzjzxbMZyFMLqAm7Dnos1s=,tag:hpbKQbkzKr+X8cSeSWwj6g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UGhLRlpvZWlGRkkyL21M
            eFFSb2VRWmFBNTVwN29oVHMxNkV1SmVBdlNZCjJwUi8xajFNcFdKR3pndnlnOXU5
            dmp4QmNSSk1Ba2p1TytaR2RGM2ZZQncKLS0tIFdJbENuRjFZTnBGNTVzOWpTdEZa
            MDlOVnZpSU1ITjNmcVUvRFNLa0ZFZlEKXkTmGxMLdVu1iR89HylPTUaBIwxxGIeq
            nYzKoN3i/602GM872znlVQ5f4HYBnVaiSiUSZDpFR4I5jgg1PMXMNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T11:03:22Z"
    mac: ENC[AES256_GCM,data:vOc9oJubHnhmO7mqIRulu9hP+D1Jbuc1TmuDNIzP3sL/aeqDuK7nNZDvJrwPuAyH05TifmFEsRh+LrWzIQ7F0L+q0KZzzdRVTBM+0gF9lwLXfx3oxYyfp7HAcsVewtur9fg6ddMMNvs3DmCQS+7XVxndbx7odJN7tRX95cI0MII=,iv:94prufIMpYkorquLUAXyd6B/DEkk6Z6laTf04ZooZg0=,tag:FwemAmcwou1Db0IGXPMkmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
