apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:vG5cDzRfP6HCBVH0xxkJcsc9p4GYKZOQ9hUC0UScoT2BzB6Hy8CzAFBEf79sDLrTWDN1o8+VAo7Kn/PFEL+B3/SrCIA5K59p5Ju3VsibUeSkSanADudDiFRZm+hUWK/MrwKh1AbGL7i9QaE0oiWxtLKOvrdcaTEbqctEI+J47t4=,iv:fNk02x5/ZXoE/SWh84Ff+K0gmx4Ty+9JLOKG4sJmaI4=,tag:l+JYqWvVZHBnscLsTNGoYQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cXhKMXFjNEtNeFpnQTdQ
            anRXL1AwbGRMUzUrRUM3aStNZXRyeUNuU1hjClNGT0VZM3VrWXpGaGtxYUl1WnF6
            UEhZbEx6Uzd1dTlsQU5oVEhLVVBpemcKLS0tIGVXVEw1ZGtDSU96VUtZUEFxN2NX
            bzBPbWpWM1IzTkQxQTVSdTVHbFhKQzAKw8xwzET8YbAnQzz9xf4nDklpxFDqh/RR
            x3tNCnt5752oLgQkI2+qRBNftu4EH2+7yx6AUMXlOZK6OgaQEDruJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T10:03:01Z"
    mac: ENC[AES256_GCM,data:n9UxidKHl1bLXWouTngBkQngcc0Y9WNpV2RwhCGq2CeCgJP8ZUjKab+9JQaT//BBtGNz91NTEfp2CospvjvkrOSXTYC+7vceym7p+EABgNdJZNMG2LRsGn3jQkpxrwO4UN67yviSfv/Kh2hY9XJsGqGPnDgMDIxZGdDmCKyJYrM=,iv:XrZhhpTmzfgktnytV26soQtZIqm2bSTBCwKqLp/xues=,tag:PY0WAuXoXFn+r7W2E5avRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
