apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:M/mgHV+b112fDmVSQlMtxno+E50exd8oTkUxreXDEuA9JIqMLnC3AJy4Z2S9wuY/xw/QjyEklrVJN2SvaaL1//wGw/N2Zryv9TwqAsIPm8aGIzQPLxrPVH00yRSFYbQHrMJpZqGsGl4HkP05fgdmspIBKvJOxvh2blJz6l5OVAY=,iv:jQIGrOAy9rNHVfVCb+3xOxalawklx5XsXjoXd4mddmU=,tag:9k5PnG2DSYHZc8+7e0DLHQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eDRzR25Eak9pS3ZOT1Rx
            ZFNQT09rQ3pqcTZKQjZoYS9rWVBETmMzVHhzCmhKTnJmWWlDeVNzNFloU2dOcWRB
            VHplcEZKTWlXb1N0QjRmNzd2a04welUKLS0tIGdhVlg1M0FFakRmb1lhWEl0WkI1
            TW5PZVZKZkljYUl4WGZYblJiSEdaWVUKVnoE/BxfyjfVuqphJG7mLbl0zKcwZWZU
            /MHJcYRpbEJvOUiZq6+IcVKGxlhsRDXmkp9ZEGoW84nQ6M4l3ZpnXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T09:07:01Z"
    mac: ENC[AES256_GCM,data:WYIhPJbCFnHo6PLQqGmsRgADcWgx1914msIf8qHst1aDrJSUAJaOKjDxt8xDLX7pxncHRYxrbDfUeaYzGdAprBMYNztKKy8jDkDa4afvuD6e1OC2GIhSKEthYLEoJoK3KhqAUzF/qfWvQ68TfVTZuy4q8pdnQ03bt0+5rMkMzks=,iv:S1WYFudzUYNh9auehBwK4CNhHbYgBPn6i0NUFSkyUwk=,tag:S1vMLyuln59Z5UqEnB46Ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
