apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:3XQToiN6GRWXZkRAnJWi5YzYFdMdlxuxul4Mqj6kWtALo4JaCDqP9z7d7dRLnUUS0TYFwfQ8QsylDst/Z8Pv7YafOAsC5wHEkzT3OwmefOzFhLAkuHBdN5UlGIHd0rbDti5kDJeIltxaRH/1j+qNqgqSeH9TwPPgBV9Pe+SD0nA=,iv:2gYjgL+UdrQP+ABuNYAdDN7TNWeKwnqxgV+42Um7Pqo=,tag:H9Lg+QYYiua6y42BmDYezQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkR1h1a0d6emtqTFlNRWRV
            UDhWZ1AvYm1ralQzdmhQRzB5Vk5INkpnaUZFCnpxVzhlMHV4L2UzN3IzR20rSjZ3
            TGtSalIwVUlJblhDaG1UTkN6VHJyYTgKLS0tIDVzTnZPWXpkZzF2Q0ZlSlNqSllG
            K3VxeEtxdXdwVThtbWtsaUJTUVdlZGsK0x5l669QrSmAceKzvYAkVlb31DxqJptC
            47syeahpW4IfOldBYDzrZJnq+1saHfkkodzeaTh0ro5T/3GNsOI2+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T10:07:11Z"
    mac: ENC[AES256_GCM,data:ZF/79D+5j2d4A9nVshSZDxkDmVDSRlQDq43E571yc6gBdsfnx9d8p3U4wVWB6YdWUjSpEblozVwbtcnq3bBZw5HZYrQL+sbN1aO1VNlHM18N+cS+n8wh77zpZn9vN85hJiWjbrPtLWKIgtCkO6APteetF/h9xI73IEX69ATWRJ8=,iv:yXW7YJQCzbB2fMOMom7UsORJIbAG/axxwc8AMiuTqc4=,tag:mEw2mkHZy5xYfJHES59V6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
