apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:WDW6NpZFBXfwW6Kp0UaPyqXj7yxozyEvaSVgY3fLlBFXVXM2YpjRAUBCoz9bve2Xws4NuDs1r0vYAMmB/hX0Ca4WNceIGI0erB2bUghvamqPTk0hries6l8OA6aeuvXJyH5sazq7gOjnV654nuzC+Oc3qmQ2aa9ORlqOJvG/er4=,iv:GB+ArxLrczlt4G7AfFGbqjsECKyfoW8lgynL53GWiuY=,tag:y/c3vwBLM0mwWQ8zzeswAQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YkNXVlFYSlZ5cmVWR3Vx
            R3FOZnRCVzZ4bnFNRENud2ozWlJaZUVmSFM0CjZYaGdWR1RRQTBodnV6bndWcWJa
            T1pRTVA3eTFXMis0OU15SmdLRXk2VWsKLS0tIHJUenhzbDllWCtNaEljQnMxNXdT
            cWowWkV5WGhkNGpzelRuWUllZ1Yvc1EK5LvfSZEFsdboosWdmodoBA/CRueouq+N
            n9PtNRxZNxSGJinWca0UBX1cvrrKswZqBNeIr321zaLpsjb5wZiS1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T08:11:41Z"
    mac: ENC[AES256_GCM,data:loL58xFstLwKMBZl79a7NUeVSWyj+CVNeTV9AkaWu8VYtQ/NM5MH1XI0ZkvPBxaOzAyTdXzBT1IJ+nELDvxUfBQBNmivpZCvlPAaifNvJCju11N5RRQ2RivZi7LDafSk58WLQ49aEgsHXYuOH2TilAHaB9iu/IX6c25wFZbJPzk=,iv:uI2HjvqT9GaxPWBhTwtosJ+GXF41d9dbjy+R5uJ9T00=,tag:z5knSn+TxZ1C44PK7La3kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
