apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:wz4ibnvPJyS+LDLd0/bHLlGFzrPLYhWqcSjP9XCamyrF4PDdJJTEiQ6zbNYwbR1viS7IPTjhw+4nBJ24zcl6X1S+7RAIMikJs/Idb7NgTW6uaK33kCc+SDIaCtybY4FU3EM94/NfiQg8QX9xMhMO4yAiO2p+gndCPlYJqXC0S6g=,iv:+5l0w4riQ9iev1g+p5HDw/idpWjgZussqHek+FoZFvA=,tag:7euq8dXUrQ7oMd9DDBkYCw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4akYrNzRWeS9LZnc3ditK
            QlV1amUrNTgxRXNBKzhEUzhYK2U4YVNHZzFBCjNBUFFiVWNSdlM5R0V1TlJrbEpj
            SkdzYlVvYWJFVlgySXY3WDI5MEpqdmsKLS0tIEtlcVh4S1NrbGpHUUsvcjdwWVhG
            cU0rN0EwbXZFZi9RckVYOHhId0VrZjQKyykPLJvZYug96O9Y5BQAtJNOVKYDochk
            DnMhOWF9m6wd/fZaJVlr6k9Hr5AKnCJPq2KDxfDiiuGZejP0oBjyIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T10:31:15Z"
    mac: ENC[AES256_GCM,data:MQxkQKj/8D8AaQbXRpqzqkJlkkX0h8QCmj125azTP7brrFwpjKnuxHs8rwlN7Hv21zc+NGjIs1Uyt2+wxgVZviinBBB3it+gm83gCKE4ddeadTdF0OJjwKPdEdT5ylSSZ/Z1GTisgk2mD/zP6KHT2l++olpOvbcukWahl4e4+kg=,iv:0dXvhFFLjXRVglIBY9RLK8qrzrQuKRrRgi3t044b3Nc=,tag:S9uihZSiRV9rCsp2Svaj6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
