apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:teLsImQn6OcmEz7a9w5XtIS2kHPCCSpOrogzaM6ThgPeMQrwoAM0crn2bnsp9JQ3U2SLJm4crRqECQLa0evGzCD1WGaYnqMGVCl6g0tFEwtjx8QYkaKnsAWiHbkb3PC/OrIJLaaI4P+7yHtAsfm919IrH+8DPtu4f+UZoQ/AYEM=,iv:fEW/mtnBorBzaGXqaNa4u4cXisoucvRk75vdPTo/xS8=,tag:xqc+3+u6vzykiRAN3uPFUw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVlA5ZFVUZEh6OGNqTy93
            UUdNdzhCc1JqT2kydWNJWVhna2I0ZnEvcFZVCkpxa2lXL01MWmpFRjg5dHRUR3U3
            c3NUZzYxZHdFeW9Xa2JDWE9PMEpUR00KLS0tIGt4b3FNME13ckZKMTJIMlBaWjBD
            VzdqRTIzeXFTUGNDaW1hQW1KNW8yYncK8tubKyK6cjL7iS/KacYTjdPfAtojqG29
            6mE0eTgIWVe1CK5vJhGN2/XeyRol/wRKDv0A0cyp5JFauN+wo7VLoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T07:02:11Z"
    mac: ENC[AES256_GCM,data:ezA0+FOuDM3JJVekkbl8AtISbULVhZr3NGoXzMO98CoZcqRaND3q5K0YgXqoxGZDJSoKFVXm0OmyC5jxzU923pS2bZaALKRq8h7GlAz/4Ug+njwzsaFrxz5iak2neLF+A0Gyc4jfDH78gd5yOeBHY61hIG7pAf9S+9XfLU/E2vk=,iv:LIxGIVrYlJcozjs+NnTzTa/ICE2df132ASYQN8YjGIY=,tag:2yEPo80Rzs/wAxRzpnRq5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
