apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:m3EXJf2UvWN8xWR5RefklDITNqMtTTf/KBftw0iHfDOnqgV2URZcYsFtUIFF5ToVOo+HPSfryDwWyT0n3LKeLPz+0LeNpeA2U60Wsn7am6Ab1PtO4hUiCaK4pPT/lI8xPI+KBkPbFlABjI4uT1HqkMEnUK5YIuC6FUFTazz8I00=,iv:pv5Fq3M2Q3D6QNiIUhvx/Xy6nHYHKSgu17cgBjcDzCU=,tag:BLZqDyprTiVUmUfUgVSmUw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUGNmQXNSVm1XTGFvMmh5
            QU5paFpQUHBPT28vNDBMTncxNXplZnNXc3o0ClEyMmlaMDVIZ2JjWjZITWFWV3Zs
            S1FFMjZJNTlPejB5c3R3cVl0QkdFNk0KLS0tIEdZcFRacG8rSnhpNDNLcTlUYTFU
            NmRIZnBQZXdRZzZXL2hyM2xjY3p6NUkKxCS/X4V7ctX0yVZLJnfsUvVXy3rifIxM
            1W3nh/TKPON/Sp84s0Jyo/ppxpyFqo4T4MIaZV1u+F2J1kpMcKBh0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T11:07:34Z"
    mac: ENC[AES256_GCM,data:EXGmjA8vvKg4FA4giiLlIQaVgKoFc+T+PMh107xOvnksItkqMQ8XiQb+VbThA3aAFLQD8a6IyT1HHSd++hQBdicq1r3aCLL+gVd2e8ghMZmpkP/NcXWJ3FFx97mouIrzxcGVONCzNMosMharFd81jh0aEyRKobyRWb88+tzFZcc=,iv:XcUljjQZTc9F4rt7Zi6gHyx6ffQ+D3W68XyfHcS35XI=,tag:aFKT+ezUAo1zgfuhArmY9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
