apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:CoUM+aGmjPvLksUJskbhrDZLr/wOn+13r6jBqVLQJ9I01jjmnESeKLspJrbsaA0kZ3gBxgIBstjzDPvqWPQf6kYiuUBp45DK27e9Ml0E0nNzsGWPLgmxBtRGto3T0Iy1J+TrV/BFWlBLFnBgRrKcSIY/kNJYAhtUM14IeYBIn9c=,iv:sznMsXah4uDKCosofVnKFDIZHXgkaBiPzxjKOp9SW/A=,tag:P3Z7Lw3/+qDI3LhhoHx5Qw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NU9JMHYybFo4cG5JSExF
            Y1VBSlMvMWpIWER4MW9SdmJkMzBFd0xxaXlRCnhrQXZwdnEwMHJ2eFh6aDR1bzRL
            MU5sOVhxc0U3NUNBRStscnNjb2ZJOW8KLS0tIDdQSXEzVlZUbzFIZDBuc0V2MTlE
            QmJiOTU3aVA1NFhRMGpYVi9VN0dZU28K1D1yYlyoXPutqvP/ii/3bjQ7HukjLOn3
            7+GVkR+sIUDi0dFMq+Vqo0iWE3Hoodsg7S57B6F2tNEzdeQcGFdsQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T09:06:56Z"
    mac: ENC[AES256_GCM,data:8v4onti1AQCy2D7m5YbsJ/JyE77ivC7ZJR8+3e+z66zUJwsQoH6EeqmEU9OkI5/wxVXY/tUrxq3of2aMPKJF0D/mkp1Wh8zqBkIQXfD7tCecGZTr4k6c72AkCLfDcd0GnDV1p6P7YlgSBRVGc+HrLozNbduzpTY5ZJm04TGNgJs=,iv:hkVPvxlMyM99nIaP48LhB6QLP3I8wqEfp9zTIfDnl0k=,tag:6ODZ5unLd74xZw6nbTSvJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
