apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:XOojYoUFb8G6kr+QxZoazvMDDZyvHgdAqnQj5yL9UrCvIEccSdTVrSOpcS+pznKll3jcEhbn7wJAMo4CYaJXsCcZsFs3pLQXGbaUrtaiVYTssHIeW3H0H+zYfbDN2p3zfVMjhJ7i4rB9MMCXdBUYBM70U+NxsUx3qhPSwGoswFM=,iv:nyBGt37LxMv9Ecu1qZbYz7TT/wZj926mqHD2Tlw+fQY=,tag:TI2IoeFa91kMDI1Cri5pJw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVURKTmZQK29Uekw0OUxZ
            aXU3bm9JRU5wMUFWSVhrTFcxNlgzNDc2UHdNCi9LSHlVaHhDREdrRDZad0RaRXJD
            VVZiWmJBendkT1ZVRzhEdUN3c2MyODgKLS0tIHRZYWNJSVdvZ3orcW0wMUFpNS9U
            WjA3cHlJazFyNWh5Q29GMmRDWWZ3NW8KaYMJyjKYSp7UfiJH/VS2LG0O67Z7AzSm
            2zcJg58mmhcD7Xo8+64/YW+EeOQVQRYwYVNGh6Hsmc8hYOaIxKdJ4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:21:01Z"
    mac: ENC[AES256_GCM,data:ZEzw8+8vCbVWly8gX82S2npWaJEgj4+tfxs5ng9kvvMQV93Nuh0hzxaRviMSMcuBFVgr3f6Ndkey+CWvCprLHsS1P+6F5nZRhx6JsvrWD2PmXK1OekJkTtyYL2UVxDK4GoAnUpcaZ5R9LhS5yDEqWBJbBdO+qlgesu68wOvZjvE=,iv:txYHbjkwjRNlLrWhISPLVavUAgEqDdNhntJpu0DgLPM=,tag:uTC4rPjg6mtUhHIL0xS2nA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
