apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:ZcFWYa5L2VO0F0Dnu9AWGRTQEX+c4k0OKnfrENMe+WNIr2jJi+BiRCywztu16IJsTldlGxTtkInWLumOM3CUCCoGHkYqTXUlsIqRLPm31J9xeg/gEP2uxfu9NZ/CrR1UkGMFqhAXrNg5toVpOuCpbZgDmdV1S0yQhCkaXN5/t+4=,iv:+F9hVFfX53Q5LoSQB+kkFBBCV4ap+n4VV5RTGBXbMiI=,tag:olb7BmePjwlG2aiupjCehw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Snh4OEIwSEY4T0JGVldG
            WHJBWlVaTkZ3V3B2MVZPdFhvU05sM1R4OUdJCkE4b1JoOS9GemFJYVZ2UEY2cGc4
            Rjdxdk94a3VjcnpIbUFoUjFxMXVmcE0KLS0tIHdTclFFak5nc3BFR1R5bjYvaG1x
            MERPSGJvRE42aDEwOUUxcGhFUkw1VjAKY0U+FiKX4VsZ/fQQhDGh+G978j3IWaCv
            rvVM5+h/ZL8+guc6sF6ZsNrJ5mA6kvr4dtjgnu6Urb4hBUnYG8DPcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T09:25:22Z"
    mac: ENC[AES256_GCM,data:ApUxBZHsacYm8U9bDta+kwJ4+h0wJM8sV3sxALkPVjRCLX2x8WLPDP//+tU4XOIJTlDthsMu732pwmVmDpZaN81X+KYPya9OafI4gU/1XEkRDE/c5vCuQEzcXGp1Zke8oR46oiTpKPtlzCL2PvemaeI/hklps1if/u70y37unn8=,iv:cmJJhpUTyVKsxYH/ez2VgLs8/L+gxvcFG1HrbdZ0464=,tag:W9+ieH6NCNWJXHYz/n9fEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
