apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:hQxapOQ1NXSsEV5miZGppahAAo4P9LHlYfmZce5+MNClXFWnWVYWZBKftNgQ4Yon5rIwIorEFtjFGNCeqNdNC1HAQQqe6Oepy0eq6xTWhLIZteZtpywDFMyvqjIDh5p+CZjYHdiBSA7fMW5wF5ekI+7YWtC3WNaIMLZvYb+cmb4=,iv:6k2k2TljOLkilXJCV/8aXV0djA7Hm3i3RZIUdgY4xQ8=,tag:eNXPvoO1jqEpGoZ2lGJDUg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaHZqeW16WlNVTjc1Z1BE
            dUNPaFIzOFJva2V0dXZaUTA4UEYrampEekNVCkJKU3VTank2NkNFSFRUSVJubjEy
            WjkxSUNsZmkzL0xIUWN3dmw1emUyUTAKLS0tIFBIaVpCSlhLMmhzNGMwWGhWbk1Z
            UkZUMVl1TmYyM1VoTjBGT0Yxd0VtZ0kKBDCc33ipNLuljZ2zigTXTaOZZU7j+GNP
            qgn/61T6ctzbyAFpQJSFQTF8pKDdEpQlXd3qVXauv8txhSepICqo9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T07:29:19Z"
    mac: ENC[AES256_GCM,data:ZV5ponRD/3qo0WU6QTF8/M8oWNLAq+eTqM1/oTDsrv5FQakCZYO0zUqdFWM4yveHTmb29BaZaGq5uATDzR5blSwmg6MN4zvJzQ84FNEBJ5pdmJvbNkxdtF5qa4OYH0YC4qBdBwXTY8+ySox95BAS3KYLmhMUnjBY/1vTyvTdvqk=,iv:qvSavhX6+lW8wDq83OuQGVUkSOG20pZDojjT0r9eAyk=,tag:oMgXhhtf0Anr9Rjmr0Xtbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
