apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:VTnCW1jxmL5ZZrv+QQyfmz6JzVGvrfpW2RxANrKVI27EmPPVoNuHYVZunu1I8chPju/gk4KgS6cJW1wFj83Hpbl7F81wtz3XPSnnF3qzevPFXJomfbb/0gXtMiHn0poBZShyF1k8SHQxTGtP94wkS3K7OhNSvm93j+XigFfFjrU=,iv:0v+fXk//PDv59s8R0R1nljvDq/y5aHCrtI/HLZCS4os=,tag:7lDEq7ynTpmcuYTycitjgQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNkxPY2F1ZUZPVmdjVmZH
            YWF3djVJRVdnQSsxSkZ6aVppenh0TXdXenhNCll0MTYvaHhrMzd4cDV2Y0RseGxt
            aEVTc0R2L2NyaWxuVy9SNU9kd0lTZm8KLS0tIE92R1U1V2dZbzNaeU1HNnVtL3Nl
            UWFaM2NnTmxFZkM1RlVyRVhxUkpZbG8KPqfFn6uHcZar3FFZL6WPFdZ68yIqTjE9
            60rn9IG4z2Ljm3DpclkqWF0KdAFDZtnYlqiTCF44z63on+VSolxg/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T09:19:03Z"
    mac: ENC[AES256_GCM,data:HcmPa2JGtXfPhQ+sRAZgepnWYmCdrdxSoT5T6t/BhvSKeM6nTkZiD6RsInp6VlBqfjIqaxE+tTOgZ42OkRfjZgY1bdJtVmCjaQVIv6GiiyprXWlUpgWD1vNs8LK2v4P+Jsw1ussHe/JLll2Z5WW1laB+uNejRcBXVgTrdvJKYis=,iv:mn+6tREDEUoG6zTAydYh9fQSpgWKktmuB6m60+qwcdk=,tag:3hrqgkH3EQuCrvsg9SVPjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
