apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:hQGOJqJXpwOfFG3oo6Lo4YrkJjI4rCFWjiW256T1sAkxAPtoH/1ucZ9zWLCwDE6JDiVoqBkePitnwclWmue8SKT23m4QjnpEdPJ0NY21t5O+AkYsqw1MYnghSiZLi3Pa1nM4Qx+zsqewGQe5QIrhsl07IRCzcWE61aKnhzLUfto=,iv:EqeHGUqsSDVGFgg0q8jxYh851RvdnrvhApgSoUIaAzg=,tag:uH5j53qWGlNI/Z1rd5UwVA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUFlUQmo0TUZRcExXYnNM
            M09RRlRKQWFHdkoxSkIwVk5tc1B4MmR0dkZvClJsbTUxV3d0bytaMlNwWUlkS2dX
            VWhKczZYaDJMLzRUb3hKc0c3TStrUm8KLS0tIFhISmdkbHdtTXhMZ1QvSXB6K1ZP
            ZzJyYk4yZmNqRnFBY0cxZllqR2NPK3cKc7QCl0FEQSw8fx7yRt5gEdbUqtNb4qat
            1icU6wkBngjmrYpc2lpAUshUW+eAN9MVFdyiPATjiudMOxwB4Rn5vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T07:48:51Z"
    mac: ENC[AES256_GCM,data:Y49Syjk6QPO1FHRp2ddjy7zRkxtiMzbm+Aq5CXPbZ+vShNl/nDxlmOYah7I7mj9E6cwTz7s3jmlS8i4a6VbGkFmOAHBNplOWAQtQYcC7a6S9siv4IV/mkEdWX+6htDJI80i8LC3ukZEsKzxRq6bOEb8Xz+jXKIeD5ZRl8I7in2Y=,iv:/85f2ww6PyLMCy+/Kxmd+F841V6Ffst6DKAq05k2j2o=,tag:9tB6QRs5VaHxpbYba1JMWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
