apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:DGVyyUSEJfWavg8uTgE9LHe97JrrRbw7qkxOXqeoIMgGeNKVMT9dSDkV0+UNN7/cQA/0BZgVdlSMp0zDfUA6do4ad3STtgseg+Dsn+kdmVNOqnlMAnSJgMSONkV9uzYdROAVgVZcz8/7WYyimMXi1nVE2BcgKsEYrtul1Rr+9JM=,iv:T6jMWYgWmYoaFiqmpVOidLwoCVa4R6DE9byaRFJr11o=,tag:i4vLukaM1mezTy18UENYkg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWnFOOFB2am1id3JzTnpW
            SjRKYndXZ1V4Ykk1UG92d0p2MVBsdy8rQTNzCkhyV3o5S3F1T3JQOS9TVzNLM2F6
            T0htc1BYaVUrWVZLemRUKzdYL0dFb0EKLS0tIHdsaitZbmgyRkRYK3pGTVBBVkJy
            dE1uNlBlOWtYQ1JTNHVCTS80Sko1SVkKhFH9ow9i1TLeC9aqfltwusP1Gv+/M8+6
            jo1NUsFKnmesWixv/bjiRXZg7wSV2B2iaoEbePbfaarVs7dbhAB5pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T10:24:49Z"
    mac: ENC[AES256_GCM,data:l4/lfJvIAKcKPWCmJfWUdYo8yTgZL2BuhvlHgJz0k/p5J0KcF1a0cL4imdXlL6oKhpuNDpUTtssAHTSy8RR41kdZVwvM5PRVG42AOelLCDHEF7nWjKlrJyTGiockSSzDMLR96FgyVzDx0iLmu9+QzIOn6Jg5IiMIlAf3Tf7s3YA=,iv:jNp8ByapuAo0Haeh675kKtdFdKN9AJrVN5BKlfZCAHo=,tag:A8CINMS70mUydhULtqfK9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
