apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:hA6Ggd+g8XEIv99VIfHfxyocNDnPUmFRPO1JP5+8p2oXyAAZ5Nit6f9m3DHTje+Lf3i7I42re+q1OyHO81+Nd6VvbmjgOZgKeGjkRUof3zSSyWkdWSSLuKNkgUVfv+dlu2pJlisbhrY1biYWi3qB56tsc1bNN155KKG9208Cnqc=,iv:U1PUc0TX2llm6dZ/qtRJIaeYf7VsSub6bQRMB1hE3GQ=,tag:rGkZKEulPZsZteNDozW80A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMU9ZU2FqV2cxY0FhNzRB
            NnhDZVJGRXlLOXgwMVFIYm41d3JZZjM5bkE4CitOa2RQVEJTd2poM1pPU3RkRXQ0
            eWdrMFhrSnVrQ0QwNWlEaHlIUlJzNEUKLS0tIE1NNU01SlB3RlU0YjZidE1LOWpD
            T3BXU2RGMzhrMTVaSTU1QncxRTNWVE0Kg4pUiQbKYSLXWQeKOJ472VGR0wOIVYLW
            YKuhT+7YBdhELxq+dxdRF3AOgfX7TWNPaSG0gwhIyoVTbD1f3eFUXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T11:27:11Z"
    mac: ENC[AES256_GCM,data:dKRJ/qGsEdC5wjd0ofTmPkXGT4P3mSrn1km3KuruqVke/XbqeyPxOz3nHv0jlIUJGH9rjZi0ZtN21rzjB95xzWHMiOOrkRRA4FlzEDyx+ILAaPqsgLSuRJ1NIZLG0nCriwM6FZhaqtxRnTXdzYcLjjj8FHm0ZuAOfFyUWo4aRUc=,iv:d++9tNPPl77bDZb6JyOo2RvAN3bQ2Dksv+c3ztsZDTQ=,tag:9szwYH3jgOsR1cMDXBWmpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
