apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:/j5wJ3KMWJPepaqFDDWQs2TJW+9KqyZcj02JvSD6xsmhHXiyp5rSNKgKqO8hEI0OP4ewp0fizhP39R2t0xAFm0WW1pyogDrQ3tYp2CXS/nn68pWIpq4IGgLmRdtj1H6c5KBICK5KJ+m7B6omV6QEruPJ5/Gd39F8mvrDOktj9VI=,iv:ZnwCZyT2Y7kNw3K9zp8NPGe2uAFhPvzcOiRDNua1l/8=,tag:9l0nCcC1XvCXOHuhzMilTA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcHUvOFE3d1A0T25DNlYr
            RkR4Wi90Tm1iVGZPbHRxY1l3d2NOVk5oL1JzCmJMUmNXbkZCbXMycnFuMCtiRVBl
            eHRsNW4wNEdnZ2hSN2dGZ0hPZURhSlUKLS0tIGduWDB5QURUMUlHSnZSUVJTU2VJ
            Q0Z3aEloaGlORWFjR05qYUFkTjQ5L3cK+OkUGL5h8yVbs+hCtvIsfE4woxHLPLiO
            HIS7TRGWvmC/Si3VDu4A035ndve/6iutl9rpxHnO3i1OGdujPi5W7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T05:55:53Z"
    mac: ENC[AES256_GCM,data:foN9eiMk/pzZD0PSNU5agYWO6R8C1EbwQ56wdLNsiFYHBq8d5fWdy6P0V0BZ7bRCthOgStjJGGWsZbmP81pSZihY8P8F+xU/X7+qKt3a+lE8/ItAzzvm/jMHn4w+88mkN5HKRUvodsEEp+JO72py5i2FbTSQ0R1Zh2sH5JzZacQ=,iv:b71EKllLHqH2KceUGULcz1iDM6D5Eqb2FQYXNQ/sKQg=,tag:PefasqJm7dKLuAOaGragAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
