apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:iwhTXZT+l0/f+VlDQyVIj3hGmz++oXxwPA4T0Q93QdqCzI3FPmNNIMuwwK7pJSlU4WfLMI+7l7Q0hLLh/s5mWpj2XsC2NrspD1LFXf5hz1NOnB/xrDm522LtXMoj+I8hkflT641ZLWOGIJa46mXKfJDtKePPEqsgvr5bnlbErkM=,iv:+zsZS1SzSIkO6LB2OBWwc9tkqiYvgHI8f6DbrbYICF8=,tag:gvbenzO3Jc4ZOd6qWwOX7Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUzREekh4eVBBY09ncWhI
            N2tUZ2EwbnBWMGV6YlNJL1dZSHZnMkwwZkRJCjJuczBnaVlOSzdjQVUyeiswYmdm
            QzI4SksvMzhma3REbndxYWRnd2xyQWcKLS0tIEsrSXpZaUIzb05oMW9EbnhzdFlW
            UERXcm1pUXNoaGtQT053V1BhV0luQ28KdTgcbeaWzwbDhvmd3X3VQuv7eBwB5eBY
            3ywVeu3Sg5QeLTUKOQGDj0tE0vtwSd6IfJ+mdoUi4JAigm0BbfPBrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T09:36:58Z"
    mac: ENC[AES256_GCM,data:I4jraVQ/xJ0k78/+kAeh0GBKHdZ7dpk1azI09DGKGwlT6uo+ACnQy2BGtCwtlRp5msNUeEqAf3ZCHOa4riFq1cznLoG8OM3CTb1nLyFOexeERGE4z5E9Kj02oJQVv6DfbhIKMYe1e9VL11wo99b3i5ilkgtCD0D7fXV2S99OJ1E=,iv:NUOLnc5wRSJnu6lCFO8hrOSJ+LDXQj6voTaSTFVWJwQ=,tag:PaulUXm8+tSiZzKr6G2e7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
