apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:c4ofx49/7qLeUkH13T8fu+eQYGu8Uh0TC+TmohHVUxanvCqfRpK6oclN5WTF3Wh09yOSok0o0ftPVWa15ntBINcY7CNrahvzmFbVFNJL3KHfhD1gggq/+w+lVVilbxjxWvryHcx31zhjzofUUti6XzvalnkVl/mSdetggRiqMbw=,iv:ZdyzB7M6Xho1/j7i+bZ8lnOdZCC/LZz/A6GYerC7yIE=,tag:SoVotSGYSnBk5RkQkbBlqA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsV2tWek1aUVBvZWJFRDBL
            UFVlOWs2SFptTEp5TWJOZTVobWtyeG1yN1dnCnpoQXBHZDBUcktnLzdROU9tSGZr
            UlhUbUFVQnVueVRtaFpvVmhMemMvcHMKLS0tIDNqWmRsK0N5b2hBTUNOYjRkQUJG
            Q1JDVGhyWVBPUHMzMEdzcTVVdFNGOGcK1gOIwF6vJp+bnxS3K5K7AP6BLeCz89En
            FS2pP9voEAiAQWcp8ZUXIc2bFNYKGtmZWdmBD/DgfUYY6XbJLqfxZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T09:30:24Z"
    mac: ENC[AES256_GCM,data:pP+KFIDyVpHj+rcj+VIlmjf+fRGycZKggRt3t0sMDlYYjOU1MJjAHRpiPMdfWhumhJ/RT+/DkspiDOhvT3l9+B61Qe0vUGKuxPB2RJRnha0soKrDxteSQproybxEGxapaklRRcDXBkz3HO1/ZlhhxZwJjUeN8JkxnTmpxJX8q6Q=,iv:BIsvf1IhdeZPjuX7SDbp/t1/xPg55I68JoXTEtHeHhs=,tag:6linKYG1AoBD5fAnro8nSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
