apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:/9rt4coY8IdCiTVzpngFXj5trAy64+mUakP8lDn/cGvDDSuRCaIc03mejJHQodtU8eXQ6n5rm+kG0GeamzR7E++IqQmshbZi2jD6L/MHGMibuZh5TePKtwKTH7Csa7ZhAqcfJ3lJ5yS0fjBp1mKXwqZvueJAQPrfKf3iH4aHpdA=,iv:L3tGkrJfCX1j46RUPl65XwUiU85p/r+Ayr1wnkfklcM=,tag:pyl8yuwGCpjv7g9JwEUoyA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MHFVN2ZBUmNzR3JPaU9T
            Um9oK3lnUnYvSzExSDI0c2tHNHV0QXN5N0ZVCmF1R2NQU0ZmSjU0UEVDMmlqb0lY
            VlhKOXNNbnRvNEFhYmtkZmN2N2FyV3cKLS0tIDNIbmhUSHdqaDBXNktzQ3Y2Z29y
            SGxKMkpNYUdvbWVjbktlUVJsdUdLOTgKDuMoFh7TvPS0kgI5aXS8seaqrSCH9Zof
            apkgxXgxl0j67hKhwArzVMPYjSPIzM3+3RjsN85HgHK4o8NjxiP8dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T07:58:58Z"
    mac: ENC[AES256_GCM,data:Y8tdCKo2h3EQUxMun6dhO0VNfxMOJDAvD65rQOyNhQiQXhJFx8AH1SdNPvgc+3vgJQsxMRCs/FkNtK6/Vp0sjON/t4bemLilCsM//SDEiE+X68eZ32Wy3VrvdDCGHR8cvRG7iNIQMKnfSpYrPrFhVYWChkwpAIfzfJN+5p66zxQ=,iv:MtQYagzXrt2WbAVsRFrym39Mgabu+H+G84q2NryHVA0=,tag:Wwciy7H3DNijth+gtsqVtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
