apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:g+LDjdkvy7weBlKOOy53ysP1uBBOXHPie9UlKcS9AjhnBfyeFwM9YcT8MreNxL85PPp1ogl7tjzfhBe2TBsUhKdAdDiphnvyyu7fQAfc1PHfvpuCpiq1ZuoZ4kojQEtWTkjj3VYxqyLBSGiors0ZQSdPOoWk4VIwgizoq/5QykU=,iv:JX6lvCm0E5X8M06DGcPjIHjwm3dQXOf8JLbor1Bgkoo=,tag:MMpkRkX57Ogzqw1SNMzI5w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WVUwMDlhaHVpMWp6cTNW
            bUlTUnJZQ2tzbW5Tb2I1RktLai83K25uR2hJCktZcXd5WjYreVFXdFpmSm0vNWVi
            Nkd1YXJ4TzIycit5UjNPRjN0TE9yZ28KLS0tIEZqTmZ0ZGI0aUFSc2NNWXgyK2JD
            MllyU3l4MmdpNmRIYUZjWnhQY3FNOEEK7OMOxzoYWrhw54oD+u8idOru0rGI0AI/
            Ke8M9aSR1rbdiU7HoxUZfOgnraX5xZwNIs0gjF+MdqnmZSUfgEEQew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T07:44:38Z"
    mac: ENC[AES256_GCM,data:1By08VVOM43xB1a9vYevMOcVZ0+8U/2rPYOHzDYOpfabYiuh0X0FwALAP+Df/wEqmrw3f0o3HkPao3f/38Mc5fSCN8DwizPHxDHlUA254YC2eb+WE60QnpMjl3vlGUOi7nkscbISbdM9eyxBxJvzox5YOsnmDnxzeOnouK5Jp3Y=,iv:fKF72Dc3ZeofPHWZ2hFWR9UvsV65F1qKwBLCesqDCE8=,tag:HAjWXcPb9aV6QCsSxT1YkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
