apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:+wh5X+tQrFWQuH5iRlZTAZLEaRub9f5N/Qb0dcEt9Ilydnkxila9liUDMAxiY2QLP6WomWgLnMOnsNu8FaYFivUq361vhLrktHj6pvK6jr/ocU00Qa5LAr/3PSICORwU3edLuyhJE9Ng3lo/zLOVDWUgovjPvcKN2cgGhs/RuuE=,iv:dcXlEJhVYY05jCQxRDXMolX/KOfspM1Ua6oWD8q4cOw=,tag:uljeRp8onRVu4L246nT6Gw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMTh1VHlUWFpuWnlud1J3
            QjUxNDBwWFhXekNGaUE4OG9hYVJHRjYva3hjCnVzc3RWK1ViV3BacUg3c2ZWK3pj
            dzhkNnJ6ZUJ6Y3h6TXJOZ1J4c0h5aUUKLS0tIGozcXdQNTRtVVNTclI4M3d1WTRk
            NGZyU3hqcCtHMnIxVnNJcVFOQktpaTgK7ikRWKp4xqfRZ6sRjxP/elcmXmATd2hd
            bWkQMnD+4bvcXsAIa4Ebbvvfp+4C7pUhSX4XvvYC2fXWo5B8Lb1Maw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T10:30:19Z"
    mac: ENC[AES256_GCM,data:LlcnLMey8rOQapHY9/TziKy2qzp5TrW8r2TcE31yq3E2l4RdXWihS6dFvgw6WnZyL9sLwTH7sqlu2+YgORdlhSx4wKT6f5C4IISJLBojLz+SUxF9LWFNbqZNU996o87yXz6MKzSZgYWDL2v63EYVvQKg3MmVPCOmbEzZUdlYEro=,iv:yajnI5NX9Lb/RTa3u7IVGwo6vpsKG+mQ/Xx3TV7UjNk=,tag:sRqlVHh9B6ntwVHk2dt2sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
