apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:cU+4TcatbWjXiEaqjA7t1XBrYBdgr7WwPzeB+j7VHfOPOAgF5T30T3OS5lIa2bivu8ous/u/kI5Tl/caLWAYhN3O5h7WpsjHnr7iOeJEMCVVr3F9MhimYkQE0PESJiWYm5Ug/TJBD2HYgE1IPbwYN8hjpYI49nZFqNVOGHy/2iI=,iv:2cfwdqUqWeMZuuAZzK82xz0+TKORG0KO5VCrfs8MsnE=,tag:hxAgsBsrEUTM3CmL313Ong==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSURtSTIwMFoxZEI5ZXRU
            WWxZU0JaenhZRDlBZVJRcUlmV0llalZhcGtBCjhRYVM3TU84MGNKQmdpOURoL25i
            cVk1VnlCVDhjYmlRZEpBUlUxQTNQY28KLS0tIDlaeFFES2o0TUxON282bUZ4dElz
            VTltQkJ5bFA2c25IU2M0VjUrNnI4WWMKwmxd9e9olQLBQ+OrULHowGOCZDfADgTK
            cB4GjNnyuFrcnaGK4hSutGGa3obxXaMYvgJmCPNUpXZH5DSFDYr8TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T02:33:45Z"
    mac: ENC[AES256_GCM,data:fzGXP2QUiEc2EhK56D4K3ZfhHZq4Ui7vnc129MpiZniPc2SbiOh4K3JaNRHUyAMJkjEHyr/eIkuuMBfjabn/yLbe4b+XO6cQjTlu4vQDfnXdAESPFP6zgJxk7i+ndV+kUVHbQb8Ac8T/Afbq9wwaYG6AdE7Jl4pokwSNSx6PNQ0=,iv:PmqPM0pMTqHJIQXBB0hxb5eltXsOLae1X2JQ+vzi4zE=,tag:+nnKMS1730krT8nx153VGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
