apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:7U40zEkdfAlj82dgvgj2ZsvIwxVtvuqvx42XShnNt3By5TNPBDOUUicwBVn5rgJd4QGxya5lFKIRh5RhmH9dposPkaBUklrS7oLm8qT1zN59l1rmdaj4WHePm1yGWXU0X75p+jaitAMsD3bHqGpDH5LlFPTNdGSQrDPTnvTjXdE=,iv:wMh498XOIlP31yKXntqlbJoz39FGt4aTQ7yBgjZN4d8=,tag:CZ3VKLiwwYKGeNJgcy7ZBg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaHZ5MDhtaHE5NDh6Q0Z4
            dGwrY0RkV0wzcEtycGV0bWl0NzIxRkhyWEZFCnE2NWh5dFNwQkFzS1lyb3gxRHMw
            S09pdnAvZERyblQrbDBjQytQWDhVWmMKLS0tIDhENHg2VUQ4Z21GTkhBTHg4emJp
            ek9nYmZ5K2hCRy9xVkE1Y09QSEcyVWcK6Jcxwv5WxUv3xaspr1DbBckHIYYUr/dP
            WrVZnQa5KCmMVNNtYoZXKs8DXUmKi/mrOXhjQ5u+O2EIMGPNiDBG2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T21:22:38Z"
    mac: ENC[AES256_GCM,data:7aMTTvxlxfGVEAnbzKhleYkrW+Ni9ETHRVUCnWv4FakmJk6XWSCQ1wKEXxVmlt7mAf1rC4P126kvw3ayhLRvUCIEZNcr+uqa3BX9GgcQvqJou8+fUjcWhWn7DXQkK3QKMAYeOi9Ca/voNT4cOeoGo30GW61kzaKV81qtKYpxjbw=,iv:zpYIDZh2ecmUOwumcmdLGJyuUwD5kAFuzzoObTU7eOQ=,tag:5Yg+N1Z1VdklFSi68wZJiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
