apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:gNhPEf3pnF+UW9uCQKopCq/SJiVjNDHEMzTrHcBOTNuBbZQ2B///96WRDZfqvEeqZJxTNFFT7wrA/353vaCT/Qwc3VaXz5/5uXHnrYXWw25S5fXb1UnRCjbsJ/fEC1UZueHnVIHdTWavIkQ3oPQhTNECxZSj73HN1RQVRbFVw8g=,iv:fc7l2DL3QoHYQvIiy2KuU9sTBxm84lWAbwth3FZKdWQ=,tag:HEN4DBAJ9EfJP91KRk020Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWjZleGNtR05tc0JteTdv
            cVlFN0dobTVEeHVNb2tvcnNmTm1wR01wWHc4ClNNME9WQi8ycStrWTk3ZjFPQTk3
            OUZJU21EczhFYUdMdzZBV1AzTVJYYmMKLS0tIEYyc0dnVHRFdlZ0MDNNeUFMUW9Y
            Q1MyVHhYRTY0SnJuak5CUE5wcHZBL28KJMYZJyFM3RuCULXccHr8cwhlA9Kdav6I
            onsdU8g8LratXxRJRfmUkaiA4e/ukv343/uqaQu3yO8zrimU5XXxlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T08:49:53Z"
    mac: ENC[AES256_GCM,data:WBrCxvHrRDh2Jp4QaMksz/Nwm6RattKv7Auv0miyCq1v2G8I78iwHLFVWYm2kzc5LSDwP47k97vEGBnEe+XvHGWCsdN176E8M2DJoWYbwACvAkI/bXIGr12wSp0ciyD7vQWphSdFU/DlEpzBJAmub0kMyermnEjqiJaf0fk5PQM=,iv:8r53T+b1FUqD7px1xJdHjomPq4Qqk/GWoQyzbWzRbQI=,tag:LeaBUwgnNxW1jfzyicxm7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
