apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:OibFD6vc6rz6OmRLVrVUduJyljob2JuCX8YW1c3D5QFqRBFXMsrXRYMn1WRXRCT0IYSfzcoyMVDj9hObs3r6vq/AVN+XBNyc+n2C22EuCnBZulEuOZFQvG+yZDOjhNVNEexH442szjrtcoWUCQ2H6gajEYmBEUH56nUMqzRbArI=,iv:51Nj+C81HBRckSJVjqK2exKw0EfJ8VoOxE/6+tNR/vs=,tag:aTtLUUGfyLa+p4mmuFnlJA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVEc3Q0c0SEJ4aUc1dkg2
            VXJwaGZwNmhkYzVaTUNWbG1IWDhzdHRkUGtZCklReHpZeWlMTVhWaDF3OHcvaEZY
            bW4yazhsa1dJTkRUODlKUlBLMk9kYWsKLS0tIGQ1azFVVjFlUkYrUVRHcU13L0ZC
            WGhBUWVOL1NMYjdZN0pQV1luK3BTR1kK0IRhkuMnGgp6I+zKBePGVQrvGbJkvtbd
            TgEuH9T7NGFw1PIfEjBypFnFMXvqOnZkLVzfUQHg/okDgIHYwi8BMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T19:51:34Z"
    mac: ENC[AES256_GCM,data:9DAaAN7AX3ZVBWcSiIQIIvsfonBsQml88QpM+wCTdCGOaA+xJfdlPOOb+peCsvnYyYUBZCFWESFyOeC4NrBiiQYAJjiqFP1X4MDCcricWNxQj006ArrofS2yuyaTB+F19zXJ5hpR5DbWyvop5PPkWhqhInJ0isDt7JUfAn+dtMs=,iv:+TpcFb4JQiqG1uQH5s6M4uKfb7UZ/ykSBl1kAHaEAF8=,tag:TCEEqeU8wrN8WUiSa7Z4Mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
