apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:VXoq6+vnVkWVxBY13Dl3zzfcdQ9e/eZ+VidSSY9uYir0GpCerz6bxsd2dHW+g8h1w7XHAGNCW5Wbu24nIwbUUDuDvJOCzec3j2APGmnN6IrncFpCvSeeVPDcB/qZ6IEJgQ4KikXCf1hO+IRLOu0aCa3j9AU1INYwJHXNBJgvVR8=,iv:m86vZJYRdowmNrzeTYD04zq4wnciRZ2kiytspnD9NSQ=,tag:JOUgDS0yKGWKjmdyI4dlgQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVWw5V3JCdUZYY0hyS3Bk
            azVNb3VRejBwenpOMlNHMWRzQmYrWm9ZajNjCjFzN1BWaUpTMW5HbWtCbFdtWEg0
            bVdjR1BHMW9WVjF5NDAzTGhPUkwvMlUKLS0tIEZtU1V2dkwwanQzc3Jvd25nU1U0
            ZTl3M2l5WWJRVHVnTTFxQ3hMVWpTUDAKTtPLFHAuTg7XQD5r4FMaoE9t/v8HzF/n
            o5O9PlRrxpMyiFAqCmLFC+agqu+tDLMZM147YFGHirAQlpzpkoK7Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T10:22:55Z"
    mac: ENC[AES256_GCM,data:egX3jGib8GkZe54C1H5cFcQKcXYX3sUltf8pUdmxvIMkSBL1ihiyq6ERHnQ0QhL/QgKObo/wUHI+wA1oHVQA4p5haaP8CNnYU5hSy8VysQRhH4NAONiXc4qELGunHyahsluQoIJ+Ta+VFq80Sf2ltESHR0R7DN5d+/UF49zLbR4=,iv:bdEOmg0TZqDgLDg1HFpsjgzCROGSoxUBfmyU4SiOeA0=,tag:BWJoEFijl3yOP8ewIXhJWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
