apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:SpJSf4FgWpJjODw55j4jLzDxkLJ/gBaGGX8h+4z9+pA2Zhn1YNkNcyOYGPWTyX3HnopPDjulFrs3yE6f/37ZebjZTbdt4W6nzmeTzL8G09bvAcUjPN52CPh/jiXYMH4KSbrCobiFgjTfZfXuROZoCKxAj9yd9TUl2TkdkDO9bm4=,iv:gq7Ynfh3GreV2K4CYOqHQLxJms4n5SgWHs9eXUgdvZA=,tag:McKvfgN7tCbxfPr5DuLBGw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaXhxSzJVNEo2d3hNOXZp
            d3BkanpLenRFaDlPeHl4NndqejJkRWcxaDEwCklyR1k0eDhZV2ZqVkVqc3N3STVv
            WXhiSzFJUnBJVFNtaGpHOXpqM2JlNWcKLS0tIEFOaEcvNXRMNDFsa3o1dzRFZUdB
            Rkc0WUZBdFlKaVROa3dEWTJUZzZzQm8K5mD/ROBfDl1klXkUDp76zzKmU1rTb3EE
            7Kbq5s73ZktweGVHF8r7Dk/JtyHcvwssrw7OFDQL+MZ5ZOXXAYrUJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T22:05:13Z"
    mac: ENC[AES256_GCM,data:E0eKYYNeA9Xzs6+H5ENJcRUx7J6BjsnXfnUuiEScCHmv/QL0HfMmLcPWou2lUGNqhEylnfTWXa+Hqr0Ft5wv2+ddQhmZYoTbf+iIIMGaxp75Sx7m9QWfgVwBO5n1dzZpmFt9l160iCaw+kQywwKdQe75eI9VjvlPlp1uDD8ozKA=,iv:G3D4sXjDbTgxr3DQjiYZMihpBXhlk/0O2GfiQISN0A4=,tag:jbywJ246NILNLfDrE5YMnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
