apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:qGhN7dEHMOVe1vW1XjOyZhho+71OXHQxKHNCcDB6j7bB+OjLpHqF8O/GeaZ27ZFBZcikfEyF946i37p1rGrUDipwtgijDg7XuTlGf74sGXux9ujkjQEd5t6DgHZE/OnrKIwW1ywLRSgz7/2jrKBXXBpzvxlZQwfhqSMgMu8xuSU=,iv:OBDlQ8avHgqpHmR9OkSZ4qIFEElnurSWaDV38BsagJU=,tag:voD/AkuDI58YA4gyS+3l4Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeTljSEV2MEpqaG1uaFNB
            QTF1RGtIRlJjbUFwNUNUdEJqNEFXZ3VWK2xvCkZKTFI1eHZGbmlwNWYyQkl4VHds
            eUdLQmdSWlE2cnRYR25uSnlmL2ZqYWMKLS0tIHlZK0dPdWxid3BiMDhMbkdJVHFn
            MEZuZHl6QnBkTGdZWlg5T3lpbDVwMzAK0OD3hgCZWTfvGls1+ve55JZlIQIKv4Ko
            /feJWxT6N4WBYnb46350YFUXhQUsbneqbrneInaBe3VEx6YeB6AdTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T08:03:02Z"
    mac: ENC[AES256_GCM,data:zmSezmzV17ZLyXjJx46PcMcuKsDNsUzGFP/F/jOafxpFPJrZ+XThT4j83RdegB80DOEmxRiyNszPsr43Wiou6JJl+n21rzTfkOfvvdaUQltJUMd1f6tUI1Abd56MaNm3RUq9zKqXOTJOqwTDPC9g+CsOgZcNAMe8DNTyeVrNgNk=,iv:PYRupvOBZ59V4fx/e/8b4o9FzYdvA6tU+LcWXF3ytig=,tag:5KZzPmrr13gsBCOtARJWVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
