apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:T8g3dzlDR7mTwCLtyOjHoiUp4gCTLUNd1JBQNk1h1NH82H/cPg3MdAIX9IOi9ez4auO3eEfv4BjV1ESqffqooaAv+cXXfFDsSbW/glayQxMe8sT0Ap7VEDeJGyKWOv1gbFYqtFgpu6XeCywQ9FBk+G/YtMgkKRQzTAUEXxUG3Ac=,iv:NnWTOCBSiN5+6TZVBlP0rjYlaqbnht3/K+FlFwcF1HE=,tag:zhH91ZZOKx29cEyB3g+8WQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmemtCV3lTMkR0Nmc1WXFS
            bXlObUtCYjIyTk16TGZ4NGhjeUl3TjhkVmlVCktUeUFtZ3kwYnQxZzBGOVFsVnhp
            Slo1dmluc2NYUnRVcHJVN3FoeXRBOGsKLS0tIER4VW02bDUrSTNGeW9MS05YaVlx
            bzdTcmptVmFwN2l1RnJvQ0tFTzB0bXcKf1flxA+zbmyp9y99EIbv18cHVIZfQa98
            4Rnehiwjh4Qyzm6pQ1RuCeGaJ8GSgKiabPoB4KIrJbKaq0JWcGVsaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T07:14:52Z"
    mac: ENC[AES256_GCM,data:5tP+KQpXS1yKO9rOYDDclI45isVcvqnd3kDS3a1J6JUf85mVTfQEmTicT8d2cOI3eSXOybK/xTo3e53FA++5MQyXvE7g4bwGNG4UQ25EgdikIpkzowG4IjSmht+gkxopJL64jbErN9YVEXRWiqJKggrX7QWfnVItj5+AB/1TdnY=,iv:c0hUEhdfpg9U88xWBdQE50DDybWPo3KlvkcbdEozD/0=,tag:2Z2d7ja8jKYqb+RSfhVPTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
