apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:3P3hzWrBSC5M1yIhgIgNBeWS3ui3VO0ExHDBXzvErdGbL7mVx1Xm4BZ2DS27oszsYDhw6CYw6bvSeA9T6kF7m7QdaIln+nv7QRS5kZtDsNKH2yRh24k4tfP45F+VI8sFC6z4NODdI+7+lAQbKNPasA/S1uSzgJ2UlBVheWC5tO4=,iv:szo8pWun6DfTivlA/0xjz2f9Didb/mw8zz1ADvScF1k=,tag:mjDB+KoqXiNwD/YS9cLVvw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4akJWSk5FMWNUTUF2Uk1l
            ZnpkSWNEWmRDTmRwZlBRMFBVODdqNFZHN2lnCmk0cHFOV3ByNHRnYVBad2RXdXRT
            NkVPMXN1a0hPOXJxT3B3dS93NlJ1TE0KLS0tIG9hVGtVNFZrbTdiVzVRekxTRC9N
            bFNBcGFqcFg2aHhUVXFRQ1pPUVVQQUUKRFvTRHukwvgYngH4/THv4HiowKrnldUU
            nROBvofnD5ql9oVaKGo51qzs3E2fm4gs2tCenGydKce5DFih6n+1AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:17:46Z"
    mac: ENC[AES256_GCM,data:iqyzp7HyhU8Clu6B/odhpV5Ni1TKwxsYWfgT9zGFwvHjQNt+7pLNzYJpU5/GCkTTX6oNB0a4mg7XbyejXHw2EPaOhikvzyHROIkHBUCVrPttZtsJxoudNLEVfiq4pBtQoBeoJW30F5xihsIViGqsIpSJSk65BVFaHdNTRqxDqEw=,iv:Oi7s4rVlPFo3Uxh/qZfPHQJHHKPXuOfHiaSY1Y2AFb0=,tag:jTtJNxppC40UOF/p6qKA5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
