apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:310J5po2xfihAWqBkRSfSOmfF/WtyzoCPuoOoqvbqQEEJJwN/EfVaRCeAGDYvu1wh9ZOeKj+snz/VuUcgtTJ8uIZzWvMSq+0j46eH/LftQRyJF3kEegG3qNCPYBUUqFIa7DATAB3R5RkstTxFhb507PWViEgBOsZioV+1IVqMwM=,iv:s9wF6UwlEcwA1eXsK3+o6DSgB1yTBK0eKxNIffQdSxM=,tag:7OWoLLbbCUbkn7WiSLTvYw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOT3l3b2NlcEEvRDFENWpr
            UFJ4KzRwbm9pL3Btak43bEluMFlvMzFNS2c4CkJFaHc4N0JWc213M2VWWjh5YXNG
            UTJGbFErY3VhNm5lWnRjR3lJU0l2Y2cKLS0tIElUUTJuL1pvRzZqN0E0TmxBL21v
            SjhGb0RFYnlIZmRiQlpWdWlmbUdnV1UKkbN1mZDm0KbHXGlYoeKG1YeoyTdtuu+I
            1CGzdEcfUEGnAO9u7iw4H8Zz1zysIa2pzR6Yc/yUtc1RhWOgpdgXJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T09:33:53Z"
    mac: ENC[AES256_GCM,data:gD+leFnTfbvCIl5CwWzjXhx+5pP8c1qkNhg7Z3LcbergOQnVw9DRpjZ8uy7z5JAPEyyjvACU+8ZwAP5cTTb3CPzlksTAuekXPoiGu62ZYHWzrRFF/28iIvF2Qd9uyLdbLR7jwXIGjl6JxR28Anghj6Noe+ccw1L86obULtdiZvU=,iv:UlIOhzsSXg5RNB7wxU4c4TUTayG7vhl69+7jP+JZ0t8=,tag:ePN3SWXBu/5wGJlfpS3haQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
