apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:m2CpxEyOvnnBNnu/kWM7ZzFG9e1G1rQ4JgznRCva7dnw+Jl3q/jab7f1r6l3I7ZLT8Efye+ReEWdUznEpJC7C3C5IkdbzcmogVLWpv2ztI3xhnoMS8yMblGAKZHcKlCvaSHYX3Ns2HaJQGb6Zd/QH+KHUXSWs5cLaAtfFKJ7VlI=,iv:9r9oYca9KZ1DAKgjWNY5siWyV78JKlWZKX9Kgw4Krgg=,tag:HWjt93qcT09yADbwWd67Yw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZnY3TlNxWm9HNTg4QzhY
            UjlVUG5FblJhUmc3K0xmclhrbWk2bkNQWlZNCmg4REpCME5kNzFYcGNMTFZHeTBT
            SC9ZSmJJVVE0WE5iM0wxOVRqWktFdlEKLS0tIEJSdHd4Ry9JVy9TK3RMWUNFL1hu
            eS9ua0xtaVhMaStUa084VTJLMlVCYzQKMME2wywg1KOQkevcA0EYoBsXYdntPUjl
            GFPsB00dfHyePqShM94Ni44uQRWcHyxhT6uop6RY7xha8d4LyxB1cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T09:08:15Z"
    mac: ENC[AES256_GCM,data:tv1UDnP6m9KVE4gCnRJw+3SgcS/NL8OIc4ylggGOnWz21AJUxXnoJRsUxBG75EFKJ/UZWteaoXNxGEWJcBsA1nDPTVUoTQ+4/X5BNiIbRtxWqffk3HJUwGk4UZmVAJiHuxlZh2OgEO0ZZRy90stU7ajecpHnJpF3G5hRi3Ym9co=,iv:hNR3+9t1lJTC4f2RoAb90jVvcMZ0gCL/DJWiBcB1LGI=,tag:qJBa/5txkq66ES8VX5aWRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
