apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:JJRHEtxocnHfBoNkiOpfzzinnjuvfGnqiEJ1MrdoJ/o4vwjw0l79HihD9e718MTSFPhI3xsKsGflN8fvNItI2p1pVKC9fDQnLG1+vS8/xUE75rqwyXUvXTfasNX48zfo4aJ/LhD1yE/Uziw0XIvBcBb2fxhXsk7D6fW5SU6XQ6w=,iv:qJ/WXYDLRfYDEbhSouoGyDqe0N3A0GsftXmux8xf96o=,tag:tf7WwnGBJicySvaM6tC5ew==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QkI5YkptNlp4eVFObmNN
            Q04xWjYrcmQ2NEFwRzE0QUpTQjNWT2tJNVd3CmR0QU1vR3VwOTE4UmpJT0tHWngw
            aWtpZFNwWGRFMzlmUFAyUzNRZFRCM2cKLS0tIHorS3JOcmRXSDNMM1ZwK0drMUtG
            VUgrYUVUejF3RFU4U3M3WFM4YTdPTk0KkOhsvOiVE2rh90wflgTKA8PrPleCo3S8
            2LDyFtY7Cbl5WP5mtAzbewycHYHx82a66KrtUq5+xxG9qJSiFV76ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:57:46Z"
    mac: ENC[AES256_GCM,data:fjbQ74PSun2rxMbriSZz9HJQ4LdljLbnemPa+0i6faJISX0NS6dUCzRnYek8fspZji8T2R9WGtFwtSYELn0n3v0RRvV5B9/who5o5Nne33O29YcvOx1ut/qpTHNlVJorKI3HywJrDKwVHgEwUOP89pMih/JY9/QPCwlnKCqJgKQ=,iv:HNwNGsPQzu1QUO5qnHfnfexvV4aRnW5wfCriILr/zcA=,tag:GiC0SblsAMIFy2VhjSW4WA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
