apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:shENYaZXn0zhPNI8n8gdheEPz5i5z8nASR6ySaJM1P6vMj8HZZ+cdILhcnGyqvXPzFDDvELhHEfI14sFysYZK9CMtWSHFYSDksUaYbHnwlYBZpwKNsojfmkbqOQHU+N+Ftv90zcVJHKgvGnxIAFUQXcjKxZ+g0sjlVAFMxbC+lU=,iv:IzKOAlzhPP6fYT8x2UziUJh4oRnw4AYZujnZFU9C5Yg=,tag:j3wkP9V+h+hXA7lfDjnVBA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSemVBOVBjZzZlY21NbGt4
            Z0dxdldGSStJaWEyYnI3ZmlWTVFUaFIreVFnClFSWnF6eUE3cktGUzZIamVKTTdE
            NzJ6bVM4RFJrM2pScWdDUHZyeWVFZHcKLS0tIDBkc3liTmNpYkxUL1dBeXlza2Rr
            ZGFqYmk4UjhrVjlEclR2NEd2NmU4aDQKbW/fVGZDfrtXpDcmhaEfrY7HMjuTXAeJ
            +FtDAg6xp8hCTC+i12XPpvruJuHP2o3Izik+zjHH2vgvPQlJ7hfYnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T09:39:40Z"
    mac: ENC[AES256_GCM,data:psQK3j6BxcqWS2s6RG3+yAVp95kwKvdm7Z4ZiDbRTS3JPW2D6aL+0CjfoKi12MTxAvT3AV/LC2fjDCSiE+iURhaxsoONPDp3LUqa4RGqE5soVx+8JFnlAk/+VYnXqd4HYWGuGqXFRxxLjxBHZCA2BeykEedkE0uL1ZIFot2qb2c=,iv:tdPcBEXyQ5ehOTnpW79KyXa4+RHjJx5ecHG8ySwgL1M=,tag:Q3co5+aX7dfBvZaVdJqz2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
