apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:1hidwzPl/yr1cQM2iFNrOls18SBK6QEfzC184hgv60nJ+Jf2P9+VG2JDnQay+GrFiCJc4aWoVolGiOaV2aUtqImPL1OgvwXceEHKDrWkTyHU6jB12xBukAGco70qPB9jQLEFvHzE1bDP7v9gzLcFyzISsmQWLK/gRvyiuzqjU/c=,iv:NXfhotwiYLtYIQVFcQXDb0ih5VBBrOqqYn1yNpJ/LtQ=,tag:COeyjHJuX/J+qzNpIMyWJA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NXdwTjgrUGtMOE40ZE00
            MjVRb3drVndxM1Awck9PdzZ4SXczM2lBb0cwCkpLN0wzbmphamRWcnh2WUhBcXo0
            Vm9Mb0dwRWxlZDNyR0VjcUVvMnN6OEkKLS0tIFZWMzEwY0drNVFUNXQ4WndqQXly
            TG5PelcxNDBsS2YrRFI3Uk10dUkvWkkKHWUzXTDAYTCjrdIFEqacvJW8nagjsutr
            SxhBP98amU01OqI6Ds85SyXmqLMhq8/QJOLOTyCID6fAPgt9PtBy5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T10:49:53Z"
    mac: ENC[AES256_GCM,data:YcOYBYY/yj2OgX1yluvFmmgxA8sdI4HbE8yBm27R5ixwG5I8ObndU4svbW/Dw0nv+Y7I6NXY+XRoULje+eCjM9/HnwNFVq4vIA49a6KscJwgU/eMxZekK/2okRa/nQRX2Ng7a0bDRMDMxMFoXeKYji5e2I5nyyqNH0gugFi5jdw=,iv:AAAvMoWjsRQh2JPReMdLwoiNGuR2bHSoI6mmaLO1zYE=,tag:wnck/D/ADpy9GQcIe74vAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
