apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:iQvpC68t43dJupaJlF8qdeSi3VmMoloXbP0ipbJjRnSh9Nu4oVTiMbKdfFiuYGhp07QNPIPLXN84W0ok0N3usxI8UwqVquHweKBPB0Sv1FqVq205i6MA9ALJwEvV1Im2BZon13KGWjMPiQuJM5tPX1+HJbg0YoFyjQb9Nx6gEZM=,iv:SarK5HA/vigOoScS/5X0iSNip0c6F+bN8K/4ehEDU54=,tag:FqoOmmfjvw2I2gdFlZwfgw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrME02YWRxU3I1ME10TmpQ
            d09rNjJ2djROSDBZdVJ2NHdqQzdpNnpySFhZCm9MNDcxeStnU0IyOENlempqNjh2
            dnNveDBENWV0YmtvbDB5enBabTcyODgKLS0tIFgva28rY1BNM1Y4aWtudlpzZGl5
            N3NydzRNVXJabVZIWDdKekV1UUZ2cmMKbR8RKh3C5mN+KVs2Kinon5FqYbZfYvIp
            4HFqpkQoI5Skjs6rGmdYePAT6f7clDqRBQ+n8IoEMGjQ7ut64iOl8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T08:36:25Z"
    mac: ENC[AES256_GCM,data:RxtYvShoHzJa4KrdMfxgxSyjnzmZ7t5XjkLHfQm5ShONiSelPlA8GJFAHn3pJbWvknzW8CRQs3y5jUfqiclpDxAheHOa2tTRLTSEzbJ7yqgM2QQL7CQBHZ6TJcL7+SDTQvZpKCpaFjE++6zfOXGiJbIQ2cRFCcZLEVkCTP/+tWw=,iv:78zkJlrzERowMMx0qDB+vDz3J96gjduBnH6YoZOD3FU=,tag:j2yRb0Qluol3Iz1B6kCc/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
