apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Btx0LKwThCaWttJmcgAmLa37xOqgFRAeV7/bpn4QHi1GvxucyFYYkDGXtAkweNIGxXLUEjWyJ8QBAbH8Hoom8Mn+8RmxMGA39RrtaK6GcUMA0d1XUA7Bs87wXMUheEzYJvzR5dZKWJUItFT9PUNZUpmY9+qfWDshUivA/IDMNrY=,iv:AyvqJXcV4FmrDd7gmTMLpSLhJKnfzkwjXHjUkOG3jM0=,tag:QlPzxh/NfwZwBW0AKwrirQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NERQZzVDYk41L290MVZK
            VTh1Yi93cUpkUFV2REpjOWFxUno3U1JhakRVCnhCMmwrUDhjdjRQYzkzTzl1OWov
            SHZaTWRHNjdjYnQxc2lteENQdnd3WncKLS0tIGtyL1o2NGJZaUE2SENMMVF3UTAx
            eVFlM1UvZXdoVFNHSHBaRnVaR1Z2MWsKlhB0dGHsV2EyZhIq/I5VSxIKsGzeDVnT
            +pJW5HLi2l+7Onz6qwJYJEDX1zaEQRdJeeitnASA39BcDH00Wk+PLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T09:03:50Z"
    mac: ENC[AES256_GCM,data:A+GsV+zGSemFQWpi9bLzedYaPWJpH0n1zDUN7y8hXMPL0SWHCV3evwRSKbxM3vjE8KZPYqNO2PIkfq/HByGTc4OfIGjF5DflGw0ar2UOZDcGJFVdOyaWJO5h0RYv+smdFxh6SmuZIBe1Mc0BC4MA+FV/dW33hWY7Y2DQCs3Sl9s=,iv:CJBxgpPvf/bJxcU5Xfqb9MfxOMUYjcV5I/0LD681gTA=,tag:522AnXhx1w4A1o94oQupTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
