apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:/lQfW+OxxPjI4gF2ggZsR8Q6GlHPpX4ile/U7duIrwMix4129i5ED6sRdOuOb/ZmKO5W63Wk2w0qGXHjtNPMHFowuDWrvCl5nYX3eTUUfTxHbIRLy+w6uX7aRkQU4N9X6eVR+Fq5pKClA3uYVoq6riMRuz0IBOeIs3fgzuuuWIE=,iv:VGRHxcA3utF2tNnFDy1vQKtY1U5Z0dGM2qV96z0B9rs=,tag:t3hqoS4J0aNsutxnGS+TXA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWkRHQWorcFF0WVVMME1k
            NFp1Q0JISS93dDdSNk0rbnBvSk9FQm5aTkc4ClZQRFFtUUJWZXp0ejZ3L0lCdy9B
            Nm1IWVRPVTZucTVEdVV0R1R5R0FZRk0KLS0tIG5iMzdORG1rTEpwUWhML1JXa2JB
            NThMSmxOWSt2cktJUzNEVlN1RkVIWVUKsryLzMHpLqV8RfHaWR9MXFY7Ubjq5zgH
            uvShHaQEH0OHkWZqGr6fC4MxR5FcfUmsgpEDSHKs6sq8C3j+iKRV9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T07:41:59Z"
    mac: ENC[AES256_GCM,data:mxXMQOdJf4Fmv0jxwOZmvVsBV6ioKd6T3GcIKbRkyKQ/YWz/o2l/9B+8ikSpBlFtCTyrimW/WsFSxlrVZTK7/IauMzYowZC4q1gO80uzmEEPBq7Rsm9tqf+4+WRDaDP96aU//Q/hszfwP7ew0h5KE6wWTNu0sDvS6hK1eKo3L7g=,iv:aee3pHwwky6aSGvuQPYKcUuJ7WkzRipX8hYALzDPYKc=,tag:GXCGuzixNZUubOKtmq69pQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
