apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:MwxEaVPmec9gUf/eUwf+/rrcnJ3nSnf7lf7x3ZjBgc+FsAwWyKq5mQqb4ogc0G7R39j484oCv0qS7DvGjqYI7IBXroLUPPT5nY3pHyIH+gUiaatiGkCc5ZdmdwXuV/GODDforKDZgMp0HZr8hAZ4dFZb3gIhkawfnoISnosO92U=,iv:xJWypVTAWb5DZmo4qpXkGes7qX7DOnoE1vGtqJNx4Xw=,tag:h3M/GYVFF5hSOmYrZ3oK6Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc2ZNYlJOQzE2L3A5dzg2
            dHVyV3ZYc1EvZVlQNVJrd25sNHg1UkU1UFJjCmRGZkRQMTU1Y1dXNXlHUVIzRXBI
            blIvT1JYejdpbFZVenBrUzFxai9kZkEKLS0tIHhJdUpWR21qbjBWbHBMWERBL0Zz
            NW1JaHdKSWFmRFpZN3JoV2ZDcExpdGsK/Tr2YGAIccyKcDObmlazjkIvMmZvd1uX
            WPAyoqzJpmpOhpjl56puCCOKvvsLav/VMBvvp3r27YCYaFz8/Ad5jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T19:35:01Z"
    mac: ENC[AES256_GCM,data:U0SrRBc8sir7zaXhuXP7GPD2PsiYvEmeSB66iFnuWaIkD7jZANyXXGNFTImJPp9YZy09wQw0utnYV3GrFli3RWcSPKNmapH2PrtF4yYQ16c/LG3a0fXfnQx1v3OGVw+2NwAxb+Q59/YMWV79nWRmBkknttpapZ79YoctsXkt0mA=,iv:6JQC9YFS7rO6tHjmkky0tJFmRJ/UkuliM+7cUa3nplY=,tag:grZwKES9VD9WmbfdqjLyWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
