apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:7Xt0XR4j6H+B/BphwvOKP4YD9pgbfQlFlDm3r/uyIk2/h/Cw9JpezuLNZdT7rmwIPLsUNDyRp2WDqyUtzMfgYdYELMf2hQIXyxNP8Dq7k6m73AYsa0CuVjTPYdvt1sTyGRbYmDhfj8OBuLRmpedGB46ggCiClA+oABdYRaOIPa4=,iv:b3tlSaCpWKcsub5T+tD8FyPAzjooDvcyMXOxUHBtikE=,tag:zS2N85TsfgvGHMnPR7wEZA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML2EzU3dTSW53N1F6UXRs
            dzZLa1J0U1FoMWJQRnM1Wi9GZmRZblViUlVVCkowSUhGUGtmSkV3ajExdDFUWWNs
            bno4Qk16ZDZKeFFndVhYUnBZeGNWYkkKLS0tIEt1bHZXcGl2Vm9jcUkrNFBzcjJv
            YlR0ZGpBd3gzM2RGTmJxQlQrYXMybGsK1VRz/Mv41TD5jePNLWcbdBAATwRSgtcT
            DlaONECaYuHwpzuq2kwgpz6A3zDl1SF8qAmfyP+aIIKJJygKlpNwHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T05:25:19Z"
    mac: ENC[AES256_GCM,data:IRl+rinpS1WE/kqBIjAYKFcmJsG0PGXR9YuKF6sxz2/MpX9hWCL6qd/hhLOe48Av4hw/viLOBRJ2bjY0Ck+XSEs1xTQ6tr1HBuoauOqFwHWBKa1hB5zmeJXPpx56woxME+8rVnj35E+pMd309OQ7KmqbQ+AyzJvqYEwUpKZu+Vo=,iv:eR7xkkuJB0/nnzIdRns/W7iHdH3LGw9Q8Nq+4/a564Q=,tag:uLEylgVWYz1vSXzBwlysHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
