apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:k7IOkkpuDYP5bMyJvDa6UDgMWjTgqZbrFMRpnTLkol1iMZ2RXfcLVdzOwgmjISRRcSZ9EJVSFoR3npL1z4Pjh14jXECU52OzmOMVZXuJzYzVnw08LPqKyi8XY1GEtw5OHKYrQ2r7hH2AaooreIsqK0sX5pFYfpKitw866Qo3uEg=,iv:7yIVjreBRmYsilcHHYA8bkoqg2ftd8TD+K8Ypz0SSTc=,tag:yWQFzSmSdkeAwSx6zP3Y1g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MGJFVjlMMS9mYjFaK2NC
            RDJ1N1IrcmRjd0lLdTFuRDhjVFVvRlRjYUM4CjJLTkNzK0FoZitHaVBXcUI5aW5i
            Q3lCZzZ3Ynk1aFlDSk1PdmZBS0VETGsKLS0tIFRMM2hwVFMrYktVMG1MOGg2NEll
            aEdYaXpLb1hZREM4NjRYbzNtM0pabWcK4Qp4nSz4ZJdGGlCS9oeaslo9UFO7darC
            uzkuMSRgv+Ty6VTxItsqMopLChE9F32vjtjPj7YXCG6YzxOyMJg/dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T07:48:07Z"
    mac: ENC[AES256_GCM,data:2SnvdSAnCUcaYwKzPal143fb64ZNWImzDMYfwttHf4OvbyxjW47iQT6rOWPrnIf3ti7YAluxlbLpO7v5zKCKNpwrTO01nqpd0blmV13/apI7FOJY6sHR7TzzO7+Cuux8h37IJJAV8wK3grNmGTkNhJCSYn20qZ9tanrPpu0ofuk=,iv:C0CD8RpFqPxEFz4Yw3pth0RX4po/bprqKP893QwL9BU=,tag:Kwdy76vzDgiIM0BV3KuOSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
