apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Hd4oS08stJ7FYbpaiZ/FmBvfdK/1L8z/6h/x9vZz1kZA8FJC3PZKsYvL+sEGS/FN1D2vvO5zlPEqxj8CzTHe9dFJ7NC4H+OOGS3AaKu3eIsQZlznC5XE1duxAeu/8ClVvTJeh6FDJymxQFWMn5yJghUefD3j7CcHoJ2/skE6wdY=,iv:NIY/lUv+IdzhHDeLaiapKkR8+9KIywVqPRT8yK/WmZ8=,tag:oBMdEGmJSZRNVlb8ZFoygw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCY1IrZDFmTitsb2pMd3dB
            NXJkS1FzVlovSjJLTEcrdEhqajZqTFlmYzJRCm1PRTg0S1NFTC82aEFYb2pqclZD
            aTVzNko2amlDN0c1VGxsYndXREM2Um8KLS0tIEVnc0ZTVTFibzkxS2FjTEN6K2pM
            TnRuZWhzcVlTb05tYUdIUTh0MkdzVkkK4YoMzky430sizm1igw2Bu3NEX7Oh+ZNy
            fBWJW/qokIsK7v2lov9kUS0gdLC6+ffkEpCdmpG69AcA1fDKlZtrxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T08:14:11Z"
    mac: ENC[AES256_GCM,data:E/vgRI34DUlkB9MSNMCdLkoD8OIlRS3BQIan44E90Gcx4VfmNhUCzgA/1eD/gcfR4Cs9e5H2s2KX24G0eBmb2Dbv30jbTQ7X2Bh49GLsPL8yJzFmOIC54k/x0Ku6GwBHfR27t1FAutkZ19M+TuUQXotJJSV9wGWYDVTPPH4oBpo=,iv:4KrbCJpA/fGB90BpHiRL4qU4mM+pfbEDr1lo35z/i7M=,tag:zXCH0UuD2J1MwEehF91Xmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
