apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:14uBS10Jp+rJ453ZNUTIpRgF17xMJ8YwWoe+HVMAxFPwWqKo4R9elFHxNOx5hH8htdp5FqNfZ7NFCLctofsFPhyDPY0/aicEtvY/PP1h5R/dWIzMCx9bgMlMCK8JXZKuuChqMDYerQWca3I/2Tzajqbb3PTxxBxvwxdLwYrjj+0=,iv:gs0z2zlLrNb7OJNa2q3dYs2ReX8+zs1DXjDK9dfqLvI=,tag:SQswKGIDtSMSuxtS1E2b0A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcG5SaGJMcXo4dWFobDdV
            S2pVUURNZUFla1IzWUhLc2FSUVBYUHBsT2x3ClhZeEN6NHd5VUdodXM3RlpqTFk1
            bVpWU0VMMmpxM2c0R2JibHRyY0E1eDQKLS0tIGtaK0d4U2NHbE8rd2txQjdURy8v
            eXdtQWJpZ2ZyZjNmRUV1RnlPUjh3aFUKu0VqUNwat6Mrrwt6fms/+ksO5vqBJmT4
            bQXTxr88gR3VWKsfBrZKZK6tfRubStF/QkxvPN4fP4i00L5JBshyDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T09:55:32Z"
    mac: ENC[AES256_GCM,data:B/KlvIBzhdinZ8IvCH+opNBlFdIEG9m7h41/pbdqxFfzB2IhTn900LgIu4+TUrxL1hAWL/rc0VszRh9NR1A2Z5CzGCguFJdSxlp7X0IUHeWVhl/d8pYJ3AHxw26drS3Q5nuWFMhoA7HukxVp8cXYaMxrPDRjnP9aq3WbZRpt+q0=,iv:okhGXcDFJQeUx6qiqHAhIhdMgsL0HOa1PuaUoKBpWZU=,tag:/v83qTN0Zrb+frTqFKTclw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
