apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:wYiovm2ywDdYluhC6TY7Af1kc6zgVD9c+LDDKC1DPK3a/NrUVcybgRJZOXaC5ziAYxYOEfhzIaPeWqb+IoCQpEeAhpj1xkjbALGEWGndfGnTLNtD3LZwfxDa+B1BP8Twhhh0Oh1aXR5iT/AI5xVjSxKGn4rA9zS5IlE7I0n9J3w=,iv:TNpsgi61bBaDsJiO/kgekMJ2FXi256156Nkq/b64NHo=,tag:jiOmTafA7e9csJJs8BdV2g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOEQrcVVNNVpTbWpTVkFW
            aDdoYW5MRDUrdDdiSUxUcWFjMEtjaGNiYlc4CittVExqcVF3VG45WnNtTW83MkEz
            QWRMVWVDUUZNSndQTkY1ZnVhbnE2dlUKLS0tIHVDZzlDZDU3QUREdlpadDVnTVg3
            K3FoSlVyTFBIVG9lWTNneHk4Smdwb1EKoBfaq0efejS5qrxZ+zVZOFGNQftnMpw+
            5YTzuGmQlRKHWVX4voy5RuKB4lK/olXi7AYNxbbg7O97V9bqWzvRrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T11:27:11Z"
    mac: ENC[AES256_GCM,data:haeGez5+rpXQNqC4Vyt0ya2SAgcTkyNWKuq7fJCazLcka+e+Upmgk7axjP6o/fCP0qTzTazyZaGQJidaOLHQelPExvaHRd+CvyBbPwXjZm0kAZBUKOM5lO/238K2u0v093aOcvDfjl3djBmVkKi13Hn5WwS8UcUbmx5QlVK+fiw=,iv:wDK95SyxLlotnMmsgPXZcbwvcjPI4mCcDczpM7DaU58=,tag:Pl1lU/Uk+vMq9EiebNu6Zg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
