apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:NcWFtBbnlKFjC1XBYYxqSegIolukXWMeXgL4PiU8Siz+/26IY0Dz23FoFHmZQaQrYAsiUsyXw1OT9y9TVIoitxUzrg+A/8ZdKX3EwjscgERCdz3SjYngB8vkulZyHuq4wbeA12DnO0AOTrk3vlJbuMfSbhVAeXLJiyDloKRWwbk=,iv:m59/0jtUxYeCM/zBL8bvWn7gDANl8qfeY31VaJ1m6og=,tag:273IzjM+EuwqTwyTtOOXXg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYWI2VmVIRmU1NkJ5bzhI
            dGVIOTdqMXRsWUR0NFJTRkZMQkx2RG5UUmlZCmFSMmw2Ti9LZkZSVDE2aE1Bb3JR
            M3NSMitkQlcyYVhYdzVldVdTNDBDd0UKLS0tIEd6dldQNE5xNFFvY3dZOTUrY2pw
            eGltRWtWamNJMUN5Rm1lQldtaU9zb3cKcJK3InGzuZJpEN8YIEHbd2QmFuEPg94r
            cmI7tedIShOtiTae03G8ZXe6IPEAhPEsh9qmmf8UmVQ5kW6UEsOFKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T10:30:47Z"
    mac: ENC[AES256_GCM,data:FFgR0QqvesP0+eQsZ2CkEktCL7+lYvvbflFW0lyjdD9FEK2O5KHa4BF0OL7MeOAoEUJyOFCQVJnFkTw1qltxZDr4cB0IuTZwBoMpZSE1SxT4jA1f7yEPGUGGKgxHm5U+1bnvn2wUes1IKU7eZ/K/Vtigif3G+utao1ugLUWVPJ8=,iv:DKY5JH44hFpzeHLi9DWsXd+x0ggUZWKQzfZcsqgGkgM=,tag:oS0bPNoEe9ZQCWoqlFTeZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
