apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:J0I2iqXMRIdygyLdaQC8TePCULKeIXHt/AsLeggHU/FPuueSguzET4M/vR9fymgPljKzqCaR0CGs+yahjbBsXLB80rjaaEvKU5imdHZep+qq3qGyRivQnL8rfil0iFwdmGfw4kQl94vlcLw3otSOH5gzY1lOTaXYhd1QNjqiJII=,iv:r1dMU7Y8aKpKhPhzcIhrlQd0FU4PNmF+Z5qNV9/VNb0=,tag:+H/rw5rw2TWbOYW+K6Ioew==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ1lFblR2OFhic1gxcFE2
            MFVOMEw3bXVraXRlVVA1Mnk1WnErN3FBZFNRCk5WZVZQWmh5Unl0aUdVejZhUU5U
            SitrbDFDSDVidko3eXZHQmhpcFEyZ1EKLS0tIHB0RjhEOXdYKzh3dFJGTnN3Vjg3
            YzNubTd6Tm1yVnRZSXJtcExqMnRqTFUKGAcEqD2nGDt/5npdfurTi7TVj4Rsuoh6
            IuwjWJWwjrRaSbpD6WoxM8ChhYiIVGuVi8TnCm/wLa39SvLAD5CO5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T19:40:41Z"
    mac: ENC[AES256_GCM,data:m3gPXoQwa7jwHR5a60ZDMRJV9t3WcRKSpdrdC0E0aEJabRhrEnhbmABCr654dh/m+xnxLMj3Ckaw4+UXl/tg458wrKcQX6hpWc392b3yn1G+xpJJcpsern8CFo4aybHVZ7d6GmKrb8x2jM9WtfMZN4zJlE54d9bzARgLy9ekTgE=,iv:C8cik3UZ2cbFkgnAD7lbKZuoxemw9A+zKTuya3W9Jx0=,tag:kdTXI7v15D4N/dg+w7jU2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
