apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Ft+YDfaNyBQjI2/FNt1yZkjV1OlHlpPwcYoNBJzeyMXCU/FuxVBq6zwUIGg7sXufavLPeRc7xGoeZn471CyCelMn1zjd/A6zkDt+A6YBJ7nO/5ztzRZjf7/PjX4VFepnK7eSknnrGYbsj3U3P8lPMujkk1QGmhjQ3XAmpYWUHlU=,iv:b5H/Z0wIhGFizRFwhjvvJTaeuKgCK6YKyv5gtyUY8fo=,tag:/ProTY4i3feyk2kT5vu6JA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaGlUekRUUWFUdG9mbTF4
            SW1ZakphU1o2b1Z5RnhseWRaZHNDUWtGUzJFClV2eThOS2N1UEZIRUpDdCtZS2sv
            UHhBYmR4SXR6SVdvUzFVdnMzbnJuT1kKLS0tIG5ET2ZvdmZCVEZRdXN2ODNoOHVS
            VlcxWmtnQnJOVnJJZWpJcE5STkZCWncKyPcqj5X2VZgotO/G5Ag9JWtOK4Rzkotq
            CpI/3h1VfK1w7DnaK2M3KeQv80woFx1SQJfdgT1V2JYn8GOwjd8kmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T09:43:54Z"
    mac: ENC[AES256_GCM,data:yLSKlltAIzQjwrbU83eQ7ruSLVMK0IOD2QDtplJnkPIGqUrEcdiBJTkwCcxbZznRdylRO+2AFUUspg97gcwjxgPBTEHjtFvNOrmBtICwskhPTOJNak6rFNUyXbKWGX8e4bszZ1qpTtCgC2c4yqP2g+KlNcPeGWYYakvT1m5SA2M=,iv:/Lg0MaXLH6N3kg41O7YEJx5dj0uYFxoNoL/x3DzjPXU=,tag:L3zUG4HbTxvyT1s6ww789g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
