apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:AS9Zyd3GVKXp+06aQlDnIF9QxF8Vmdl1pa8A8SnmuMfm4xn8fz11/8VRuAvLvabpL6+BryTR2raQWSSeN+Nf8ecwopkidmu5PwU13sx1Pl1WiJ0UeGrp0yIRCVPFbAYRc27YIDUrBDB85P1pAnNMwLOuErgc/i27+TDHO/5PdRY=,iv:CUGSQohA3dmz73QvlLcFJuJNhEEW2ofiYJ3oDNSBTtw=,tag:VjNk9QZ5bbv3Uwil7y9OzA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MTR5NHZNcmZzVXZlU3c1
            aWNHK2ptc2ttRjV4OG5SWVdCRU43Z1JibVc0Ck9pUll0OW00a0dNWE9xbFhjLytO
            akFxTmRaWnJyczU2VUxnelFtU2tzN00KLS0tIGhwNStqZEdWd2RzcXhmdXJDbyt3
            YThvQTZZU2FKcW9Icm02R01IZkpLbUkKypQ5azfEbrAZyNfMw3HG6oh2U5vpRqbH
            5u7vgQoy7Oln2K7GVXcPrFG/0j0gcV3bcpmFKYVulEoWt7hanmU7Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T07:06:06Z"
    mac: ENC[AES256_GCM,data:J94JfPU/0sacGocU0RmZlyERQXl8+CFo6RgjSl9M6sCLESGjVtWakIU7v+AdIA3qdEAqB9E3fgUTCyXlEhw5143bxIzBvTFqBAPYTP8pGDaZimWRwTvKlMjkxR4sOqNdDqJ/+cY2KszKS60Buf8/2/e+1n1WYszJ0G0lS1j9JEQ=,iv:yGtdcLem2wkNlA/XLQ4/BTPl/paHU3FYJkqKgsXbhx0=,tag:KdtaWz9A+LRSeF8OlgHMug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
