apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:vKrs7IGUTyxTa7priw8Wu9vncfyAWSFbnyoC4GoPA+B4QiDgp6HjFTlUE8bm7Ly6L4Wf3ABsmU+Nj3EA2SfHEZtH4MRD8gAiE3q/H2mb3V2YJVhUxY6mSS4Z/1fekGA3eQ+1J+mizWFBI9CUTCYyKH9HZoM6+DyeUE7337TAMbw=,iv:UvOU+ncVo74W5lrtUeB6iVG5o3oC5Rj28/qD/pn3AVw=,tag:nAU9uJgIWfbMEAwxZ3/rWg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSWx0RmpoZ1lTK1c1WFV2
            VFE2YkJuclJWK1RrY3dXdDdRVzd4bnZ6OWw4CnA0Q09HK0hXaGVmNitXazJZZTNx
            SlZGdnIyWWw1VjJ6NjhLOEs4UlpId0UKLS0tIE5DOFV2ZEpJbzljZFRFTzdKaVQx
            VFFVV04vcHhNTnhjbWYzR0hEeVpieW8KrgBfUgeS9ezI421pZlyU5eSOEPOOUc13
            dNUu0ekI+fm7e8YiX0ilcUpeUHxyMamXXc2ZffD3kS1CyknqYKsCsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T04:57:28Z"
    mac: ENC[AES256_GCM,data:0ZxUFZLisSdPwkRHIoMo65yfGo/eOknCll4y9xrYkv7pUmCu5IgGHiI++zQNce//8qyG6NUoPInA03rASUQgwuyJuMQpzUEp9jX6/Uf9ztapbH3P8FerBOlyZSGXj4fWB1+Z5SdIJ5gF7ZcQGh6Q48RArriEHfYYgXlPBEae2O0=,iv:wCltjvKyczMO+MZYCgVKnO5CIZ8PO08YHDdMCdwAtyU=,tag:PjI+STKgQrlGfpyvnknAuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
