apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:/fn6BX4AHXnQqqvFFXs+Bt+Yb/HyJ0KwkGT0T5jrMK/KfK8K7y14Tu41YyqI4SE46Pbzph0JJz4SNfi9l0ac59u3aOcVnoUP0fhxbHiJvYDaFJlGgQN0dmko18XiTu365sdhba8VBv/MZWQD4+LvhN9kPWwgiODPdfrnl1soUrA=,iv:wIoae9xTIHkvXVt70kXs6vHaPKFEKblM3q+n1Cddutg=,tag:Zf6Q+oxMyiky6lUDpseGsg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWGlDRzZPY1djSFNZWk96
            RW1vMVg1ek5SNWoxREFvdmZLZ2lOWE1zM2o0Cm9iaUZVWFhkVmxIeW1HOFdCR3pE
            a2JsS3hCNEdJdURLZFdJTDFueVBuRE0KLS0tIDB5OVo0M0ZYWndFVE1tclkyM3Ni
            OWNLSmhsdU05WEl0ZjFzbXhjTXplRkkKLRSWeISpDpoazHyjKrXyFOxTcDPMT4vo
            Ub1CcjybxsGfkWBwRUY63MEl6K4e6aXb0D2oL96/eOAMgyBUS/f5Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T07:11:22Z"
    mac: ENC[AES256_GCM,data:TERDgvDG83mWadEIGNtecNjn0Vcs6F1X3o0tFeiCS7lABeIgNWKc8BFP4ccLsLL5jA8/pr9R85w4cDMS5kqiIk0KE/6DCBus1ilekl89/UCwqpy7eD0baZ/HlJC6g+9b3NrGFZbW0oVI/vFCALhCJ5+v6paeg03KLwtO77Al1UM=,iv:Rkpu2QEMVx7APpw38LdovgIDWORp+y1kd3cZttgoyV0=,tag:EzzGK8NP7Nm11SwbPzv/TA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
