apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:0HKTpTgHn7xgMIBkf66gbLpx2pUJxaiGZ4UiverVRIscy2CsZ8muklD+ztmYJp6oB29elytG1vVt+5Qulnh3CXG6St+CKEoCcMhwiPfWCOYAxJE2Y9kp1iLnxO8FSamqMOFZbNQiLC9WEtrqcZJXph8C2f0lwV6FA2+aPDEPaK0=,iv:Xffs1/WZrhTI3dab9pF7mKcPxqSVMEdok0oGclvw6lc=,tag:J12K7NVfPVShyykzhniqPQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETW0wOXRuNDg5dDE4R2Ur
            Z2JvSGxFOHZLVVBPNk8wY1ZKaXNTaEFBOEhNCkk0SzNMUFF1R2xyZ2M1VEtoM1RF
            eXFGc3dGcDRjMDVrd1hWZFdCUS9wYWsKLS0tIEVlSlFLNE8wNWo0a2xsU0J1RU9H
            NkVmZjBmcTg1UU9jd0hNSGxVeHRHYTAKPdryHTeCpWtZ7lwZX59TawOLIhiHuVbn
            77Mw3BCbb1F+EcUg3fEm3MAh5PZ+xF7qp+qDUHuejMbHG8aK02MG3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T21:27:03Z"
    mac: ENC[AES256_GCM,data:f3yddWvrN8Sp0KJN+N0cCeybxmEQlJCtvvlA08X+sWu5Uc+eKA74JY7/Qt9gdAAIReL6BhlpGYVG1pCkCqO6xjeqCKCwOSiKI8ChbEFqd9j6G3ADIffMmHbmioqBlbfmhbcZJPxWC+42Wj5R140f+M28+R7qlE/J5LDOY2B6eEY=,iv:SyM54U0swMHl56MAwguiHrkSJl9z9BLiJZIlSTgn+mU=,tag:EVHbENq3TFazQxakO59H1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
