apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:lvPwPS62nSCMq3QHiYJCjYIXvB6M9QlmNw30zrf3kzMk3b1LSVYr/QnDm78wNm2Xw1IiHU3d7CylQYO/h5qMEkqtKt1qS71j+VBV2Lf1t0CqZ3ucdHEGEj5aa6oyej/9X7tEOSqn31p96LSYrp6f4gtDv/CEJ0Hixu558SRWvR0=,iv:B9R+688TbxxLjIHVKye27Lgx3ivy7FnYwOXTbv3tjzg=,tag:EhsYHg1X4HCVg7xigeQ7sQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUckVqaCtDYmo3RitXdloz
            S0hPM2dXcUQzQXBGL1l5SjRjSERTQWVCY1JFCnVWcjYvOWltMDk3bmtjNGR4VlQ3
            WTdvSE5jSU12ZVU4VklKVlpjYjRnZjgKLS0tIFFsWlBKeldMTmxGQ2dVR0c5L0NO
            bmRqN1pxeGo5VGtyQmNONmE2cVJGTGsK/GJZyau/lIB9+8ZIe6XRS7uUFbqQkhvc
            GsUD+RbEWlklIDIwd7qTBGfKCVfZIRvJ+U6XW1kwr94jzZwVj0tYCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T10:07:07Z"
    mac: ENC[AES256_GCM,data:76va4R5TswKNZ7wb8rSu4A37ruQczTJETIcHDsUtwp7bHP/RXGZLiDsgpc4S+PhBhRhdNoifqSYe649DVXBd1+h0MnCK3gMbbUDl+6Y+VJDgDUHiayAO3cThYLbtIPTPFoEIJ9W0B2r35vPnZfaalCb4ftcK+au+3pZyLuyI7AM=,iv:oCnPnPhGzYsKbOmG/rX3kj6tfcFD2xOHd5CZLhUh6PI=,tag:nj2h4+J9z9tiL0mY6tiQBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
