apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:pQr0zs0f1/EL750BRtcmIuRXOzCjIaQ52yQz7wD93XSRersflIq8yK1VTv2nkCA1tHRG1O8m9fLC1adB/VOtzwDjJfPm58GLVx+aGZxz0l91EjcUoPPYrJlJA6Nac+LMct4AcJC+SmFKrhQ0OAZJapfeirvtK3vpSV2OaJz/fv0=,iv:qFFuehsTWLXYXFIfqj7cRKcK95PLnGQ5ZmDtbqOgyvc=,tag:cdtpgZIcCG/ImnKsyZ4/Ug==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN3ZjUXhkZ2ptV1h5YkxX
            azJDenhyekVqNW9xZlZCUGhSeVUwZ0JXYVVZCkhqYUtnS29jMit4MlRNTlRLVEQ5
            aUlUdld5UjJETHhWZmlDRGwya0hubDgKLS0tIE5HQW1FMGR2SUdTTHVsQ2M4dmhZ
            Vm5VVmM0aUtuMllmbi9UTTByS3RXZEkK3NjFs7/Zuorti6D32lAa4lB3KFHT0fUk
            mKUQklDl7Fy1x4GI2SHRZ8ygIfiTxDfcnvXs0fTyKLOQTEM4YVeRCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T09:59:49Z"
    mac: ENC[AES256_GCM,data:ZYb5qrfwuU8CQA1YMvNvDzfNYDD7Z3og2tUJP6LDvzreKJesJb19blDGxGnLqDB7EyObOGuE9z3qxjv0UrBCiKNFHHarFUmwMb4Fa1Z4EkG9OFW75WMBtQ1bMUWiTM9T+ytlwdvorn3xIkaumnPq/YMlPJKjNLW+YLPXBw4Z7T8=,iv:QCfZ6w7hfy4DenKFMGamnRl6Sn7UnNDZ+7KokrS+TJo=,tag:WWBnuPPSf9XGDvHsl+TLLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
