apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:M9J8goPHWO0AYySdS37+WBn68GCgjfK84Jyi5EU0xuJ3Pkj8n2SXJULJrn1LkfPM3gWyaab4agwPnX7L0Kr9NDwrXim5vreuA3tIvldufcVOL1FNArBGmyn8kMgFx5k2GmTZ6y3ncejq4uQnu2HpD3UtRgKnFNH5p7mT3RA05AY=,iv:UaW06zNp7wl9JlhK6ZOyRJd4hVtUiUKwk68b/RcF7Bg=,tag:OyCWo+g3m3e9elgNto1bYQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEd2pITlhzcXNHZnhXQk1q
            R2JTWVora21IWTVUemFjczhCakFXQ1plY2t3Cm9pb0duUDd1VUVSNmFadU1XY0ps
            bjFJZ2ZJMEdHZ1dhZDJVckw4N3lrdGcKLS0tIE5hdFpZN294SExmQXVrVE0rYlAx
            MlkySGt6RzMrbW8ycVRHYkUyVjdWTVUKFd8zfP75mEbKMbTZ/+6IAICiU+dzCDgt
            bTAjWgpTZaIUCRz+Mz6ohpuLYZkb6jLw7wKapQ7v97VvcQdoRM+fbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T11:00:31Z"
    mac: ENC[AES256_GCM,data:9ztoWixNKnO/dZeIN/hY3k38Fa/s+kxxpVU43fg2IHbjjlnrsqYs3unOvNPxxZKcaMY0fPa/jWXyAek2ReUTS+7aAQUIUhBGr+9aN2OEDiBgAFEos4zLw7dOfEMyyBKJrVi4r5ln8uRYbGdBdWv1/y8pdJI3KZL1LMt0mxw9pL4=,iv:0i4BetlJvoh7wan5HeEi87LzhmYy7TfQzNW0gMlZ7n0=,tag:XoMQ8pCG1QB8e97DoBxO6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
