apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:oANHHYuYE0sbo+OzXue4SqTEyBuqQkx9GbG/skWtFJpcjvgujhHmUeCOjGv9AuQG/yP/YhwTIyVqkpyA7N+47DFPADTX/DSZ32QUkN3fi1yFutF5V9K3WqBnBYoeHGCTCJX7X0B0vm02Jqekp/y2R0SyVuAIbthO6msfkLsZ4bM=,iv:9svZEhqkgAol3GoJanH8dnbGpvQhAbYT9Q9lpbPBoL4=,tag:nT5TvXPqsUpjP6PLjdDiOg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcmtNUmJmc2xGdWtORzNj
            eWlPTHZQNGFHakVDUGFHV2wwNWwzM2J5NlRVCjE3RW0xNmdEbHJSY1o3c0Jka2dW
            SFBYODJCQzFyVUlpSEZUMXFSaEppL2sKLS0tIG9hRXBEYTdtbHJTZXhteHAxckNm
            NUNlWElCa2xaUDJueE1hWkU1QmhsRWMKf2sIhYf2KzrYEAf+pt8YTOuR3sfCJfGv
            gaR1DBpfFUl09hwd121+7Tfe/oZHylLUtYew5oTZGiNwMUm0eKouew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T10:31:21Z"
    mac: ENC[AES256_GCM,data:IAWIONoefH9gQdkIhBRBre5rcnEfUjlKeJTwzwGEqlBkvtBPERgk08pY/zNxLsvZankWVAKEvxqN/gLXFogGDjCIQax7xpHTai3HBTtf3DZLSl8wwnn4j6cZcosphJjwDldxOQzM2h/6Dw6ZFj95+7li5WNIHWLa9SHxZDiYAeQ=,iv:H6/aY4yAtJIv50XqrXdHXqUHc4Mr1uBknfEBvHCB1/Q=,tag:1rAx2bW1K/753v9FvssPYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
