apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:G1eBxaBMdSPajG73HxymSvQUqFe1gaBu8DfJI/Hyav6e6CPDDHdPt2AbRfHb91BFKLZ9ceCrBSoJKPg9C9sojckPQElO6SjdaIQ+aBxePF83jVLb1fytVwbWaHgfraXVaWo250cndlVb1WnOudyBkCK1FhMQifi+g1vch6RpP7k=,iv:OnjgqCWnvq23J+7y1+RdFWa1ns6NPcJK1YKIxYhQvNs=,tag:9TcaXvmPxAFFidMvvHGDSw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeFExQkFmNXkwV21Uc0Vj
            OFBya3poVDAzY1dGUjJUT29waWkvZHlRR3gwClQ0eGVVem05c3VpeGdRbk1aUjRL
            Z0YvcFNkclZiTU9nMytkOFN0WlpLSGsKLS0tIEhHQkdpbW5WMzV4dmpzcWdQWENi
            OCtxVzk3TUhRSWVUcjQ4WUVZSVFieW8K8e2wMJds3N5Gmf2tVenfpZuMGS3kInPz
            M18S622N6EzPTkCcbdbJmVxM1fIZcN5D9OH/yuimVs7Xva6YNkQCDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T08:31:15Z"
    mac: ENC[AES256_GCM,data:rg/edaYNVMjvwFID8tAOBRkmmZI5/dOilXzTdBSxsXJrzxa518KXv40b549WrBv2A+Zhy/AZo+MWIK8dj6yeDyFO5/QuH8pnXOyp3rKvYjRF1elwDTzElFhifvo8GfS+VNMKJaHlNGuoL5ht2mOuGQWMSV06d3PA3SFQ/tMP0aU=,iv:NPXO658WnbPqcgHUeVtfXaAoWu70J3L+3zic4Xo3hZM=,tag:qLSEDVlIuZsHYl7h7xOpRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
