apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:63/7nBo0xB9sfpHYfe/fErADtZKTRMHiOdoNgn9lc2bm2VyGjbntYW+/AF14cYAvgY8sxJHjhpW++sUxEiljH3rDUdY470eV9c5KrOQHqJu0b6BKeLAJorPRuWu0WWFKAceWQQyn73MEuPiR3adGPCeXtYsYdQTr7+ndIQBz3H8=,iv:35z6GDjmq87wLsdosxyKYNmyCpi5yFtuNzcTjL7B+dM=,tag:zMkP7rWEIyqVe8SG8PokUw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaUdsQmtWbE9iTjIxRWda
            UVQ1YlQ2MDNRRU90NnJ6L240WDZsZkl6Z3pNCmI1U1JwcktIQ0JRYjJ1Q0JkdTdY
            d09kZms5NEhSVy8wUS9uQmVpNWtXQUkKLS0tIEhJRURpM2xmT055Unk2VDdETnp3
            aVhkSXc3a3VHaCtMWUlxSTFuN0ZpdTAKdgI7scEq/r05VWJHTnCZ0ry+6ICLvrhH
            qoBnV+WVmsKzqF1+n9WmTuORYY2UyXqstSXU+6M9H/9Yqolfv6REqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T11:47:15Z"
    mac: ENC[AES256_GCM,data:ttdvHIY14YrsRxOG0yOqFbQi3ZvUTqeKfQXwo8+6SX+olE9LXQtxOpgXe7yLIKNLAmXSWvagZrWfNGi4RH1d5NzA83Ar74ITmaLcunso0dmLxKQOKph9NgLp9QAg5PFEfi8XMc+gmsxyNYYy+XblqvdaklPvKFfLvBFtcZmNAPk=,iv:sWJWuC0J3+2Un6+x/yDl1Uwe1OXJuh+CQPWT4nePBkI=,tag:gI3naZL8Cjq7UiiWQol+QQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
