apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:ztebVTVUQeOQMZc0wvESkli7GPoVR/Vlcg7PDFFJsXcyrNKql4YycwLJTtr71OJeJP6b1DZl4jzbaY66UFXZSn5YJACJvCnUAIoeLHHegBYyxhzq1rX6sds4Swz1siEflaQWtaQx+QDjgAQz8xD+ECoRdD+FI8j/szCRS4K/fTo=,iv:2ZdMcrsgUCwTeL2ol1ZASlRJS85ieS4arqCbSenHxpY=,tag:ni1mLE33v51lP/R2vYIZQg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbG5pa1VYSHJkMDRSNWhJ
            UHpEWDlTOC95TmczZCs1dGZyWGZCWFdOd2drCkVYV05nL2tTMVU2VmlaN1RpZDBT
            UEhhVUhKWVFQNExjTkYwd2ZTMlRPWDQKLS0tIGlvb3p4SmZOVWVldUxHcFVwRTAz
            Ty8zSGMybWFMVytSQlZWNm5XVVptTDAKb0ReZE5RtG380XwnfzYXPsp2SHegFH6s
            tbBAp7RXjSMxPquDEWrid1Ey0qgzyJsAVLSlOAJh8DgUz5DJOojyww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T08:54:46Z"
    mac: ENC[AES256_GCM,data:cpZ/n6Gnjn+OfIig/q8dBuVjrmznYAYL0uetgLRj7KjvvFB1UPO08Ftk9viKiTde6cPpUEnAkJUra1PkXPaMkl09GkOxHXJRcTQBJJ9Eh5bq/x7ALgdijVTLraQRZ5LPCozKIf+ijYKVQ6Ev6qIOrvNHTui4nvIreenbjT3vP9A=,iv:strzS3Xs7Yc7e3d0fKlQ/34myztL9cVLy6LlKUcswEQ=,tag:AK8y1FKJMv7jSb9oJ32FLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
