apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:EHKgV6VvSozTvKLM/nOOiLV8tVss7DpzjFRBgP/AiZ1nyhbsfmn0PkB83AwcvlREfWNnbahYHNrIH2tLnAWtmPhGpdwGdxXAND6WZF7xwS4OsBsT1N65nojfkUJ2Rpx3SKPExWbMC7i8oq37GAFj7AZ1/A2rmKwvmkxsrcX3P+8=,iv:72393wJUXTlDEoIBIUVNaDUf+8ZaFIRUN7J5apYRdlk=,tag:NJVOe5KxpBlvtw/WnA5oXA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQS9zQWpUSEJQVlE3cTBQ
            L2pMV3JsOWd2ZkxXL3NidElzTHM0RWx3VmprClhrNnVSazhSYVRndnl5Q29VVWwv
            dnc2WjJxMmpQSGlKSC9KQXdXNkd6WUEKLS0tIG5yU04zeWNIMGFvV3k3YWhtN0s3
            bUliNjhrYi9HTll2V01SN2IySTZrS3MK8PuJfNTq+3+Ci5auTxEL4sy0BKAvzXOY
            564vK5AMaOySiTB5cuW3RVKBBh0AlbsixtSgiFqIKmu4aUfebGaiOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T08:43:09Z"
    mac: ENC[AES256_GCM,data:QwZOysznASlHzo5WT3ESHqkqcXmyCXsSFooiBJWJnq3Xzx6BBeYsktafmkEdQ3/b9SR/t4VexFcKHzvyQQXMQ96cUfQgxEexP5O6UAxq53Kgz0IhP0bDmRr+NOmEd8R7Dpyyg9HkzvtUt6SuZuMPPWwPOOw5Rcy27sayCiWj0Hc=,iv:UAa4rkSeNNvr8RiRARjfiiaR9JQQ6Kb5FAaS0DAzKxc=,tag:feaV1hfpH2oj+ChaIbwVrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
