apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:T5ql15cPLvR1XOurTPpCVzSD8I/bmwsUrZg0CHHYwUJqpdPjaqu5ajVkjFfhmnPwe3LKVjdu6ELlmgjiszyqtTng9b6BBRsByrOGabrwR748HgQunT28ASMMoK4Lzg66IaW0DgWGm2g8cT0CCF3B6SlYuNQuYqh1DAiHamt5Mpg=,iv:NKvd1TLF3G7YFfy+JBc/AF9SAgs6EfApumpo6yAz2t4=,tag:aMTNMoTFQ+Eti1uOQP9obQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bVJ5TlFSSGFYNVdHKy8w
            RERHZ2o3dHhKVEF0Q2VrMW1KM3QybDAxajJJCmQ2Wk9BWkZZRFp0RzhwbmQyQVN3
            VEZHaEZUMVFzcDVRSU4vcy81MEV6TGMKLS0tIEdBMndQREswcUxFd2pZOXBHOVhm
            ZG5hOXhIS2hxM1FaV29CSTJNamsxTHcKdY8ZS5ntk6ifAYpj4+42gg3uqoY1wTK6
            1Z+I2+hHMxQv16rUXfnjMyL/xqVW5pMrlF09owYJEFf2hvW1v/TvWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T11:06:09Z"
    mac: ENC[AES256_GCM,data:RMMn+ZAIi9/bVbM1Zv4UL94BGZ9kHwErU/iRJpKW4ZCGMuxq54ltjUxGeu83gWIfW5S6KHvoqOzU5OUimftiUcD/8IFaJAzlaE+Mx6Tn2j7Z1+1G4vypOWpblkFSKN3SsyvXcvrzRtXwBcD0nFU5HTratJLsRzdkc3eybOkYg8s=,iv:n/zL2flflCP9NJGfNiMEEfuDsZ12yR3mC5Ylspxsa9o=,tag:jIhcg3zhuAodDGcBMM0otA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
