apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:+9/vbFQUWZ4aJP+tLGwhKiOOXdjlXShqFw1xQ7Gdwg2noPQwCn+hCjdhuwOjegqk67aLOo1o97XvEu1B8rO/hkOjFaJGUVT/9ocFXjDU4PqAaWXOCRbWjyNviQXafUQ5VTY4J0fQlky2VfGv882hh1crOeqtpeXgIUc7i9ouk6I=,iv:/J21Mq7VKJybdhBKWkn9QsemFOCyB55bbjF3ihHhsM0=,tag:ysky4MhXQjMWcrkGZ3GWew==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscG5DUWg0bUc2eWpSaXpP
            c0wzT3FSMVB1azg4bDAxdjJackZiVEVNc1N3CjI2QnJJWG8rSFZjajNXZy9nSEFh
            Vm9mMjFYS0FOZ3NwY1krcDYrL2NITkEKLS0tIHJab0hGbWhTSUhtR2pFK0VYTnJR
            VzJWaWkwR3IxbFRHbXZRMGpmVUxWYTQKurtX05AohbXqpD1mW68T1X5lq/O+GQMg
            t9AXVkFinsqN13QFnoZVg/rAIWtP1u4pT0h+usK0ilERxuOxPAia9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:25:19Z"
    mac: ENC[AES256_GCM,data:rfbjFBCFe5WDq4lgr6ut2hP68OCda+8JJHewRbdYnxoaxjMM9lBxIdVXh2v0v8GfhWBQtEkY7JZ4wdK3CaaShpNYDTOCzDrRujisRh75d8zoycHPFqQhufD8vm3rOJL8a0hCnX+KIfVLtchCADDkuiLSvFFKVIxF2F2MLg15mMA=,iv:DZG49TMgc/5XJhdROTRtynyLqkeStHFRN3ZMBL65E8I=,tag:UzS2XdRxpX8r7EayF6Zisw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
