apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/4J8/oSgeRP6qH0lp9+n+4QLJ6q28ev+Kiq0jqmIaE/YgzZH4F/J6SuExjyEOT9N0mNQedrPYB/eCFLKxbZJCkDPwdu1zM7mqEiQi4SCeZmtNRMCUz2JikdcoRrdEuFJCKCG9eA2+5bicSuboFMWWaYXwLDfJzVHZ//7IjYZb+SEetuQiEvxVwwDfiqqk8WtP0pQ6Pn2uWWaWP2JsJSNbH6xjFEsU91XkmsubgsMR10TrTmnW9fVKbha1B+36XkpClFB/LQqY8cLwdr0157POsBpAqtR0lu/7FZH5g5+dnnNpx4W0go492yK0M7ZBUHF4XaNBvoPOgZvnlN4G/d4Ylna0UVW1UO0daq+MolU2tzrX98CiTz/Krv6MgrFGZT9,iv:K+r0RbPgpt2BQR42ZpTExxlO4Y+NVM1Tr5IF7eawJN8=,tag:RIusn0Sh13CPds27AapxYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:RvR6cpIyBA3IV8IdfasOVzaYAqb/ZGSt/IY4E/NtFAl+quXdkfldPysb+smo/nwylGB7cGCBz9IRp5KGetijxcKxY9yc7GYdXbbqZZ/abeuVSt1WVcTDZr7b0PAcNnNMZnAjKMVcOQohzZkzfd0cb3cwdspnjhxbBCpU338Y1mG9tV4mTYVw1UJEkg3d0a4VTyJoDss03Jd31wkfKFl1lMfFY9TYX2NXdIVY9YScAy2ay8O7mji0c68XyA37Z3BNc9hg4uBymoLXsYcR3g==,iv:JyFM0OAWgH9Y8eRo96mQtsz0eZqsbHojKsA8EeG1G2Y=,tag:Kqcs0UFkRi0froIiZXuSkw==,type:str]
    known_hosts: ENC[AES256_GCM,data:tawNsnCvR+hNT0IDtqNrkDj/oAFlQcbJqD1mqFLt3ZXhpNqMBO0wpCHGb7+C+oHt0PL5R+vDh2h4UelrRP6TFiRQO9utbdngX3LQRET8T+5whi6V0TRHN/heb5WR/ovE4DwNch36Jpbkdmu5uvuY34d+45qL4Bf6lACkX6GYdcu19bwmZIlstjP4Enk52i8bJ6Yu39ZSpfoXxu5qr8x264PW7TPgOz1Be/Rq,iv:ZEf6ZCO2tv0NJjd/pnbtrzUwA4iGFF/C9TH5zlOkYcU=,tag:SZLl6WLr2x83Wk4S7G9RAA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aDlxUmhZT2FOb1kwMTYy
            MlZIY05oNk5xUmZ6eGdEQm1peUxHajJtbEYwCk9CbTNmOUpQalFLNDRuVFNLTksw
            VHlhUjNKYzRaQ1Y5Q3J6NHhNL2RrcUUKLS0tIDRhR0gyQkxxby80dE9EcExtWE92
            by9EeGZIUHFCSGlMWWVJUkxKSE9GN3cK08PNTR9pN/J9nF9VdYOL4zc+XTomc4gG
            u+9Z7ws33Jv4dWLSKuuf8eJ3Ej4qMQNvBAf40QALfuuTgpAhZVCx2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T05:55:53Z"
    mac: ENC[AES256_GCM,data:3egW+ZwKqdLqBCjSQmguqbwW4wFnfyJ23KBQDvCFhy4KLX6glePuU+ZI8AupzJYkbtcXq/pA4o31xBmFQ7zU4v42DzjgKmwog9oY5jqjoaKe4FHFKvATcSc+zbVXD+6vAfhnCEhxmKabJDi6ZavPWIe5DVbkwMf3b8nyDM/CChA=,iv:Gjd0qZ4XEL6b3HyecAI9Id94IDvYUhtx3RiJw6HhTmU=,tag:6Qs0LvCJS+IMoJIyltMMYw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
