apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Rnr1JOzTaviJPLGIe1ZOuhnv4PBMB1wOuP1uhkJ5/Pvh6cKjAs7HrPsTfHKxUbO2PBV6hSDJfLpAKeJUgp2XN+g6l0iEL3V49K4/G0hHSbuyZY3D1cY//cSnQt3KUi4WLwm5d0xRnQkCp8igfjatJ2UDD0TMO7QIikSbkgvkjVwa2rD7u2aQ0jxRRGZwSWXb2+DH0DCFrh28dwe946PPx8uxEdTZeILTanEsa/UddcbpADtdufkdjqDstwRIh8iszT4/TO1bY87ixiZn22Jz/EcVBJyjvNiSHH1n3BgtYxFxUYQbjl+Gej8gl088or+uqXUSXenVO95ZW4+w07KXCsrFa4Bdcw3UhZ+YiMjyU6H4ezwHIa7uGyhZp9Oxv43l,iv:/p+bxsAZSPEKB7fl1NXa3OUitPlQjZLyICLDfYjEkNY=,tag:zUTe9PcLLJsDOD3RJ2v/xQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:j1jNC8PiHvkwEBor+62xkBFC220L9kEWml+dNpYh/tcq3dqFYv0ul5F4Bf26c2bMdxgQIsIoLbdzilrKfrZUHZQI7qlZUrQEwfPSe03br8e56f5ze5GKoeN6h6plgESSKTX4OmLhoMjmP/EtFae0kUydIofHxga7+5aZk1/dxjqesW0J58PdgAO8gShF2EkE9UrszO4oYD8axULNUlpvnXgNsf6tQBcpjdGnDz7KGBz3H6JJv0Qni8fa+VafhD1jghrTa/DoDCl7tWH1tA==,iv:t8TEaui2g1vX3MMnL2MUdNRu/BOx3gT4BcCktkRwvhs=,tag:WTZbhYwyeWs4v8+Th2ot2A==,type:str]
    known_hosts: ENC[AES256_GCM,data:Akmf8ChEA9UCv/J/DLrtxBB1A1+RtnRlmVbAahZ3ydLCcIUKhb8jYVTOKgDVJsgqE6CToBmJT6ABys3KiNkxXKYz2ms6HbJ2CLe4Na6uBQwecDcqZ66t3ZQwi+8MomS/oo9qYcRPAf1HyJdbXT08mSeLlEBoN4mrCniGfLbJbC71v2hr5zEaiNW8F4GENcUwtohdiYKR5zpD/CCFoqapk8b+/TQKP1Pyh8DV,iv:lPR6ozC1fZ8Dby7jOgSiAEnBAp9W32T7kSnm6CVoclo=,tag:4YKh0PRoTurfZ1iIJfJ9+g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVlR5bjczT1lidnYrbzQr
            UXJQTjZyaUdzbEFuZ1IrNit6THc2RGZaZmpvCjlFTzVwQnBvbW1rZUgxY1d1MytK
            L2VqU0hKZ1ZBOFVDblVPNmh4b1ZpU2MKLS0tIHJhZjVyV2daQW02TTlFV1RvQU5k
            SjdJYjJJYzJhbXRFcmpKYlVybThaNkkKIkHdDamQKhzryrF2Kyet/Jz8vOodphaz
            ryCIKp6IhdNFTnOPvxhieD/6tBfljqI/gcV6EKInyv5EwX6SwmWPqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T10:31:15Z"
    mac: ENC[AES256_GCM,data:pmKCNE2xfO7IIt80vPV7BEgFq3ydW/hTEWnSWnuEJ97l2qS53FFUvDSlMTjVbbwLyA7TWmt3A8s8EvoXNmNbOqHXUoPV0xVhXRcoKoC18YwmYPUAU+PKYVk7csw+jgC1MPQXiGfxNVxVMs8mmro83QjOIshF3DG5xEKyQYFdX8o=,iv:meKm61RFlM/h7PArYZSOzpfCSNDE/KaP06q+dlHTMg0=,tag:UUVUPvCUhZ2wQNtHtBbDrA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
