apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8dE0sIfuU4eKIsy7FsP9GGco+zMQN3zaNuzWdoP0Ja+nKWN0mai70TVbx2TvjoZP2Sk4w3LMeGw5Ff5PzGS6N5jQJdJXHLI8b+pFvIeuzbgSrHpEnAtTmtjEbYLtdJQA6dF/ouC/8xpjU0SXLpShtzyz8Xc0Q17F1XfcP8K3DxfpPQ1uPOFglPV/JPuygAjvRuOdodSQwQ96ler8rIUgFG0SYUJyaHeVBR8JdZLQwZTAisZwJQI4FU7Fry9A3+pUJnvTO2EJlTSllf6xqpsMnTtgGVM2B+iblWSMTllsfix7rdo9wCQsqzvxHJuQ/OYXxXmyZHepQouT1IprJ264slxJbW+I4yO0FHEoKXc5TYXEeFKXMdp+c08lm98LATxV,iv:xPimQkizq+uSPTs04/56RycmNlkd6MAXuYdAy0uub4U=,tag:W2gnpmgXB3XwPro3aMPCog==,type:str]
    identity.pub: ENC[AES256_GCM,data:mZK0zzZ8APodrxfqJ9NRPEkGTDgS/IQnyGSCZ9LgKK6MN/IX2OqYYl+C6hNqgUuM8YT9cNdB+QGu+bNRPtYn1DPNJsOZ85VGC2+wLvdb7EI6vJMTCQgX06oCH+0qhEa2l+4DNlayzUd9lfCKbmhfEFGq+TZTwEhfXceykyRfCAIQAtg7YvERxP/LNA0LBw5IML0EixNm6bq5IBS/CbodOBGiozDulksxv5c4au65vUZr3y43C6YMo3M9+G/t0BdI5ARMrqlUspPzu50/MQ==,iv:yPWnLisamn3BcJsZRZS+a4i79zQzdDjrUTw24aVhpDQ=,tag:Hr3pz16UY7mf/6ebWW1YDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:hdk/dptibVBn237H97gXihB+7WCoo6AqBqQmpbeEuSsspbeDqckcC/iJbVvTLEfpbBvFBaE4uNBIB6GgR/9dd3a6kRw0b/Ez2KrdUwLRLDOG6/GQBUFGFhNFfsAY3pe+CZt9RYJDLN6giCHTjbjLYEvxVYMuVrcXFv5Y8vwS+I3EiSlOh7XSDpmq0+CzEoNKQNG02R5qLScGKjfp0Ud3SKg512owNy1ZEO1e,iv:KdW9xIEn3bMc8IdRz0gLC55PrE1LudQA+KPSOuU89Tg=,tag:5hHOASrII6A5lUGwC1Ct4Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTmpNWm9TUGVPQ3BZeVdx
            dW1WRTRqeTJJN0dNNkpuZUpZbHJscW1NZWtZCjFvL0I5QVJ3bWIzdGNVVEtmU21T
            QUY2bFl0eGk4YVZKQTZTL0s1dFM4UUUKLS0tIGVTN25jQUNzNUU2RlBrcHlvdkxO
            d3Z3c3UzVFk1ek44SnA1TnErejNQOHMKmHAGsoP854i8kPMfkGdBr1m1ErT8smUg
            mcb2gXolz9RrCkcfgnsw/9s/cWqc6jhGEm0wBxl2jn9UTXxUxSKoZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T09:59:49Z"
    mac: ENC[AES256_GCM,data:mjtQd4Uc94RaVwKWI1fTyawzz369p14H4fmS4AuGYiY2YS0UeDnM9pLA+cMBjHrYEgdpmlOooqwKI+kzx2kzeFWOJs1b7d+LRS9uofa0nB/H+/IkRQYGrDKbdd7wwBHNkh9LBTQFpFIgcPi0WNYe4cPaMjYrvRtjVF4bdnIEiUI=,iv:aY7R9GZltsaAhho2oSwJXk9TDUxRLu2m/1mzeLrfmzg=,tag:TMbb7zlsZHTQRbG6+0bYig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
