apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LHRLDv+CFP3ZzW31aFSSm2I/pDnR6f8GBvf0geEy8VkuEuip8FQTf24E5ZlXl4LVBvu20WMmEV0ymxibFmgX8vuj9bP7vi18bv6u1FjF+ht2GDsizxbc8n9QVBNUxZh5Nfg7z5TAn9U60/lwDi3C9MAZTy61U3jY+6H7dzrh/s8M53N0vysTOPv9dsQB06ny2AnRD+2H6p+6Pn+0j0oLK3TIxGiWJfMBPFuMNle2agcts4pZ/RJ0PENci6YDe4IkLt+5JJ40sdg0Vy3QvGMQfIaJIg6zAuBURhGkvXjp8UC3o+z1EPlLFXNDt/YrH9D+ap+5ya98x+QrMLl/IMjl5joV4pS3WDLI1CngTMIodzJsc1rP5ojl9FUmxMOUFj1J,iv:CMALriFhci3UsUricnJFOsqgko+pwJt/CJKjpZXfiY8=,tag:2qOD5VpNEIDd3+PaYPz81Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:WVOgID0ddSp8RAg9n6I5hQTOuM6dfh9Uh0UEmcBez+IQM7yoiAtOBQfDad9+6kCwCqeH54jz6BWnk28N1mKRenyAnJoP7uufVPwteacT0LRQ+ckNUYMabN0nC9b/CGUT3YSc5poQftpsfCYPifWbN2+sL3JDnIlvhk1Gm7deK5/4MoyjQLdZ9kgnUjmx5LbmbdtXzErjcsHCXmPCCMgx2hfBfkL5OC6LkocgwvCCD5ppnlNGpb6LX3K4qIQH4EbsL/i+qZgH1WNoj/4oJw==,iv:WVhdbBPZQR8p6+yQ9KJEISB9pykgP+WOIF7y18uDgPU=,tag:IKcsNwky8vNLBdHbgeh7rw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Gf8Na/yenhULxq31bl4CzoWJuSSsS5C+0N30hdIdPrIQSkMh+cjQTq+nZeOQ8ZuavrVlp70+fQevMrIwDoxrH4fpovQAmy6HEvmKLOG5n0rQ/JfThGuxha6wdXwFOSIy+zOYkorsOMg3s+dd/KUn52NxTEovarnrQavfm7A6Vdtr5I1rbjhy1PRKEZdRofIVAqXw7ZUCGGZJcfYUlsCJheDj3P61nLLFd3GH,iv:tPUlqVJorcMRuXOnvvRSTJjQzpRGZMTbKyJQm4b1LQ4=,tag:VFgAPbTTxCokpIboEJRNnQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQWdzSWZDKzltRGVrRk9q
            R2J2RjBzdEdrOUVaNWVIU2xXOWs1cDEvZFdvCjh3VnZOS3dIVmJla2pZdGpGMS9M
            WkpReXFQVXcrVnlDUjJkSHlSWnFoREkKLS0tIHNoOVpwTllLMSttNStUbGMxRGs4
            bDh5dVVlRlRvNjdNcVFxaFZ0bTkzTG8KXXdCyzUQkU/85iFgeeRYkQC1MTDPjcII
            1zM7x4Z2SzH5tQWXebVtvCRBHmfxrSbwYVU2go4L6JexY0YQSlG//A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T19:51:34Z"
    mac: ENC[AES256_GCM,data:GhT0gULMk0fhbzdT7EmWDafuWXlvGR86jb7FsTWeYpQn0Ip/JYsySD2Qsr/7tweYL9FO7gv6IiRsFuq+3/NWh3N6//dWfWHv/ZVIM1n4SkwNphBX1CAA7ZACPefronogHa9kdKNngOCkMjRVhpiZ6SqtmYeGpbZuIj7qtJxgKgk=,iv:Km+hzvt/JCbAh+q090ueDY9eCazeJfeRbBlyWugM090=,tag:CSGS5jEP0g6JqbMz5aNkOg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
