apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:i8h5SqUV8E6kANEhXC71yih18/FSre13/aQGiTBZAb9FsSvLzcwSua5HyhzWMud/KwWiAHGH+B2AUXpERQ8WwXLODVkPO9efbEfPo2tRByiJ90t6Qvp7kW0yK5d+rGVrN+K2/btOdYftBT/esWa+NnZYOInSWqjoUCGYYedBXUT5VwubxF5FcGeB1W1FPpCHW23G3JhVjlfIp9b8+1Z58lJgziybmybiArHjWCJQtQlLYSBkznxH7GYC8GOKYonhyRLLoJWanSQItssZh5134yq3EafMkYrh8gz8na8wUVXc9MRSdIGbP8wEFyH/+7YUw3Ib+SJIAHFo+4lJ/XLlYuEIxx8x1GDAlLCalqiAMup1h393eQ+jOvRHLKmrx8eC,iv:DnzU9ot184Fy8AwWG10bJIszA07E83pD6Nkx8iN2+W0=,tag:WCJwiEcxTnEiFDu7Qn4zyg==,type:str]
    identity.pub: ENC[AES256_GCM,data:vrSFAXhwYcI6gC91xJp9t7zfCeT5rHzJUr3JKfmCfy1hxqZzFzRJAzEjPt4vAwuK10zz5s34L363zSEwPEvcmrNTVpUlfcPooVn/xreVI5fsTCb+1budhAOqmjmf9hYsVnqlobJ8c7NAc2+k6MRxWg/3IGeTGyeLFcTVnS07xevQg0kSFSrVueG0jUALEmEpoXi5Fw6bEEzyZ9eZZZOkzou0S5SEx5XPLdfmMAdnbcOLhVo9725KVeDPFoPSfTrI9UlxU9KZav4EplEApg==,iv:X74+2/fJyO3pbjL+DTbIn28dKC6At5gh9FlN0Ja0ZqE=,tag:HQVA3Jzxc55tlbN20bpnRw==,type:str]
    known_hosts: ENC[AES256_GCM,data:MTcEnKs3db4Xpt6sGYh7AmtE79hIwGPCBWeEr0UMA/mfuAhQSe1pApjmJn+nBlDDmI+4y6IpPrtbclxzF++ozBs6Fae7BXjZCFpsjESzTtGWA/N/5ONmRw7CKRYApjA4E979q9W1K/ZWYyFlb0fCs8drGUe+JiKAIlEpxWXVhtBY+qgshwRU+roIlYPQndfNQnj6Vp0A5gicOwK/r8Z2padkdEjR7qCLtMO7,iv:jpCsnHcjv9w10k3x9iIr1P89BvHJgEQoT1Vp+LOG700=,tag:tubOWABlo6rPCL7ZL71/KQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN280WTJ5YnUramx0NkR2
            SlZYU0ZJck12c2tjVFEzMnRpR0grK1FCdjJBCm14OEdoc0NPMllLcGU4UTZjdzA0
            bnNnelVvN1RYdUpHdHZQNmN1NzVvcjgKLS0tIEliY3RNeXVHcmRZdmhzSjg5ZVJT
            VUV6SjEvZ096L25sZGJyMEoxRk9CUGMK5AtoEgs18Esu5VHqSJKGDvoB/JDvYZbk
            CqtG63wvypixxbuzxXxbgka9fSk7NyyG59YQ+Wk+qTOaGecBJkDocA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:17:46Z"
    mac: ENC[AES256_GCM,data:gqQlazxYUd+bHnvyu9vvty+loO3gP6KZmXx1bpoUj61PyWDrvvVtOOJ/4NvK421thM93FD6yw/C33HBli6ad3RSLXWWS/2Tcs70mUccse4m3jbVZHFXdydr8Uw2ozOR/T1GE9/CR11Njz+4EMNGqGi7L2pUYuXH0KzT4NTEicRg=,iv:MMo+cQHVT+zwAbjrYfHzquYOCj9f3r0BhpGgbjpqDNE=,tag:jFaEd430X/stiZuqkQm4cQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
