apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0DDp0am3vv+LONT+prgujOhxTvPTfoSo93Y88h44ggAQY6iviIu4ThHr1/muUtshozAXylEgL+K5UOJNAdSaG4HNTwutQcS0rpK/kTg/rrFMu9u+yFZb/uP/0s43r9kOAyepUsMMrWfQ/OpOZEyUWnjjeb1CBFrBbFQSD9Dw8dSsPQaLtevc/Oy8+0rmk9iyZNqz3144OzQiIIv3IACUA0sYiGNGnAXloHy/qEgvJEnvT6pFjXVBqovKOSwIg9ekbU+CPbf/Jmyei/xkkGMV038NL6GfcQYa1kT1etNT+NSL3r7rR0siuTQT3WzHgtbR9SnDTDETBAnCTHnqexYuIbWkevL1lOoJGVDwYLPQzI8NYyQsz8bZ4IJMTYTLnvOz,iv:UeSLiD152TMA8qWua/YAFBqybdZYIEqJAxmcFc3zups=,tag:fGhy0BJccvMbWdd6PvdeUQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:pxd06UNaVDyo7hSpIRtT5EdBWn8E/b60wPp7h2FvzEVygkHouFSV6bMvZy8oQ4szJSJZgmWgmXVI6wLVnlrGfHooQC/IXPRNDkEqthkehAsnRX7hbA+SgAs4rHgNVTT7DrVyoK6DzaObi4whyUpdiBjqIAZgCcMmoNNju0Eq2qztV5NrfsdfDCcnppsvSn7TFfyoO6vD4CYiZqrBNZOmHwu5giwYegQvZgPGhpjyMQKx1rNtQa5EvQluiXu3QvHPoYrGtjOJrX42j9WeUg==,iv:MH13gGnEiCXV9tHhnuQkCm/3XtwORNvjflVfNqIhw/8=,tag:KieGPMLzWEngVE5vZKLO0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:tLhmBku6gYucgNoinhWEuq8BlOrfoAjvMre69WJTG6wITAzgOissw8WpbbTzvzWPxmZ23fASwwBB0p3qoscpbTqDG4EnY9wCa328eygtRe3i5R2w8+L6kkGVsngaoJjKHUBU2Hd8cYo1LDqw0CwV4yCG8WOR6pQ9vD3gUh2sT9bQPKJNQArnu8z4JA0XDBos0I4iBhTvJ2DWN+gThpFIGckcL5q+vHHgknn2,iv:837PAFuA27BuaZg2LjbfY7146xQ/Zu3eKPtJY7aP9cE=,tag:1WoEi7dwGN4zfIurGFqK3w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRd2o5U0V5ZXRORHFKTlhC
            YWllbmRBblZsSzc2Y1BYYlVwZXJ5a1NLaFFVCksvcVRLc0o2YmxIUUVSdGhwd3VS
            bXhMYnVQbjlBc0hKTXdJNlZzQ3hlZmMKLS0tIGRBTUdKWHhBa2FScWhYaHFUeUpo
            c3ppbjRVTmkyVkZQcHp5TmN2ZzNESnMKqVna3C6wN4DRaizOXjB9+SR326Gfz/88
            oylscIQUDyGpWLUta+k7bKfSixKhYC322CGdntyRBgLqcYuNS+d7PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T07:48:07Z"
    mac: ENC[AES256_GCM,data:YzH22CbqgoUjVQkY1sNQJVtko3u8rfkxpgKjWtdusP/V6em6uIZunQN5SS2WG4eL0pXa9N/Lvk1vz0A6NFX7hZF0LRrTp+zZpkA1VJu/U9f+QLPmw6/fdYKUNlub+s/0JSmiCA0nPoa111pMtlFix8mgtHyhTEGRGuYjw9kvBzw=,iv:8GrAGvHpbT9niYL3y2mpX3zPDzvPXwxoM9aOhb6p2JQ=,tag:4bEYI4bTeMkWySHhXzxhPg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
