apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Nh2RiPl32F578ygpiMHJXKxQM2PxaDC8mo/HCdk6TjJTDQ30KV1RTOOVN0PDl8J1hJuVY3o4qGgCTmtXxa3tN628qKwUIRderzz3B5EPJj+RDy/+V0H7EjHDxJJwguvEZbESCOHDdLRcH3xyv2LyKsArxmSVgWlYgkFuMH1LIR/GF5Uh7C6gBOKigbjUEVwnBcwgZZh5CuwPA+SxXlYvAjUoNlAz5Zrm2xw8hmq3i3mvt+PV9RpX9sW1CvaFYE362PcIFGWQ8YaCxiKNoq6B1IuBVqNndyzDOzy1Cf9s9OhxCsSAvNtV5Qa/uhHLmjKwDB5yhmxTgUH6+Zta0k8tnO9LeLAorkDe1BCq7saMoezu9Yi+rNQcvd3v8rsW0Qtr,iv:p5lU1YWnZGEk3gYLThcQYQMj9eHq+LvgUtxEQeZHxgo=,tag:NgohMTXiU3u4wlZ51LMxQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:NKPDMOV1taYOozityANrfkIh4hnHZjLC/u0PzxfD5Bb7L2KBSbkkGLQ1Er0SvA4/GlrBWKkrCIcpayOhe2R3kQoH2Jl6zSKRrypwLaPerkTc7nmyN4tIs1XO2azK/n+I2nYYiC1AQ/mrIVYikYDpuuoGUZoyXJ9mIc6fwVxQZWUYlHFn5OIL4NSot0bvrnON189oqaCdblu6viEQXTcry2oGT6ddxqSPMjmykgujEcvxUXXnTJm60QR56t5wyA+DVy2oZfHBk5AJdJaoHg==,iv:GNuOlTJxR03gsmBXDkxTvLBLl6aYCtwe5y/g/oj/Kh4=,tag:AyakP1C9Dn1eaNk9OenvwQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:OKl+NIF2e8EeDoRRJFfEbMQbQCanida6ycmkFG0aHVg0hqHZkwj/2AHeRG47JNum8duuKCL3jiyuvYKyxgvORPWadzqm75yuXe2CZJLIvJ/eq97FVf8C60FDiasKzYwa5lWIqQydeKpMRgfGuMDmJ9UDxKrUEo1Kadl7dos9lCWXOWLq2R9uxW2h7JkorKjiM/7vVGkfePbcRuJxw/Smf+IJL8oM6utR2Twf,iv:lrZrvksJXv2+fNLZ2rTcgvM3OaW13sDafgWRG2EFHEo=,tag:hoHwzDd7BD1l/IdTk0Zl4g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNUlxQm9tMGp0MDd4VVpw
            NXBmWFZYTjBXT2V4TGl1QWZHaVhGS2FRUVFnClFTOHdJR25ZSGJERlo5M2kyczVk
            UTBleHl6T3dvbHdFTTdFck9tRzB0alkKLS0tIEdUa25qVGJSaDVrbFVjVGJTZ2lX
            dlVzaC83cHVacEdSa3JDRXN1UW50Sk0KoiimEP0PSwyjvZODxdE9MzEkDAesNV53
            AbXXkpHfJ/OQqD28oS1mwW7nz/u2k0unyYm7F0sEuqA5eZZyppTgLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T09:08:15Z"
    mac: ENC[AES256_GCM,data:T/NjdmWY+vwOvp3nbOJDaCkOvlWr7Ybg+gSOeym5UPXT2N4PrSZnQPLfjF9rdxFwO56W6jUHo0VIPd6pWjMu9aYGF8N3dWoBJXR3pBYwvd4txjZT0h2SWQoQwaJ3EkL0RiGCiBI8iaSaDnYaZNSuFyNYuULqfQLD4OV+P++nnpQ=,iv:VkPIRMsr6lwWovTaBFBB8CHrzmXQdhsPr8qp2eQV9ig=,tag:c51HycBB0hKNZQnh8M4VAA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
