apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Wsb1/vH2xgBc8ZzIB3lZP5bk3zlR7g3wlUCh11Bz8fWPoans2Fj5MHQgivsjlN0R/aKD5ohUJku6bDfuB/ksfFr+VWzE0d6+1HYDNEWNN3HYBOvJAza6cyVQsZlcnFvyDBFbiAiQsxcFwIhGM05Yf3R2md3Fz+g+t5KQvrjtYKZf40jw/B9ra73R7HxWYBZL11Iqbfqe5z5qJpeiBUnCC3Q1lFrGGguGgO/J6QcXMtOnCHP4QJdg7WLHnWAiZUstqjSlTveatKSlnZSFaUEDSG2pUANDWOMeHDqOxMOXncWssjvxjXztwPDfIfqUgoLL5JmuUbU8fWk2AuZoHiD79rdHnGpQThEdm2I+1BfSchGLlawMM7VrcDH4UoTX0tWX,iv:U1kL3FNNxzjsxyK2wiHpCNwreWoM6pzH21a6pu9TpS8=,tag:Tdbj/MojkJoc/ZLihUDoOA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ytyaRDB8jhbIWDe0Y91pZnAzAc+n1ebe73D6O81sUvx/yd9MTB80ioKqW79LleN9t3NPyf0AnCSDF+iUoFjh45LsYS2tJmzWzZJtzOb4l3W3h+u939fTP9E6YNKomZ9H6yyizEP/EJrFmvTT81MSI7A2Z7yVEKABsiuZRKsSfXXGqrI0mt8PTGQ3zm+0bj92WCWqgO/NQW7H7RLbRO+IVYD0lZdEQKb1Qq5Xsf1l8V3spjOqmbARBNnsZ+1ygGnDaN7GnAwXcw0GJB3D2A==,iv:0VParQt35s59eQoSmqh5GPCjTyjVC/YC7/oCLXoMbhA=,tag:ZCX45+TVzEiE7AbJzAiFvQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:salbY8AHpYrE3QzsvCPIvw2EbNnZWFqcjoRj/6h19zAbGB0ccBso+BCsNwule3wHm38M90XyDflCseP+cIJ801DqGNqh+IJvPJrcwMH3dW9+WLrjauouLsv5QYYQHoyvfbbbwWXIWteIxyBdoRBbePB7F0vnrHjWeyKP6R0L3T+b6Z07f7UP6mr4UQqNsUfFKBq4cnHlx4ESB22zLsKOjKHIVlhM1VE5mz+v,iv:WSYsgaHIoaXr0iKuSTjMGWxVp2QFLjyFr+RCtq2ud3c=,tag:zzUC+/ORi4FC6lfbdXHKwQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV1RWRHpnSGc3RlVSRjhD
            Q1h1M1pPQzhWdjRRS2VxeEppVE95NVZLUXdnClRFYmZnMWRyMFYzUEp4WFZ5NFdW
            dkkrWm0yYU82SkJ6S3MyU0hrT3FIRnMKLS0tIFpWUGkvUUgxcDRicFUwb1VMT29N
            TE4zTkNzRkJQZ0h1U3dMLzhJd0FwR28K6k7WNdH6szS+JfOpAZwCNb/57PrQgaBR
            kNujz/uciEVko9s6rpMCDY1Mh6vqVA8mwmaoQ6ULaLSZkIQimq5C+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T07:29:19Z"
    mac: ENC[AES256_GCM,data:KoPvtVKnqTeHXtPRQL/8HNpg+cOe+29Wsi19CNJqmixDT+iSFM1abSmJ4/UeHFZ65fk+Pgkf85U7hJN62129ELeSkPhUjIx+37dT7TptEyG0owiAP9aTywPi2WEuThTcQfrKcLlshHvi5LgtOZg4EqnNHMSUDysyclQ1Umo9CAQ=,iv:3Vmh5Dz7YLn3dMoSakeQ+ZoT25PXczSsRUvI/Di5mqA=,tag:fQ6jGAl9vV6xTNxOqbO4rA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
