apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:h959uEr30Mj4mFaMp6O0PBcVpRaIg5Vz0Gw+xkRJQz0OB67d3tkfMCl3DrJsYTN2f4aOX9AmIzkbASRbCziT5VRRMDYpWKyr2CmXS2OtPFBqlh2YDl6rfmyIc7ArDIuxpfwb3+ULT8kLSb2tjPzj2Cp2A2/lNHvuZ3m09n/cOJQaYo2tZnLPnQvbZ77/ui8DdnM8RC329QL4uthrFqYucMbqP/SNfxSKPeTjpZ3sN5/Hy+8wLyFN8mtSUctYl3ekJGwmqZQz5lIIEpyYDrz4JIUMz66oc5fH7MnP/TdweDX6lS4xoeK14/CGKnJxa6KdbvykBrz31QT/gk6d4wOtRL4oirdvCWoSNXqs2UaYUqkO9IHryNGS1hENneUdNerX,iv:/HK/8Y7HuVevbJEkhsMwM9lR8IEpHHay6SMz6uX0nTA=,tag:n1kHQKIRTKoOEeDDO+KPxA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Oq8eK9BGlS2A57CM3/H8I/ikbnQWcMsO/nxPjOzNLzspgERpiw5S++D4lgXksHEJpXHGdTqX3LIx/RAnlH5jHHEeWVG/hHkGSWKGHGtRDdKG3XW4Pky0pltFHnHnNWf7IRNHFZPGu1oDiFiIdtFNb65UhvS2peDt0tTFU//9YWBt9HOWLOJsWF3hJFQzJuXXGzar8z1GuvNbX3ARr2YIHBz0kEw9eZptE7Bm1Js0M3nyvCvf9TrXsyRBSm5tF0XFTcBeA7wn55gVtz2lqA==,iv:ioP62VPPVJc3acKwnKOEw6iqoESVqrOCgMQpERY6lRg=,tag:dhdEcoMh918MTwZUivQAcQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Y9v8+m3cY6g8Q2YBdniFEeVP33ZkMRKxpG9shJYk6yvF86dIWHecKXWOO48ywXmRgZNLNFKvSyz692sBEh2V7mnXcPMcuv3ECPMWjtOvwFCb94Q7p5b0zwHqZdFVXViQ8Z1icQVbOap4aQeumpB+17gcy4J9jMSW12pJNatb9AumZfrQRUjkDYDqMQI4UOnLVFSlP7OoqGjQhpFgB9CgXdSVxXdTu8NEzG8Z,iv:pGcbo5tWXCBKeQC7mLWO0S9haApSNEm1J/byGHEik10=,tag:TxC5FZy7WgZ1vgyQVa/bpA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NXlJUTl0Rml4UDBNQm9w
            Q0wveFFxcjdEQ3RoaGdRUkRmd1VoSHJaTkNrCjB3MjFoSUU5akhvSHI5STNDb0dW
            cmFOSy9ZdXhuMzVxYnBja0JGVmJLUmsKLS0tIGRPdmsxQUZhVjJzNXdVYW9EQnVL
            MmEveitNSWRuQ2trYllxTDRXTjNNaWMKeZON1XNrdAsi8Wpzks20WzwmsEzwpMGt
            TEys/+hpWcWAx/fpPKUVIMXlqn9ZxMepNjaE0OWIT0HMVpQlwTPKdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T09:07:00Z"
    mac: ENC[AES256_GCM,data:rVZuXN9kU/zE/o5m7oz/xpUa/T+bfoxnbsLud8TvNIAXI0n9RPaxPr0E7zs/5C8h2Jm95BtGRF+39U+BpWfhJBxUx6r2PxhcUv1XxMj591pHjxNWLnXyt8zpFE+aba67ZhViPlhZQxVHK5Q/KqzPI/7pmhTH/fo1AY1iGFXkK1o=,iv:xOZmUVbuyeb2YYivRaFeXHMcDFeIahc3nnL+mREvJGg=,tag:k9j+fdR9U1POOMyNR8rmuQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
