apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Sz0LolFDA9vOwkMqfUG8RdPFjjybWGSlzawnAt5xTOtB/B+VjCYyrge+X505fMkBLfruQ9bcrT5Gtps32V8zo6O5uq5RB4Fc5zNmT2iUHxwuEyjec6RWrTmmCyyrB+vgtsOLSrYooUpXhx5Xv9tEXtXd7htExTSIFJdBFd3Ki+hSR49tIEyAJRp/sNStEg/T2M3ocVM+b21OTS7zrELesdb0EcQwU00/P3/qPHB3xW8m3W0hNKTEznZgPFZDce505OGJhM7DodigplEicGEWlusrgnHxPF9zSVo7VIr2Tqq7rAFvBO6ZGCS53LBO+5Z8Boi0/+J8XjQT2ERhqNmuvhazfscHvCj+nfWqYi3+3JOt5jx85gDWh8gfK17UZQsR,iv:TuV6XSTGRQQPShUcUsXvwoGBc/j8PW3W10UTpauOYJ4=,tag:bRNCTr/sgtK4eZHiSvXWCg==,type:str]
    identity.pub: ENC[AES256_GCM,data:2/mo8WxBo2yYj3/P6/obksZj73TFu5uueWi/72VNXfJH6+fklyomqWaXy2lf0xXqSVhOaO6lbTN0DoI1I1Zkn8NMCYPFD++3BbQ2EocVl7PjyM7WHjFULwUOf950PXLBfzeBvul6xcKgxOJduWCPUBRGiBYwXBrOyIgNc4h4GoRJ1jKcxWj+74EGIG37Tvj/x+oeJ1PJoK3LEDEWXab70cBc3Kvk78PCllPOP0MmzY4TTKVEXQgk3qoSsOq8UvQD4fKSGITQBGTDXql8iQ==,iv:NlkefpV7dpF8Pa3ATq4XM+OhvqFqk/RRUCj7USOBJl4=,tag:5T7QnfDUrh5WJQW4WrP9YQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:4a6UCOFPuSN+LJ3BRHH4b1M43VsSkQ9jhlSmohrcyfVYEEhTcejarhKHnQypFsnE1KXUfbiGZA0U+8WeK5/GuPbxYSomZO57Wv4GFi1NkkdmvzpSZVmAcgiemUaWBB2teIVd2ZwenNod9ZZv2fMcx2+c5Kt/z3iA77Hcu9JcALq65FDxkAS5EvfcN9iCTJzI5eV5yLfi8gQPNnhk9bfQqkw1/rSsmKBHeK9u,iv:C8mfnIt9WOeXxvisocQClIqMyl60e1sXVQys+sjd+Vc=,tag:SjR7Gp0sSJcBNVlpBoBnGQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMXhyMmlSQXV0b2EwbUdY
            QWJEeFU2Ymsva0RkMUIycTFzTGpXU1pzR0VjCnluTE1pSm5jbnBITkluNmFTcG5C
            ckhNZmhsSWl0akkveVJEUHplMUlDcUkKLS0tIEx1S1U3UFpzV2xKMHQrMmNCMXFt
            b3VMdVdUMTJtNjM2WENzN3Q1TmlsajQKo9zHHdN3pHInYVmV7SWPts3wdQ+m2PDC
            4Z5hPkTizPXPakLzzdxBwFz+bDuwDnzDbPPxQhRyR1rPfB0TgoUjxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T09:39:40Z"
    mac: ENC[AES256_GCM,data:ACOxs5CJj93GMgBBmYlEryYDENO5klwlzfalBxhy4YcOWWdQtzi+wH8TteGgkUZeK71SCOYejUQO2srHMPX0pEcKq7Z/2NJkJwOzVXMO2CtwxfAVCRXhgHYg0ta7inR1a9KTPJov9VVYaPwDIeU9WPTgDfCYttNWbk2CwFaY1Yc=,iv:bMaKGlYzItnaD5pGLds8BGMBPRW1DcS4ZUuYv1XCidA=,tag:PSHDAzO3LJjuNrbdyvj/Xw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
