apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pWBfNlOA8iKgKPUf9DOqF9FyE6rTCWNgONP//8M7BM+awKGXiNou2Nrdz48SH8WU+EWwvT5OifZYAhlHUGpq3RHSv0LYlom5u6Fctm3G+qDp9j0gNg3HqrQOgMfLyyr3SLDYRbBrOYKFYsE1F9ayiK7gmJPnnrDKnyPAm+Xx0Jm+tFmuse/sV3EmiY7hOpkzxj3Rd9hvXzmM/S4zV1VbReWLr5IInuV18Qtep0dpIf5O6H9fZoTX9+gj+a1rGC08D1DET+iOeSd6HAs/XkIvI8MDMHXvQ3UnZTj/ETW5kxDMkgwvdpoOYaIAdO8C7fxJf5ZS8mM3g90JgYkFl3xsVJSy283qjw3/fnF4vc2ABynMPlPU0VDxsNGQnl2N1xX4,iv:7UwXDh5jqXDOFfJEJMVFfgFkW6X2jt6scz2BMMcizkk=,tag:zOBxGivhSAg5rY6aRDpZ/Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:TeaIXrYsqaiL5y61cq4NE3O8Ryr4SvLoCXvv1/ksrwxdnzdYBccNx/XlEUKv4gat6fFgplGq7siM1azGbI/jzCC7+MkGHbU1fuBup4zi/3DkHETJ3ZguxLFFHD1G/2pcSPuJ7ntvA9Dc28U3ioL4Zje3DDq76XnR67ucm63HGGkAVZZrDUaYMGxbT0z40sZgiMQdWOUfiqM2kgfe+g58WPTCJmr8KHgvdJXzfd4AULKpqwGLAbEVGQ54WKDWExDGQyQgcXVEutETm44Qbw==,iv:H9BGHudUd6m+ZlpA6zYtAjQSW4L+sUdiKBSQO0Y1iWM=,tag:VM6C6iAYv3XSkGw7gAlLkg==,type:str]
    known_hosts: ENC[AES256_GCM,data:roV61bA+h5AIuvOgBXBXkAZShRPF+hAm6Uu/wyMM74g9Ml7DcjhG4pW0R9a8z3NLE6iAQvQoWO0YsEQdsIb87xWhVN7I7u4SFFdlDY3/V5yeikridtPv1xF44pF88KwK4SbFgt8tU3OPmqkSUWqnOim6ShXK198HeTNG7jFh1wdoxrRb3yoAbwkLY2AyeAJKshKSjPTENhK6t/zawoBVYpQMHvz3NTrD9GhO,iv:MXE0vKfugwt9ar+7dDYkoh9pCchvQLlGIJFyR15Hj/E=,tag:3FuCVu4Mj7qoBd9kVyb/Qw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M0d6bktzZDZnemZFYVhG
            L21kZDVTQUZkOVdHQlI5VG9xNUdBd2F2cXlvCkZCeUhEQlZqUk0rY3RLVE5kSGRi
            b2RKN045M1lNeUpvNUFIOEtiYWZwb0EKLS0tIE1EZ0gxMUVGdXFEQUhhOGZEby8z
            aVBVbkN3M01qY0ZHdkdXMmhCejhhL3cKvAqwknmx78ayrZ3L+cpK+56U2BLHdZBH
            poaPTNw/U8zYzOKkC335KH2cPRuhDbeP4ULI5lO9ncV2/dn6ub1RyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T11:03:22Z"
    mac: ENC[AES256_GCM,data:mpSN3q7zuA5z+TZrIO/yxnw+FBpN7/pg0guM1LezIzxgMEeBDbSZ/MMLuLNdqpvyoCKluX2C4Kcw0EY3iDGUD0ceuw5hOMcTmkjTU6KGUAI+VrYY7fDkUbUylBqqxCVYhoeWibMRa80uScxzrnbMJFqcKUEY3Z/d3rCPsXIAaq4=,iv:gDS8GVtiJBQCYoM93T5MBMPhg0m7/sA/HJuSqrFiGrM=,tag:aLJLqNF+2Mn49lz6kPsgIA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
