apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GCZ7yWCp+mfOOFnSrF0TKN9vCA30R6JMra3lLebQ/84LQG3CHJLoG3QbQ/oENscnbzI1Fg8cBbAnpZvsjPGLPs0jT1JRF80UoXnCnPPE8UxnrHmjcQDM0/u290iiatnEwrKpudML7FkvDuNdVT47RDgt6UxBUiS+nyaQ5clcudZhmG97bcXliM2sq/CYRboAdNgT/j8EmNbhPST1I/3WaHqzlysQv2S6MkRdkhugWRKQJr54clv69000Uuw0ThGRdmVbvEwwBic2knGxl1GS+PrdjgS406ZqP3E/Et2V21X07XICAZfpABj4jM8wnWRkwDVt/PAciRHN+Ic7R+GfAGzgzH6b3H4AzOAuRfC4QH3bi/wrsgolRy4pmPTxNukr,iv:er09Juw9PriE9PBycdYacXeT//k0zp4nL/bxE1Wg6pE=,tag:CaunhR/9hLEUHIqyqFINGA==,type:str]
    identity.pub: ENC[AES256_GCM,data:9eBN9sipJ42oqQsh56H/zYeWkI52zJ8eHn2HFVDkokLD6NYMIZOC3g3XaqLa9TGsP4S9C5vwxcJFB75wrmMd1a/CZ08cYR1zwAZHhtRwO/6s2dSIhdHRaHvFTwXKIIH6+ZFKTkbaswr9jqZKL43I7xBPlU9GkuNWgTekjZl3PbsHjxM5hWBJYpE7rBYPeixYhfG7icpKaixpDDCtV7xVAEcR5EfX+yqjkBKde/Kghi8N5ECi8XPxBA9IwDBDidvrgWczaef84SFQx8G4Ww==,iv:zKddWplUJ4JevFAC7ak8Ldzr3CJXWpWMjfV3YR5+vDs=,tag:B97r5eEcp9P3IsXxseuEYw==,type:str]
    known_hosts: ENC[AES256_GCM,data:dDOg7Q8EGSfzl6lAJSJlZs4AAkkPk+WqlXCsIJq8GD7P/SDe9qy1YQakrKTXugm3kK2oYlb1/q8dDrPRac0/NUz7QsLpohHqlKIJNnZzts4eXdrSjMr2E/adFLe9KP6YGl9CQ1G8ZbMTy5ZNImTCvHXYIlnuspPuUMWjD/var75Na++fJjibiVeTs2m/QS1qoUELvtsFou0/arVY5NXZZh0Aiu6COM1jQNgw,iv:H0dlD/toYYZKIFMprhSb8OVBWf+ElcN7/mkk2MZuYJg=,tag:cqpsqD5qB8FJf2xF6ptCRw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR1IyTmJyNHhybjQ3eTN5
            Wk5CdUVBOWUreHYyOGsyRVdWbkRPRHQwdGlrCkdEb2FJWlRCbHNrd3VzTG9ITG5H
            WG9mRFQ2RkF2cUxudjlhUitRWEpjajQKLS0tIGwva2ltd1BuZks2NTBpaGFGMmhU
            TjhYQTMwSStaWldjMnhySUJwd2swU2sKHrXIZTvi/d8qSeN8UiWQ8QtC3l6PlML/
            8RhX/T/2V3G4GL7pfN6LTee3NFd1ZhJykF0kOBQxREKiDLmfY0wGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T09:33:53Z"
    mac: ENC[AES256_GCM,data:TkXWJJHN4uMGEqiRE5HrE4qWOC8YgyH2m9+EJmr2aasyYIOIr4jFJxdy4gbfriEgn6O6yJI8q7e5KsHlBRugNp6hjyK6hB4QtIbimmxsdjxLG3Ku/i6bQnl+M7H+12HOYzi5sfyBOZP0maL6tf9/WT5lnpli7Ja5J6UJBuwB2OU=,iv:8tNTENfIgYd9u9xUoTmKyS1f/4O0zVzMMMR688TUf0Q=,tag:aVn8cC7zmmTykk0tK2sdWg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
