apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:srD1cgT0uyQyPtqtl/oDRvVDLFPiyrLWDOGHfw+5aOIvj3FdsgSoMQNBg8LfToLKkdaMvkZTzgJykrgTOx2CBi7LjIcHbqgjaDwnjvm8VBM18GUfLodmGR2zraSFEIZDLQAuV0TRfkKrdVW6+MO8rfAu7I00GkeMsTNVabzx7UkPnbKYxo+rSe8WTWdj38izPhpNkvrPAmpal9VkTy8Oo4OKMa5uMf6SzgkBjo5Cje0Gk+fy7PL0XGo1UwHpcO/nm7CiCwPCb3cSwyM/h4Y1lZywuEtqwnlPIJwIkSK5tkfOFIySk+ja/Rn187uVoV90ydF1qQ8bt1If3ZDpqT6SfveI1deHiMRC79CiskdLl1rybrMJpZScrA0yZE/Mzz3u,iv:nLiBCRiFXFVClorpuU+0dkDHmxzGgabZ6fjGj146QGg=,tag:Z5lJbIr5d0Xt5ts7WxWEQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:whIyyo7wxq7z7w04P/rYhNLrmiiUCjFaDazVbaG2nPoqF1+d+PmCfOALdNphG6fnmbd+3xcEkk1Nt+3hCQ/V2j2MVAh1sRWNc8hGZ54HvR3p76eV95k+9d7vXlWoVyUZfFg72DSkpBDzWPvwwDb+I+sDBGDSGGtLORRs+hxcxydwOf0ACX+mf1xF/Vf0Y8DY0SuiTh88MYeJrJdVMJgCy7oqR0wmCsKLJVPNmNA/zu6wxH6ILXGA987FgEt6TWKDMI3RGrMLti2hhex8VQ==,iv:ZB/WW+y5ZYAHQ0X9WrlGZTCJPEwgoPCjpYr5JYdGwdk=,tag:xp6H5drAGv7UscHzu+zC0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:L4toXdXX6p1eiJDveadeyOuFkeaGxukcX3lWiNvdHwGNtD+7BzcmsblUlBxfd7vdFvpQnG/5ilD2s75b29LC8ymGpKYrwe/ZMLvN+P+/uWSzhmLhSfhAP1qAXXN1TISPs1QUM3jFmOVdcxXm03j0hxSgWA/ruJynzw1gm+TU1CtuHNOEUAu714onbzyPDTKcZYNtBlodrqsmhi1wDWrgfDcJngvooL6LlAiI,iv:w9IVAmye6kr7Aawpk03fLKWLbpVoiD2LNIWC9m6Piks=,tag:n7LvAiVyQh6dotN4k1kZDA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYY3ppZWtadEt0VERWQmxv
            TFZuSE9GdlpIbElTbzU1SHRNS1JmdkUvdEZjCkZCYWVPTWgrMkdtR0pTcEUydE8z
            QldCbzgwWG5mYzNzNURBdzUyTEV0YWsKLS0tIGM3dUpRUEIxME4xcjM2MzJUMFdw
            WGJwcFFyWFJOeUZSaUlYc0VrN3RiMTQK9+S63vTW/ZFgoEQuRa16194G1qJd2YAZ
            e/AnnACeyxARwzqPFmXNZ607HTFPbCNX1n/saRlf30eWYqh1DXBmyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T10:22:54Z"
    mac: ENC[AES256_GCM,data:EmyU2Yr8v49s6J21xM0AdYf5RNrzxJaorxcBoThPBKKZq+znrmTfEPzOZ3Wgws73FqXgl73Fh/gSn6TJRkn00yWXd+CKVIe4dctJ3PsxUJ+ozZzlB09w0VmM5Ub89rGBCAOkwDNp9ptiyh13ytFLOKOgCBjOi9Rjd0QM9wFPx0o=,iv:JZJyizEYU4yh6A/iHOO5oWexg6lMOv5plMjbz01Aun0=,tag:L/68D4dlGuBCxDi4b8NZ5w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
