apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:m4ezcP+F+Lo6bOmooJ4TtQV3csBzYkETAW1YHVpF3ECPQQYSutmbRZzvfynzljMtK+Kgoqck7LDQnIEM3VfEX9JErzTd6k5GhPuLoJRU90d/Tum41hlmaqBv3TjbtlIbOaBONtyUi80urLr3FRFFjIzV2VfBYYc4pHS7vNGlKtuM5yHVO+n7h8lcWMNBHDLboeF0SQfp7u7NXxtMlTja2cyv64Gf+WgrSj1sFlSSB3RYAQQeHgtygwJQL1Rf5xvqZcDLu83jhx4nBjKxpeJOQaj7phWVDcPNlMUjEgvmrN+S8xRKCp/CwLsXCKaUvqDKQu1+1Hu8L8WxAAPxo8Aaq17y6ritZ5EPJdI88hkzx64A83KJuWTi8hQZG1ociw9b,iv:C2XlzCjo5m/NfiGOwgz6oFz2Nx2/VhqnSxw/r4FAaqw=,tag:dcRLl/jH9Y0X+HwGHVjNcg==,type:str]
    identity.pub: ENC[AES256_GCM,data:zxB5uonaWTi+t+dtBr1HimmHcbP6TNsaWPcltksqvZrZwJtoRpNzB345/qH5e5geShAc6QDvOl5KV7o+14Gmwlfx8PxeV0InczvQEqcmk5LOqPWGt6EszoCS/OdHgoot8hLRPPKQYjz/UsyNOxDxT6cDoudM/lb3wzsAJ7lifHsGYPCNr++OP46x2gQ1G2wiQ6por9TA3EIo3q0AReVnd52JP+alVE8LLELjX0tMDyoT3CA3fKEIYSMjh0Afiwa7oewmX7khTCjT2KhUOw==,iv:7DYEffy99gobhOSrpyIL2OPo8tUjBY+4mo06P80wwMc=,tag:qU03+hFGZlnwPQk8HCYQvA==,type:str]
    known_hosts: ENC[AES256_GCM,data:bXsGFkTdTp/JxaOPAjyyytQ+8HlCPnWW8f8gT7kF2rLg1ua9CaMWI410rVvqF0Lnf8JRyZO04+tDqlvv31NQGq66RNxxCWOwap5IcIU8gU2oFq/FryRlZ/0xONgzPA+u8h2ELqlF5O4T7mqXoZ77VsoEErl7IFCXowLfpzaSBtXnHDHu/VSOY0O/p935tiSOXuzT1fDNRIpqzpEET/XYiQJM91BdHmHAbLI/,iv:fhWaZXjGbhekY4PllHI9NBazMlhXT4rq32SIDiYTeUU=,tag:Kh30wpEstsbrtYTVFOV9UQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eWFreXFQNUdvbEJIR0dM
            VWNVb0VxMi9VMHVOcHlDa3gvaTJITE5aUFNjCnhVdEJjZXRXdVJQSlRZUno5dnEv
            YlIwcjh5YmNiUXRWZ2VwRUxGVmNlbXMKLS0tIENvYnlla2dITm1GUTc4YmZIcmhN
            Ui82bGQwd3JTSVRvTWdlQlpPcTdPNVUKhhuFu/4Tef7KLr7BeKUHY6bgUZYKLdBr
            90DeXQRJ6+mfX/6j5h+9M5aCc17Utd98aCZDxi8XmQCBWlw4jF5ZHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T11:06:09Z"
    mac: ENC[AES256_GCM,data:qCFh0xr7GGYlZcnp2OqJYqOFsPqdoi4grjg6Ci0ePmLdx4B2KmbaMwMjXjsmGA7ACv9BuloNw9KkvwfQx2BkgDZFlTtdadxDVg1iKH1dGETVEB/VyLe94qUzzNSIdEwWnvktry5OVz1uzD4MkuzgW+RdeVsYCh3UYE3kUN32wEw=,iv:YkR+ZGhHxojIQGKX5d9mfo9nNL87XQkdKda01fBcyQ8=,tag:JtK4OPbqO/1UEzxtFbRJfw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
