apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eJDvHI9yyMFZSX42rsEqqDnM5xolMFheJYtCZOvjNpjOJT987fnd3EtlCayzkuNDlYQaAUY8x8vKW2dNFylW2sSj6Vnnowb2VAs06aFdD2E1FwCUfbNNZ0iPcLJel+yZbmUoQ7pgF0E7A8LHnPF/WjtKslWR3+TLx6IvK8KUICOYxkTZXEtoYNrz4rS/py+fQkILqSXbDWEVb/VmLVqpppmFs0XSuc0KCTz90knDNCDsMqTwHOsihx51JRFKhVXxkiVNZN5F5SGhVRww+n8XkDu0hmUyO4wFOfJRCWPffFHnOSx25x4YaJ3ouoEt+pl7xof1lT14Zr6dkSixmqUrdvBWvMrKjuCmrG4qCpKZj9f5xAZCNg/sTUeprhteH61f,iv:OWU4oYYO6NSVKMEkRBJzyn3wW79qi0fjuH5/ULbYIbI=,tag:XlyRsvPtTCkVi9PiGRbnJA==,type:str]
    identity.pub: ENC[AES256_GCM,data:4wLgXBYQgBREs95goSHc83+5bahIXBhMflj908k9ApjTAYfNzu4jipNqjgsM+LwH6S8eoYeIVqOXh9OYARrPJ2s6ArglUzI9F1ts0hmdbeXgCQc/fA52Kw4n6eRJLzOehHEoP4SB1zXTc60REsq2Kr8g0SP5r27opuR4c/kkMhOm25G8DS3dyw7FxcEJrkfFnyamaWJJnb+ruU2ui5567j9MH1OvFh7TpMB4/ounP/4MQAhM4HF0KJzqdcj5768xg8N35VC1EeG/2cYQnQ==,iv:IjS9VKHjmUaJ4rHIqKbm7WnQFuIf2cgqlFs2/V5i+MU=,tag:npqXOSWoHzCvFZ6SDSVxog==,type:str]
    known_hosts: ENC[AES256_GCM,data:ce3CYoqDuqlcTmXtOChGvHCMbDfggpa8XxRR0Q8aqct2LiG4kUPaCasUia15PILIAIFnp6wrSe4ey9mkOnPzhPqhGlrwMwlZJFl7jnvypn3HlTsQTNgio0VjyGeIBaSfxAPZHXl4V2WWw9uwwK29v02VDRAXHF1Jjq9zhgxLuZIeLKux0viWVh7J164zjRcpL+cqAJWLYM9tUaTnvoeoGpxhoJoeob6UOyDb,iv:R1ayQumdCE9maR9wQMHQLbfSC7nWl5kRjtmOsY5KIxA=,tag:uxrdIoiklulfyBH/CupYjg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbEQxM04vS28vbEhyWC95
            amp0TTZKbVE2L0FDemwyT0NYY2FKS1VaZ3d3CnZIdHpqRGZqMG0ySXU5UU5CVjZO
            eHI5QVNtOE9Uc29uOGFRdUl2RGd6L2cKLS0tIHNIa2U5UVAwclEyeFFyckwyVGRU
            RHNnKzFQZFpCeW9wMXkwTjIrRUdqK2MKr6i7/eLJXEYcaZYPsARsh3/f5Ll6G/xj
            EtsSpCVBuMvuiGr5IDOJp9XjoQAzjNxLKEWnM+U9dKTnk0mvZ+b7gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T07:44:38Z"
    mac: ENC[AES256_GCM,data:qfrfmG6S9/1DdwhVK6+DAHiefvbF7j6QBuldT+I9LJ39bpJ8qw9T+bq8uJLNT9WBV2ImfNlJOrnW24fbxmlctGYmZyef8Bk6bGv2uhgyWxEkccadlEqV0Qrp7i3o0hQd1LJ1EMibSvnODDHR9CrXQTtyiXVm30tSWgYFrIvIZiE=,iv:Els4k95Idf2GSow55RsnY+h+5glsc7yvfhRXRlkdn5g=,tag:ZVjn/ftW9fh6UlpHa+UXJQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
