apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Yo4iQroEXVUNgBs/roH/iyOLRzbH8sbzenVifZyP5J2QL3OoHbIrJAo2yAYewSKbWK+yOX85cix1y8wr6KfVVqYLl2qU3ZnK7xeJG8oboPARsEgMPbqe+3ib5ndurTEBcV+AJGHWrQA4b5ASP4qYAUVgvbyCYyWEKkXR2EjvOvAT5HRE4dx6hjIEuORzlFIsEZD7lpF8jeoND60R1TA1MQsgkEYXxasxekIyA37p8PaqkLmf9+YS8acfMU4sy0QuwuQ8puK6Yqm3jp0r07+kKdhqgltauvgZYzWZB4DY8SyLlu3fgVHhHNddWV08ldp/xCnhrU0ylfhA1Bhol8DEaMZRoVfjrynm9hn1KrCsnbFnzIDEjOxsJoVj8ClGlZTE,iv:Nq1WLVZWXSp9fnpFTL8i1UqgdrOKF7sqblJzvX13yZE=,tag:7GIKdbUBp6A9zw7jE8+8qg==,type:str]
    identity.pub: ENC[AES256_GCM,data:6yDBEnvxLk8BTm/dHeXJcd0/iTqq9jAULb3f4OByuhJ3gPNGI/nB2nMgyKnc7vh7q1b4tfiPIN0d1W0VCrO9M1SLx8n+BM+rZVhthZhkrHjnUcEiI+NvqCIBx8JsJ3aBBHyq0C17KsN4XgrbpWrofqLgpxYkD8iFt4//G8mdaXTgEQMRGhoEPl9YQ6xFBh43mzH9RgAdt6Jy8ctU5ZlZbUwYkx9+OA79Djkq2iL0JX7EhSlXX82Cs/bAyMLQyxCjqxkBNg/5wNn8WJlf9g==,iv:lMA/sXpqoSx77V2Mp10ysG2SSCpj0k5A20WVKE4jjTY=,tag:1M7RoR5deXqEl8UFrho8Ng==,type:str]
    known_hosts: ENC[AES256_GCM,data:kFTEnl60eNxQwiIu2JBw1r3Sl+FIeiu99zmMGNHUfMZJfAYtN6RK1BEcqJKiB7JNt7PMxo1k4UlP3MGpRApUnnCespj8gEqJtjRDrwFVV8GrLiyMBEn/yhUXCe3jetlSXEofxrOpU/A5x+VMQg4sThP0ADbW1uZ9xhAfBMIl4scd+FujLyAh3rw7Xt/aa4Tm7igAvi1f5kQ8evlsdo7891d+MKPWOy+qxhr+,iv:7klZwEKsn4kvq29/CEEXYcL76r0Kij9HG/QE7lgSg7Y=,tag:xeGSrJYg5qhKqp7cK/nFvg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMzltbXdZdGovNDI2MEdj
            bUhNKytWVnROc1FQQWVLTTdHLzZ6SGlHc3hRClZqK29Eak1JSVA0SnBwc3ZDMmhH
            UHJPbGdsbmkyeGV6RklkRUkwTXFsSjQKLS0tIHkrd2RXWVA3YjdsNDh2SEdGd2pB
            d3lUcFU5UmxIZmNpdWZKYURvVjJNYUkKsklmFEAfMLRyLUTK8/96Y5j0nAr5iIqW
            GRXW5qluSPtsvw1GTvDGZdESL4SrOCkjTQwe/chKL69P/5uRIe49TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T09:19:03Z"
    mac: ENC[AES256_GCM,data:VsXCl/tr1olYIFDN/SNJUK4B5YMJeS0glDZC2hsFNZ/5VtWjt3meVRGWPhte+0+of+AZ79hELpgVi9eKNEgbmr3KPnMeXFAIPYO1k4fUplsWqHD+s/N7OHK8xy/LIh9WP+qiJoq/NhQNOSWiCCb85SQ6xfNfMxS85Lpl2LdVTm0=,iv:n/RNGz/8HdHRK/HMEmOiaBkIb/uM+bjbL5M6iT0aZ0s=,tag:Mplo8gE1G5Cpl9+3oD7XTg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
