apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wvvNGnZH/A8FJmDybmVFXJmMKEquW4zbLySCQyleQe+rrWU/qJwC7k+Jeg3DW2v4HdNwQnkXnPZN5SHbtKXlXmyWZmm3QlsMtNvHzsDr7WpN1nxOalObQgxf31oidbRND28zrD1O7gUInqubSpnK5tceUb5hltJrhn4KTqaSt5zJlcC6nfzqHZhSeZ6XYnxv6R1oglkUrNxxxouh0MHCGwXAE/RFNYvGLg6WvsuExMikumAy+k5FX1c0ejqPrn+LYm4Gb+Pg9na0w6o63FF5aDNoILMx2SqnNZfclDAsnp90RHmp40fsCXOH7GHElsQmwsds5p39HRP6OMKCaxoGZd1JY5lfZeLV1MEXtA4ldHX6PXEFHpzHo/+XYT4iKdf/,iv:ACHTXvtvR+/4io1cChLagLe43rLsQ5lyI0rDo//X4eA=,tag:ak3bIuJEJWSlN0EdGX1DYg==,type:str]
    identity.pub: ENC[AES256_GCM,data:7AQVrFgvV6RB81uFQl1BPDPVjoS6ArmcfGYd6qlKFmAp50hT1+00+7ak+cjRritsVEBwDNQxY83KReB1MmDYM9K/rtPgYHBZxkVpPXCMjKppTWCwXcmCthTBNxoZt9h5QJxWSAtorgNfDVKTPxDd/S9xS3IVmxwGsylm+7uvfVZsgUTIw1BkltDcsorIo1Y79QHMD2jZ7YM42lgABHN0feEw9oFVDJhantNaOGSYanm6r9srYp+xXVxFJBI2O++aeF9p+Umtq4msLsYExQ==,iv:ctLvC5QYq2/Clw8qwwN6TrO2Lp6I9svmJQMXnzkW0H4=,tag:Ts7agtDAo3n71Fo0S1qyig==,type:str]
    known_hosts: ENC[AES256_GCM,data:Kt17pt9t5Okc8CTasczuNJXznF7gSUjL8EMXUq/WArr389cv9T7cIaPUhlGZkli/3+mSQv+NGH2l1emCjanYRDiExTJarixaad0Mk09WX/+/NLyzVcPGvjXXhCyXmErEbKboCde4/VgRJkSzipazPYN5/ur7GAxIB2QHTnuorsQowi9iCMG94bpOy+/HOMBcc25YVvBdcSJK2mv3+1bNwpAfi8Y7yGscNjvW,iv:lH389+Zeg/+t778Is7ihkA5zhs6fGQhHrIyPM9zJHAc=,tag:aNDd7v58Vv0N7EGTFlAo2g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb0dKZ1NqVWpPT2xlMk1X
            eGxTbk5hUm5zQUphVHdEeGxDYVBFUnYxVUhJCnpVcWVwaGZEN1J1OTJydkhpSnpr
            Y3E1RWNORlg5Mll5cThyL1NKeStGTEUKLS0tIFNGbk1mM25MNzRHVi84TkRZd2NK
            VFFRbHZHaUdQekEzSSt0d2VYaEdGeFUKR8lM1w+CBi4BfBLYzRIEIavo90pg5sAW
            XOc8YIJH/TIl7LW1inW9InS2WY80b6whTHteWaQB4blGGDjhlgxHkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T11:00:30Z"
    mac: ENC[AES256_GCM,data:d4GRG1te1R21vk91nz3fP+G38WzgzIMeP3Ee488ptxRydUpOwC+ARBUXXlRth7KmPYSQljDSwUodXF5o/szBlumDvMSQDHlldLsmKQuscIH16VPmp6fIuqd46cIvTAq+/qSbwOKl0IaFlum64tW1tY/PZKzmaWg0iYUK9TsG+eU=,iv:R5+HSZuhXqIRQIyfCfG4qBKel03Gf26n1siOW8nPlNY=,tag:t+F9kuJPupw+OMS0MDYZAg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
