apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HZGS5DziW2a9qS1Ds/ncnY4WzstdufM8wqQLrnsiI5t3cM2fP2saULNfeft8cMBZV9PW8D1Fg0t++/rXIsQXSkJ/7SKHXnAR0h9tXUNJZG+pS4vvnnlo5ovJOahqOHrOoEQo0k71vFtTRRybElYKfWNnQwOeySOWPzc7mVo46VEwE2tYr8JyQK6FbVRdmBg6/9eSRU9ixE65x02psyHUX+x/3dNsD7dKpvzf+g7pZ8xf32vuHOu5Qa0G51idGCuasTo8aiO6x1qRG7LhpTmZjhNQ4KXxuGaVvMIChBOPJqrfFWbM+UyAB1gdfq3Hp+x1mkHjzmWMlr7dNM2m/Ckg6QNocCxBzkPodKWm3ygW+4fdAYPmE6jAWlBUs52G/jsx,iv:HgeG8+1pVd1dhTXQSX+9otOBL91Ec0bd2Hh01b2eUc8=,tag:CQZJPEsUgvEmhuvCnDD9Pg==,type:str]
    identity.pub: ENC[AES256_GCM,data:15Y7lAedTxe0gyGXbNUu1US0psCxsa/9K6c2yZUN4eop+EXWmfgAWNBqyLg692iEwfsGEp7rGKXhPRl+7BxpF5GpjqeD6do8d49DKUQnCMDxKThkqh6W6F0bieyP3Ng7uAqIoe2+jvjouzQR4egxYVOB37rvnQ0sqCR/QUQxRdj77sCMTHs2AMjkLtZy+U/x1LVYOZfoGG+4au8pyBg7yLLlL/X1wOmq13ANIaEZPjWp6RTCxOSxa7HzDyOuktCx0VT3OrtKnA2PLkQK5g==,iv:wA8bKTBFFSuKaz+PGmvkAItasdBa+iyctXtZ1Lc9C1o=,tag:+0dMAnzpOI1Z3EOtzFc/zQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:8FbpXOhxRCX+XqeeoK3SnezDNOvhKyCG6NAqvHXOBF+DYQRzi0c0sWRfg97lWlw544lpJ6rluX2X4QTugDXC272MhDAGQpgaEm0G5LamNj2izNkkXk3rqgBlAgqcyV5084PAaPxe24yUSvFeflq6Qls0x9nVHELAzyUvQJRextPeHnvnlLfUNkSNlHB/1yw8Q8W0F4Qsht9zAKz4zwNXh6dn8M+WvzrHwk7L,iv:hdt85c+2qEBoThN0q/mbhpWYw/nGvNel+JeCFVIG7SQ=,tag:JrxUwhBdzfNpnx9CJ5lwjQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q25oejhJQWtGRk1JNXQ5
            UkdFRTRPdHBJb3pIcEE1ZnBjdHh5VzBrK1JrCklIcm10R3d4TEU2U3dEZ3VZMTRD
            OWNPOU5uQWNjSXQ3RXBiV3ZnSFdGMlEKLS0tIFRNSlFXazJSSm9mNlV6Tm9uVVdE
            c2NXemtmaTQvQi9MRjJHRHpUelhRUWsKv4YKGlsomye/U5GfEq2Y2wwCESQtZC76
            rMqLb+Re+RZDUB+KW/TY3jjXDWjqFWmmyt1Hj0g4pIkdl3uRBgA4aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T10:49:53Z"
    mac: ENC[AES256_GCM,data:oiEgz59LDri5wOpPOtwzq4CCSUcxg9oMbEKfbryvQyQtjj3y6quLgT3QcMPElkEEWqFe21w1VThlGfwl6jO2Pp4S0NYBjKpoksoKqITnMn2TX4Dy6+bihamnWDSw7MAiMZj9UQ6IYfC7z3UXqlrgwHBrijVGwpUlSlgrTRU3HYA=,iv:MA+ge4tnyXxuqQiwmLoOjrIqfrVA2WpUr2LK0TYTrNM=,tag:tyFY6fNojqSjvclzcfvsBQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
