apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7ST/Z5RDvq/uiJ2Arnxe6IqU48cSOw2oo/+RRjfV83FdmxqkAyAo0JBJ0XitwGBvoImygOeBeJovriq+f9/a5NdwAt9LfmldgYzr5uVyPxwvws5d8q3BzRcWTXnZqMem8WoPwFjLtaPAeFDbkHPILkGe9PvnQv2i64UcKiWaxH5aBjuXnD1UUQDZxuXUcbDLkskg6tPL6sDRJenmV0Ie/AkOX9b2iX3Pq5gx4Q9ig/qwDxb6Eau3aHGW7KKxlBn8KtFAyv9WJqnEZNq3QUmWh3LpOihNeF7iphGewp4kYMdpuFGlynw46Qq6hfLaRcZmZCyK07P+5kdhOKNkPP5o1+2huAK4vBlJlupPZe9ftDnrG2zrvVab8JRz+yLInnKV,iv:rnBj06y9ibCKxaCOkePJvmeoRpwJ1XSrtH+c11DKe9U=,tag:sri5zBKRLm2Dmnqc/Fx8WA==,type:str]
    identity.pub: ENC[AES256_GCM,data:5hHO1TUYmKOHGNWbNJG7sAQKsmssj1nF8XV3NZvTOyVPdozKTCHsjmyg0zFs8BS2fUHSXACdXh6oZwM0ZBbsZElpgcXJVkWz8v3k62wHq4FZa+JwTevKKGR+p4WGzvjXB53x/01htNLIrEsSIHmUPpDrni4idVEia1tfR4DYGAwvpvIodlLqsZlWw3yqBZromumS/T1X66U/pGv7rdLSzUWNeFhJC+Kgx7wNJxkBJ6zVeqKwPecq2UcFlyE+wVo3YuEJNHa5UfwLFD0BlQ==,iv:KMSpJyZ2HUQTU7rID7Q51krgbKNVO8kwrs/GZpvdKI0=,tag:QMl5OL/OXqcj/rdhjRMm9A==,type:str]
    known_hosts: ENC[AES256_GCM,data:pmYxSokM5is+p630XQSuqgV3qUKXSqI7sd6QTbP1SIxC82X1ou1tgVIpldZ0tl+XscF7ZtE9BM4zL37B7CXcSgSNSSbMAnVu80Hu5D2HzQR73koAGuxmH/pDZqCaYhzbapQmQ1URHpsiU+vRlEtFCu77Csq+dK7PNJ+HdLR68f4fdxwgx4GfVkhiKGXiCr+FF0RfFbMvRZBkvHnkfrjgP3mN97x3Fd/uj1ou,iv:gT/qfp9WQRXL9C3L5JWJPMWxMEetXrVPKN+Eln+YpNo=,tag:exriN8Bxe+BytrBAA2q/+Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRy8yRHZqTGdTU1M1ZUZK
            bklqN0FNVjFmU3pidk1LazNDdFFFWmVRNWlVCmJIajBvaUtUeDFJZEtZdkZnZWhJ
            ZVZEb2V0ejc0OFVaVXJ4c0FKTTlxdncKLS0tIHR1M0dySGN2U3hVcHd6ejgwM3Vl
            bTRPV2NBWXNGZlNwTEQ1d1FQR09qQjgKE8iuGY8W824CM4IEiEFnoS09nQV8Enwi
            Vdum+GJwR4vxwLqrvn0k/fsM31vWt77R98GT53Ez2dc9hYn9ADVnFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T08:36:25Z"
    mac: ENC[AES256_GCM,data:iM/dzz1GgKhLe3bnYTjSi112qiQIOFq3t/OcW1cuEjU9uUgmTvoVNOmAL8u5CHVtNU/qpaq4iVEhI7iA6NjQ34tgaG6rghSrT2eM6qIoMCNLP2M5i2TYCnsTA3A+aBjtmcGnZV2c1Z4phPsfGm25KiziiCcmL7y2oQ40x9p1ewQ=,iv:8/6FTzVD845sgPaS+IHCMrOsbdGH61Gkptl/eIwJRDY=,tag:VsX/AsHc4BYmiG038cy7Jg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
