apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RsJIXP9KtScpr5ca0x5vXTX2vw53opzZP6wFlc481ThO961BRb8tBAtctcxxGsZurpMHZm5iaxwMdGueURUrQDKzG0nr8m7lr/QOdOFh7vdwAkiNqT1clgzTLe7WsYaZ15Isx0YFO62mXYvbNMzNmcaElle9XsurilDbpvPZDxDxFK+r1RHhcRjP3sPm2/8OCN78+IQb/NiebEGL7JlyGB3wwHbC8rcH6V6iF7euUXK1JkDoal1Run6mipygw5vwRnd9TtA4/Xgbii86/MSYcsMXPeFeX8oKnRMuwv8u3XrLm04hV2euyEcgQXx6HFe54+e237xmPwOaQNS/EKXqo0+sXQ8+xrfqJKqNeHAoqlvVtwGMF8Fb1lmOBuXymcq9,iv:Jn73HsChU26XH6vgc4J9klt2AxeTt2nrfrzoE+O/RE4=,tag:z4dUeH3me9xHTfl2rP86rg==,type:str]
    identity.pub: ENC[AES256_GCM,data:TZTElBUYmDFX5PaNXNGqmhBEFMFQHvxCt+DbPGVLrI41hoJeFnqP6zCFGW7MHW/WwwHcgNMVPWpaKeoNNZNyg/H9RSA2gi4GdjDXh9mLU3s1jFXCVqyyJ2g1DkVx0BpoR7GLPfi4sYKMGEAjd2ZpIX/3RrnBIqtccskCOswPwGapG05yqdUranyoHMh+4fISKeWgESo2uhJrj5NEuvsiKw8Z9ASO/n2cNRpoASIXMYiImhD7qWXOEj0y/c00lKP+TICrvP6OSqzOLqgUAA==,iv:lgeaTxKeWnkbUB2HnCBFFiagtjcOBsyjxY3FhuDinzM=,tag:aEKobH3xpso3WsR/COz2YQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:tFNXSKg+K7z/GI0agffkm+BVDVmPQdYfvp9Red2bsQqzg45UFiHhv0oOV+YEEdQjIVLwHUnMDBb7qb/0OfN6n8JYoAXuoVUv37W8gcJ9gLlszoAcS3n6mT1PAyMxq7Nzo00LpQxsJhSj5fONTYS01Xv//inTtLqnEryf9pW8021Xt5rKv40Enm8EbCbXcu1WiVQQcdFm2/OjnONizzaujiX/+m/uTql5Ggsf,iv:zbgMntx4HjHQ5XY3j0547x4+gXltiq5Iovn5ExzKNjw=,tag:JdXSu8s8IpdOlNxS2vbdfQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad2MvZ1dobDFJcEg4RUx2
            RWRSRFdBcmJqWmV2WDh4TmpDSUxIczZZOUZnCml1elFEb0h4cUF3SjFMdzY0UHhh
            ZGZ2NTRWRjdRcjA3bmxYbVlsUitKTWcKLS0tIGwwZDU5RFZScm9wb2orVndGeUFj
            VXFVVkJ5Z0VjMGhlRld1QUxUd29FS0EKNUiJA+EPfRJd0XejGZBOxvUdScA+nPjR
            NC8nB2xK4BBjazTFY+aWtR0nfnO1lAw5AgdgFoCUpYjojQZDxvKVtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T09:03:50Z"
    mac: ENC[AES256_GCM,data:6btOMd/rwfmAudmPjXYUh/Kou5+3nhULOg7m4QiyUtZAQDNQY6kfB3AF1oFW6S3TVO+7xM/CIBzyYGc8ELWQI6Yp3QKlsKexqo2+dxSIcYCmp8E5B3Zs50SP/ls9FmvuEG18DQphQvU917MYXko84PEX3A5tdqsorWIZnVz4T00=,iv:z79GGQ1ysLY0hk6gt6k1hNeafhG7crX9thRGOrNWjf0=,tag:P71ijgafBy2YqBrKtjF16w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
