apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zO9VbZB1YnPkhjTGzaIEu/QEU4FR/AMzNXCpg4k4CWQcVnuvJ9YgATJBJsFSY7q9HjpobWK+KeW8qza+hQvhP68IA2Jt/RHkGpGf64zoSQT6R8Uyx6T/cG8Mvb8He0Nbza2ElwcTw//OEp6hqPfhzDl1lcKdyl9PKVQtp4hRapP+zqdIhtROKE7s3tVZQRuVwC0yCILHocGMY9HZr9hxzJt/SgzrGucoItPHf59ps20iWls2dYCIJPPB4yZG2BnQJ3UM8O+Tm+3alrWA9cEOWSYgTn3+fqBVdp6samUwSsdFsWZ7Q5xwUNL4bXDuuLsp7VSNRfaUSIXCFWpQB48Lpa6VcwtWwdaKwlYE8bDuSyYbt5ONCBBbfjCAqdG4ppID,iv:qqoyWiFvDjLNA5Zt+DHH+QUvNeJ/xKHVew2H3TUbO80=,tag:ky1TJFMm/47DZQrd6pQXeA==,type:str]
    identity.pub: ENC[AES256_GCM,data:XZjtKFAIz0ub4T78Q75wAtQEDCqn8s4aQXcp0bvKg76zNjYos4An0h0GOAkdPDd0Nq+AIAy6Vhc2xqz1cD8iruiLSH4CgAIZyK98brzqOMfmhOBLj7WTnH0AeskNjJLTtsiJuJPGbaF1T4Ns4w3y+euVpaKdozgQ3LsjHJP6rUM12tzVdw7z0kVNIXYkWW1UnPkAGUkkGu9rm+dQt86jQNLaPe5eFUyBMcOpJ/WehCjSi46F30a1jPke9d2+OGz4Y1gGCvbSTiDV2N4lDg==,iv:rrJZzB+76BS20AeiaLU6Hlc+sMjjG4ZPRe1B3cxhG4Y=,tag:QKmpz9Q/B2zsLEUNSa66IQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:n5YcTGKPGWU9PFdSjffvHOzQA5ury/1YQ+s4RG6aja6yog40BKDoff6XXFv4r/hIIjBSTEdX2iHyR7JeVZXbNYdNFk/UUQfcDnh7grgWzkojot5Cdf42TxvrjL0wANSwrEalB1nTbwgYN04N8DNIxATUR4Ql9WKzegD25c7MOPbaEjhvRaX1fpi8Alvl+YbNCSZisPf9oYpXneK+JRKVAUK8c1MiKp8ullaY,iv:JFHi4zju8zHPrk4EdVz7SvR0ZrE75aeO2KqVRpe0xdY=,tag:dUpZJZQFUZJlh9mxoy9uMA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTmJQN0ttalJua21KdjR5
            U1VoaVpHUC9PNkJIejhhelFYYi80aC9sY0VzClpCbTg2akhkaEpCVUl5OW5sWUY2
            azBnRkovOUVuWnBJVHlmRlJQWHVLeWcKLS0tIEpublRQQkdlbmcwQUtBSHZvWFAv
            VmxUdFAvZnN0ZGZuOGwySCtJRTFKbFkKFXBwAIGWSSSTJentC/avyYKmsfY91IN0
            ORzc/u8DXMRq6zMAsKMOBCYJyB1J9J0DLpsJisXFilKQA0xzG3mAVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T22:05:13Z"
    mac: ENC[AES256_GCM,data:ta6uqzTI6prOGQ6hKilaQlYkvdWkGSo+Rtw35nVotOJry595NieFL4zAhY7bCQHWmRKvA8RZHjmsfzYxm9Cc+ZLQ4ohF05JkHBmQBQcCpzxlnFT9GR/CuvYMqWpmOmUROfcZAQqKqUTzhaEKaK1d9/mpwyuA3l51c+Pwk8BbEc4=,iv:Xfbty7y4wL+HVp4XjbnR3d0diAweX19x+wetM6UZEpI=,tag:iwBxYujDXgBb2cRuHRKJAw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
