apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:A1zNYsJ/70BVvVetDSkhK4T//cNVBtnSfbhlSjSVMlDbt+R9uiHEUJaZYIw74WyDlI0BQR1zaf9LLXnN5EtCUdf5+M/AAQ4VC44VzWB1wbzidxkJ5Yk/w+6jAVBD24BY/2IoQQ1K0FX84KBBmYSiKCecLgVYjHocmDEN1UmVBk4o04sLIxisMbP/hNZKXYbtPUHNh+tauO34lbcCidi0hMHIgH6ejkvNBypWyIkkg8MtUwUdLKLURqEoNL98x26hS35tNx4JiTP4KlF5L7TDLMHWIKGTXgzYXcY++KliEZi2VGGtwdkx6+x4fx3MnfrrN0VuQ57Kf34iVv1atp+EhUJzHJTkopAte1bpWjZXbbFzSr1ad4T5m/LksJtSi62h,iv:+skh8yMbjDC5Gw5zaTRCp0llAMdccLBAIflLpdRSiu8=,tag:GzLLh1wgX05aDcjsVK8oQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:PuZ9Uhjmqhlj96GFoKo5uUYUPybFPqd+tXKG33XiqGfmz0w39RRWnWxKBDlbVxK45huKpTce421reXmXxLSZSNguyqfh7CYkyOzruc3XJrxOcGrUMc6Ut7RVmP6CqThCdg1ysO2Vw4egGA1ChOqj2DNe1YaMl58oC0UgM2VBEKaLFHlyZFVpZt6jurabIrphEa7kTjWeT2Gvis0LW/slm/7thtcENJZDU+34h1nBd94GO9XcuykGpvxrhmP+cpyN+orS3T3lTW681paGJQ==,iv:5juRWY+kYy8m7+Ir6sbNiuBGVPt8ABJJ92IOnTj+igE=,tag:/GCtZnoHVWjO5qSCVuCS9w==,type:str]
    known_hosts: ENC[AES256_GCM,data:fsppIzWVRVuyu0xGx1Ath4uy9XtvVDlysvTb6Q50Rh+RqMA2eAN3JAYuX9K/FUySwIJU+qZdMz+EVDGgCB/sIBFATdMBuSz9nv80UK1tw3pbvOccrvqVDrr/G6cns+OdDpPfttvFeiZIYz7KKpWZWEhOQHF5xUZWmA1VHMp0S8Ora5gIkVHqv6khvIPTKQVl1Wx0VstYtwIgIrLmNRErp/SATk5tsuzODUbH,iv:UQl/AMRwCKUc+B6Gon8nqLv5nieULH0S6ScCDpzWy4c=,tag:/WC6CcEjtMtkfzTtNcOOSQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVmxxMDcvcFo0dHpIVE5u
            cVNnZGlMaTRYTEdVbG5vVGhVWEk4UmZ0NW1vCm0yb0t4T1VVRUgya3JDRUptTDdr
            TFR3Q0VQSFIrZVZlVWZEZ3VSbi9Jem8KLS0tIER2R1FSci9NYml3YW4zQTB6K3Rv
            QVNxK0h1M3FrdmxZN0czTVdHaFdxU1UK8CnsdYEQ9rDQas4gNZsxEg5UDCA8IkZ1
            T/Y3U9dvwdqT6ej5BpjFU9TEjahvfxssHBCJVTwe1hr2pqyzj0wx8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T07:48:50Z"
    mac: ENC[AES256_GCM,data:PxzCOWBozw1qSPgfgM4Ub2BRLp/cvsRizQvAcSrYWk25EwtQBHpfDcBnNHXam6aDicrPwPnvHeQOsUZqy+gDNDGHWX9rML2TiwMb7rDl76gXCf79LmnWDRIYSIl9f2oWNy42cuwwO73fIj5zTy1cgOk/iZRw7w0ezauMB+o4fNA=,iv:0Pjv9MQPnbxqYnSkmBRTgr7+qo6tktFwbIPhX2d+0NA=,tag:QqVu55D2Kj4/eejMsx17Sw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
