apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hKi5TMZiVMOpnsmOfow/Rcp6TNxSqWPAI2F5+sfOUZYkWO6/I7ZMh0y5Kl4aOBCDsqwO8bwc664PQdZ/Mn5lS+em9y87nKeo4wrKl9QKiOjgpsl5D+zR2wbbMoFthOxYUK9ohCKvR5OWfl6dc9aUj4I8+b1lvI32eCHqG2HL3xPlTGpjkSQydDscPQSsK+PyIz2EoD3AdGnHjt5t5iHsBbC/oV4biBXTYs4lKlUm6aZCCBNlhU3OxRPUjiCHw7jgZa47X9pZUkbiXLy9HP7DcE+WUZSgJlya+DoLoYHqVklDUhpqhcn9HS45UCJHs4T56PRFJABqlpRUF4sNC6zLmy8mOW0Ozy4rqDz7bFDlcintZLx/EMDtriCQiHy2ZX1i,iv:WVCs3cTKt9Mvzy/fwBVlf3Cn4mBnMfAt4/Iz2q2+a5o=,tag:N5lu8J5KZFMVltCFe/XdTg==,type:str]
    identity.pub: ENC[AES256_GCM,data:4lcfMcf01vNp2aoRh8BN53yZl1Rqv3DOs2ATHMBfhOEfJozlxxc/wrxUE6KMG7ZU+KI8hGCJTWsG2tbEQqHnG0BluPMWYUN1gTqOj5R8ctxQLndvmCSDob0AL4r+xuy+6heBm/rCRmlWJwPP7J7PU8Glw7ouXt2yeGLJbkvd4duQqx7x/uH5qDlOshTNxQUQ5af9rkWnsxJInfd5b80/RJuVXTDO63S6BjoJtrbVUL7oO+EWmlaBLbJPexZlpaZ2d4l5ZI9c0HcDsRN+Cg==,iv:PuarMe1DtY+MAJdQXns5yWI2M50g9db0Wb0c5wQmzds=,tag:V0mlOjaRIIBQVQ62yaGQGA==,type:str]
    known_hosts: ENC[AES256_GCM,data:oAK+RIuzHaPbtpAM1c85D5xDKRCuNnp9aEMhaO4sr6IwtlWyUm9R3G04KZrsNGNwrLoDRVX4kGrB3mFL4Y4J53njDvC+ZRFRoI3ld778qJw8KgnqSq0px+u46ZhYropBgAEbj8lZ8vN35pY4yQgKXMlvKklK9GRfGBg3decKnft+rp4zQfVwGXQmihYMmet1zJ2RJiTsAObpS/j11/u7UumYqxXmLlIkkt4H,iv:uq5akPw+b74slrVF3Z/B332rqcWQRzqOYFwT9MpYtek=,tag:RqXYi+AifDx/MZTUT7gTFg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN05VSVBManJLSVZqYytr
            amVqZDM0VXQ4alRDc21BaU0wc3ppZjF4TGlnCnJBbmFIRzRFVy84L1BRWXd2LzZ1
            TWdOcFlQZG1SdE41THdJNlBFb2krQ0UKLS0tIGlPRmhyNUtFSnV6SjdqQXdGeVIz
            V2VIOEdWVSt4VHRlWk54aXNJa0h3SU0KLirT+daFxXQM5S4UTNupYqxDdANcRVII
            /fXVaO0JPuFS/93Xlut69CDvjfPxeo26dv2galqsJDYCjehco/n7pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T04:57:28Z"
    mac: ENC[AES256_GCM,data:4e7AxDa9dXOqu0c80hrFg+TsbiYV0Jh+vBKFl3+NAhy1i7MsVxIIAy+V/7CtW8XvSpGg508QkkNa4L5QOArqwswQGVySwhK9UwIe6hHyTfDf7ygQQysqdZaFz25ojwLxdCIZVbD59GDHNSPvKa2+jatzmx2JXigcGQ6Lx9OcF7Y=,iv:5B5RD24WHHJnvKBQ42sDJc9xk5zTCOXcNk+/fBg1L98=,tag:vjjFmwbtdlyTrkq3rCRGtg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
