apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:k1ezW+rN4MoRF6O/2QdIBOl6tB0PhU+wRFC62ELfHg8a0pjEFxujNJPT3FvRTRbCSwdA3eA5og9MH7M8YV6WLQm3TkrkdW7FoR9mvpu+ZqV+2sU8G390hmNYkxa/0xEU9I1KFKv/TP5tuOcby1gOTpta10JwJYcVs18CT67Uk++lbC+Pbym4QKtdxo3acHASAeLl1w5fK1gTmnarNnJsR92PM598B95qdIdbNaXp4JJ40zylg6tz9R2H437BsNzh9O7TsJYUf4kkwtiEdRkPpWYUIBrb9rP2mx1ACbcmuM2xhphCZM6POfbdeGmsfuGkpZjGtdAdeacZfZ/+CA5C6Jmtdr19eMIOT4RdZpi3kQkJnWjAz9OSmfkZY206uvwC,iv:s7e84BlQigJDvyzRAtQ0dnIPDfI3xdf/jFQVNLzN0dE=,tag:qIWHA3Abu3EUe86SUZszQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:L6mSda8yFVelYNqaeDoeC32zKXKqoX9d/fmv2877IJLKqt9n4JuWvKHGP7ShLn4C0/7dtn0H9ainnPuEM3In5c6GVZyjVS9UL9fvngcIDqYDxm/63Du5imqY3MT5Iy3VocH0SOC0qggLG8wnC9V052ip43b2KytGzKn4jhzbLXaNevFwLqOuXO+aW7aBsPXXcxY4GoEN8fmY7jmf8TwjFciP8lDYbDd5LT/KS0lPr7YuwyCrqME5X/TgAm37LmueW1xK7mJo8KvDv0T7Dw==,iv:jRdyMoQhmiomuLE9WKIJd/tJnBsGalUcVMWiM5c6z4s=,tag:tTa8PPsvq7uKlm6x01AnrQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:7gZhNvpjBC1Q4+3aTKU+aV6lSn31Gj0BZrRvIPW7zfMMnouybA5v/kbWBtZO3Ls4KzlsEm4gwcdNvF4gf4Psr9FjU6KtMG9WDQTlVMqy1S8JIh+gIc0GDuMTIZKJsrqOa1u0YowTQ/NllXAkU3wCuXaI20zPeDvDW9CeHw0pQuM2vmZk47ozsaMBxgcWDMXMQxLV07RbIJi8Jec47ZQImEfz1MXT88V+0pIW,iv:nbIqzNVlWml9iI6wfi5aipMC/ZmE7c0YTWlSYqXVSaw=,tag:u15DIeqB4hb1YsGMV0nr6w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlKzJrTFMxalYvamRkRStX
            a25JRG45Y3hmUjJXQUVTTjZZSEZoajI1djFBCklsYURka0pzbGgyeWQ5dklvSGky
            c3JPeGN3MHYyVTVsNStCNm1ZQUhxVncKLS0tIHM3aEFaRVYwdjJHUWFsU3FEM2NV
            MGkyNDRhRFpNenJDUnpSTFJ5RktFMEEKnBzP1YuDtonxjraNIrZT4fYP2sPnfg5K
            BOmeZA4aMLlSn/QiN2giXDSJP5NRD2Aa2NK0NbWh1Sq9zXyRtGcTWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T08:11:41Z"
    mac: ENC[AES256_GCM,data:brHOKKnql/E/dJV8uW6+YLT0p10LRhdPtVaeQAgc7SSWPQmpPwq08jb3VZZHiL6ztzdLmLuGz/LsFYsUCyq5I1XqSZ5uF2zNemILpmiYhMeQpFc2UzIfuxwcq8QDaLD8bBHpMwDB9P/tq9nUPhwkIRapX1Pq066/lZW1CXLIXqA=,iv:GThjFKudYe8Y2a3k0+Xd0rGzdBJUsctBZAMDaMmr1i4=,tag:nkYl91GkBHja0nhKmhra4g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
