apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uJKmxWg9pPYjbWUW/D/FDlvVuqZ5vZtJEEyiKJbprlPuCQZ04cwE6UFiO7vXhpMAFYljqyq+ICI0zmUO8DdrbbTqvwWnViove49AXudSSi/znyxYN4nrMbnalDRY2yW6dX7eAjrxoc8jeu/6CpI+CFKCoDTLhoEylHW8aJfFmo3E5vOx4ww5VJw3NRtnENZRlQwltmoYrvOmPwZHDsjwKJs72f5t3K1SRwP+VDx1pN/Sl4TpjSYIp8mLfoROPocjwnsCOz1wqnipzFOrq7FeT4FG3wRP1zCDHIiJuv5WDXnA9MotKl7/bqC97SpGfNlkFpBQVtmkf7/VqWCSOXNubddZPvZRazZOLic+goEdSYZSeeAwJY1PU1gT68IRGfA1,iv:gJY37hc/0YNteSPb1VwpZAPbYlS0osckSIVfuTpXcXI=,tag:t7ZigQzXheyuWXQ5K/DNVw==,type:str]
    identity.pub: ENC[AES256_GCM,data:rZld9LecG0lu2a9MGxXM7XxbS1Au42qhUF05gESk5ppYzzRtcdLiFDW7Q716NrWbPlhP40RX825VOFAZWin/dkN1mNCuNFKE48L/jrYAstWXvNmQ0XmJUrmzgaylR3kYM8XPw0ib6BT0wZfwNmmg3oNUsBEGpjnl7GvmJ0Z/Uw+/Hic9Ms17RZx0UpHcEbvGz8q97x9YRFxzkxL5XYyjvvPADPoKjGc/apVHE4eV72GXj1gEjhD18i61dWJW4sJIJE7Cxjbyz9jqdsx7/g==,iv:VJiqjdAE/wEX1xjc0WoFkOAHTZv+bBU59OOshvA+JuA=,tag:TsKpRmT35TO5ThsEWeZgcw==,type:str]
    known_hosts: ENC[AES256_GCM,data:EmJqRIjiBEuK7fjV+dBYSR81a+ks2I1qDk5fi9ynct9PX+ZubTz52kLo8Aoi4EJp7GkmCj17rnaRIyWB2IvgSSwYbcM8z2OGWsJYWInvtTeQ1dIJHfRVGluQ0XeAiqwm9ssbcUt/yQaNafRwn6e82aPukuxPffb1xOUUnErb81GDBTEwLsl1UdXKBWZnhr14NK/DViM2vT6G6PSnUwlYYoTjL+g0iIGQ0Zke,iv:qKg3i/Wg2/2WwhyTEPuPeJrBQNaRy6W1mbw4ObvEe3A=,tag:4syEnwpXTDXOAaDOGZr5iw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrN0pheWZ0U0VQS25ucTht
            eG5pdEtKTVozZzkyOGZOMHgyYUwzeEZGQzM0CldEMFZVTS81OGxZTDVIS3hvcko5
            YTQrTzlIWU0wamhpTU5zRDY2RHdoS1kKLS0tIGRuTnRWS1lNWHVhS2s0M2FIN1BB
            VjRWeitleGNVK3dzUk9QWUsyRVhNcjQKjzHgQ5dMHp17+wgSWdk3ZPlg9wu/6VqA
            aUCP/IkhqniSbTCMNNMRp6BoI6FNVG3ALkYPRstwuF7+uT9K//exYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T08:54:46Z"
    mac: ENC[AES256_GCM,data:iQ8MmwV15gh4XHmcOnatekj3dMLvy3RCb67s+ABCgnILnXMbGkBx74Tx+k3TBcDQ62B2tX2kJX/ZoUgaBIeJT3qbEu6eyKGKyhd/YdyB+rwdhyoAYrmAnsEHkwLPz1iMkN7QEub7LopBXtJwFosZxAa6lezXL2dRS04h5bmrro4=,iv:gqs/ock8hibIIj+SLrb98wfvZ1/8ULxw8T7PAskusag=,tag:GNbJyt6wXBiAOUqbpokZyA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
