apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vsuSIO8jK0PRo1OaNbhAxZzXO+E9udVvvfE8ppzzGDsVWxQZmVN5eNe+PORHr52uRxsehkf84FNWOG8O8Exoofdh2sJGPgc8XdktmtYY4OB+0qfchpTJY7ko/RzYwJPdor5JpJZvJbXf7l7CYPfD6UE63K9kNTyzL3kxCbSCJQqzHyipBMkEBaQjxjAbJ3cU3PBflVI70v7aRbeuIjYbLe4dNr0WXCSUhvl6wIV5i0scbv6iHoWXUzAgtvu3anniRMcEgw0n/V7mIRfMewpjphnTGM0KEiA5zE8bLl0ztYXQMPCRvdrAzCoiGw/F0Yj9MQgYpyWbfGA8owu7UFSOTmBLmg7quHL7pwKt4/GQCfnDxea3dt8OxgkKtI1W1iGK,iv:/h+wCiEWLobZKmYy9Ep4HgDY9WakWX8SgzWW8reFqe0=,tag:+sRvEMrL5SFEFouQcBCq4Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:555y1l0U6cDWoX1LhLHhJ6NZ0MBe8MIv1Whz1zaw6MZqfuGnJF5J/Flpfi71y79fPQV34uW+UsHzbhZo0r+dfnpiIZu9rtsTlHhc3u5l+NCS7ioEipCstzcUuZ+QDACOcjnPsp+mSqQHLcMOk5y0c7HjnLXIkIQtm0vWN/syOREHz7lAkwl9uz2igfqTffe5u6XdbfpQv+zLofLgntT2tdMH/WHfpMwoWHXFsTnIPDZ/xhQJfITJ8Xhxd+hZTNhlXH8KYi6qVLLWRrRJuQ==,iv:SOzUqbJ9oJg/IKorf+wfxFQ6GTlxrGDc9uf8AapOKGQ=,tag:0xr+ipuOLJIE/8SyiUVfpA==,type:str]
    known_hosts: ENC[AES256_GCM,data:tsK41UepVEkpvh13W23bCZowGVcrNqwVu/raddIH4RlGyo3+wekei+AUuSJ9NId1F8oWDSWi/vwP0Bb1thX/XXLyNiAaKo2hMQKPcF+kkicAN0SJWxsSoI888+8HcU9tk9uqfW4jvP8BkZWZ5xiOdP4QP5MaJWA9WTiW4IfIJetlQ6ZKZkUcFdly5wcH4T7+7bYN6798KyZACKzJRquTm33/Kb2MjJcu2sAS,iv:+5wU5Ud2UK7DlqV4VWvNlWA+KZkC6NYS4LobZ1nrBPs=,tag:1vloe5k+wpPexTyK3CMx4g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSFR2SVYzSTR2NkJsSi9v
            QWliL3dPUW1jMjZnSmIzZGhCSlhRSXVROGdFCitOcWFoZjFKcGxDUGtOTlNXRnNH
            Vk50YVJlVE5YOG5wSS9WWjdtYVRwVmsKLS0tIHNrQm9JQkVrWm8rMkU0OE1iU0dw
            Q1pSWE1HbzJORmh1c1ZjNlpQcTgvY3cKECGW5+sXa0RLPnRe2SMnMTjh8YNqBtEl
            1hlTbcCpzzZ3HV/RyCgYQWLG+TofcGUpVUjUaaCV+rILBo66SmrSDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T02:33:45Z"
    mac: ENC[AES256_GCM,data:yqK4GES3d61eSqbfYd/DGJ3I6zL3dx7MM+nl61fXsH4axl7hy1nuAgsWTZ4kZ1mJIaVhTnGNfk4Yzi5OxXG1FEO8ie+GoVQL6XoNVrR2Pb2qS9efYj05zhaI4wYBNtGstDUr/lRrYcMdxyhOrWCMhi61TFv1SPmyW/MbymkcFtk=,iv:GKKPTwsbsb2hYj9B52nWtPACej4iLG9HOOT4pcGFtks=,tag:kMYMQ3gFy6AE4zvQL5U6zg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
