apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3TDQDQi92LCF01zvqmPbwYpsoPDP+18fK2s1Iw057/btAs7+isqH/99QbnWf0RidKWWRwpkGwXexP0JLEot/nnLq0uJQAKPo20GtadhYkqNFKFa+5fPTENxzmuehezinp4jzQ3wes5rko7BYqB7/5YnCBF80qiut0vqHEFEKtKbGu6+o86IJ/bPh5pujknRyVYm5GhmuG9NAqPROKo55J6Fok4YnxY2dfgZqYZ6EmffZ+wQ6rAvuRyYZ8X6d5YfL6PbQO4FixF00yj3WnO/NCMcI8CymJ9PgsXYOXifGokKJmiCauusNaqAsia1OPXqTNcG+bK5RzJ7hkR5oEqVteb8ioo5YqdtpoFdEpxcfoBTdpzBXMLRd7jyMo58ismvx,iv:XdVvAmwTz6Mqh1UNGA/qeETKqsWwvePFLou6VFTvQ4U=,tag:pNJ7jx5WNXaDjzbs4j2yUw==,type:str]
    identity.pub: ENC[AES256_GCM,data:aEiutR+wCkxLf/8tNWRplf5q+32XJZjF0VhIvfSsHwXOxF+7gBI40lcfvVgzRIGFph35/vIhgchSFMjaBindeAKE9x3JT6QInLUYZ7U+P01TWljM1N7m6BrlT5Vzdx8frlMFeJc9t6CeuknXsjFIQKCKro0u1CrdEHm8qKktLEcQWmkARkoX/ln+/iFFvOfpSJXPz4rsVciA8A+lmsLqlaD17W7HFvbavZkEaCm8E31pHF87yT6lMfzfOcswtpprhPn5JQtP34y3UMLfuw==,iv:b54A6tEGYWp9q97UFRBUT3sW4e5ANtZVafStkQjc/38=,tag:FD74A1Q22/ChbI63Urzsqw==,type:str]
    known_hosts: ENC[AES256_GCM,data:eYL4wZtrJwOKwo/1RLgXM/ktGOMGZuldWU1A4Dqh+ui6/BtE1uZ/XyEd1F659kRucqdApGk9WzjLYfHLoBP7nv7eE8v6AJrwEUrKErjCq5kyzWLWa4qEQ2crlxGGaD8ekQ3Ky10IqBOXvXyLjuKi7RBSW3ktuGCQSLj3QRDylWTIJ88F2eTUw9QckqZ4IlQnoVfcxacvRUBuDGsJDeuwukooZod9kKL2Wb8E,iv:2NDQfdsv7h7q12FL9GgXo7N55gFbmPPkChrMwBANszA=,tag:8x+qC1fnHY5CzEhrzyRA7Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM0RaUkhkazZXblIwcXdh
            aWhIK3RQeVYxOVdhdEhHbzR1TXFrbUxPSDFnCm0vdnFVUitQMGFrTFVJd0pPOXF4
            RlZOME9CUmVCbzQwOVIzcTduMk9oWUEKLS0tIFQ0RWswZGN4UVR0akUwV3ZGcGkv
            Wm1La01lWTBQdkpzM3RNUURYWmdaU2MKuEvda/YqgWSCtrM7VFljP6e/e4wtvqwN
            6h+kYGFsLS1uKEZV/CJaFwJUK1ABPbPnS58UtZqccZBzCJ13G6mRZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:21:01Z"
    mac: ENC[AES256_GCM,data:pG9+3ZEr9Q6FSML2X3S6yfM2xKDCj5oJ3eCUea42hDP6cVzBElC17IQ4L1lAmIfc7YV4piKA97QTfBPwz6eu/nlEUdvBqguv1eqaMmxxq0nQjS/OW8WGtAs1Ijs/VSvMAJvWQYov4SQ9pxTV2ECVTR5fqD+her5Tjuv4ZLSEgFY=,iv:bJ6R0loE9qTEYd5bUH5Fo8PSd/ppkfBJ8ZhvrGwQvXY=,tag:pVQcvvT1VlXbvvtyprmkiw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
