apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:M6xVcpU+FcjMEaTCLOD5ucocCK7DKthBjIeUZH05KTcob20XHgVUFxkMt8pkQstXgLx0KmmC/GSoDGmVNakUzdDdnzkEYazj+3rRmDapuwr+QkIjys2E7brefKUVkG62wQUe1Hdtw9vdJbV/quRbaOGjZkXJLlYirjqbOOYq4UD/d+f9G0HzTWx8puqNFZjQyqLJKhl+U1qvGEHwb9A9sKTrfcwz0FWSAfAAXBfNWEs92yVMRnnFecZmWbnrmnFYHL7NeEloMVduY14/sLp1oL3QJCkr2xXBZA7DMOV1m9cVbZq/aLjQWeSSjS+zPmv2O18NB86k59liNTc2Seh4JFfYZNdwZXckJTI93fAwcefKhugsMg2hXP40Z5bAngf4,iv:A5IjeESYWrqL0lYU1m44J7nemoksXeOm+I1mIqKIL2w=,tag:Jpjh6gQsRmd5xIxiWY7Cmg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Wx35aEKesFlx5EsQouuv0LHvCCvRb4h/VZfdqNYVaJi12ciQyatOB8zIIa9kIGc5I6tmnSGgnEd984Gk2LNu1UlRh3S2/xJHB9a0UHEBx0xTMvsM2C0LX70vRY2Z4iDjO+j3TmjGocNoWtWBrXvs00ckAtwiDl3kA99WHZo1iGvq4k1hx44I2jMsCH6NSm94AHlwG+P3JLnP394kNiC2JvIif2E2G27ua63JYJq4Eeka3WEVF+X7sOpgR8rpuQeu4IsRrVYvPsrggCY6wA==,iv:AYG2pmuG1sZRD+ADjmTDHNOHZ79/ftd8a3OzbDVVbxg=,tag:twdUTLk/J4ejY8btAm9SSA==,type:str]
    known_hosts: ENC[AES256_GCM,data:YscFKFeE7O14QBkx5wM634Oj0ABlQ/4kR5fDYjT2OYbx5WlVGam85YmSZGCcP0Uta89YW00+JcFAeTho5N3tanqhs+e9Zx6AuHc6EmPX2LqBjiGX5McpNBUGsJfj9jFINtqCR+kcHC7sC7GNiukV1it1B3mE5HTnXS/qEzXhVJ1BDMFm0G1PLHiL605UCR5l/UeRbDegGNvjSiCxMC90zdvBNj68Wp3MVpyv,iv:hYQ9tnaQeMy3Gj1xiRbhh827xpcNCCSCKJwAJ4/qeLI=,tag:e5ucPR7iZccmBEXe69VcOQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTVJsMEdCa0pOQ05VYWRP
            cnIrQ3IzeVNNM0l6bVIxWi9oRkRReG5CVDFJCmdDd0RSNVRZTFE0ZEMwdmtac0I1
            NTZKWUxjR1VMSG8wYVZrU2tQb2p2MWcKLS0tIDVPK2FmVDBaZ2VWc3ZTMUYweHlx
            OGFxT2JWaXBjV3QwNXVnUTE1dmlXcU0KMZSJd5CnVzlGVISyi6jX4OPDsyE96AqL
            z7WZw/kKxmNVW4wgC5ALFoDQT4+t8yDEHqbl2d/D/ouAmiMcnjFyoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T07:41:59Z"
    mac: ENC[AES256_GCM,data:fLf+cfxKpPnEGzUtfO/imfATZ6oGJMyNvJnMIk7g5gUzsvB5ep+sW0cz/eCW6yODZSMHC5zs3Rwnkt8Yt8MdfECR/tnnkBUwbQkr6K4I3Oe5k581+2PJXovJ/LOWmksD7mEjLREWgcjf/kjJEMvfFlKJem7S5092njJzopELpl4=,iv:byabIKlwGKZ2RhNqdTMGhVEudFEoY0snG1SlpzQGGVs=,tag:kwIQ9S9sjcmg9X1Tb4vDig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
