apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Dka6WAhf7SOVMMF8tf8/IG3QZ6B3vjqTuZoeLXRBXGB2Ln0+vsCk/C+TE2DsKLS83OGuS8GjrXRJxJWH3PyOEVpr7Csm75aBeo8AOXFt2aTuIadaO4NyCP2e8xalf3cypAIGFE7Jr5CgVpWwoSbzl27qxYv46VO0XIbmUe8XptaEYynQsnugcMYp7zxtQpx5mok5pKO1bMg+8QVYazuUm1O2uAUcER0iAytLWq3NrqfqeiQeYh8e+qMNqmjPmgetiAgkvx7H8bzUHNhPQIGTEcf9RmSq08bhDxd+2vpJthdf6+k8OgvmxeflOKhBb/iOh6wg1ZN3T84BIXDkBQB4gArbPE5G5yEY4fmln9+i1q6HUbgEfCO4ypRTGF66A4Lo,iv:I+OsD/S5fYKHwYJt9xEssJQQpFfzge0dyHsCBpsUb2A=,tag:Zd3tV1XzLjiLN3Fi5hRZkw==,type:str]
    identity.pub: ENC[AES256_GCM,data:yTUYM1MQyGlJQxl17cCjd2VLfY4Vhia7Xhf6tzzIGAJKSSgDNKtjk1DRWqhPtc4kuvbDidTRYgdestHgz5/gOT4ouGvmRXgUUwkpCeUd83MqIHc9+P0XKzHT9FJunP6i1stYJXU6Hef8E8BMuKTl0jPaJQ6zd1zXuB0zP5j8yb3ZGXngF6Hwr8UZ0/vAOZvdzHGuKwECZlZkHeBAgSbad/oKQJfoEl6V66cY6li0ULGKSYmIT3mYSYNR0j6qPIADNC3SN8tTuNmrSJW1Yg==,iv:OkWh50UFuX6wUhchWARm4jUI2rAoeLlyNaSV2UwIzLk=,tag:uNtMB05wiv3qKe2n4IJqtA==,type:str]
    known_hosts: ENC[AES256_GCM,data:9WAxPF0Nq1rgC/QyQb5dT58/H2KcEq7Lc2Ea6YBI+uQWGoPYl+pOC36HQXzhJX3bUtPWQ/BuFC/8rPuyksxvPqGTOkIOnZNSg0Lu/cM7YJ+Pi7Jhi/0Z4dS8Exbb+8NJf/a1T6P6cVTQTURBHATki33P4cVo0hfFlbihOejRTxd8CELdHpGux8J8+hNwmjBb5zUXh9cmVvE+7iYSG2iKeVsOeNOUzNsy1Bn/,iv:KOlCzIhi6X4EHHf6J+d4E4aRB/7Zo/bdDHUrSdn0pJo=,tag:4SbjrMeiIKr6l5nGRWD4uw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFIwa3RTaTA1NmpXNkx5
            QkJ3Ukl2SlN2L1ZmSXJLb3VNYUtydnpHWDF3CmxSVHJvR2tCMkhJZTFJUmdhcW1Q
            Z0tnTCtwM3ExZHh0THBLVWNuWVNjOVUKLS0tIE1sR0hOcUpUTzRodU9BeHlISUhS
            QmttYzVsS2FpUS9ta0dCZzlrSzkzMmMKWY+6mb7sMM4CmvMJgk/yH8G1dRbN3hKe
            MV+4ZmIqmtPBWA3Og6GyC2jDl1ATA0ryBiOlMGHP+dSkJZ0ioIznag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T07:02:10Z"
    mac: ENC[AES256_GCM,data:bvZE2rCP6zVdePJ+prBDHdbQSw62X4q+30THzFzPjnZp57X4rtre6SzrnRavEDE0CaFbhWvVDIZmS3g6/kpNxSvwBv9f9qd6kdr9Fi+w4G52DPu5/+rRNv3akbgh0J8YErj9aIN5dm4NXtFMXQbV7DrbuUmSFRxBLl6e/0CF9Fk=,iv:H0FUO1wotNfjrmDtZ5NZervXE7LjgEyp3FVSBrZs2RI=,tag:rOMW6RDsSA8PfNPFDX6Myg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
