apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EF5GxGs6IRmsShcuLWnIUoBZQW/COUkndDLv9MotmSjPJslTP0YlUgOaNcf0tbdKzXtt0/bGorsszfzvW/Lt9sdAO2BtZWXLBnuwR0abcC6nPGjsuMvoH/rVDp/9FmVf3JcboFHTAiifNGgG64VhyrARmJU9N+Oas98elfCobqHv6SDB1ezoL1uv9Piz9b/ZvpgPEcSsYtJy633eCOWsbcJhBD6N/GJ+JegA4V8hQZna/NlUD0ewQLRGa6RnxyfkeJ33WYKxTfgEvpbBylBRxA+JtbO2wN18pUT+2oT9V3k1fANul7hpcpHZbU/vJMnLuuUWnUHgamMgt5ASmUqGExpCzAHrcV6yvWl8RpOejsOq6XHf6kHBBE0pIl061C1n,iv:Nou6f65kgAApfMGYKicc7xkogLyNMJ2yFiagb5FRWjY=,tag:2p9QAqwscJxfeRy7Jjf0FQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ddPWLEvLfoQASAEFiFD+wIaJJnKPrwbsXv6xVLdF+bdVhJQ0/Zm1QRfMOJxONH76q9PWuia5u3OmpLuHsrM9CbOlvp8orvpSeCqIVI8W0jABqFfyRwGJehZihyaMJQBcPu3xD8wmiCGMVm1sa5aFxxs4IVtgXXdjqqFcIVUhzriiD2Oha4bihqGxxz24HUvXifTvVdfpKZYjhFvrDviF/67a6Ep60qlrwyhEoq+gJPTB0/h21xUKmctiLdNPhwMo6WzWhZFrLnDieNymYw==,iv:lFiqm9U4A4xMRbRYWFbiaauyXeEVXAnm1StTNaqNQZ0=,tag:eVw6zOQFevbHkPPQ87cKZQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:E1+X4jPOUpacaoTD9iMqrCizlSuXEA0Zfw2Eh56PYLLgHxjAPfspfpYKpZVy5HdsvREIv2zFOltI3XLwdUOGjG0Vcf52vg8nrT91xO1NGVzjyFuckTbBUphgfKUsyjoEpivgtXNPVqNto9TTjSDtYOEckOVFKvov2igOAtSPw35T/1Fu6T/7Qvada6VXzMOmAZLKjnleGeTvPrT2UvIR3kwTZL/n4sakXwXC,iv:k103hGEmNsn2nyRhhFJaS8Rils2WLoBZ7nAuF1h+dPk=,tag:GoGn8SyzfsqCVkBT2Va05A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSmh2UWU0dEJCM0srYjNw
            SHFLOVhVMWkvMzhIUS9LckdndE40QzBuWDFNCkRLSGtBdFVDWlEyendxOW9iR0VW
            UW96ZWVJVGtQcmUzcnR0Zk5FRDFRMUUKLS0tIDQ3ZllITFU3SW54UWl1cnZaejFC
            WDFpejlvNUlGMWErVnhiTitQQnY2M0UKpq26vjyxXLLG11J1K9JDjJqNe3C+gER2
            FuKbbBiuC3Rxvfrvv2fRZHa3irvKzaN0EC6PkP7/cDmXUFdaWm5CWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T07:11:22Z"
    mac: ENC[AES256_GCM,data:wcUjqL10ftFWDaIYCGsvdDI3oPyDbirzL7ijtvJrdibl/ncOxrNjICpiHpDbpxMelVxbNsRNwsyYUqmjzM75GsyfqTyzQGgZGJGQ4ggkLG6sf+jBJApmeufP1Or9d6qlLm4ptYSrA4zKX2JOeuaCaGvJcT3t3BJWAGXPkonncng=,iv:onBXheBREXohBweRlJwd71jw4S1zituzOdVZ973R63g=,tag:viKAaybSbBP0eK8tIRkPJA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
