apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6hcPxI0O6lFtUxjt9/GKLcnRe+PLbcTM4z5GDfkGRVW9qrOuMmNPsjzDGHLanOb4u0fqpWpZ2ug4eKH56CRz6j5Ihpff64Tq/TDmzz/6KY5shMiADiR/auoolg9DWgkWJW9GUgeMh+x/aqh4Ja6Gpbo2icMSAY9yav+qVTC2rEL7R/kvvcg2RNVE37BZ+FXYor32ExC+WrD19sKIBs8k1jHE1Tec89ft6qFKgBm78WeUdaRcYVDbljQgRE2wfFOFz3H4fzyVR3FjsLWCXS3JGsBd+Esa/KW8mYsCVhDyxCn7Ly510pA82OegtneaC0ufs9w0UX2y5YB4T8Pmm4sC3VfuGHtL8W40A/RJRr9pOKXaVGnI48IWGDHaU69rz2d8,iv:QwrEd6JMdPihIT7o8LL0Y4+IyZ0bEYVtIvWLHQ7HD2w=,tag:deh82P6DIKuhlCkTLjfiXQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:7MvAW6ViTg0fWNPvCXrZWWajqA1Ju6DaXvVXPl2vK2+3sA9g/asXvIxMRwMz13SZWbayjdq6EphnVNPzxf28N6/wfTOO1tXPeH1GeezBsJN8/FRceZiKIGSzoW+0U0/fomBuhFURDGDFBjsIWYGFRLfEGR+kMiDiEPdyxo4HaVCBrc0py+I//hJIVyH0/mppG5njbW+c5N0Se0X1HtYFizUrjpv/aEy7eVr8z0pUmBWBJwYLnRATEzHkKiaztjuA7kAZFX1dTcDz3aok1A==,iv:QbloWzMMXzju74wX6OFFgba5ZUJOBhMOar3qQDa03x4=,tag:dkaO8VyrnBgLPegFVV5I/w==,type:str]
    known_hosts: ENC[AES256_GCM,data:w5H+J99k1WVkXUx6IzZ5+HFCwmbD+oMcEg9m7WKAecEYEjz2KOTPukOETJlaMFtyBm/LEbfx5djDuH4G2t5yLMB9UCD09iDjI/ZcVEKJraEc1Fq687UcMSVVpkCGyBWxrswod/hGSkZFtcYNiSvm3GpKkOYUJn8IxLXlYveYwEBy39fUno8lfyvHm0Bat0SvYN6LRTwvRcneV+3g/xNAa+5Wv+Zipf2YNGFk,iv:FRiMXNkqHb6d9W+tNlkVqb4VcblyKpxAoDbwjBQOt2M=,tag:dgijmRkTvV2zpbdC1YxynQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cEU0NExyeHoyWTRqcVFo
            STk3RUVZY1dxdkd4WlB0Nm5kU1pqY204d2tRCkkzemVJaTJ6L0pwU2VPcUlWVG1m
            aHVsaUtib0VjYTZ4bkxMMEQ2dUVMNU0KLS0tIExVdnlWSjlJaWNLQ3dLYVRyRzhr
            Y1o0V2J0djIvbmhRNi8zMkJLanZOMWMKZzuNMTKu0nFWxn/DZjWnxRWfYiAfgVhr
            Q6mznYBqgJ774pq7lxnTk6vNndGiLT0GnE7GHPZXZfE9jO4dOQREfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T21:27:03Z"
    mac: ENC[AES256_GCM,data:jbdcne6wNytWzphKD7isqvyBRiEMYHEWEBuKJYKR2+7+umkHHmffNQP1ZxonkTDTVxAECfJX2xAtZHw/vsr0CDl1tIOeZjBfCs7tknwNBAvsJLvwB2ofZ/e4qq62RuCRopXzv0V7GLE/r92Yd76qNKfwwjLslmtGBN0SSl6h7PM=,iv:RVnHPlucVRsiaVb31USFimaq1FqO21zPLVw+U5Zs/w0=,tag:OCNFHUnC84+hy1ti8pRcNg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
