apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CcB0aWAotgtrRS9utXUw6zFHyOqPqaboEs7EQZdySffcsKTo9mCtmTBrwEZ64l53peXtFPQFZHny3SZ7xK6Ebm7eEgP4gx9XXck43Gl09gCkk25b9/CiN5DgFeMxw3G6QOlLlxObEfLpYLKWjPEg9l8sYPEvM5IRVNX0ahA3cO9bz4BAsHfSFO4/vg+qd4q5tS+3bog0pGOprTqC+qE9xQxmua8BtVWRnLCEEsrJ7WpCnNYb+RTyNhTBSFy4idi5HZ0G5gpY0+G+QqP0G3eIs0OFxMIrCLK+TaTZia7qf5hHBuYdvVFJ8hSSf1obE2IMo1r2ghWkXyJ19q4p8ImDwuYKujTTpabJ5Svw7J4uMU+JkAkUrNTtQm+YRN9CkQ1l,iv:2zVBVZYYbUEdwXmGyktZOIA0Do+EOZrfFabF+04KTy4=,tag:wmy3SieQd8C3VSvx79OyeA==,type:str]
    identity.pub: ENC[AES256_GCM,data:dPIDaPEhDMdkYzxIee36o9KcU1mmVXZuFM2UgC+U+32KXm8s32aomPsk+l2hrDCOcVHzsvLvnwkb+97xAX2ApVfUUblxIG+I7yhg+G6z4QYx1FkZ/u+HU35wTXm1ZkOrqnTcOnsc4UkBJM4ZyqDCcSe5Az9rlvO/aDvTPZuX2DhX37kRidodsDj6Q7FIqy6as9vm7aS6I4OR792OYPw9+2u8/CPL6ViyFVDBQdhBaZtMHtSAh29ZO7TAOI7eFj3tmmY65nQM+GPRwoN8lQ==,iv:jxDzp4M9NuejABdKAiTwXh/2IA/LaCoLkYDrKS3VVZw=,tag:6p7yQtuwhue9oEALZ/2WMA==,type:str]
    known_hosts: ENC[AES256_GCM,data:dmE7ecAjsaUhxxwrSxiRZR1pXsU4wb57K2up5s6nvEfm8VaUi1n8GqE34LJ9mDrKbOOCuhQOTh6HTWLMCR7oHXx3RFgQD087ESNa8d8Gq9S0pZ7qA++6qeQrs2ZRC0X2Yw8I/KvOU2cQmiYrfNpm1bs2WikOY968tlmynTjmNsuhgOXi1KWwEBjLO5AQwo+fGAz6/AswYC/gfI7NSP6o+TCksJXJ4MxvyZk8,iv:IUc9HkXYgAy8mM0Sq8OzmLH4P9Uzq+dr29aMAJOj7wk=,tag:51y6rQEQ4PkgofhR4zcGag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTE9lME5Eb2lUTlE3NSsr
            aFZNV3FIMHJLMHVhTEx1OEVNVDJ3bTRCb3hJCmZKeUs0Nmo4MlBTeGQ5SFJyN2NJ
            RDFnNTFnWUtVNzJvSk1rc25YSDFhK0kKLS0tIGhRT2ZuS3JTZXRlcDF4Y0VnWEk1
            djJSNTFvQ0JxSW4wOWVQMXlIaGxXaEkK3Isih8yyFMNcK+GFCg6DelbnsI5/BPU1
            a7J1lTGj2kCSaHeGyP1ve6HR4lmNmwi1WzWwolPQ+hZmSQFuErYgnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T07:06:06Z"
    mac: ENC[AES256_GCM,data:L4jICIIfKhRo2vJ1vQJlxvqAABUWR/HNedk7ulAN2hLmGWzJ5d8rYTgO8ulj43FWn2TV8MksKC8mh5lmY5qmZ2iri/rA0lGIllAu3+aKaYgbbfPbCRF89htig4pxDvxy/No6D5Z/FCC+lo3ekQdBxbXCKfWwMVo+9KcSBGQTvk4=,iv:zOEevp1Xx1hQq3ub2My7hOB6ZFIYK0rpHxkzMnekgNE=,tag:EHRLXfNtCMzw3eeIwJB9rA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
