apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fbFSt9xN5HQCIEq0FYlFIn7dvr8FE9JVAr7hDWtj+oqcXLLhpWL1FiAaoGeNQhlIjVhszBtFpj0Dv3zzMZDK44hawC6ej75D4d/3oFVIBra4VH56KkHwd6aQq2EuJ3EQT3AWHsGrHlFw0paJaq9gcBVxdOBvxbmVQ80hwJn6zYmj1bBruaFj+qZUfA4frVOFNWodaHBaSDdqhsj6Hadj+CNIbWw24c/rxMgC7tkx0gBNdWf2K1FOQbyn5Ma3tvCVGD2wP+GCSmMo7tnrWl01EvfQzzxzIzZoJDm83J5dlc7JZzucaSRWKcjk884N0h95VY6W/9/yCkbg3CUVg27krW3UINplX9sEcUNqhd5Jgk9bLLV7cuPizfMEBGED2Vfq,iv:8RmOjUUALvmKDjO5kLhTfeLiGCsrWqjTPYQZ/isf6z8=,tag:anYW+djNSmU6RJUPnkAV2g==,type:str]
    identity.pub: ENC[AES256_GCM,data:k2dcuNFS19/zSMAs0FcjadlxgDdZC78aC3jlZDQs9quoMIqfs4uMVHtrH9a0svyPNa/Ukkljpo7wRvwZSXn8mx7exl9DtZNSSFIJjEDNwaVkc3HBatrjguh0SlbYS3LmF3F5oXzMqhdmbrrWuKzMq3TFSyByJ8Jb3v10/eoJrWJGgFqNzAc+Tc876lR+NPi2D3fT2v4p0TbfripI2Ba6oxv2NnN2p/N/eiLctChJvosp4+skrqB00L/+0GRwCTN+4XyZb8nPbHIYQ0+97A==,iv:6BEw4qJ5LAXXVHMDhYrPrIA/G+1DhrxmjHKJ2KVeRzw=,tag:HXh1Zk7E7+nmyJW5lGkpeA==,type:str]
    known_hosts: ENC[AES256_GCM,data:cnxcao4Q2UHKx/CSxKzh/stn063uvCIHvjJH0hp58/z0oPwTBbq3OhoRzbMcIl5gh4/cHhBm7OT6+jMFSlnqLjVROG6xx1TBxAWc4+7S1brez271JaRcSYhNnYDwBJ1uGduZK3rK62p6LTrON/W0HEZZ9Vb/wYv66uQUAIRx8+mbTHRqoRnwdkA/UYYCGz2LUPERnaNT3BPCd5KqdLUJKOh9sveD5pKuEDiL,iv:PEHSN4QhKjHBleY4Hf4pUvoWDw6/ITiUPIVawRta+Es=,tag:6HYFA2Om86EhtQYIaGyMxA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOWl3TktRK3dlUktQeUMr
            MFdkUm5zT3AwbWpKM212dEpqK01ON2FQa1FBClN0UjlXRE5mMU81bVRUbkhVUEpr
            QWVEZ09RcExtdHdyVk9WV0R5ODE1NDQKLS0tIHhVUWluZE9iaDBjN1pPRUY5NWoy
            YnVmamFYQVdEM0RIU1hrRDZCeU5MZTQKwD9Eb3yuZMHusVuDKnM4Yubdbrsu/JwF
            +rRrKKSooNGJJiOpEO7U8ShZYaYmWIBsKGHoSB1VM+bxLoOb+a7c3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T11:27:10Z"
    mac: ENC[AES256_GCM,data:lpzw9fkNeEpav11Yy94Z8R/jxrnPpGjsgMp/No/3c290KJxSb9jZT+60tO2U8FSGmLi+ljQF0TSX7Yt6ozuo1/0cAR84fp9auqqs/XprD46gFc+VfrOd1s77IJi7GNw6r7+OAVAsgpR8+82CxQhhB87vIq6GH1yBqwQVCWlSvtM=,iv:msryRMWW8hvH5uOCRg1C31YOwlLhelNTZtMCYW2CDYQ=,tag:JXsV/3Ffiq5ACdWOoDJEFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
