apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+u+rsBoa+snGOaA1zI5ssqhKY+US8NBAz0u0xwPClM73wvxbslAzokhmfsKZVEGQYfpAhxoxsZRbcaoeknlEjcIfj5/LXfui6Y3URs7gcl7UhMn4IJQ9h/VLfITJd9wHU71ayEjOAePVMzzwNshJKlfrfXkS0zuF7TGFK2aFNf4UWLd20P5YQWL16Z3P5PKejjbvuWLw4LhKZ3Mz/luZeZC3h5JmIBkJvLmsSph0tVS9hqaPibnDNZZ3pM2TtpTWEa+JR2lfvqGI37yhsCsuRsmz0xSSuavWjU8xCKx/YnE0vJ6S1vyCr84snMGmtq6WRLBfXmasXeUYl0s+FE16EdCLJd0rWtNYTXb6FyMtN2f/Iez9HZr4JvWnVNh65lUt,iv:X10+nY3Pg2iwfxJziPgorKpCOfBgEWprIoqtnmJiSw8=,tag:oIgojQQJ31+U7tyxTp7Okw==,type:str]
    identity.pub: ENC[AES256_GCM,data:3PWJQU+CPwpe8XUyAzNi+6E+JUuMdprdFrCZGkueiY3fsGmhSH3kU3D3fN5qrCqjlArsD4LPpkzVjjLdakTW8fqqZDqwGQ0FMUY+Tec/b4GMjd6TqpdbnhV9zZNboXUL2YBBMkjGcm19+8j8SqH+kigxw/sNV7TW0yw/MDU+s4HRw6zU84d+vNkUFF7p8j38FupcjlXB/nj492CD4yHbuzjEWIsfbh/jTtXo2LCJbkMvYcQA1d2Zp5ZvL+nkiBtU44Pg5ouX1l/1twg3nQ==,iv:OqDp1kp3B1M6Oge9fWdg6thPOYjjtdgkZAffuwBbno8=,tag:SRQNrrj04ymfYbnYS/x4Tw==,type:str]
    known_hosts: ENC[AES256_GCM,data:GEELFtmT+fjXCNXxwSjBOvzrvq/MV/nRFvZRZKI7RhD6DwVh4ZKsZJ2F6YDTfa5a3i+f2WY23OZ9IvMfH0J+pYQPUn1pcMZ3Xd+RJuakzi50eCgvb1iJ4T4P+BMHxQcWwlGJRu0IlfzfB1pBK76K26WddlH0zijgXw5xA/Ctz3BgavdOin1KDFaJOm+MpAyAHEIDckKPpuX+AgYeqmKLhbACGAIiNLlenyZq,iv:stz5MYardNiPdbDMpY89BZjpHaVIDYqjtACC9xMm7Po=,tag:lSIqPvDtx3xLgJaCmZ0zmw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aXl0ZGQ2a3dreFdTekd6
            UTg3OFYzV1Rvb1pyVkRqeEQ3Nk5QakNKRWgwCkpHK1NPaE40N0hTbGVqcnA0Tjgw
            UUZQRDljSjlxbEUweENITHg5ZWMwNDAKLS0tIGFwMDNkODlCY0plZEUvN01ZaDFO
            MnFBVDJ4Z0h4RXlTVUNzK21zSHhVd3MKnj3ta83B0hjTatCYaTiD7OQ5yO+kwzQt
            ssIQWeVRp2VO/pqLIqdiUBe5aSR1spPRvJeXP1r5zlC8flZ4loQifg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T10:07:07Z"
    mac: ENC[AES256_GCM,data:Nsz5G3erl+pIziuvD9/D0rcgVOdBMHyCI5tnRjvtpxBr7Dtv10Guj8eJeNMR9SlY54HUxEODJikVevU5UiBURq+sR/S0mNjCtoD6imLrXiEGRwGBX3b7rkmzyhnLW5/NV2CyB3tOC0J6iLnXesbFFQQG6yRHrdwO7b9+pRymQm8=,iv:8m/EXOZ98H44ViXFGjYu8EkOhDsFbVby0Cn1j2zaBkE=,tag:yh9GPF1nrmZfFUJmWI+6Fw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
