apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+MqyHvi9fq1KLtpupIB1R0rPdprXruGEJk0OGjksU/yh9nDB14juJ2DsjzBXxwWJSYxheESHAte9VlEMThV3wFPYsTYMsyPikGuZTI0RUn47RX/F0qVBV7A0k3IpytbY8+RqJ7zRtuAr1vPkAo3VF+XzyLLzPL+5RoSUoJJc9f10U2+W4DYYjQXnRXdvN3FJAFlIbYjXwwURC7H5tST7WD1QEhGvdML+K1tAI01SsJ1HA0SzmwlDxPtinD1dy+BC23ghN8H1H9Z3in0oNy3Q4GWWGYJsiZJAreNDLCzuYeGYfzozfKJ+z8wHg8FE+OXPEDlXbFyXKaOx2gZ+KDyFQHgBtKa/ye/YJ6HDK2B+cCcLJna2og/XzVpTem1uka4g,iv:CQ+TB6SYdXRJrXPZGpdi03vSxE/hjGsE88iXqVxDpAE=,tag:FqOf6DasgzXvkLnkAWBXxA==,type:str]
    identity.pub: ENC[AES256_GCM,data:BtiKkkVqsnBbcf628ymm9Cs/jB+F49m44GvyDUAqCT1jXS2K2vv+XM7nCFTqmaaqXZ43sKIQDLECrJHKhrGES51RNVjNUqSSRYrv8GFwPUFT2O5VnAe396w3s4UfelmlalzYGDjsXFMzBVs/Zexo5h63HAHJmrKK67Y+4XT6IXk8Y6OGhRoCjGrQcFoYZWFhyhgsX77GCYJOIPZOhUOd84rjCMEqMJIWlKl2oaLt9fdPB0qEikk2n2j8F1FhsT5ozW/3bsWeBwbTxEhljQ==,iv:L8KNzSVkecmdCjgISOglyEPnyr4lWdufSmdzt43huMI=,tag:3ht7oQjRjHAU/bRlA/kJww==,type:str]
    known_hosts: ENC[AES256_GCM,data:tKCrygUsyKxA8fYMJwtpK1y+VonZrYHOthKuNiYGnYNLGbLRXpKRYGcKesaMrijehG27Md0Xb1qVy8ilmfVBYfL8oRCbQqC1CwyvGH+NPXrzaizTGnUZzaqVB8FCAUxBA9U10mnC9X6+auml9oRWr2IpmomQIiIu67c2uzE/kqxvabHsWFY221RwoRoFrwIY6PX3/GvIX7U5CPFtjb+Ki564sGXM3KPK63/N,iv:YbecK+ffeoT/aa9AyDhpDZ55251azZ09g1cos0WTrb0=,tag:Jml9cu6ZoPMemJ7R69cjZw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTXNrTlNuMGtxM2lraE4z
            NmsyWnR1akU0ZzViVU5jRG0wOGZITHYvNDA0ClR0YVNueTlGTmdZbE5VOUpBQk5E
            L1AvajdiYzFxbDFjSDA1bllMQXdwNVUKLS0tIDgzaHRreUZqT3Y3V1VWZmIvMXhk
            dm5XZWdaRTk3SXRRREFkdlV5OW5lVjgKTT660JIyq3876AKe7QQ9GGf9WIymn3ES
            0RBvkCYeBpDNguQ6pjdKoyJm4FpC9i1GuuUnk6iDSiw5M2tt/z8FYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T08:03:02Z"
    mac: ENC[AES256_GCM,data:4C6qEgOdVs0d2Y0LeB7so4LWJ0Hgw9WHdqo6aXBnUSZFGhBFkjIbYWMoON9lzSRvRspP4aLz0PB97vXK2gOKUYMR2nI0YxQHQkFFvOmZblIoGTCHr06/Av6eawMXkYhaI6rtALQka8k5/bsBnFEvL2bNAl+yUIEtYVHmOcUAF7Y=,iv:Aam6hNYlOjvL5chZWPxSQGi3AXN8vjeuc9iScc4M/7w=,tag:ljq6aGOORKgUj+EtmHm4QA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
