apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jONE42vJm2D6tlpuAilx5MsCUfLV9V+pwYZmXyiiwTjzIWox6Gybb6MLsCaeGCfRz+isDxtKf0nGOd9tZKuqcKeRby/0gEytaPzQ0B2jmQh7RVrlx2i7OfEDH28aNhdkLIVFPIN0awKvtfM2JL/MUm8/2+p82hc7p11O75hQH/xUR47jPEJqu+TvFKIS8ECii/R4YUPXDKBIAU+yuItuSM4h+mwpsiHEl78XQu9NP0rjfOCW6QSLpmAG/cuPtI32Cen4cifwd++Bla0NK9ndPY7PCHmHzyY7hqUZUqxLvdcklTgeDPWNY9vetZ3+xgC0yrwa100S+p6skqx3RXMmK3CyS3UjEBkGMN/DCuY3t4/+MLqt0OP68y58ZXc1FZsO,iv:vdywGPaB0u21MkXQHHavdE8ictrPR/EdMIF1T5Zgcqo=,tag:zyqNXu+9aeOi6a29vnu17Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:1WatN0t3GWM4DMohzJKK3Mdu72ujoOqiwJvIDzTtZIFbcfIEw9lqeQlsxiKQCHHHqw5HBs4nOYFztuS4k/G2AT2UXBgoBMXiQ94i1Cy4tFhr5xCHMK+Sna+JNizOU6RjOETFCpG8kmE/nkzwbfvPRti1oguYU1V+wTycgjnXVeQwrwRZvoEKvx5z7LSfI5oSYtpflvxPuI7rSAtysV3X4kkFGxV4IdLzBxABx9ft2O6klMBynWlB7FoPcFcEWsb2gPq7biX4Lbch7zeFLw==,iv:ONMPUGVJNshd3NwSpBgbOsJTDaurS9+Of1bmK9Whn4M=,tag:3VyfG0gGg/PZqUPpp2K5kQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:mx7CGD12AvJAsw66AG+Dx89kimvPxCkPX3iDP+OLPHLQH0XB7eRIXnSFZY8NJm0gVYv0f/lS5WWB7UD4VHUG5tNM3dFi3CItoZ8cLk/FNaico/gpAOPOnz81FVKLql5uKTB+//I8ulVdDVOhoOSTSlaF7CcqvZJIutQreubwHYtgbx+uZo/9cnY5tz/0Zq+lwA+Jyf60O2NYif/FTiOHpWptHvhhqC3Dm39V,iv:dcIk2ONOkdKqazmQYpiOY5sGUzMMliW3LxFDpHkrNTQ=,tag:T0Rv7TbOvLiYPvAnYdFEeg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTk5tZ2NBQ1hzRndqZDk0
            RktUSFRKWHQwN0h5UVhQdG1FRExydVNjd1NJCjlLOVZDc0RmWmpRdkM2d3RSY043
            N1psamtTZGpEMGZWSjlXbXlrZlRRcWsKLS0tIDFDZHEyZE1TZ01DUEcxd2pTTm9G
            RzdvanZzdFdHVWRmdERoNjIwMWh1NFkKMbCeZ/8LGT7uSm+ZNT0if7xJYo/hL74l
            VCfHOin3+eatwliCXbRJ26StX2laFXWKLXqNL5UySxuNP8vLX2UAnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T07:58:57Z"
    mac: ENC[AES256_GCM,data:pvJonwncCVMlgxfKJMkB23TBuOV6BYpbAiQJeqXvfEi9sp7axZxy/Jb1rR5ASi8ZaIIK8ObVyna6/7hpqrjUi/6XCkDklvu9jp87ryjczOGrPhXI8HGxkmH1GYXNfv1+AA2sKbDKOBEn0GZn7rZlJOkWqO0h+LaQEsFUPhTylmg=,iv:URHNVMWr6Be/GOHqQsg70IstP+gxWyB2kqIDgIMEmq4=,tag:eoLpbdjhLiE1oZOw3noVHw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
