apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PZt3rD+EgZKfmxXw6UA2EICP+FK3gdypLrfNdhk9OBVpXoW7J8fw5f4SFfKZUJY/eOcBJAlPElNJyfoLXd0UsexXWzM6unhyKvEpH6cBhLTZ1jGqpSJ5+U7ixsTLacyoHshkyOIOn+5gNvtGG06Do/Ffyri/wq/XIBQKd00GdSHNFq2NUsTQo8iJUR6sQ4rhO1AiXhR+jqe50BpaSgPNqzmTVC2O/fzM/NU0dhnKiD7janGwq7dS9tJEZzJIJlQdjySXryP5s22PBaBIg7pFgxaaYimULPoxoDgnWNI+ivPts3kMaRE/Qf42fBe7RcEmHjCjA8eQ1GGQEvERQ9KqRdp7kwMLhdDNq8KjKfw7NU4yK8fVDOj7Xy3Qtpb5g0W2,iv:GVbs8SI7JeCESTWVcZcAVf2JaZ1DF9YgQg+EG0gpuyw=,tag:FraIrz6S8P8Lj6J1v1lizg==,type:str]
    identity.pub: ENC[AES256_GCM,data:BtcQju2hQ02SCSv9o7S6Lwzkc1bshJronMmYhR2LciJuI6LkxevP687P9ngMl4j+v1wdnOvPKxK2UcjmsZwKGB1anX/sEaNfxXDXF87yPmGW6gfHtT2LtCdSAPSirDXEHYcqLFsI4QcLoRxLUxaexXHcuJGbTGQyQ9dteRdQaj7GufC1hyyNi8BR1zzMf2kqJHTpE+DLINo0GhEDijvG9SHvD9qbVuqy4nKyPMvHpjvNpiWSBr3Oz/M7rn/Fr85MTpbg+iUNCVFYzPHbSQ==,iv:73WmwCEZAxhj6+mAkWvbdqDRVCDZcLogo38xuIxrRs8=,tag:XoXQ62Q9q5BZxVzGk/lYUg==,type:str]
    known_hosts: ENC[AES256_GCM,data:kU5L55hRqN47NLwikNNVpkL4Du7LY/SspnRPlVvA/gDdB08FlVyyHZGHxptXj44ai3Apg3IK3/qFdGyNvYwWgqA8Ax+oUPT5le/XfMX9L4RKQuQvBIJ3BzM0JKhIFsJA2vbTNgA6lupPBXMIDVdiBdYdZLyHxXd7jxPbAoRLbcB5NYJDqwxEVoK09r3NBDJ/QYk8Dk40+uZIVUiS6Ynz4/ul5w+m2+Xxu08R,iv:HdUq6lr52RbUYQXiowUPjpruPR/HVT3Ym+g6ig2/HgE=,tag:GbRY45zf6NzuZa02Vamvlw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1anF4bnF2TnRLMkU2YkdI
            c3IyaG1zVFpKc3VxcFR3R0lKWUhqY0w1TVVZCmFHTkkxaVRSdEZXWHNheVRkRHp3
            SElrV1piR1YySEtBS09RVGs5QlJNb1kKLS0tIHVEeHNHL0RoR0pnTGNJaE5YK2V1
            bnQwWjRKVHZCNUE5L3cyVUhVS1Y1Z1UKoYof7jsBcvqpUqe6feC5aq/pNVuuhab0
            EP+pILbf4YK/J13SAmITiJq15yl3bmecj5aHskGz6xUTLCsvLttGqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T11:47:14Z"
    mac: ENC[AES256_GCM,data:icL4ZBhgnGimYm7CRK8YzHukDjU4ePrvvlhVxCsI41kKvgROLGjR9t8cmnOE7jQd2RrlkyGOt1G5FID5EMoyIzLh96s5aIYqk8AjfggasqNCgFNu2CNtpTPTqwCXQyTvLUXD/VlR8F89Tkv2Nzhd8Uu8gumOuLVxO6OnjFFdwHc=,iv:JE8wY3wE68KPCYVYkoXnqsS6sJfVWKh44KYL660N0bw=,tag:ebPsAR5hI5syav0B0GYeag==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
