apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PQdAOlwVbgxkuFAzXdGoZSKpFgjHvhmxsmGXYFzSuYIzvW9yplQagyrzNBkdy4TRIa4fUzm8d65qPv0kH5w8YWUi+H5MXsmX7um65j5apVHTPtwwFUsgLuF5iLqUOO5KW51HYAYUIY0XL/9cR50jTr7Dc+kbNVRoyQyYCiFaZf/GakMzMT10buicK/63jhifwqrDicFK/VvOH7tkX5P7S3nvt8OGsnm+9GPMMTRx1x43NbEuJSGuFeJvh4ZcykLMefUuI1imtHiSbo0h4s6DVNJqNbma7i4uivCuj+xGlS2gPyMu3GrjOwaff4aGNXgudhP5r8PGypqr47b3JFvdj0uaQuz7DNeBy69L2LMkuG+Xcvzaq2ayyB8iyZDJQPC7,iv:oTQDeUcz2GEEva3G+1F7sMrn0Xilf5xP8YciGp9YNYU=,tag:sssOGQzn5U6kISKoS+ZDgw==,type:str]
    identity.pub: ENC[AES256_GCM,data:UQ2RTmhj8MktTbxHXvkq7Vht/Kantl4HQkbRcBtgNpECxPCr782JsYakYFQg5HPTLCkJuBvasUuzuSH5T6N24kc7jSxNvROJAj1FW0YezcYJfuQCHwQasUlQM9XSgfPviIl8vuO66gkXFYGE0Tyr068j7VTA7fHiJRYzQEkA6zxxmvJVXGPTJamp4oPUWMh/MkXj1Ws6DV1IBLiQXTIC/AsJaW70c9nu37dwXoCsH8HHZPrays1gX50zgYq88ePIdcQHehyGMFEZaad5qQ==,iv:mAWqZAyYzz6LDRaPtsdLvz8ZfMjLIUjlthozae3eBOM=,tag:Emr5f1bPIIO16nHdZ5/1LA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ni0piQ0YcHA+E6tvmh39cf+Dhuhv9/3WalblVIml7yNE9xaEX3QxYEXAKzqQLiitveqdPw6DIFp4dHBZMzrqHTwyR1PYLerGMLoyaBYiQRhFVFc72ZQXQU8GkUFd4k25wdwIoyDQ64B9YQex0ljIQa1UgHApsVsfPQXoPNstWTm9m6aRnavJXmlSlqQ01TeI3WfJ0C6JunBxodACRZUk5CEXJiadlC1exdqn,iv:V/q26qS8jWNij+dzoTpxyeqjQNn/yVdcPfXnD4QoHu0=,tag:EJZflhKBsHFkjfjeyBrFsg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUHErd1llajlDYllnbllv
            bWp0RC96UlU2ejhJSkY1UTN3QkxpV3k2akZFCjFyb2h2QW85Z2dRWkZhQjJWWWJ0
            TVJBdjhrdzQ3c0ZLckd3QnhCaFZZSkkKLS0tIHdUc09ydlVNSFpvYTN3T2RjdFBv
            bDJyQkhnODBQTmhmTkF6Zk5PTExKM0kKqjUybpYqYXc7NtMLNxj1yBYujHAWCXXR
            L5n7OR9uCt1kKYUV7Ei93q9yLoT4de009qNxsx1NPDI7K9ZP9J5bdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T10:30:47Z"
    mac: ENC[AES256_GCM,data:VuHxdBU77p2FoSm85K7EBqxv9c6QGdNI+HZ7ancf7bDjrS43+hnqdYO6228foNUFnotWvTHbNHfu7LeSuU3DR2AvtLyxmE+qBtfNRrJO63AxtnCLqdZ3qXuQk7nb561UPTzBnfN1Fd4IZESzFDhVN1hTrTeb+KBhjoDWDiwdxw8=,iv:E7Njvyb3p2fqE1pBw9snj3zrUFJeMlGx0VN9WHOMrBw=,tag:7se3q855sybgmcsAIc2L6Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
