apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ruf8jbzgNOoZjb1FGoMpoOTyBAaaM270LL3loQ72RxuKFdAuBVoNHC0viiRZAW/OCFQIjJfO1nyei0s5+RFqnC3IcUF9xmc3Krsd5hn0NWbVmdH9oTXhbGa0fNmFxRQCAh/4uHHDeOCS3KEa7/h4679qN4i4gdfXNAkLKR5ZAEJ3YUL34tZzuuQg/7i5BUs0sXgHbNsGDmC8VVtEyMcH3Xfw74NbRtYoz7ebOmeIuxZy5hZK+F6XkZbQqm2l6j9cAVnlZnW6ojyGsEFfxjWkVQIwkTagKi+xMVJtLsIx/6CS0SLLrdXtZfQSgdIJmI5iWaUH+J14PUHgckXoR7J6QdE68pKDD2DAV0iXTphQEm61fvugtkuiOQXYGfZ57iBL,iv:N7r6ZD0Hpheaar3ob2Klu7jgaTLaO1SODm6Qc81dyRE=,tag:2DzaEQXCjHnMTVU8rmjtug==,type:str]
    identity.pub: ENC[AES256_GCM,data:JI4nQP2jNSxOcirm0qbnj+4iJuJsUtM/uXhcKxSC05O8lYpcY6pWQTg4XlGDztl/zEy5spfkm3OIL4UTYiBdZtg5aD4h0GyqWEF4h0/HvvGj7IySGMb+Eqv3bEsaDQMnTb0tmW8GGHgu+amFPTIGahYYn4jVzkbD6cYQbWuhSgi9s/5umQkh7uJltFOkdRiqYowxRbv6nNVyE3XVAahiJA9jTYpEtEzCXcQbCuFOP2NKJJsOR+uHWcXnYMbKpZBgORDxvKpYtpkyvgb46w==,iv:oC+U9OExKNkJpOpsy0zw7IfnbSnlGIzngahS0gMMTh0=,tag:i41OKfPMeHWqtnyaFNO47g==,type:str]
    known_hosts: ENC[AES256_GCM,data:2pd2vEGKdnDcp/IXRwhrymFfvcEd7jp7ipsOtFIt4zCgaOwCMc4kR7ezrPOOnjakDmv74LCQQKPxXqebCWR9BdoMq/7GVaNS1avXUirGI2REr/eojwnNbwTnUPjuC5/MRTjFEwbAGPZlPhAXI9sgIjShNy0r184ZP6gV6UruRBW4XS8STW4mZ5yqwuWcK7hQSvr8pewrSNj+n2VZPw7VyS8asfG1nZmW/dZg,iv:D8aIbOuKzEynPEagUU3cztNRBGmpbFLOnmW5NehqnZ8=,tag:wN4hGovkt7qIeCSLWN6Pfw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaXNXcmFVUXJZY0ZMRXBO
            djZTZkR2Qjc1TUsvU2FGV2tOQm5ZakZTRERvClVJV21jU09PRUptdnV2MWYvSy9Z
            WmZnMGxOMmtHQWpkRFdVTkdOb0l3djgKLS0tIHFabEhSUmUxVWtiS0xNbXlMV21C
            VXoweG5YU0UreGVNUk8rN2FBQkVYd28Ku0Nn81vJe7Bq/scHtHWs1xBl5cSJwMGT
            /7h6zC1YY5UgB+0rrAYgQIeevsGtVIFi0zmEwzrqjUrd3Ka5cGTjWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T05:25:19Z"
    mac: ENC[AES256_GCM,data:fhvA9BOrjwHpIxdFNj/mKQFKNw976w2QhRUB1+kkdCWJPdF26BeTTV+sGR4E0x/wK8rrYOP6CC++SPSTCVBE++Z0n2D5HUEufFLymwe+9ggzRhBXBKC/iKTYmYnoAC20conV1UwmqpVzpXay98aOXhPTJS8zDb9C9PGdfBfN6Lg=,iv:7HCxzuWnIymbQKjZ/hdRZ+jbjSQicnjHaUH3mhnuCV0=,tag:0VMm5Jsj5+kOUQWBa9KkMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
