apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ve94IFwLC8wPYVzUINv/Cij12h8lBsPkMhqJR4/fhzLxiE+T4NySTdPzGHCaTPe5L1LE5LlpA9TQa7796apQ3YaJ6N7va4iMcDXwIyxnb0W654YjzD+QBwxWywMUj6tbpkNfXbfFKZoAftVrPAIE5rs78s7nr5UFpFmEZ+sg1isnVXFxjZDBFasJTospnoon/17LOBLWjqwGaaAac9dbs1rckaxFKgprDMyUOiNevSWhNwBokLlNOGkI+rQVcofg6kyA2H4ZftKEUa7DXr0/28x6usaK+gFgpoy972/v44y90jnj4R8mlOroC/9XeqWxFAAACRyaOiyeHXgff59TM9lSUG4DIOlKj7Kw0k4Xwaf8eMLJfg+mOir0hdrYJc6U,iv:ncmFyyE0wgIo5KuHjzIQoqBm41G+ZiXJnFA2whsKdzs=,tag:0t4M8RG1I2aW+wosVioXWA==,type:str]
    identity.pub: ENC[AES256_GCM,data:YKSqtLhsblbwv+TcOOOnQ8o5iOx0aLrgMpkq1p7dSp8agj5JorvyMMA4QTcjmtn4QZoVDQK/mYioDxpTnGzu29y1rQjJUZH/4grYgVjB6jiOrCPyetmDymVFeHmYHa+YoPsoFWj5m3cHHxk8XtKJl76gUTc/jVau/tzb2rnvixKgU6dfw1uJjEc1VcX1J/jIgvwwfs/m0Lj0hf24iSdqebisMXtX5ma7iS9658x9zTQQGWWqZK6vQ29/87O51+R1KTnVRDheKPFrXZDM/A==,iv:mOTnKm+2VMyhiBz09wtpBqqDmJaF5k2P/CDZXdePKpI=,tag:1Vx/1hNfPr2D+gPlfO5c1g==,type:str]
    known_hosts: ENC[AES256_GCM,data:dckC8EvjPLAKtFrBw5d/TSBibfyJ+oMT2y3vgQfQVHK4mZk1AI8k74JEEKj1ZRDOxUS2kYdbki8vSrS9kNCLAexdhn3J3inUxAeQJ2yO0Y6PlUCBkocZqcIlGIb/M+LwIDPxqyJdvCQUc/mPQ9he3rvZb2LQurJ5m8eXp+g1/dFweMWfTz/QEXeIP8sIrF/ZsS3/vaSf+Ltebn4g299Wcw6O96ECG3vzeIiG,iv:3UBK1YV+n+/iehJ9NQ2XRGeOmqqsd7wyQvHUlg7jPiA=,tag:j2qM7PFTTmlu6C870xL2TQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZjBIS0VETkg2anJCRzVi
            NXFsNFN4SWlpQm9xdlVaQU5jc0lBVzZVVkVJCmpTWGI1NS84bzB2UnNyZ0xLR0da
            amtpS2U2UWovRGNJclAwZzlvRWMrZU0KLS0tIEkzM29tL2ZoNzY3d0gwRGlmeHgz
            eHIvaEI4THV4SVVjclB5TmYybjJaN1UKmVH3DNqoiUrU0vKoeL6xAy7KFd9PBpwR
            HCsWwSpC5sSixemOkQMYxyRkmzxDz82iBktviZRO1NomuIoHbHyRXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T10:24:49Z"
    mac: ENC[AES256_GCM,data:oE3lL7copqOZrMpBdYfCwVB83xs80oYn1Jen/omaaZva5DMdB+gfoXeLHKZZ1LZt7THg0zMAljhw/B3ebBBku/jalbLo/QG2eJZwR5CSlaEQfdAh3OfH9hm0o2+ox6k4OG1MJc/9am6noHoowjsUlOlYhOxQikocBUnJUc7bkCk=,iv:dBD/TCv0BLHo5FFeoxg717lce+LBefsqr+wIJ3S+Rp4=,tag:+WMLDxf7VxROm4rzJvWurQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
