apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OPTDsDuxFz0PiZy1iAsdr+IpskewyCIW+c+tm1xIFdfbjyx1PNfTYvObmsrT7DNG4oX7sBp8rpJB5B1Mfhi32/ofHLQ3h8gNXEcStJVvYsS7vdC+OELTIYkFo17L3lEjZNz6rX1QnnC4Xf/vjvJZNjT4AXPBxQLs5LaHQlvMwqfHCosmJe1LKsQH7NY/mFvj9z3v8CiA0DhYzmchYua43GIXYJxCRGBsIbw5py0iieDGbuYgYcGilgO2xj2rg5NWSLmizJUT4XtCJo1ku2WkkXEnsHmMj/HeBxcP8EsKtBnF8Z0WVQn4gI4rWuHskqrbR8mMiE4E8T9d+oTlnVP+NJBeL2xbBZcexXeezb6dmWT/XD09iMm/g9FZqxA/Ok8h,iv:k5iB60W6H8kDKVUR6YX5Av/b+lxTkwckhChCvLR8lYU=,tag:R/sEbexk3Xnp+B1KRbrXpA==,type:str]
    identity.pub: ENC[AES256_GCM,data:nROo/q6YMylzzDPR4xjJcIwfPIEy8x80/0xQTNm7m4abIiAv7ZtR57/wMT4DoCbeaWt+0ZCbemcyVbHFACXZAOEspNdkCTuwEhnkFrWvFeb6yqLw1Vs719fHXmw4vnikVe1nQOtFAMX48Cvokml0tpi/YV3QODtDDcDpluT/u9cGrMnp5FJKCKI2HePMGmh3jStgZt/OV4YBiV8ObSdM2iPEeOH1DBrX6lVHfq2KRlV85+KNOy07o/SUu7XfBGNA4Bmc2jsImDl0/HhuAQ==,iv:QyjbJgW9boY7X8wAURCq6/f3dVMEzEOtb/Sox8IzEuY=,tag:/xfb3tUw/PZ2Xk40UojGkA==,type:str]
    known_hosts: ENC[AES256_GCM,data:S6ZaMvZI4ckoAJHAS36X2AwkT0jeyPlLQZa36KGsvxqcEX54AcFqbi1VGNDSRcJLuSR0rKsFVSnSz9EI1PhR1LXgfcxaQwhrws5ezqu1R1nGb1N0QIkgdvMU+f0/mjBx0XBUcBmnjWooSTv2a0MObd8CoBfYx1BQpPA+eNF4I7eGoSTfxrd+iWcntoeJE76dsdHNNuU0hRlzB0AtyVpto/mshw4nqPdw/gGc,iv:atQmWB2IuaefkCEo6l1grkWoU5eqCh9KGK066f8URlM=,tag:7NIQaRbaX4eSlYARjdkjZg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoak9qelFFQ3lITzN2TEZ3
            V3FXNUdEby8wayt5Wjg4NmIvUFJlQjBsaGpzCnk5Ync3K0ZwTzFYVzB5K3V1ZFFD
            dlNoR1VIRE4wVS9reDJUcmpTRmdySm8KLS0tIElnMk0vS1IzdDZtNGJVU3QzSjc4
            L3k2Y01YSWpnUjJWd3NLUGp4aVFpR1UKIAcuHQAFQT7joK+xv2fKq5ZH68YbJW5g
            TrcOrG0+opVTFyTRp560w1cl0At7J90R+VQuHOvP90SPbSHzTtbvDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T09:06:56Z"
    mac: ENC[AES256_GCM,data:MWP4zAs/mlD7N2KQS7uE2VMKTBaONr/9Xg81TAcj59AOQ2zsK4Xt8+dpsF/+UOu66JlmQM8ojxE84nfPdXdhnp8b54KJTf0+6KSQeVTPL8CKb3+n5207imTZuuWAs2ACyN/DIeF/YJjtP7W3br2nf4vjQXwsii2urOmZQbe8Oro=,iv:rpQHgEQnbmoSZEizIqSEfeaqq8/+ua/VNpBjVoQbPig=,tag:R+lm7rJr/O1x66z2La6ksg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
