apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6dIWbXtOIUw1w19q5mmGK2jam6e8mi+6TkeIisyJjWjLxvWqiHCylPSQ/XZ8QNlBdjYeAuA8Xq7sWisal1lA/oF6JXkEvdsbyN7kYYFR/Xe4NI5kWFPpH5JM61CxYBWkzQrQyOXZWBn6P/7VR10wDuZTkQkrh3nIEVBYZ43faFLnpLEKfog+DTzJJ3tG7pbvqsu4QVnpRvTNlhZmDMkSbITRmA9YRk1q/UletupdeJPQp1fdCfwxdVbDqOeFHJbmd5QeRgKNr9h9KWs1atCfY9u76NDGbCARbbJpMMkk9GK/xts4rjj6fkjrvp4u5jHB11HK+3h1IRK+PJe6DxyPU7fvVkYZrOw+HnOHEBlHtOBtBvYJPDa9rqV4C1mVHrG3,iv:DNMM64h+rr5ilIuoThom/fNxEfbtQlwOHjbDigusXVo=,tag:fo892Iua/vge2QjydQ+ciQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:6ccAztD8CwprZpocsAXpoAhK8ccYdnfLcGjD4DUbP9Vsxl/+4CWBwBJw1JBnVCeYTPSqfnCJ8eLPre3CcKO9ScJ/BejSzYgCb703c3EO9T7xr6rnQqCSvghJDaW7+U5tUBXY00/ypplGx/8ziLntVbyw+DRfcKphwWnk1uRnfg9L/QZqvM974p9BLYKddXCvtN5mtuFW4hiFnA8FVeDNEkQ20tiI1byffGsmwjrNg1w4DMWCQs1qFJao4fEtmTTtnh76K6SdvBySgwax1g==,iv:D9EZC/tkQ/jIKKkAHdcvGvIXZgpW0jDz6Hl5XCisTQc=,tag:1ueUbEILPQuLxk2QsT3a9w==,type:str]
    known_hosts: ENC[AES256_GCM,data:LeLHRSPdRuFaUXSyjE7Tm7n7xnKjuyFguSeuX5+ydlXjssWWtYkfkRU84YtPuMsK1GfNLF73uesn/5EoB+7jSI7ofjY3VRCTgIZoRCH8h89sAr5JxgSBG7RzEm4vFFxbA0GSZz6SCps7Vfq/LYr1dmm39fc54ugZDybwr1oLF1bj1ta86R2R6EN8qOyqw5J2VMOL0AM/8Yvs1bGiSpqvjp3YXMKNK/1V3zvF,iv:y0Z1++h2IYAFQEkGRn8SB11N38Fgg9x+y6LyRVcqqG0=,tag:gjXYkNjmBBZx38y4uLT1Hg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cVN5Q1BWVENGN2l2K1NV
            aExBU29sUDVzNWxCV1dPVno4L0sxOVlsb0R3CnlpcEdoUkZUTjZ0bk1QdUNvcFJx
            eHJ2cjNFS0NiSlpEYnNsOGhtNTFhNjQKLS0tICs4U3NIbDdXRGZ5UlhqWk5JVS9v
            VVg1M1BUSTNLeXNNT29JWkR3NVptcjAKoJ/BP3CRD7EgjEQN5PtQ/fGdlbJcgOvF
            48LqPT7G4HGMIEH2oTMDvHr0myZFsHXJyOUeiTWmSm6KTJlkkaNKFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T07:14:52Z"
    mac: ENC[AES256_GCM,data:lpi2Bom3XtS/L0tDccvbJA9wEnqMpd+jpvko1r0YPyJuu1G+mlTdYhb9LZcwLzoPrknNkOhdJTPZ3kStGRNKDKxWblwzRA/xI1/tyI5/rdLXxiMKIR1pk//dROnd9gXaC8DPelp55HkRUr9GKUvHjjnj5TyrWzYYFEKdr0zfFrM=,iv:k8PDXgHNFrWhoiGjBIFE+AvPv2CtXFaH4ZKELnB2VAo=,tag:bnOHA2wJ5f/dZ0NrYTy5gw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
