apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DlAno7PVixfy7il8k3Ldo7fVSq3ne/dHqxTdH4RyS6B4mRPmp94E49kXtKYjvw7odKVwga1gnDnpHC6UrU6bN9XdggDfzg0Td8YtUCgS7CysyYpDb6riDPesMd2NkBQ+fQODX7prfCehxbzeE3v2VwPPd972fJZplUgoTwroMogu/v3i0rItm/SOr3uJqQubm51qDR4JuYo1UBwI6vZTG5ve2UjOD2xYGS+L1vHulq8kCuufr6TrHDf6cpgmYz+sJTQIEPHTA8NQF96tti4DxRW2tZv/4AKjenZjqw7qC6CQGzmvw1Z5Api5jUKu1aMHtfPFV+trMngkEw0SkLWSF+5OZVP9v6m0ImMFLFdadgyoe9Vv72r4AMhTIB1qlY7N,iv:ZL2xIM3yAwfKnxoQz0weGv9gOijusy0/M7+FspCbX/U=,tag:TlF4kzd/gagxiNuv1gvn3Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:R5wquVuSqva3tMO/D6MGS3jKnlNfu4M4yQ5WYeiajENfuDG4MQoZlPFUkFdxP9a2g+n0rVCx6nWXPcgootsPjvtrtAnU/YHvBOixQlNHfiCOOohbk4L+C7LYi6YMUEMSM9yHIQZuCbCpnV3Ktyz/s03rFVC3IxMDmbXfYdt7aPzbYpnrIzuTaIZpkCuV4Xi72HjLbMC2VaihjuZeDAOJK+lw+LYD75ROUUn70gQl643FO9KZmwJqFxtOspvjgNsHzNgV0ok2NQAeibFXnA==,iv:iT6VYXX/YyUUfcYGTSaDnSGJujq+CcjdU9s5xou1YjQ=,tag:HUivv7i83hH+WLbfRAEcaQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:EahFlF3xiZPyD8N7ww3PHJYITMk8XifvP7EBh8Yx6RpJCa5ieaoV8qNho+wR9AH7FDzeUbgFsidHilr2SJu56PpI/x6K7Dg9tqB4ZqOcX89zSrI2ofhpqwnQNKdF9uFFdeIUv6V5FC1LF18CoIx1yeqAqZa5vdLQRfgRAA1OuFXIAh3xAgjv/+vfr+LcvyE1CMrwMgGY4M7SkwZrEQKLNGJQ6Lv47gE6O+aN,iv:DnqR+DqjK7TXXqTXSjDvbCXQO9ZCcMGftNKp+2IKbH4=,tag:PpM+B2FwtVaw+2XTlii5QA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cnc1Mm8wL0hPL2pka3o2
            N2dVS1lONUQ3eVcwYmppajc1Y0RQK3g4WFZjCmRHUUwwcjh3Zlh0citHMUpkTTVv
            eVRYanJaYW9VVWlXNXBVN0NZZ09vUkEKLS0tIHNMNlpjT0xLRktZbVQ3NTBGWUlk
            bDNsVG9QSnVoSktYWTJMV25pbktrcm8K6nl4MmYfVQhl/WExQ8VmAAH10ZR7sVfn
            BdTl54zBho/BOCWmQs4dbfbBoQXPadAAlwxmYGdTKn5Oq7evy7xfjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T08:31:14Z"
    mac: ENC[AES256_GCM,data:+fR8aJE0qKBvaQU+lpa4ID/CPE1vtWM1jOMlFNZ3XPIXAR7Be9ooXIwrT5QsWm78U6+8rbSncfXtqpLmiVntp2+nkPwBAfNSOGZno1875uDIZNiMOYPo7cdRvJpGBq9Bn6jmhJb8kqyN3/qGr+6B8utnqHA0Gg4KS86T0DKd3/g=,iv:WW1w8MU4GP84ra3Rowpdro3/+FyEgeTS/W97a62KOvM=,tag:4XZm1tsQlg5i62wuqFz6/g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
