apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VdVQQqEutivagqTHr4g18Dokcig19c4aNAXPWBaN1WY5iM7xs6P+Z+3hRMPpekybmkO+oaHlVBVk78Wy9wWcwbncCqGuWh5ixmghc8gCQ43UeqwVepBfxUDP4uy7pHppqoSi5MyuvUSNtSEeqqLWW8tEckBPsczvaeD8pFnKSvcJJd65R2ff6M29/UHIDafSv9rLfOrNbQO7ae4cKPatsr9rEDHanNFeG0v+Hvk+BYuMYPR5+Qr0XWlw6DgOh+6TD3dWpxb3VUGeMpO4AxsjdU/1ZOmh8p0IlHyrQdQEIDClipL0+BkQuloCR3Pkzi9GYZfVNh/NtCvrXvBH2HzwCkKZIG/rwA7la5V+poFu8YL3yCbYxv4FeX4Lrxu5CLQW,iv:2Iq/N9P6DfSP3HtyOy8u8P52jC7n7E7RcQg8SLiqqbA=,tag:bRAyTZ6+7eatYFAkOGxa6Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:6mKJedBlBznacjrGC3KBaDDU67KTcped7tbutx/lGrY5U8EAEcFgciGbD3TQNb4ThNR0dmWTxLzQEA6kndPwpwBLkkxu+MjO3a2JRIAw9vZqiEv1NrNCrcwDCA2VZFh6E6FhjtYBMG0QAihjxXUvt7TL8rNxUo/aYtOQGq9QZf4TrGMpV1Hvq2exWGM2/veeRW2/WCQNe5UllQHGFL2EyTY6jy2vOKE12iqjwNMGs5s6x4Ico67WjvOhfD0xumfew+/iVUzRrcha0GKcYg==,iv:8o1XoAryclzLsxS7e8sNPf3OOpBHAspkL17yh8ixgn8=,tag:XcaKynZpPoVVcCCPMwaAMw==,type:str]
    known_hosts: ENC[AES256_GCM,data:/VURyG9y7G9uXz/sKo9x3Wp/zaj4V83lrf/u4I1/yOl0NcE/Be7BgyaGvfoJzar8UO1dGWV50KJyMq2hxTaywr5tSPxM1vRx0650yY1UdLE3sTmcSvaefFxJvcAFy+n4QTYF4K4Wb90DWjGGBxFlRS9Oip9KxwOhiaugrachW1o9rIdog/Itn9suuFbBXIfzV+VH79hRKStdWSxM6qliqJE7RmXvuHgDvX5S,iv:hXMhhsVRnreOFWoLiHGyJ8Mh5ZXPI0ohYzPawp8xQmY=,tag:M1kHu5iGIcdSXwWmmzJ9Cg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeTVydk9rMlA3RENnR2la
            UVlpVW8xaXhaaVZBSUdLV0orVjdONHdwUGw4CjZkSG1SQmQ3cWI2ZDZ5aURqeUlP
            SzlSV2U2TlhyV2VhNWRsRXZPUVdUdkkKLS0tIDhJSjluaS9sZnlYSHlTSnM4NWsy
            WVp5QS8xSGliSEpzNkRiVzFIRTh4Z2cK5YxE+lhuiz/tummj9Bh+Dg2RnftsNzz/
            iOvHm2e9upkY18jlJ7dwt9DK+X+C3OHA8u9oIZGy0pol1vrNWKWo/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T19:35:01Z"
    mac: ENC[AES256_GCM,data:cV7gOmOS9WVxYGTH4n3A2nH2CHup23nux+UpSIiP3mTTuLSPMLlhz5FbjpqtTj8+LGI2kbXZ7RcyYxoTgCTNsPW4s4xheauZEKfUJtMR+fOwHd7wMKcll5/SJ2k/2xSrqx3wGy3kqJ+qfsZIYUZ42lh6n67rgQlSDrbGvJqwMCU=,iv:c9o9Qm3rGwOD58mAgOpNwtNhj5ne3iXWh080Rg8ADIc=,tag:/4kV5zbXfTpZYsY32/nYMQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
