apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ttupSgmebtToyYDy3Gb7f6X83WvkFmNlkuBYRReoP58dkmStyP5m0OtB4sJSMI0gDXaNdoclxla9wy8PNi4F+R2q09wpbKDZy/y9LuqzeUrkqj23+QHkxBWon3kXEPXYVzW5wHZjT/23QnvzVwWCvK3Clw5RKZXfagv9z1F02FMr9YlT4eR9VlaQISm1kGmhhG6TeodIQZKsHBuv+96s/NFgSTS7N+nJjm4RaJj+16Ee3ue/gNE3FdOkJ2m+bpytYRhYYgfMLe4qgELsSj3/yFPLRHm6H3gx8JVFeTK1nEDAaRai3N6cVL+rDQ5MIm2phjZJEIX46j+OTVaPDp6bxh4S4WCUFK3xAO38b4Kw9nccgj0upQyVhkU2P727EowT,iv:67eZAQGW9qnRrC+PkzsSi2eJYGdUxGpfERitKP51Ra0=,tag:R1PJg6tqR//vzUF0NM700g==,type:str]
    identity.pub: ENC[AES256_GCM,data:0svzm1uvGnL37uoGjaCD18GNAFgxmSow2/YUrDMqcqrP3pImMsEtueoIsMs088LGOLL/SBj05Uw3Eq4r69WeQMpLhWP9hpa4CjKjIHtD6pKop85zmGXKerb+yIqnkl74GdJNhqZmaLjVPZup5R+RQPL04iHGEuGw23zIOvLKzDfpoeTiTsws6SQ2mdQQyiraHjjUfKaP0+9A8DydDMP0jPjKnr91MlWOfDjF68w2Aeawd2z+dxqR1BM3q/ff0zfe2OsBaXrx+sa34PWhOg==,iv:2P7usl/YpxdJ1HmwfobBEIEThYzMDi7fGP389XIZgPU=,tag:thxJdgN+JH485x0ViqHDUw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZeMGRnAr2FPPRSceE+YL5+T3F1PSWOpt4C8dqetTNr9MzfxRPpYZr7yfxswXvYZxSOkSKDtYcNxsI9VZyjdTAXW4udBsf+seStKhSqxSmckS/Hoop57xl3gPWwvI4oXCtybv/ewexc3uHU7LhyMh76ziSz3oIXe+hA2noeCtDjqJpaXQ/stX/qlDNehFQN6bAwdn64O8HwOVaGkJrqN/bMlB7er3JKL3G3TU,iv:DNqvD6ZRUeJIaFFo9gIs2K4WL3QPHancxijrdL0j/60=,tag:KI4e/CYrleoGlniXyvW90w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWK3RObDMrQ0dCK2ZFMFRD
            UXpsQzBNK0hUc0hMSFd0TWpHWTVhNzh4QWlRCjVwYkF3ejdXUVA4bTNwaUhoS0V3
            MHJIVFBxMXRpSVJyVEpHbEo1WDVxeDQKLS0tIFRLMjk3eXZPM1h3L2U3SnJGczJq
            UjVHNGZXU01NQm5FbGtCVVpmbmsybDAKtI/9KVfCxYgazFE7OPzWm9Vksh11Jfee
            Fg+FN8ZEpkOO3B6jY0AzG8m3AdVbClW1QdcfVCqyzXZKFBWaoKOURw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T08:49:53Z"
    mac: ENC[AES256_GCM,data:RJ4NynfmgbRhpwA7cWE6V2IQvD41wpymCP4wLmRxoZQvXRjFHQzHWY4ygLJEAaL0nIqQnvooxZtoVLWVISmuSaC9cTKNxCmnwc7zAzn2hamUdcPluHzBE8kc5Il95mav95T8sbIImdmHWprL1XhCx06DPLyNqsRlb2u+2bldohM=,iv:DVakMScsBVlNNYZpklDCaS+2Mbt3JjcbX29bBg7PBS4=,tag:3zsXDCn27/L42o8jeAiZgA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
