apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:o/qFIlcbKSUlC65m+8kNiHNQkxU+vvMBUFeROz2gDAf1B4i7JFZOrJud/RwAuNq6Akr8tDW6LVU1ifJlyysrBfhmtmm7qJPt6TTD1+PPgcBNYrshjM2tpALpESSqYanqEpcf+2JHdVZc98ns+ySOBU9Np6Fj2i9tbq0L2wXNSt1hfgleGA8BEKegDSv91n+zv0tRxQU0A4vMvRtcumUto/vrnZyYTE8BItKK6T1KXj6QYso8KjXru+nDkeNLv4JeVeexcG9ih+GSvKLq4gg3w7jY8HlzaMf7XXY6ZqK0MeFBLbZXWGeHTaTTWt2wuGDlxJJFx5clOvQ4SbJ92aYPFeESVIiDXH++8Cx6RQVFHhCCLJ0J453YEzxKRlSfeeva,iv:OlafbV50aFnGDeJhpAbW0PaVipSSfNXPAuqQrHlhS/w=,tag:ba7QCexsmfMkq4x0bIogdA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Yem4Aco4bsOe54c/dvw+T6Xv01IgJf1E0c0g0eoRXitIEbqg2fwJkmh58jqS2MPy6n58FU+nJ6YxAj+Pt28k/mjl0F/nx4mz9sthePKVfw8PbB5hVIciKihwKBF3Qg08IrU09tK+CsKEFi1XL0eS4E6oHQTWx70X93AG450zxlHkhDY82qyjWaAe0d5lmR2Ga1JTsMi+vjcCX6AWsvKppGw6m3AD23s9wkd/3rNGXGI+ypQ+iQTfBXELZdUCkuPSyzcKbdSpZQH71Z+d9Q==,iv:psVSUfq03UaxQw+O25y0nOgXz+jnLDEc+nxG5l2DzXA=,tag:dBg8ju3vrM8Z8LmfxcE2gw==,type:str]
    known_hosts: ENC[AES256_GCM,data:v4zB6NR4bvHcPm7km1WIA7wu9MrbKfHjkBKTpXh8ZfBNtF5bEbHFHUGo4COlMKg7xfZScT2SNzT5ieCPyl8ABCMJTqctMbJ+AH/SbJ3bYlD2LqGZMtRFJsARYIZrBtts5HpixPTZlZqj1sJM0Wd+x+210RxZkcFhB7OXi2NIXZ9rNPlqKUiHjcP3dvzN7eEPO8mXZwZplJ9Tsj8hLlkE8vbAUevj4TNwsBOx,iv:yUBnYz69OvQENQurL8ao8ZF7wNJRUSMfYtas7fDvGsY=,tag:Lnn8cqTxnlE3oHoCEX/rnQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTEVIbDgrajQvNTFPWkNM
            blpENGVMazJJYTZrRi84bGllSVN2OG9KT0ZNCjcvZHdhM01XUlkzTmVGRjIzcEJa
            YmFYbGZHTVNlVVh0bEQwU1p1QXVzZzAKLS0tIDBscmJwdkh3bjlZWHBOcms5Nnlq
            Nk5MbVZFajlucHRORmxiY2VwemZkOWsKemeBcgG8RoWwLSDoHlxm3r8TXFQgAjQA
            kQUtU4Wo2q4z+uTR9yn5qSa3tWa+Q/TcQIV8jQMkvsDGZNH/62UwUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T08:43:09Z"
    mac: ENC[AES256_GCM,data:VTkw2dzTutlKtujBBKsATAjx+DTfin8LNdcmrael4BcQSg8zLpBYIiibSBDELtX85zFze5lKIKv06iNk0fXlLbBUDDjTFYaXwxXxoqZLFQ4QsEKpwQo+c7S/ys56qeS1om9q7Bd5j0fCCoZFo0BqDXSlUhrH4Ql4q1xB8y5FIjo=,iv:Adk5j5nKtnVSIl2qCKReXKtcgfVN3POnnuEF00qJqbU=,tag:NquESde35VkcA3kxPlaOyg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
