apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NvU/NuQgVJoEmnaLAHFTYkxEbv0nNlfJ1unuAoAwv1OiHozpAuQB9twp+BLF1G8yOi54E+cIIFSiYmQEKQ+Wl53n7IlJD6IUs2mAC03QI+L9snW05aLlG+iFetWRUPul1fcD+cqbLnxZBRWr7w/0W6wXL1OHtqjmU+syr6WEzv0kxU3yLIMc6oakWhEJNutjzaFZN5PaLDDzRLY0Sa2Lwmk2FBAg6sDaz1EReSpTSJ/YUBbpqwLr15DWbPyAiZVFU8X/HV3lGGTIpSzza51MpxzDtsjqgqEicfh3XLYT0LMPErvL7i20ZsWOIhKzMFI+oMyZclkohv0oCJn0iGwNUTLdLUID2JR9d99TurkS5JFhm2u2IVXkZsuR3arxKIBR,iv:dXq8IiT7EstObOX+vdTtsOgaa7lIGDh/o9eQUdCVrKQ=,tag:jSzr8N/e/JmQVcqYD3s24g==,type:str]
    identity.pub: ENC[AES256_GCM,data:4hOH0XD1hOh1KvSaORQo3Xlv+fGECgLLuPb6m7/7Zhs4Pgx7c+6oegRFgVYrzx00Iza2m34CKTas7RkUbJNXRv3THGhw+3nh5S2LRXOlszonoFa/964CV1n4v7Jei0JH/N8ooE78ypN3VqT2fitrwPeCmkdoDaCPY2xn/qxDljFXP74ouCgoKbE6t9+WUQusvYnJXk+D2UKEKJk7HQgdUZ6MDUVy78n9ZiIzbMP2YpfKQ4oUqVfxMUpnb9Cko0veVp3UTDMnDre4VYEaAw==,iv:GK6l7IrRyHdhem4gBjHQ5Ql67I0Ydk80a9Ky4/bCf8c=,tag:R/829c0iAfx8Po+syszYuA==,type:str]
    known_hosts: ENC[AES256_GCM,data:+eNUvKnP2LhZ0zR8xQ8aoRutrjKqWn6KHgknGYfawdhJgUfbSr2gHEvbMRfdWRK60K+ksHy/7hezPjqgdkEug8cmETSKzyywyg3TrnTRhPblUfeL4+Nv3yjlHwVIonuNHfdp+F4eFASBqueEhnkPnZgmCnNRXdlyvux0m0v4/cLfbGqhrpU/KFGdQJHm8wpVOtYpsK5YWEarK1+UXuHiyo0xKW6YCARs2x4F,iv:lzJAAbmkYn9nn82qIzlvh6VuIBVcGS/ZUg+j9pwKQ98=,tag:dSl2SaZur09kP4ez31CFBw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZzkrNGpzMmt6bXYzTWxF
            dGQvc1VLQ3ZvRlJ4eGIrR2JmT2tyZUx4VHh3Cnd4QWpjdmZZS28zMlM2QnprNzJU
            V3pncy85S1Z2dUROK2dqUGdTcVJpdTAKLS0tIDBrQ3FPcVZQeTgvVzh3dDFzZzRR
            NjM0a0xHM1QyNUJZMXlENjR2N2tITkkK20ArAbLMuJuGXCO5cTHQuvSdR8y8rS2k
            w9ljdP+zn9podRpNBDD7dLst/2iie/js40QwKozIqN3F1cxFpMjIJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T11:27:11Z"
    mac: ENC[AES256_GCM,data:vGiZXfDV3NvoZF6kdvx9ZT3lcPqW5WRzbef93uLmTVcAwd59BLr2usN9F6FfdJrASo0efI1tWZbXd87+Auen8BZQIgYdou8CbN6EfEpmOpRnznCIEPf5cXjjG8yK22Ppe6XfbZppCMbv+8E+3XhJbr5te24QZ+Fu7lL+ppygNzw=,iv:Js7Is1Z/IWUMzXxAa5BUd5xJdVMcULDxC3UWscfCqJQ=,tag:v4iamVwu4zYpYRO9KGi9+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
