apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iAG4Pyt4y/wYGiXfMKC4pqJZW7q6jFgDzGx1mbFxu1dGxFu/cxDWisnT5qaZNu5ZHZZ6Z+XNqTzR251sf8YQGY5cPglj/EKr+4WJtfhkDThAO6i0oMmKtCBZlwRJMmJR9tLNJk07bvadUf/tV/X3fSmJNyH+owcLhgNUPfjZAjLDTa8GxQEvYLYfpW4LVJaRh0VVpDg/zbi0a0qHgZaZ7onlBaOOkCaaFXdzxQbCW4sAX3S23S022B63eOqNZBFPkQrOJyEaXbnMHqVBeuf6S59qmVs2R1tZhnFikDMV7U79ysYuMLD0W7joEiEWZcYFwXRh2gsmD6Xib5DyPmOn3ZjSBf3hpr1i62Cf2h8rGv5Tn6pYotTNgYGFKpAWBbpC,iv:zOjTO4poqnIZwbdvBgh/GthkEwoOq2KmRtoo19BU5IY=,tag:Lp971xWM0ERF6m1NetbKjg==,type:str]
    identity.pub: ENC[AES256_GCM,data:yosVqPRca3AB8dXktGMK2DqKMLQoFzxMAauRq1bw7b0qgNzFWQv9qfiRUimZwVJYJd9oXKE+7bojQmczDpLx6xo5eY7k/4TFEd4b8n/iYxFHWgOKyUUB/tApa7qLZ/ODRjT0SzAAWyQavobiwlWO5xZlIRuJzjBu3vlz4mG/stJqjFk47iYowDnVHe3eBsO1E9HWepbPbvV9okKBA0nl8IlrNrs/2//K/ElUQWvSsvytN2sg/tLSejm1yf2530gJH8A7cNXtOIqPRoPW8w==,iv:s+6NPpgQHGp+2K9fs7j96mIcqMv2mwSX5QJ0JpSL6d8=,tag:V+wznAhbiOmAgsZy5A98kg==,type:str]
    known_hosts: ENC[AES256_GCM,data:xWisruc726cBtgHEvSLmKEFZcnkUiAoJVZDvi0O5jvKQZt81E2X/ek/8RiHBBbXC+D/3qaFjs4QIBvtwWYRjaWF9PPL+Y+f4W75y+ckLAqkIUszeZRihytIPkOOPj9vEyfXQqusdayXSo31JJlGHswx9ZTcDOIkgLGOhZjPj494YfNKRRvc9pllpeC9Yy8Y6iH7a3z2uD8WoMtuGw/SGSXZHE36/DR63Z/dZ,iv:H33irdagooIlFSJiuAXMFBHnFxbrEV8QnD2CPwxkBnw=,tag:NGzeFaiWAC6DsYeCypmJug==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS2hPenE2ajJRZ0VLUEYr
            M1F6MFY3RkRGV0FQckI0N0haTExTeVhXOWdnCjdXRFlESGg4YnN3YnlBQVlVQU4v
            TS9aRzFLZ01vTkU3RkVrSys3MEJMeDQKLS0tIGRvc2tzeEw1cytaTkJKQVU1WnFt
            d3V4STN6Q1czMUdFdkxtZE4vS3NHM1UKtJdQzk5Ul4h+eg1C5GNeFQ79bIp3nRdJ
            8TUrF5qojBcBo11h88uJutYEpQ0zU8v78UgPXNRoAp0zK/X5MqKhOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T09:30:23Z"
    mac: ENC[AES256_GCM,data:i6l3aOJjwdr3H2OnAOZouXiynx5RM3eC7hGopxk84Vd7DK0Dn6N68treghdAiOr9AzFZMT4oAjKj3nyLfL1mrNd9ulABFLf3niNQUmUYmxQp5CdJxDYMxikBK7kUU7o71Nu+ok533n2bIJS6iVcIewp56teGYT7kTcETg1yiWQU=,iv:BE8ZetZnN0UopDNTgGq/CNHnrUpC/U3gXgxvnlTNCmQ=,tag:bbYHpZMrs1ZMh8ytzrERYw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
