apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JRqwZn6mP/Ex4Z6nG9HiZgoBU12TQzqWxMV3N86VnQxDuDoz6dY2dwbA31zCkg+OThH6jUD/ycr6lOY8+Xny3J15sNz1+1GWkpcO5wbMsVLiB+soZhYSNbHjk5jlvtVzBKXevJXig9BA0J2qISKv0xWZqgsGwxz/30DPKrgM0g2qdHL7GfoxyOLkyXWbVMgURIRQsKBrMxKL4L5XKo5jADbzvG3bDHddRmSN9rn9pLtmKmhHTePWmtW/fhVkNaItW1cQrnfmAlTm8RKVanljdxqkE5kNzPIno8YEZlAJm7ltmB0j2FzFofrkbdE/MAWD7E1admv+v7fAPlZM9JKbnBKkjiR7V8VybWPP/IEOKiCwCGj83rbdaHQt19/07EM0,iv:ZaIK1Qe9T9KpATZAMomSCgjPBxMkHl8FoNEbx47p1oY=,tag:ZWRcJ8R+6gyMs5f2ru5KEw==,type:str]
    identity.pub: ENC[AES256_GCM,data:m/23LWtdNE0NqQAtxNKhTP5L8qDzLuWBvZGwYr6XPq4HLtM5YzLOTfyUUkHLbW7LwlA205/v+HlC2UioTIobvv9cCOJx3NVIOj+g53apSLqevlaNIMOFz0D8sRhKIUDgPX6Etk/Xt7bihCKySkvPco2AgUzXj3n36wE2DteUVQgKC3vGwdwp8wuFxvOwIXca4xH8k30nkNSRkDR7+LAJygn4tgF/Gcoiq7XNO/cQ16ORksrE4GwoES5aNnKg/8KCzGTyI6hO3JcGtT79Dw==,iv:D16fvDn0oQTvFOVqHgpicJfpqvznh2RVplQ4UStXnds=,tag:Y4VjM/U1qOY65h4yhji/+g==,type:str]
    known_hosts: ENC[AES256_GCM,data:4hoFH0zlbVtL/zb2UJIO4HCUtioGcVUYlOVkqgjPxhu+WGu8HRgI+reFW7Ya4clPZUkN0+MGk9E/oC27S5FhabUmPV/NvnlBR2RZEnttMeMB01Nu9+QqeGMwr0sUlaEFXKAnxLViC4hsS36zq1C17pb+5g+5V1ncjiRNcymTBqT3G7taJBbTCh93CrZy4Ho2Z4Phh2jawSgexXuXkzBOcHUeRuRcMxeuce6l,iv:6NbiXlSn1tHiIZEdZ4b9/n0I8ytsm3L1hOaPZE1le6k=,tag:GrWVUBsIuntIaDJiV6jvIw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR2h6V21jWGJ4ekpIT2ox
            cUFSU0NKV2ZUcUI0WXFSUkcxU2xDbUdUbFVvCnR4a09jWGhjNE9MUkl6R25UTmZZ
            SGpxQ0dSNm5aVjlVcUwvdkhvVXhZWmsKLS0tIEFsaHNrQ3B4dTczd3NYVEhDRk1T
            cVgxWjVYdkFydXFNdGtZdlZqZzFhMlEKEfV/HRuPgUEIJ5QoK0kOp1rVw6eXLeQG
            dzlELOD4/FpoTPF6cuXg8D1VpFFb3ZQuL6+Dy3sp4C5M8gszG1gaQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T11:07:34Z"
    mac: ENC[AES256_GCM,data:lwiv62dIowq6nanVtu8sjsIG9J+ELHtv5Jzfx8K7u/q3s2uKEBaxL3wXjvZlo9bcNNPrjA5DxjNgoDcKQOFZcqXOyweO2ZBbUb07mrVMSvfZMvtX6or6NjxiCtb6JlLjQOOK8crmZquXhk30cbBwSz8HCnAFNYBG44l5Z6PntJk=,iv:A6P0hFHdWxrib8y0E1Ige16oUqJ6RR5gOQYXm8LFaWU=,tag:2u2QaAJ5p5pv4bJJohCBtQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
