apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LRJn27qybdAuVUNFKJBu8I13gUeyp/dQZhXYuaNKLFhvvkrva5WdDkez99PydoILZ4Z/rJZi4f+cySB/BmUY6Cbu5fGx+Tse5QXCBjNYqgSkZM+R7Ve6+6cMU9sNUq5TNTGx7YLlikXn+9WJjsEUimT+I0DSWcneu67EYsVh/yQsMH6SiQ5fRbMltLM6eT52A2c7KUL4OqPjKBA6JijUOIjbfdeznkfkXNg4lZcmPIBcP/LCY06QAZyweu3kIH3yzKYbGLn9GLWbbL59iq8nGeTje4mKCxhw+MPVh0Et0J43aXqtKpY8RTiRdUyrZTOXxA569xPTQNjp6kq8k++PPUxO5HT6rp2bcBhcFCLgJJM5HPYAC+uGNUcFmCcs53DD,iv:l66SrA0FL7IbdSRkNdjW8wGJH+9bOWg9rDkg5VelObI=,tag:f3aM8OWaXbww/2ioUWRnkA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Tu3whTgivhja57c9hVPzAcEzcEohwjuFg3aTDRj+e50ewgJbEdKWFUlPA1VHGXuRrHgambbVDGFCBz/Yc8AsaI6G6eoIAw/rtKgRcuSWwASicSXg7Z59ng79x0/0N/fW2RBQxkpHupNmZaTx87ZWulZ/OMnMlmWQYd/Gc+pyQPy+Epv2d7VkbZYJsOf37E4tzYjplFLeJ3B75V75LGsrNUH6Tp6PJW2EMIZgpUS5wNFrggKm6NT4gqoJ+F9jgJPPCmdmAaTj/2oEJtJBiQ==,iv:qrOBJjXzNTFdCH8WD8QwKJEE3MDSEDVvjHtO/Si5rw0=,tag:bFUfpbl2z1ISX5eS1IKNiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZYsxmY77qURIJQaT6/lzmbK2vnU6Iq0qoGxjcmSptaaAYh6x0jSI9DudI9vqqhbSlbag7/ru0kg+Jin4IP6cleO/fP715C3bKUbJnI8xIi0F75FEjwuckm7KHpPCpqx7Yg4WT7anYny6qZJIqYI7/8ydWPTrlpAkMbeRiVw9ygp2RkCHvfkuID6aR3uA17GqsVL/ndJ5SSW9U6hJkjY9QVQDwryf3kAMXdQP,iv:yrW5NPZ3qvTChXwVJcbm/QcIjn2dsBSZ8xY3aMNPBws=,tag:0RBPe4YebFbcrrhxhbT+eA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2L3c0OGhBM0l5SDVuUXRz
            aHFUTUVNVDI2THZpMTZJc2NnaklUbVoxazJZCk1BMnl2bC82Y1RMamdTQXRkUVds
            RTUyRU93WENQNTdaNFRNaVM4SHlmSWcKLS0tIDE1YXBmdGJ2NlBmelpCZjcxaXpa
            MXZNSVUvdzdoZXFESEwyMGRnSUZnSDAKGGaKV+0CPI5kG/5nvuVlDGbUjgEGrcP6
            8Ufy48eAq//SfFW8CIOk6VG4h0qiAhryt1f2wcdUSwHT5xT9EUYfAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T21:23:36Z"
    mac: ENC[AES256_GCM,data:9uPx2ATdIYyvfRzAS3nFauS/0B2ptWIllQ3n5KXQX+NNXLsxBqV8Wk1/3CG1HoCUKS5tHFMX9KT1Yp+lxx/KeashBA1wVb6S9WV3RRBP47IpGWIHUBQV2KhEf2cpyiQ17SacZbTOMXjn5NgfyyVJ5dxlKJVOPAAzfM1YIlcFcw4=,iv:i1DkBQShPvhXWqYi+av6wZhwTVilKa76Fk2n7yT0Sww=,tag:4h8I9RNIpFQ6XQ5x0VaPYw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
