apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:c3/v4jFguTyn2h0WTFKnN59GMyILWF3MDH9uQrZ/k6ZNDA2tYtzyr/UrGTv3Sqm/WJPdMI/P4/6QPgUDc0OzGtk7Je6KjxVa6ZDx2S/c2ECqnrDLOVOLjZSfGx1YLi7koPLeEcoqY/ZiD+dxhPNw/xPUVFRQ3kA6ATEQkhhbxZiPmi+L1HX2YJXzDbJP8E2YayeQuaA2Z5dI4wvI7eMSb4pb4yFnvLD5i8mC43Z/CUfNesRTFEax/dnTYah6ehF78DcK4YbYlWkc03+Ekmp7uRZTJWc9GdA4Dmcj+E7IXn4yZJq3LjHU5WDhpr/+/ZB3bdcE4ZzFOSpJS43wIGdI1HpeRkTBT5oqJ6n+l/ds0/0suQBxokk3TGegdFDNkQC1,iv:l27knK/OhH1sgPlpSgfaKEFFzL7hRCZrelWklclm4g0=,tag:WleISgw/xbxgp+NiIdvUGw==,type:str]
    identity.pub: ENC[AES256_GCM,data:VHRA7DQ+j8FW41+iW8B/o/a2E3z8OJzCz3PMJdwTiEPNOHJ6iVdlCLfag5RLYPgIujY0PG39MSpUxavHwZecfcNfWMr5iNBhi1XIGL2FoxeZsGhBQflxSMyPAhXnyWk8s/WFpLfiQDSBgTWa29a7zxQ1ypMppA3rJVR2heqCnmiqfd9f5Ckqeij80gbbQmFcA1+uij/MoOL0hIFpIrwEGrRrLZV+0kcS37qhpbT8M/rsbGZE3zLoUyt3zIm95Odd5nwhxuCq6k+6JB/X6A==,iv:6zSipKFl+71rI+urnShsqrA+6vEjiXUg9Nbwj/vI0KM=,tag:ziPpk2JXnf+ed9aMS6CMeQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:4lRnV2eY8hd9bKNfQ84jrzOAiSpQnIoSibj6uJ2VruGm5QcgKFmMpC/QLpnU4vAovR+KWLFbWjZBGGP1BKGF+dqJfHrOvt96BH41WV6vmE8uRddByhOElVLI/juIcQq+6iDTkHu/PIEOokMC/FRUoIRinLOIADiNB1cpihV48iMQt6JzlxUEMdZmUSPDpxv+rghMBtsy4HnC5GyX/tV02ib7OAkXDZAeyCbc,iv:ioQ6Y5nHlB5oshqnxTmeuMg3cjpA3TKUaYHNPLcRZJk=,tag:LwjN+ssO1n5gdeHA4hs9NQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRkx3dW0wTVBiblJ0LzJt
            Y1ZXU2E5VldFSE0raDROMHpmMHJ0RzBUaUc0CklubkJtOHAzcHFMU1MwK1lnS2E0
            WXNVcHV1TDRNd0c5OVZleFYwQzRlczgKLS0tIGYzYVBjeUd1RENSd0txMGJoNWJk
            Q0EzUHpMb3dhWmlGZThIMGtXMjM4KzQKyt+JEgw1dAhEcSRH8KItkz6/fzPG5HFs
            SNoVlENsSMK9d8oDBJVYChV6KOnmPM2QccsT8uPB27hWwDL6SoHPQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T19:40:40Z"
    mac: ENC[AES256_GCM,data:OhlrOP6nPJlmudQAKR8MdRbrfXCIdfoDhMV8Da2QmcQrl07JhrDt9yA7b8aO10tVXtlTmrr3uXZAYlbY3VuO8OYXAgHOa0tZntxCUOUrDvCgJHEbKy1nR1pip+r1LbHUCOAHn+Af4vLQZkTUaCJDoBQqawwXeOtO2XQHMUTd1X0=,iv:pvGuKGP17OAVmfYxMZ1v7hvTNArKaMo5GVQicClezl4=,tag:TXSCITuAmJfMrYtdC9qToA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
