apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Qn0RTYgItYl/POCfW/544affqrHNvbfYdbfab4qr4KVAHn0YQfWdJSBtewdj5aq/Z7zigetpL8krAu4MWjp9OOf1L2/gQ9vxJPphDRPZ1Cx6hHcN5HENPX5G1IxU7KICqxMCKm6rRwZJOH0gO0b+CIIA2sm8Q8pYdOkL+eZbyOeweGr9kiXnte/IcT19fu1lft6XK2f18NRxhu+bnqugPA/Gsjj0BA1c7DwuHKlUc3xD5IDXO9RSmce1y0iIVHn2JUHyOEonLOlL2mX7n523yfTW7+jbmN1IcEhdFY4yL4Yl77wAprXNUsBk/d+Gs63Ylwv/45vaU6D8jh0/BDU6dFs4VO5Qd2mRUOp3rG2GKYYYHwwum7k6Rn9bg9YhWpM9,iv:PcVZOhxzcrAbJUzJEI96p7noM9HOHhkbJluPDcTC/bk=,tag:6Sg2f++jOnJtCm1LuPoVHA==,type:str]
    identity.pub: ENC[AES256_GCM,data:efr1KkSbKC2eygtW/ni74S5u2LscaJ+CqpkfNG+fjek7voPV1mse9qf94fYnDkjSGdMkRC8upvJFPBNI4/sur4P+/TrDOz8ThOcNKJYWkjk9M1H17aDJ7bgh7azyu447jTWluO0aPml68JuioLJ6MgpxUIbsWW3S4UT1DkDx9SGBpc79C4sI32/2kjBsTTZhQMe2LUKiIsPS4CcTrVOtNs470z+Sr0ZzbgG8aBOR4b9ExQVJvgCYFVr6wWfdDSRYTzBVCSgOiXqR/H0O9g==,iv:CyR5AUdEKyOwjBwGZY4NqOt2sreh5fpLh+w97apc1Rk=,tag:HO+lU7pxZMZ0pbAMQFL0bQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:1Q1CY2qUfg1nER97BHGC4CWY3Eu485Uv+tPttV310tucm1B0Ux6IvjiQbYq8ylMoBKuptRHkNaomU/lCcoZ4NcKN35vtY6GgQ4TYwRmRfbWHqQ9E/Ghcw/hgDnz40tQ4XE6NjwO07mvaga03j2z+XBwww5ww5b19RFB0f82hp3zc3cBFrDosWIO4K4MybFulRuhhzOVN8i4bvlXqyGhwgvNtuUbchfWNystr,iv:cVd3hcW1pv5xs3yhQgdhqGz2gB5/ftjvzFEGJ91nJYM=,tag:ge61q1Dl/LtHj9VXjkS/cA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScWZ4dnFJaXZBVjlGbGxl
            c29vNkZ4OVY2Y0dGSHhyVmZNM2ZicEFuc1VZCndyU2paUkFUQ1VpN0JiQjNxdUI2
            d3NBRGNES1hPUjhURkgwZzBtUTYyWVEKLS0tIGpZaElNOUdrSk9SNFNEdTlrbnpw
            Q1plRU9rMUNwNU1GWmdBbjhnSTBSTVkKWqM59G6spkJpcQg88BPBFF5jonHTQexz
            cQj4uyDj/0yq0UlDec0C4Bx3mH4IaRO2c0Ipn8SbrpxTvcf4VeGEHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:25:19Z"
    mac: ENC[AES256_GCM,data:edmjztTUuJBvjwF3tzusRfV05fVi/AK8pZFk2eFQm4F+/ZpF2pmYR8Gg2xMv0QzJk98u6EI9p4R/Irdi6iPO8jtV1OOGi38vsMPOijlrs5ji8UV2+dSkGRTQBRW/xb00T7sdkjUzE6JgGF+0m7dfVXyWsLrZnKtDtZfbClV4DAs=,iv:+D91zuA4K2Gx3XgS98jwaNyZCqTPy+EMRL957Vne8wM=,tag:u2nUgSvGRH0tF9dfwOep3A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
