apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FxMfiYbpy9Wtt+H1ac+QJwVr8nCcAw2bmrTWpo2IrzZ1ZAUU5G9IKRY0Sz5NYZp3Cj9BEFJX8rEpLxxtcgRDC16Iv2E9V/CVU70eyZdEA5afHFfhUFfxH1ltgPKPHNGqM+Ttyu008S43ZXfrlfJmb8cPJZ3guOlAp5d3Ea1jmkb0o5AWGBc5Dabc5b9lzkca76hjoAno7HS6xSFtLT6SJnm6ExwDwqKnlzJrUMVdj+rAEJ/HXm7YJxCdX22lAVxzn2paFf9/GkU16s/wtb44s6eTVUBqZtOInczj7KHiwnz6/OSVONkRBmxHrf6XgjXd+2G5I0pgCngzI4yBO+UINx15YtM6QPsfjfVGZHFGMfQU6/wHLvJPz5Kuvs2j2bqZ,iv:/LILFEXtBEQsM/ReBQzDgaRafznFVNIAo9mRrQC8z/8=,tag:6xWp3itIwTBslD+hfnSH9A==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZmlXsOlJ8h1QiF7buwueK6uT7js49GeIoqoFquCzPqve9bbBrs1FwpuDB5Pc9KhdibfgDIIfq2HzXRCCLID1h+9Feq+QhlIkm+/Zg8s4KgJlFyWsxR1i77QiySIkAS4lpu2E8/4IAVxuq/UGeqf9qZRccWGaEmDK5Qtbj4JDWnD3U/U2V+3IqoFetQKl9T3FioFFmBpHu3CyCSPRAFMhkdlfEu9nI9fpNETvjLr1VUW10DvuAsM1mG7eRpBgau8LqiyE4s/87Tu6B3H0+Q==,iv:QnzZH5u9Yaj95bnxxN5CiSVBd9VtlyRCZmIQEnp70JE=,tag:5pqnbmg6dSw/MESuMIR6Nw==,type:str]
    known_hosts: ENC[AES256_GCM,data:NwIiyxfo3ygg7LhsbE2CjVpJd3iVGh20xIUuEp+Sav17gZa/+Y2Pf18XQB5C+Qb6RT0LjqISd6dw1eD6BdNqBVkfm7gDXVgc69nhwEA1nbHKQogqCbf1tKT4rfg1MOxMQmeUQl3Vf173TUgQukI2FhnEYSlc5lbr65gqYVDYXYsdL3phChhcTTggwSGLCCIqvoBoM3f6KKbnrACcAVAPqyofDZjB/RAZfpGH,iv:9vxzX8exC049sty4V/VObYU/BGIi9c4vbTmTH0K4YGs=,tag:7aCbozYuIZG/uTprklaX/Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOUZVRVc4UVVUSTVDN3lN
            RDFlSDFSL0tTUUFqVytPQXFuR3laOG5tUkJnCjRQL0hMejZCSklaSFl0Zm40alg0
            azZ1UE5NVkEzQjV0aHo2VHJWTnYvVlEKLS0tIEZyQndhUEwreUFpeUpMcWNBckJE
            cVhQbE9LSFR4bWVFQlpCY3c0T3dkQjQKUZzf9BJhI6xlQ+JT5vG1aNzTITUvn+wu
            DOUDQQdA51OKupOUK5/2LWub+Qzw2uqfhN6OAJL8ljMsC7TdvpWBtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T09:43:54Z"
    mac: ENC[AES256_GCM,data:duQ2bEn+E+apEM8qZtOGzlmu+rcVV8BlrKUcGLRj/m6ra16P1D0g4M4I6gWkbOODFtD6UJOe7ezlXBIItsmyXDd4kSmB5mrCWoerpD37LFvdrTMf4U82YrAf8MuB/pS3srrv+syQyp5j2+AQv8wtc/yojPJt6D+gGgtX0i7qiL4=,iv:z2w7OuaTHkOLLkS7+WxN2X3uBKh3YjfsdJ2n6+NgN0U=,tag:R7kbtabENelxKEsVWjaMhw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
