apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Nc2vfiQnuHfJEa+KBZq+ZuZgqXiakNrNVfvOkJ6UfVVNUHPvjt8bUm792+vkrQpnuTtSrClJlMi+n4Zx+Dlkh7z3SKKaApxRv2uKguHld6T3ZNTm82rVNHylAVEiRYqUgXcY3K4jFDXo8x0d0lVxwKSYUOQgHclVZ7L6Sx3KL0Cwv1dj8MMpNYaxB7J06Y0uXm4xGpjfFIJebufMO2kXDgfDQKCGOYK/2K7Owo3F1gDQOyOFsQpi4P38uXwDFBxIWXDeq0h3t9yMOxv1Q/BApPAdCKs+l3JO9hmDAJq9jrs39Ml2Vduq6954TY66+b9sHnz0I5F3sPl1j+MbXTsb4kzzDddT4rhyr/RF9iQDA/k2smV/VfFGyS5KdxfMmsoO,iv:Der/EDzuBrXWJhUzb/Y0e+TsNUhGjDKVrub8wsPXp2A=,tag:8nvD3ppnolEmZnAfMi1NQw==,type:str]
    identity.pub: ENC[AES256_GCM,data:cF1NM+r8GtDZ4sPE301AmevHGNgOCdlKQIReB+x5lGsRDhA9y430MRrs1GDtqS6KDNseWMETavCMfen7EQ3GjJ9KhN3MkbnwXrglAfXzej47clDzFGJD9k+FLGLmRHedAAhGYAQcI5xpcxlQ7OX8wkd0tZldYCkxsQVJuqNOuESZSmS8qgMFSEt7340xYkUcAynvxt3InB0ama63fc4CuCcloN5AL6KKULcLxykkjqR9r0VnALMn1O0c4hOl8SBCxZbq8G92+dUQ7niNKg==,iv:+HQEqfgKwkaXkld5tv9K72Kh1C+hOS1V9sWfhyHLy0c=,tag:KAgwPjmA8CUkWOxdYkmEqg==,type:str]
    known_hosts: ENC[AES256_GCM,data:tTqecd8BcULuwFvfjDxChLllCPmCV71HSGTtDWbNJ+nnCvEoPRjm2u/opX0G8czbqGF2A6zV2NHj0+LMIcMuHYLft92wX9AKaYVVcRICM3uZM3fpHHj1jM1R/e9G0zJUvBHhAhiLHc2kkkewql3NcAh7m7S9vEpQgx75GDsHue+TgXiPHwAJkoYYumblWXfND9VwgVnM5JpE+5t3PMYNTX4SLoboYeOSXRNa,iv:HfwQyCykIABRhryZNOtoa2fhyTvSOTWUQDGibYXrdYs=,tag:7eDD1CEAfLcrWP5ET9YeqA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsc1NmZEdiaitxb1RPRVFC
            MTNQeTZjZkRzRGgyQTBodUFiV2lEVGxTV1hRCmdUREM1WlM1Y2xlSnhzR1RoaUlN
            VVhWUGl1RkVCdjlxd3ZoTmJFYisyQ0UKLS0tIDA4am1jeGFoQVFhTmNyRzBxSFRI
            VzNGdzFMN3lpTWwxWHQ0d0xnYStGOVEK8b4mrTqypt89tIWVIXnJ5n2BtuFCzZtn
            uq8ireZSiN/dSE/XgYeUFpT+EyUova8q59JG2qGie0R6LBi0ipPbOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T10:07:11Z"
    mac: ENC[AES256_GCM,data:xYukUlvkJFQ2TAG56h6/jMvWxUhxyPogvoIAPYFgGBGM1pq1sm1VxuIMk4yVlgTEsTt1g4rnWH/CtDTqo+LUbs1S58a1gVKO86cyshbui1hyjFuBIYMk+zZawh/rvCfleqER3K+Dmblbx11Iz59311tjbrfSxeg4rYaKUT12HbM=,iv:zDUWFa8FWaG7YPkUOi202baDoujmTEIJP6QYIJx6ArA=,tag:XC+mwIDDwusleGHkD7hL7w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
