apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:M/F/M4ZojSgVxghjMO4KzTMcQpSemSIgV/Pip/2bPNW2/G7814ISwMG0UTutbXUM8/aydisETZyk+XKI9hw4WcdJxg0oFrGs2mbmiDSss7tZolGIRnWsLuUSLetp863FMk59vjpvRoWXM36qmuHueS3JEcC30AW6k39wROz9u8WxUBJvLF1V99cYxDqqKZ+uH3QUyp4vLYU7i3zX7VwcZcupprDLylD7rthUgjxfHwgQhuh8AB9jZFeVhgl6ppx+QIC1WJyY8ACrI/COSBJs7DSnnknSibt58YYcuT816GwFQ/r8Ux1OYED98dJKr9hNLgk3sGUtXgTfClvS1Vtlt8+CvpJLGi1EZTkU5IEKGNI8EWADvLBUD/EETMV+mc0n,iv:tYsKqPmha/GStWhruVlPDTfwAaqPGKzArzBtLIHZ43w=,tag:ZqsVrTgJbqadj78EHG6D6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:Bw33sHMAOW71Ib445d5a0r16X3c8e8Or/ztER9uq2j1Fg2/0D3xL3rlPc8enAD+Qep86l8Mm+hOBZv5OKZ4qDFk6kgius/ljqIH2bVrnh0ZiUlXbii8NM6ukFoHS7xyn97Q1mk8V74j8H/p+xVqSLLmIB8eXBh+XBFU6jFhvstkY7i6Tu/u1UJ8qCTSgTaqPcc+AC2EnFQC8sKjeltEzXdc4OSEK/hYW4fcBO4LLGmvOciBcxX/VUD3/UrlyFUAQ2su7csq/k3/P585O8A==,iv:DztFaS3K59r0puhVhYfA8frjwIDKLtL3vvIbbgDZ7fY=,tag:9+jrmVOV1gPBr0SZGeIOrg==,type:str]
    known_hosts: ENC[AES256_GCM,data:9czrr6pFufC/HilJQ6QvS7qobMdRzsqVsDPNAs6tYhmCSvagUSfM04au2ujeJU//D3rl7La9kWWOPNgsN73HFPUkoC9jykhNpo8bVlJ/5GfmRfN7UcuK26d3p+7zuiwwt48HviGzAWgt6RycHrfq40XqzElRyJswtbPrl8q2d2TGou93Idoe63Ys27nrJO/n7PaH7MUR7tuxncVdjMSjqIvRmqzt68OSNVq6,iv:jMlA7cmQ+mvWhFpHD7hhBshjBPah3wTJjdcYRTRlBvE=,tag:vfmRt3d0Kf8YuuW8ZZTlRw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjakdNbXFtQ3JHekxJTlQv
            OGg5TFlSRktvQ2tidlIwTDdUc3FvQjlHL0RvCm5nTmZKdmhQa290dWh3aUQ4SjB3
            V3I0WnBqN1BSVFIvR2tIZEg1Zlo1YVUKLS0tIEpLYXV2amdpeER3cmxhUHNUMzV1
            QVA1TnIvSXdnOUo4cVZPUXR3RnJHTm8KISTioczSv3pp/xP7PcO2+plCPVts0eFL
            iEweaPAtUgrPTsCG5R7Fv44Rvht/KyxuzzCO4BXAJt2lm9BSW2RPwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T09:36:58Z"
    mac: ENC[AES256_GCM,data:STH7uAYwJKMqk2ApvY7npRTqo3RVyg5pL7JE8zgWsQwLzD5qytx/ooSYXRiOXqKLy6SNQKro42RNB8D2HBAmL9rvhA3at4/Fw8fjECo9F3NN90/T38HKsn0LZf9bwqsI40DrVDJifvaY9UOvA7Aib3y2rxDEBE2E2MZCfWeGH6Y=,iv:M3Rnyaon4W/o+KLLM8SPz2j8OIWLirS9w5bnfWAyeJs=,tag:NheQqieYXfARiXMOxRiJSQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
