apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eC6tKmW92YuF8rUoraT1Rs7vXjeJQhPEDsOXBmrmUkiSNfao/3d8n8aDofbTXm6Aye9tNPpIpgi4owZJsWBdCMdyh7w2Iwa6MwmYMOLZJV+3X3Uzo/3rkfy/VZIRUZuhOxP1sWowyEoGNAtFNK66oLZVDsKodlhLUfI2b/hXti7K7T/LikEqo6ImOEojsiN5zqHVOZdB7G78nh7kx59INxtsZCKMNVBYhUZ1r52gCXBWQaXwPlyj1BV2C+QDTD4i5hin2axajf+dExCQMqDuzntPTUTSUvd/Jjkbr+6mo9PyNvPBHpcp4QpUsknmsdJeRUbFSuhl8NgDOBHXBgnexmUq4puZC6h5PcHLDveLzwphVel+zzHzNJj1yTIBBDHV,iv:mTrULlfQQ/GtW8bsWZv0STILuLU4iCKX1GsVcWsTDMA=,tag:UNufUOe56Ut/QlLufXETvQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:OF8DapbKMpms72H41SoqlaYMXIT1/H1W1ClkTbhl+rnHZCw5v9Dfc5qtLk5gmle+hgmJNf+zbFyQ1a7l+Gk87932lyczi48qCODeCTVTeQUqyXydlxQNxqJExEcTby5Ps1hYjVocBBi/kp+Z8/WuPQBMIQ2AFwcnqMk+purcX1TWtwsOCXluTiHdWcUWgTKOTFUxBivwIzvO5BKClCyJI8Z40C4o8waGtMT2cXPOv66/kAR/jMQhU2E4KcEP2XRCSBOEFKmjhA8xuBG1mg==,iv:5dk0y4Sr1t44YxdPnpVz9861z+ggS5Zuk9I0zDxv8MQ=,tag:8rfaw1efI681at1Ce5iGgg==,type:str]
    known_hosts: ENC[AES256_GCM,data:HVDbjLO+G0XwtjgNUu0j2Ub9ox/zBOlhN2Qx+N4GZpbVK7Jf6zT5+U30gKJyrkM8mfw1q7zpkiP1KotDDK1kicFm64q/2ERinwZglNY7xHjyx6qop7YKtT51N5umTE72240hGkPKmcSmWuHvYttJzXKVJKlvJtrk1tN5cBsqPlXtTDOYDcrI1k+JmKcY65g85r71TyZONV+KnZIcsFeJeYLKHXbf1h/UVHiE,iv:Y0aVvc0jyaoc9N6zlGCaVcB3yl9NpIyXKqreQOmMhE4=,tag:nY7VAbDI72bBFWD7D9XaXg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkT1B1K0J5dEU2OUJTSEN6
            OHJkbytWWHFqU0JzYzBPTFdhMFd4ZzhlZTBJCnRRZWovQ2pnTDJqZHFScHcwb1FB
            S3ZET3dWcTZ5a2x1c3E3NmZLYmRJODAKLS0tIGZUdXJiOFkwQ3lHMmpTWUxFTU9k
            VFhnck5nMWZleE82OGhaeUg5VTdTc2sK9TWCTRZj0zeGO3Zpj0XrMxUd4VH5cQT7
            RIRNU3TDZKYv6XBBKRaV00leN6tc4iwvWrHma5pKyW6dWHgJxbXHjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T07:41:40Z"
    mac: ENC[AES256_GCM,data:bFGylG+T6gBSccoB4yosp7pioUB10wufKUg35eCYNaPDIOAza/JCAt2SO33QxFoDYf2grzjAW3dm8bH48DwC13Ya82zdrNejiuXz72h9gjVLUV9Co+TyG6YPESR7uUuwjKkRxrYMcnq5XDKvvTGs07tZDHIyZPximkmW3pLj7mk=,iv:7P/6X/IUzDDTfSD2AEXqcxr3HHNRj7MDYVmEgFCWyzQ=,tag:ejIq4ATGW4brfQc3Yz05mA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
