apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2ZB7Vb3GnY94tPTATE1BimS+z9nCL/J01HzMvOu7NcvX+CfTj3+tq2awPLRAqKKdQ3BDcNMUyL43PjRBAhqUJYLxnO6g30giL2ls8rVJooZKcERVE+mY6iOSpskIMcjDSGw7h+dvRMzOgtIhSNNrzL7mKlfY9aqCNLCh789dHaAg8BS8za0l+VEdf3F6lShqrAOheGbkl7FqlnWy7yNWQwPDOcZEYUvUhD/OeEPzLSX/6odltngNGMpZOyYZBgmTlvV0RSE/LUyI4RLgDI0+ZvBhA22hrIQDX//KkOlCdibPoLqvtAE2ipl8wfTzBRFfzu8OBOxWX8w5kJZEtpj5V+yCpigitkkazXyunu8rfzcaGFKiE0E4qjgnR2I6yyjO,iv:4jg9NYrKYvl2l1i++ij2AnM5bHvwqFDHSQ9f3guPKN4=,tag:Dv4CbWppavjHxb5s6JzmHA==,type:str]
    identity.pub: ENC[AES256_GCM,data:CIcvOgDnEFIkOztEIxD+jkJ6jjMOBKHjjOm217m9o/dQHWpTU74MNpHXJfhoRZEPiwbWEr874g1IbC3wOw7H/bVu3zoI3FxHJa6snErLHO6cgSnytWzKtoS/o6oAqL6t4ZHUAUMYUnj5SZgvNMRzvYZ5i6dInJo92l3COTiJIR7pMMYOsF68o13FsZqyqZwMM/J0NZjZTJT6ZNfh86WkZbu3ut6LsZdvOcNjH5fujA5YDE9Kk1lD1YOMdzQRXFVQS0wuha9DdxOuCIAMdw==,iv:zAfWyvOkqzv6twPuXuTwsBjCchKHQ/zlMUWChYGcu3U=,tag:t/bSmAF06FY2XHvoWyueBg==,type:str]
    known_hosts: ENC[AES256_GCM,data:twdv9B6CmdYbVeOeX3dvnQOSKgqu7qdTshwCoE3r95IRHPi6aIJbU53MlvyoXQoFeDVfgANUkk7qi8SbqzXFxZ22robFq8uwJh7nQHdYUtCFIbSWySJJJR6NN26fwXz250bWrhZ+DtScgc4eBysdX7CMgvng6tpXpyqFE/WWjPbuHRgKZlYCyGGmGHda3TVQGEVM06Mk1MdeZzkRYrLxt0saTXMtYjJFrXSS,iv:TkDk79gofumK31V8fe+h/GX8lAAv0wSQKKVKGcx4o50=,tag:UxL2HT2k/r1naKMvVwrtmg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ajRTMXE2am5yTkxPSVA5
            MXZxV0xhZU42N0VrNE9qUFhkVFVXbG1tdVVFCmxteThWaUcyaHcyeGlkRklUZTU3
            WU9hQ3lOZkpqeHR3eHZCMjl2SHlkRVkKLS0tIEEvOW9veXNVWXdCanM5UVd5K2dw
            aGVqUU11WlJ2MmtPeCtpdmxEUS8wTE0KI+JV5UTwEhszp86HzplQz1y5yoz5xPSF
            lFVH2dM+5SZDdhFniUpI6B/cPNCXVqm0uSs2XtlLICeqpyD2zlGQNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T09:55:32Z"
    mac: ENC[AES256_GCM,data:MNB42P17f0YY52qfckyldvb+F3UFtuvmkc8DaizJzmVFXvXfz4ZlEmm4K4FyDB4jA2lnm2F/V3B/MMPuG4/BnvhP+t7WBw1OeUIpkKrvTMjLVEYjBYjArdgnttvbaqGjYeWIyJcH4xdTGu/egXlUIv0FnOy7J+XzX3F+OQMVdXI=,iv:EkN0b3YPsqFTZ/GED97APW/7RUvJah+gp7Ubu8/aGHQ=,tag:3AripzHAY6sQbaaujFQZEg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
