apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JcG9mH1yedC7XlaO2I+UOO8/UJIKOcMyjgjKsqR0j75qID2KjH1s8xsfkK7VsWf3kaoaBNDmzF1YXrfDmCEzL4QreKVcoobFFZp3lkrTgynHSSPS7wsvF07ZCmOtkUlMCajkG7bbKlzs4As2OQsfFdA75YpwU26DJter2/QNam7Qrr/WpFJMmBVGXSxxkwvFKevEb2qpkOEScTXVvHE8OoAQGBg6UVBNVyPzkfa7zNnQm3OfbIiFaT6agX+1CZcddeFNcjmcoh1PBUqblxutMLf6yCClm/+xXEiVd10eFp8lnU2mft7J6leU9lPgEpYhy2jD4GfcV057HhiFQEE4qwDw9NxxoTG4Xzf78g2DJsZsdV5rOq1k5YJK5wrcZH1Q,iv:39/JoOkus8eHza6+f9DsNdnhCTKSmcIPz/6G0mvLTm4=,tag:K/A9vYP57Dr68u1lJbz7KQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:yPatpK4liWKV9e83vtIVh5a+KV105/GVCOkqwjuLvf73rQsaEipFqfKT/G1QaGA//4TjPIFbBPFO8xTu4oTim+74LySCRjxYC+TxsqdxPOR/8fEOoKTJ79kw1TVSG1Mr8yaAKoNZclMQpBMQtkIu24mn16RdzkLf8v3gzZzfQVScgoXpGn2Di2IRS9UgCs0OLJG94T2V+dAsZ/PpETGzAe6+wUG+eoQnxKqWKRT1h8TawHg5QIAI3Oq0DD8rrUYlmv1CczYVBcqg/3AY8w==,iv:3K/2lx2O+e1MTLqzcunHQ04fEcJ5m9DoAXd5asyO604=,tag:1LSiXQ7df6BgMU9WOVrc2g==,type:str]
    known_hosts: ENC[AES256_GCM,data:pqZpYCE/fI8XHopjg+VUhNsNmH26kTSsKXxZpM/mIVR2owkBSO0Q2Q2mq2es8cSjs9fFpPkgm4o3XNHqU6ghRJp7vkJs+1dRAZtKvBjKhg3+cqAGZAtkykmHPo5d7fx6J+Or1F0i2MhhcD6S0SGkZr0FJO1SOAKZAYRObPhTOOpaR9QPVu3+44cX2uQyNfkkZLM9UNC0ILOPWbvf2t1vJmdF6V+Qr6uTRJkD,iv:e+Fy/+d4AVbj2UsRAR+j9wEOCnmVxoKoOngV7FQVWYo=,tag:ziB0hJc0PICHd4IMxOtv0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUDk4Ly9HdWxPNFpveWJ2
            ZVJubER3MTVqc21XakNkK2lldGpPbFM2MWpBCkZ1UmtOejVic1lvLzM4VEZxZmdm
            SDBycllkdTFtYjd3b28rUFVJWXNwTTAKLS0tIENHS3NoR0VDakpTM25xc0ZaUzd3
            UGhqUkFZSTFzZEN4d1NsSUpPV2R2a00KL4v269U6GH1LFJMkitaKlKVUNdeRYYye
            LK7TkVx9HkoJspqt+PICLIFjTpqVvsKo6eKQuZc1/8NZG0di9urchw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:57:46Z"
    mac: ENC[AES256_GCM,data:uIX4BRu4Nx4aABjIQ5m+6sbDW9fxkzc3c4AypPQzhXCIOfBN81HAQGowc/VY5YQO6xVZ8tfGW6eYEtr7MGhUd9KwxyapDj+2mm/qCFFH+7nMb0DAVNLLBU9qAgxp04wwffiNfdCQZMAgdL4HjHf/VIzUY/4WJkQoG6MKtBF75fo=,iv:hMVKcN37VJZMgdjsgeAIlH7LePFmRkNbz+gd22Mnd4g=,tag:1I7aBRmcpSN6sW17SYof5Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
