apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ytnkqv6RV2sbIiupXXyOGff7kVoit1ajULqpIN+M+r3BkKLzkBrJjJpbWo99xtcX4to+tzm/G96X3mdW8JoQUjiJ/wMXBUImOouWx/oPO2BZ33Q2wlXKHZ7pEqi5YnR6Pbyv/HORxYSGrn3ZuwqJnaGPc7NGBhwhUiQ2lj9ilDvshzzElJuO8jZdNaaFmwpz504lqX+AmpXdsc5UaAlgMIFx3Wgv9ErhFOeVWMVZiPNoEUkLVpK4l1rEWtKqC5EXYWs9rAfqFXijFDMy0avopA+FcXDzuYmJE5Z+2JAtyxyY3YoA2K8zd6Dj026wLV1CXTCsD0ugJB+Zng2TWuqpThZCutOqdj+Vz6htwjtjeJL2TD0XXW5aF4oczI/EYkrh,iv:w8Pp1GmuMTyvDSBGEM52LwfOTIvQFiPawr/Cwo/qvh0=,tag:DauySQ1td1/+wUVlvea/Yw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ns5ep/3HiA1WaimbKpfqQajNpDtNMCrffE5y1aAWboENt1QbTyN6v8a3YVOK3ZhGtG8aAcNTnf0ICc5WEnxUQzZJ2f0ivFlwqcNLIB5drIiqMx3GNfL5S/fGabeCCwWw8SMJ2ZnnZyGjXFbTWdPioWEj5wpGgHb75jn2i/hcV5NRyxcpY0enk9A2FZwoaQXD8z2PvHuTR/VxnkddsyeJJp/PMUk+FBivvCXvv+7Npk2VZUVQVDUi0oe74urDA93d9FRii10ZXT5+w6VLFg==,iv:dBpEqVk+zrZkVEZjMjlWCX2fVtmGBXYysZ6W1nQvG3A=,tag:MkOMTNcpzS/K8vO3ZnZs1A==,type:str]
    known_hosts: ENC[AES256_GCM,data:Nn8fVqFy9ubAOYsVcRphV3Y6La12YShr7/BbhhUv60q5bhXBqnytWJdTa06JZT7LVWM4/zxflIbfxf7+SNrKvAM8DOCHLL8yrXa/C4LGPl34enqzfJIXJDPupe3o5S094569F9vB97SHQavH/fg4c+bI2gVhPi5/eTsmVE21oIfy9MFjQffoDivG/vicwYTEop1B1uw6QMpVTXXcU8LtM0vhAc3r2kVnC6MF,iv:5+Qv/lSxZiKKaECso7xojbx3pgG77f/GKFGsTYtOdhk=,tag:kGfLzBg0zVm/TtCXFd4+mQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQjdoenRzTkxFWDUzU3RW
            clNPWkNUeVd5dEFkdjZiRjZoL29mODZHZW44CjFidlVjdHo2dTdzMXhyamFhMUNR
            Sm1IMjlEMElHaVEzL0pHU3pHRnh0MjgKLS0tIGxKUVhCTXpNWmN0WnAxVTdwU1p3
            T0hVeHI0T1ljWmx2M1RPaUZ6MnJqMEEKXmyzXB1fDYYJdig5XwTlYg/OXmZsMzxp
            c6P/o/jEojoXEB37kgtwWY+ap0FtB9+eRtPh+xsSig0gfXdGMInBqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T10:31:20Z"
    mac: ENC[AES256_GCM,data:pc35qhg0sk0mv0/QU3dMoctPgBqQPQylcw8AOzBM0tcF1PF0QtfjeHY2CGf4XelZNpBLpxSEupgoZ3KVtRGj+2RNctIhZBmKoRQdJveRZnsJtqcI++3osMlvOoENjbl1gKEipQ5Suf+/esaNLI1EY+3J8xWTF4HCEP+RHDyP//k=,iv:xIOimSNlaASxlJ4KgmtZJW8/NglejVSivjNEftMizKs=,tag:fg3fAY31fjXy/WfwpxOUkA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
