apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:d/qjOgw/wMlT/6+tn1IM9EvFSWVjAAUPZ8D15njkP1KVs8jYKxwqHmWcCY3snGyEk369ymABPeVYOLldHeAe2iJe97tRv0PtU/x+wc4iaFeH9zm7oE4IV4bZnfbJ7SrSc5W7KBcWuwJyHQceH0vbqKgx3lsoTSVToOLO7u/spUAiaS5Q1oZmFunuhxJ/LAs9v51CSl1EBl+TbX4FX27rDvujmWsPs/L8VG+KBQs5zaq/YaZRuRk6JfCwBcgBWsnGT09bkSzDRpdab5rR0IPYgzQkbyoxFWLLd4L1AXkVsBJpCABlfw0/zSSajRTS11r2gvvMTmjKJPegsJbAwr169dEJz7mxCOMbiCcvKOfPQnM6dlZh1yNhvEotuMKkhl2U,iv:/5O8Gy5t/YiAwnN9t35wr0h/y4ejGOib66mIi/AhLwM=,tag:xzh1eiQVd5Uo85WB+Tcqnw==,type:str]
    identity.pub: ENC[AES256_GCM,data:VhPTw0qWEiw2Tw5eMjnOMDM1hU8ekMr+9K/6frvnPSQozSiBF5MRVdGrmUK+EL6mKT7G66NuRYIlxMj+I2M8D2OCpbTkSgX8o/7yNKiIh/M8G6rj+svYQwHZ6dJl9h22aXdJxe6/BY2DL5X1Nk+9f60KMo56X/AzuDXDP5+3xAwiJv3i+gSCnSn4XS0Ha51GZa/hi9AKFPi4xkUzuQg8w/1w08bRkFNU0IfRiYkkY1h9yUPFu+fQBj5Q38R22xaK3KiKH6yF/ecc8UTdLw==,iv:/9B/0kLGT3uXFTDCvJw9C6gXLg+PRYjccBLVEORXvZY=,tag:aTnGqtJyrTmj9xbr7dGJEA==,type:str]
    known_hosts: ENC[AES256_GCM,data:hf35CjuXzlJw+9vs6QLECYKYA1/sFwYVGudbBlaYR9kq33RQWAgDtZzCgS9etETml1ZWla5J+ddYDo6lDk0UmzBWjTcQxdcD+ob4A97Qi/EcuAckMrJizATvp6cuE0CnADm4RgHB3uz4vxdE43Yn9WoeHK6JMvxRMHrt2AUOn2S1lZK6r8IdursOoTNuYft9U8GKxhJTEtllMcZPjD8g5IB83u8x1Ag0zAkx,iv:Fl0d21tKrqZaV4pzO9gKn5yozdYLeNp378Q67MjaRlU=,tag:tQAKC1hDmRN23YmkGqzTzA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTnBpRTBMbDRjdmk3c293
            L0pUVGdhUDQ4MWNackhsQktvb1NhODhNSzNRCnNHWlczUEdYSDVYalJ1Q0p5NEs0
            TVhJQTY1ZDZIUXZuYTZoNEVjalVDck0KLS0tIGhoZklFREI3NEYvMmRyZzRZbkkw
            UGEwbmdYWnhXQVVXVTRJU2Z6WDNrUTQKLrq0O9nhM+a4Rl/gjNCiFshISZgPzbN6
            WtsyZVaHmsNbXeGldNLpMyrPg7lJA+XhyTqDtYjDM8PjUUsMD3dxag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T09:25:22Z"
    mac: ENC[AES256_GCM,data:dknhwRNe4b6/NRcmkt8kDuhwe3IGOzr61cGxcvJzHmTdeQxoJbVY0zXNbcjKyEK+QVZYvhAWZE31CmiS/xeaHzNc6gaBKYUioXo1TtQ+pcThtAZQL/gWh+TNrvAabWlp7Xe8tq9QvaycXVW63PSlz2BNm+8ZZ0vvbzCMTpv+Wq0=,iv:adKYtfwIP9FHm9sr8uUjhC0nJcWDHvligJ16Oc++tr4=,tag:XnVXy7vc+ZGRqTDRHzqhJQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
