apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KVDXb2QaSDDUq4kPkkSOlJVHW96W3gBjZHbZISDL2/BIMKuwuaBAkSJRydkIAnXJ6wGL9wppRxMwUgayIJlOysyn1D/9WuSm4gmauFGjFeefePxQAuHXaEK6U6oKYupXqy4Uid1EAqL6HjO33EpG+9F2oqtRLnvozn4UZ6s5RhDyGD9KdovPuRqNXWDyuCvppi1YVNrqYRtJj2jm51ReH3jP6MoKTIXzODrFmuKSkSZ9N1W8oUdCeO8BtHsJiejAjRMvx1d0nh4dQ+mOtbS4CmRovuY8RtLIADX9ckaaOyOj0AXJYYcY83Z2ttxJ3Gf1ZPCa13EdiotIzgvwNdGOGnV2qdnF/Bw4H+nge2s7L4/iagng0ctRhBP3nwzPNpDU,iv:1cM9Ys4pqYk286Qpt8zl5zOIKNIT1ClE853jajFTgbY=,tag:K0UifaOsELumTBhKCqmdzg==,type:str]
    identity.pub: ENC[AES256_GCM,data:N1qeU2ahzWsvP5uwhkhaH4hjk51wcga3OXGLOqshxnyx8QvK/KrC7+2KZ6DGWfNwrKnjGYkx3X0rkub4bkQPquXXVnE198BZE+yMU8/k6s9kWq2khBi7vQDoP1i6OZmokH+LgJdLp8v+gDSwn69sRv7iN6XPqeGoL7Xw0l/YmpNzDObwDXd8du8fXxWg5ioY5UbExwIkiHmp/6FQ1ASHlm2CJHR17gNQvqtLrS5u355bm8prDgDeVIYUyR9caukQIXw+hf5tz2zWvu2WEQ==,iv:UrxlS8R/Ghfw5dulOr3lJw72gDBXuPPAGFbEWBBvrxU=,tag:wQQgzqg7LtptDw7LVY4clw==,type:str]
    known_hosts: ENC[AES256_GCM,data:jIVjxeaNhIFx6NVsGkTuMEgTxhmvgWeTQgSy8anrDb0vvYn0ZA9gHScP60vBnjDl0h2Fyz4hbqlq5ewmCCCBgZm3LklwzQarrECgewXQG4MmdWrYKvngFXA36FkJYB+WivDBA6qfqIdrSnCz7naQZ+IoGBNOKsNx1czBCmluaNT2pC9htFXySVOayFaCE10RPAEPyUO9uBmaLrnLHdlUnosgpm3I31adN1GQ,iv:FgtgNP2xZYoNOHoJ238HJbIkyy/RiFC37f2RJO4JWdo=,tag:qZTB94IjF/WLpaTI1vHMsQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSclRjZy8wMXBneXRVM2V1
            NTVBcDd2QzVQa2ZaK3pqQ0dvWlFraFd0b1N3Cko1N29kMUJxQUZKOVZPekZiUFJq
            MzRrZlA1YjlHR0twaFZMcjBiN1BXcVUKLS0tIGZNUzUxRUFNdUhlYkZQSlEvdkFR
            Y0xkMFRJa1hwclorRkxMdWJjNHpaNDgKkHwbaQsgUduahK4DtaeyFB1VTLRleyst
            QiYETtENlrrzwp3PDjhgQjqal4+E2FxUXz0VGLtoPnYeCNHBqKS9JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T10:30:19Z"
    mac: ENC[AES256_GCM,data:Wob1XeXIdg/pFCwUWeFe5enHtVXMEr/va3Tc8zFGvwOqyJ/7NdTHbG2UrzC9MuEYGeCCMZfjOU1wm8qbFMenWrK1hAJO5uQdlEX9GyBMJ2mE5ViyFEiQY36kIZ4j0EmEtWxldiAdMP2KhtymtrIJmLt0GJ4GiR7bI/7iym3ftZQ=,iv:QgORfuYhvlvZ0SLOXMB75fZPr2qnH61TiNqf2xYX/qQ=,tag:Gtkp0K1gyCdUPbUXPBGxGQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
