apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:d4tRlJeoNkeWf9XHwQH+n9eMADjcfspXvqbSEp+xxFMkoOge+8VtUIrScBXCJtHQMVSrkoXTn8YmHSPuDEeFCyqIm9IeWNeRdf1+3geLmshqnlfQ9qsO3ANAXMVkOVqdaX7LmgogG8elN04AcjvKWCPTbfA0VuXKfrCnI+DDY0HtFI0Ei4ivvDx4E7Mhw7eXGe1mZrEeLEf4GqhIwndWCtK6J6ev+m6Hj5/9yn2hoUWb+vKwlazzheXApsDKSz0uM21Sz2O5lG8LrLZXIF3s38Xi2+YcK+dq52NWw8ztGg69jNsyo/xb7hSKLf9/uI1QSvK+EdqcXME4F2LjuruYMhgkap6hcnDIt7HakubO3ZP0Mvur79t6U64cmxPLyikz,iv:JnpRUrgIFRcWg4stOuGjDFPbX0by+sDGqLbRv8o03cc=,tag:gSG2tvU90ujnhQ1RzsMetg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Rx7TjjOvgGrpudc92SNWOvi8boDVVLw/7fGAB8AhK8jc0RHHJnvA/c7ZPoayjpQ0rNp4WzglOE3LHbL/e/JL1iNYuY/Z8M9VQCma1TYtL/c3FDUscEfF61Q4igiz14RbKerWVtoo2LdJmxW8OOuF3407zLXHTDSX4+73cnaJ4IoE/csSorjbAE8w57cLYJwZ4U/VdJP2T5+DOfsMMielDCpdMd8rGl8vz35WAlV3FSRB7+46wiIhl54X4Te2WtU+AnOwgoNQnmYYVDupYw==,iv:NELiCcsw1StXOKm8Xv1LCQDOXzreOnB0X2Ru3MfNQN8=,tag:G+U5EpJfq8ee9onvRwDeZw==,type:str]
    known_hosts: ENC[AES256_GCM,data:1PZTNG/AH2bamUaedsjNGnwtgjtrzmTME6Zh4dxviQ4d6qqOZCox5FgHZFhgWrd52PmGvIakdt6kCE9ZkjURa2kdDHkfcCoXT0r9KTbxP3S34QkbbulPNB1GvKVPyS9MEm0Xyn55oJwz90q0utgj0K97iU9gQKct2nSHRCeGAuCLvI/V4TQbsok4wlhd8M1rYu/C1K0kExp//7WrChfR1KKdC6cwRAx+RzpV,iv:P3yPTHcX1DPIMWZHxv+FoSGuFhZ6V0m3uA6pb/F3iFA=,tag:CvBt4hcBd0R30SORWJhxZQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M2ozcG1wSlpxTTkxdzBQ
            SUNUWWl3UE53QmVTOFhjdEhkK0o5MjR2NkRRCi9PbU5pakV1VXU2cm9maGo2Qm40
            eEtGdTU1dlVzNGJPSVdTK2Zmb2FxTlkKLS0tIE95eXJHRFpGbzNEQ2ZoaTB6cDYv
            eGV6S3hoODFHUVBpMEoxQnRmTi9CeWsKW6AjNoFusE5sF+xZu2IgyKBUFxttBG1o
            Ia5Esc7alT+XyIdz2a/pOvpeGe+j0WH4v9fw9kn9akJsvrY0Tl+Cyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T10:03:01Z"
    mac: ENC[AES256_GCM,data:yxnyEW+nFXRwkYvkGCYslkr9fXx9/c4fg85xOA/CX81dvY8gen82eggEd7V/73b8uwpf4BisLDBX0JWT5azwb6WzlsKJX3N7wlk7xU8X1Cao/mfjYBlYqP7nQy5oqjzdPLjrNaIWGcTIF/UqrANJXdjPspZcJY2bwhTwAkKHAlY=,iv:6EeGfnk0/DbnkbnN9SrBwV5Ac+Q7qJd1Fa7pKQtRpPo=,tag:0/nKpMm1L4+nBL7ie8XPcQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
