apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:V94StMaC8w8eqXCusspMmOwnIz0qqI97TYGtUtDJrFRbbmfLBBsiiFQqaZYX9aTNqcomn5erpjVpDMJPHknBJNRN02ovo4A33P4zyf6t26lPlGZOLj0kaGmr8OeZI5oIlOnIolQXBj9ML/HOsCugXnWucKjU0+I1oUgpYh/iecsW7r294elDM+fbIYOtbDOXlvVxL+mh2aX9+hSYSgXyYxxuUAyatk6GDNKq4DfOP0T78hTh5P2bZrUUxRKhO/UL9wACmk0ytl6bGEsKvA3QnmLshlI1eRb9dJeJr9B2McztiM2NH/rna5IFgJXni7lAAUvkuIgxtknBPGRl0Y696jw59Q5ZATfrSCFKpAJC6RgQPeqR/yR+0HeR2scDLx8U,iv:7HFnMYlm7h1/V86ICtZC2mN5rDZjQ00gzPC1tfc1TzM=,tag:DytjcBPlUIfclXOzHHyNTg==,type:str]
    identity.pub: ENC[AES256_GCM,data:tNxUhTHipvTsMCMmtHXvl8CEr/3p3RdCiGKd6dRYNQ/5vtOsEGeG51k44paX8DWyj20/nV5B1XVCvqqWMS6zLCF+2ulrLVv6DoeAiYKfWJhW4muPcU4HSIXfoPakzyCmYPotnpn5l7y6dUcpXjOo/J1m+u5bCOgSSzAyDQlIMbND6EwF40QXLNzjTo5ZpvWIV3zrMYfZBsFbCBU0ZJSaOSUiGgA2dq4o6Q5zzxmRM8gB0SoS+6gh8fYreu2EigYYDyAU0KTSa4SXuL44Lg==,iv:57Dbm0nsPq2dGvct68GaA4OaHjhvlT/f12W5luY7y6o=,tag:Zkq1tS4YoemLs97w2aQiCg==,type:str]
    known_hosts: ENC[AES256_GCM,data:94r7PLZzuyx3qF8pykYJjEyQsVCgTXd9fwbr9MI0/l95fkZ7041elwB3Y6FQOPup0AChpwxFW6mRd3YPFe1hAl0tAzk6w4qxmI3csPV1mreNuIC8qr63Ml9fYYXob+ZGVBN+MHjHjle2WO3fHv7AOQmmNIhR5GoF1aILcr4BzLqKA0k6AKlNNUsV7ruzGQecUx2SjzoKcz57BpvAXFG9wUha4KBw6dDUbdGp,iv:trxQWDrO7zT25pDkgjzVVrFgZE/ZSSim/WUb7mG7Pa4=,tag:5/cpLWxHFd3CSUelzPl60g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbVdaVWVQdUU5VXRWU1dL
            V2pPbGZJc1oxYkM4SEV5dTIzNDc4bm5Hd1hVCmxPOHplWW1yNEVzQnRqSTFiNTdM
            Ry9TQkpZMlRQTzZ0UFVyUmhIVHI0eDgKLS0tIEw4c2l5dlMxSWhJOFJQT2NsU2t6
            RklMSTdrUUFjT1dTL1JYVTBCUldvS00KsiBa1/B1ZS1ZKMbL2nFNVbG/rrfXjph7
            y0XpuHUvxrsBEPA+G+U5HHeG4Os0E95evMyzYZXmsf5JA78PBqmQpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T21:22:38Z"
    mac: ENC[AES256_GCM,data:LW3YlM0n/MPXeEiKJPdz9inwFOtZqYmLSxKE8e/goWeUDZ1LOGeYBXCiNbPc6j1f7esI8X8kUNILjQ/LE0GshLBamyD7L1DKDtmmFa9kj3Pzbrd/g+jJzT/zX9++ENL6Zy5808dFjLjjdGwkkNDu9dqrCVXsXqRJzlPoMx/hUp8=,iv:9U9Jsgd6RTzJBCcBa/bWfGYO80VpS5ChjP50rUOp59U=,tag:0jif8Gwa483/q5MpLeDgkA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
