apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tdlDWnN4DCe67Vy13xP0AvHIK2dfR5AQaWJRX6CH9dU5xyO14we9Fg==,iv:B7qZSth4SNEdkaogODwBecO3Qf+T3WA69wJgGv+53zk=,tag:JZGYWqfeNN0YoQmwDDmLUA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YVlkbEI5d09IODFncFRK
            ZjRHT2hGYVVVbmMvdUVtZVh5VUUrSXluU2pzCjJHS2N3L0RRWmd1S0tXQU5aRDBQ
            M0ttdHRyVVI4L1pYUkpHTk1XV3pqVDgKLS0tIGViaCtMelBCSHVMRmRDWXAwRGFn
            eURleklyajFubWVvbGRTZTQ0OXlLZXMKaq8uBFWGqBcfYVPReFXrnsyKgQ2cD/NF
            FGd8VxjaaMKrfLhkT7MyxpGupE3/d8AiDy8wYavruCBVcm0nY0//vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T08:49:53Z"
    mac: ENC[AES256_GCM,data:7SOKrw1ztXzFcZz0qrxj5dKmxdHehMBwrb7ZSjhhbl/CeKDKEK/estbTcP0LmKAlNvjHsZkGjwppsGa1+yDablo/pIGL3/4LSqtHNw55nEdwSiOgU5uq5KVqbS1J0r/7MwQkeoJlGrFc5jRfPgH6qPsfM0n3wNGZNT1EsOKWsV4=,iv:JABnYxgUuDOfqrniY5J1nk0S4bZzDPjg6Hi8vVqCKBI=,tag:g8PoG+9syRkH72RyvMWTdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
