apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:c1R/Ionvb0/P9jNP+D6msl3j7zWDRoDGG+MA1lAhVY/ctHaYTRVhrw==,iv:ptjxP2gqav4oEQJJU64Q1DjThKTnZ7QxCFZpJV7pEKM=,tag:6LCVpS1CyWOxBIWe8R9ApA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbFpjbzRzdkR5VzBuNWxh
            czlwRnAwcVRBNlM0OWR0bkRoaWRiTEpIdjB3CnJDZEFJcUxJeXhMTVlPcmp2Kzdo
            dkoxckswSjBPZnM4c1JiVGRJSGpLdDAKLS0tIEl2M2hxLzBlMGNiTmk1dXBNL0xB
            dUREN0NtZVdmV20wdlNBQUI3ZFc0WDQKi0PVXMAGCH/Rm2x1mmgAGcE5mQ6VQxfi
            goRWc351bVLhIKVPA1WtsO73WsyskH11fXXJaolsEt6a3HjkUH4Hag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T07:02:11Z"
    mac: ENC[AES256_GCM,data:9negKmQJcMnR+40cm+lXHa9WQkHgArv+M8QU4GZq8Y1c5m8GmGiOonFAQF0brAMjW7D0JgKT3EkXeveFekjB/YQux0d5jI8AlBSLzqSXluw67Z9U4ez9/7+Zx7SX62D51xlFk9tO3CSuMBbhLePysk/fUBnNLfhFDSQLzark21A=,iv:gYL5D8dz93VXDZU0Y8mR/fqRoeRvp3KvCRI+QvqCeeU=,tag:Z6L3qAKd1ucVwW8h1263lA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
