apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:NwPCZQk95/xSq3Q7UD9oVRTMdqSgVHJ1QsMk1s5tZQPRdVuB4O3FkQ==,iv:O/D0AOWtTcALSDQvqs/nLRr/s9lC5OBFJ2SHH10tx6M=,tag:Hfvrp6nubG1WUZtCZBbOfw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaEJlbHpBWU9yZFhjNG1z
            N3hNalRVNThMeTVYTVg0QXlxN0I4VWc1V2p3CkxIa2J2a003V3FhL2JPbHowclRv
            Q2k3WHd0cUFTL2psUmc2VEN2UUJoMzgKLS0tIC9SbzdrY0J6R0Y1Q0c5MDVQMmlv
            OEpVakJNMXB6KzBRbEwvUkJwc3ppT1UKbHQZVBauaV2hRZZUywPjFZtxCl7o4eMJ
            OokG4V5QMXGbRvyZfhnQMAIp5SVtMPtntQLZlCWhasQYNKaGMDSRwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T10:22:55Z"
    mac: ENC[AES256_GCM,data:hcokEPm6CfHHYnEuREPfqxbjjlsXCZCSYM92eaN5m8EkYaRpN8eCCNUxlmISLED2kZXVZNO22cXrSpof0CrO+5qn3o6F8pfE0MbNJdTt/6oNLxcIEH7qO1FnUqFVHnvQFuQacDiyNNplVkZcUmcgSUQFErU8w5EpRH40jn37Pew=,iv:24U9eTnfd3ZTrsVStDdGn2F8t7ewcWVuOHHUAOucDM4=,tag:RnPOyTuSBsRXk82SGSgzpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
