apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XuP2G/QoX0qFZGPUlVLTZApnG5j5rywHPAoEck+XaKIwwGFdx/QR1Q==,iv:4KBaMNoR2bZhJDeDSGXHbI9wM9I8xTcQRDivVY4zdlE=,tag:XOUuPb3XGEP30cpTDdJQrg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOWlFMTljcmVBR2JMQ29V
            c1REcG81bWJEdytBdXpOYkZJOTBremp3S1U4Cnh3MHZLUkh3MmkwM1RGREUxb2Qz
            SCsyblRKZGJmMWRqMllzTzRPSzlSYmMKLS0tIHpqMTNsUzJmN3lIUFA1VGxnYWhx
            d1MwNVRKV0N1bXNkd1BocmpxTHlkWDAKtWKJnTzDD+e0QLsR0R5+JlpKP9DsXOtp
            eFnecVp9Wcrr4xFsBddyji+t7wh1nMGWxpXe8tWJ4lUdT2HlxDahBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:21:01Z"
    mac: ENC[AES256_GCM,data:BU5N1b6YrMhbX94NNYcRwOU73S9UynQg0ptgUlbI4AX3Ty2SR81ZqgLBYRbLMLKOQaauUT6502rTLJnOHyp6Q2mTZh8TR0xMs/xaA/UMpHu/uRdWmrsa89ivHQAGMNNXnr1Jc19BLHvzSZP2KblWxtg4EcDRjUPpZtGGwPTD63o=,iv:JffkpsUrekPq6DZpsDszdkyL5IfiFZNQ/FFT9/XKnFs=,tag:9pvRB8NUNZzIPBSSVTc67A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
