apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:MZrJUoeGS4p6kTb1LPDxM4kaLtePCrgFCHRAhCBwbZOtnzEmOjRHTA==,iv:AZVK3Rgufis8ntLXjGOszHoDgpKRNwsM2tST8Otkrfo=,tag:tLvVZ22p+5NNPjKCD5UNpQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZkhmb2lsamdyY0o3R0xV
            VzErTURad1doQVJLM0xyVFNiN1FZdW9lY2prClcxdklIVWd5WVRNV05Zb3pOeEtJ
            Q2hiRlJBNk9yRzcxcTQzRlFra0c3ZHMKLS0tIGNIbkJMdG83Q2ZobFNBSWpxVWMx
            VTZGalhRR2I4M1NKeXdiZWdwL3E4U1EKtB0aLd8IHkEImyM7LP9XGknuDkF99TGc
            LvMSa7aRIoIJMYeCWVvFgwhduehXs3uwSE3wjaWHmv0tgaDXoXLykw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T21:27:03Z"
    mac: ENC[AES256_GCM,data:14HwGwWTEt7iRgFcteaALd+J/t+bKOkTMgfOyAyRQkBW5Rf0+n097ivYakJ2KxEB1bZrNI7BHuNo3hJpB4YMgM7wYrJuWc96J8N8re2hm3aGYIwW3ydkEIuegK0InwNPUjw6I27ib5UA/NBEq+8WSHFQmLpSnELD2gZ/FkO2Gu8=,iv:FjBh1Wlj1/+X6rmmE7AOgUtQgtwYyFTOYDd3xscMIUw=,tag:2BsKqSjp4hsE5T8xz6gI4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
