apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AO+QC+8xlMN8ONoFjpETe6uwXdtW6p23OF1+UCGgRe9NfUQ/C1W/Og==,iv:MMSGQFC2CTtXd2hr9Bng/CyCZBK8VCce6SJ9B2c6fQI=,tag:lAuuzrzMzBlZzRr2k9/vAw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT292V0NjOTk0ajZ0eU8y
            SE1nNHZ1cVZsR2hFbWYxZ3ZxSHREWUFuVVJnCi9pa3d2YkxLbjVmbmZtUC9LalNG
            RWgvMFZ6eHZnSTlGYTRUWDRNd2trQ1kKLS0tIFdwOTdpZlNKNXdFZnFtTHNCa1ZG
            WVE0RnkzZ3g1Q1ZkN3ozaFdLR0JkKzgKnEC+WwxSBrEyn+H0HSJOam0zg/v0ekDA
            Sec+HTw+OrWKOu6JUxobMYDFB8YZgX7QkNKA43gfZ8kEdu3rbSWDqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T22:05:14Z"
    mac: ENC[AES256_GCM,data:rIzgshUIN8sHDzXweywny8izJPfKTbwIWqu/VJW3u6xVDykPt1beqh6f5ET9Z9VpLwDNkh4iK6iBzh91ZJaH0H5uhNC7SDyvNfuS0df5WEjNKbLWs3hmecK4/fQ4D9zf+FSoCh5lhSg9ICMq9QVVDppZquGgN4L4/fjDHEHUi8g=,iv:zVL8M/AdNQAjSBJHZGsnQ4+5QAtqdM+KQqR4UJEN7i0=,tag:tS9nVI23ajqll5ebLh0zRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
