apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Vefa9F0C7Yrv7VwAYE81UqroI7+AiDvBnkfrZ/Hw0spufgla2rf7aA==,iv:1f+fwox3I3tK3lC5SKDH3GwQaJmom3z5quKufYTBMh0=,tag:I7QuQhgr7SrSZtMnIae+yw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdG9kNW4xUVN6V3ExdXRI
            eWZNWjY5RUtwMG1UT2hvQk9LWlhHWVNZSmtrCllnZDhzYTgzL0I0QlRVOGVXTnVZ
            YW9IK3g3OHVHQ3QvdWJ0UlV5MldMSk0KLS0tIGd6VGhxdVMzL2hjNFBoNlZXSURh
            RTY1a0FBZm52MnVlNUVIcVVUMUZ4SDQKer8HWW5urNREKTLcaoIKjh8cizVkv1RP
            Treis7+Yl59QhNM3gMq1iErylSwkhxx6ptFFBAPJqGofrQAfQXAjPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T05:55:53Z"
    mac: ENC[AES256_GCM,data:aIP2ynivv/q7aExYIfbhM/8Se8lh8ZoAdRrbJWZhQh5v2B3pdiH0K1M6oCPh7pbHaCRW4rfAspoCIt8UmBMd7yJeJDS8q1elz7K503PvVTLkFeyZFR2YVsNB0Cnq6t9+bcS5OSO6RmTUaxg5x7Xi8M6Yym4pkoBsUGfP592PL+M=,iv:tVxOCUNv1HgqUmvq8qUFTQ7SUuW3cZv53EOIyySgjTo=,tag:efk5g9X9Vkiylti517f6oA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
