apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TOX9o2pVG0LAus1fv3HeiSaXfk3gPO5TrT4a3GeySbVsPD5dllX77Q==,iv:4BMmbL5nYfDGhtAmKiwiGVH975Xllj7xstQYtNpSrFg=,tag:L6+SION9IQT4vC2QpYys0A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZmdFZXhFNkRUTExJcmRy
            RWY1b3dVVW1oazZaL1Y3ZVVNcFhmMFR1amgwCm5jaWRDazZJOXhXZk8ydjhEdHZQ
            aXB6U1FTUmNKV3ZhWTA3b2ZJTnd0Z3cKLS0tIEtMaS96MXlmZzZ6WHdqSXRoNW1z
            djZ0NnMxODQzRUYzK09WL25DRHl3TVEKOqNbbAyg5B2r3Mm4R71/fR1kNnRYatW6
            9Ccac1FaBIlp4of+CJly3LQNmo3FYamQ5vHYZaN4TRcTrmDou6jmmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T21:23:37Z"
    mac: ENC[AES256_GCM,data:jqkEwJ5WtDRlWNXBuWV/vvpSrucKYlfIpZQJNLdr19bvEOJCnW7Lrr18ppdB71NGICPaFEDbmM8ksc8ya1bsSuC3+MKSL8ly3Masq3BvgvCDIekubh3Qck7tCRr6swrT+ar3OormoU+PTowiyZDeIQcO33K+Ws1D9TIaT/R8NHw=,iv:fVCharEaV/RGEzFVOBAAo/fADtNdYkywoQRJL57B5fU=,tag:RtuuXPn4NMM3HFer8nAj1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
