apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:S3dMBlIURrtL1pHowShAvdTjNIoTsrDDyzIDJC1vZ+Cj5H+9YG4eHA==,iv:O/vyhnyIepllgZ0c/3wiiRXKw5rn2qIco9SEZ+l/Idc=,tag:sIKJnHpYyM9Hy1+EyKW2jw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORjlQT1JDQm90SXI3bldO
            SURhSUNrZVJ5NGs2UjlReHU4RXpwTElqelJrCmhBU3R6Sytlb3hDNXQzSXMvb2Fu
            aStuV3hVQ2UrWktaTUtpUXRCaU5VenMKLS0tIEpRZGovQmxBbmFSS1JQQ1ltYUVH
            OWxhT1pkZUVub0UxcWpjZzRlVDlMWVUK0J2mmII+jA3+thzuGpHro6GvFJdfHdUE
            GvhZjew+p4GmNYGBqdSlk6H5hOSnir0W3aTNl2SSLadKun84EX6GMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T07:44:38Z"
    mac: ENC[AES256_GCM,data:u16jfO6p/HdYNHfolI6/q5GRl4B4mC3lrU7PlDMbSGHapEFxTZLls4MUvZ/xMxANAornal+wXAqmy9BNVo4VgMQSMgcbFYTnB/6kX8zn+vlki9SU4877SH1vYd8AzWqMlcoD3JJQSWsrjguqIzb5tv4gkbfYI8JT5LSBww0Dh8E=,iv:Ve/UI2+MMY6A4pY7wX+ruaWRyV45xaNESDAjXUbnJb4=,tag:DKsR+acVUJX2F2xKC8xEBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
