apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TavajT26EgZ5wrgyOwsjAze4wTtVp7VNuAHy3ksPv9+u6K36oE6TxA==,iv:QmQHiaHZw+DVykzY+89t1xYRY1uuloZpDT8CcaNKxUE=,tag:NHxQ/mx543Cgo7INESzMHw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByemRpMmE0NnJUNmd2ekx3
            dUhVY1AxQmdKVW96ZFRBNmJudzduVXk4UFJnCldrZUkvKzU3cEZRdU5FK2J5Z2ZJ
            R0QyUmxlL0lUS1V4c0dWVWg1MlRFZE0KLS0tIFh2NzQ3VkdaNlRieGdFMlhkRFNP
            QitoTlgvdWVwQ2dIV0pLaVpYRThqVDgKbH1zrPcC5yTbVgr3wNly4nvv3YyGf2Xg
            ORLGivwj9yg4tnd2VlQFnnUvMOlX4FCMQIHNvbE32hHgO/myAxqUDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T09:39:40Z"
    mac: ENC[AES256_GCM,data:a+68ef2VgYfe5+xIN2rJnUkuAAEgR185sXbMUTXljS4VPMUefMapD5Xkijs2hnyNcXvb7gaihZyyJW7qQC/Hfz58S0tHFpvTUtf5gyXABuUJ6KirEDqJnbeshp9nFzcOnUAHTec4wTn7v9jFI811mrjFxeZxkKO0RjnY+i4v0eo=,iv:rJKC0OTMwJ98YODkC1vElw8eSWgASwPR292gpZqaG8Y=,tag:jqyWrO3uPGlwH3+wj0R1Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
