apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:D0EKJyx8Ny4gq1f2IyDVpbr8wFrRJS7KOpjsE+hpDTsuoEPOo2eD0Q==,iv:znZRVzgeytk4R9+hmqdZWxgIpQ+VjOpX5UETW90Pbfo=,tag:Vs6yhRqg1EZnHVOEmkTSPQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMDBNeDZsSk1YM29zQTZG
            ajY4UDlYYk41SElqejR0dWZGOXd5Ky9HVjBBCkZqRW5aZXkvSXlIdnFmamduMWkr
            TDlLZXVVdnM2cWlPNjl4a0hZNU1aZ1UKLS0tIHN5UElZc2NnSVp6MXpPc3c1b2Nk
            aFNLRmpoYUNSQW5FYllXRTcwK3pxLzAKCSmhTEcL7u+G83BCKR1zFtGy3tzCceGp
            VggajHHB16c64+UUCpGGGPwDJ5a8wHWvS7pMLisWLEAO5OXy43+vLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T21:22:38Z"
    mac: ENC[AES256_GCM,data:cMorHE7iEHaIVLl6qks+I8a/fP8tIUKmv52Nru8gVQT1sZZs6AlGeYDL4RHPbhUQurdaygCV1wV6dpzqXPdRSLmZN+Ba0VcX2DzKkyWKoMukuIW3TjhRTNH65lj86Fmp/soqbt6jSdCemEVdqPboGr8JFo+Haz382FhYoa+dtwo=,iv:Dbb1z1+BK43xWZeG6nDSzyhEUuq8BR6aPl50Hm5EPYY=,tag:nphzh4fB3L294RQ/ayYInA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
