apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:86RSNh6lxkpRW85kAFHNLhKgLDCNsEBkF9qdH9Rc7NA3xveU0DHSKA==,iv:s7l9MZIW8RIKP11RLrCy4yp+l9vjSyHvZUrtepDhzz0=,tag:RvVsM9sp+cL3v/adkGhTDg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcERpZlRZc1V1OVZUakx6
            elk4Z1VnUk9EYlZ2WUpPYmI2QUhWYkZDVkJjCmFISXNKMVp1TFhkMk9ITzJpY24x
            YWsvMytsZXQ2dG8yNUZaRExSVC9yTEEKLS0tIDU3QytsdnZKckpFQ2x2U3RYTVdW
            OGhGVUg4aE5kTW92RFV4cDk3RHRSMDQK1QDWaqwhBKFHUzClBr+chm+7zs7JNUTp
            Li1Sju5wdgqWkwjtuu9B1jlyv1ZPSU7K0SVlsWO4B3f+uBu87bs5og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T08:14:11Z"
    mac: ENC[AES256_GCM,data:n2UuOcoR5bYfbcyqPQPuOL7i90ZMiku7Yf8iAihfYu3mvD7JfUMhzW8Xr1oajPSc7xrBiVvFEhw5ZDWWP3fchEkWbR33qEyB/SqpksGnYqe4WTLwUYM7zlwwXzfpScy8imEGdHulM8gT9pc2QQnPikSD2ilKWOGGuMOtunX8iGc=,iv:8DC5KEHP4/7bNBfpIlTQ8EAyEUzyIP28g1K10P3215c=,tag:fqEBdR0CqeYk5P8BcdCIhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
