apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bvBKE5OjPWXdfEG2XcaE/OU0N2Kwi6rkrK0LEcKErArjaA0QzhguNg==,iv:DZhMQE6/ZYrd3enF+TiHb6KUcWXq4osW0stVS1xjs88=,tag:61tLLd4j8L9wZ690Up2Sng==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dEtoenJKZFcyRUROU294
            MU9KVHlWSUxpSDJqL2pOTHhsS0VIMmVTczJNCm41bjM2aXdqc1VYMW1UU2Z6MjM3
            TnNicDZ2S3VnVzFnL29aMnhCdUZpWTAKLS0tIDg1TWVIdG94Mmk5aDJhSjkrTzQ1
            enFIWm5SWW16WHZrMGZBYU9NMVJrVU0Kfvigwb4H0kfsKxMGi/e0B7291wscodI4
            7RZ8gqD1rLIUudiIKKClbHnKxG23wNQtq5oBlmqRHH/9u4BhK7Ts7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T11:00:31Z"
    mac: ENC[AES256_GCM,data:Lvsd/sXAZcHOZkxqprcqRRJt1dynQ0m9RggY2Ko2uT7Ht6RO/PcSrBveX0Wn4kqiE2RQV/j6g6OnqE0/uCP1nRWmeDOkLmR8samrxPy86RxRTCj43ZFLFvEChOKiEd4zDo/IpbyH7B4wH7L9mXHI5Nf+3chXIGoAgqys1Y6OpAM=,iv:JGqba9IdyM9AV3b3LnahqZcKIbKqNE++5FD93ckPGe8=,tag:hENqOy4NsGGj9JAD58shTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
