apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:c+vRwO0onanwGyeNlSj/q9daHcqT1wK5hg3V3uoE8hPP16va6L9Kpw==,iv:AcWLIHpZ0MTj2FCV9s1uaqxH2ID8aFAzsHMn91lyqM8=,tag:0fWzww1Hz4btcTPhp3cmhw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdmZkNmRmSlorYzlRMGVr
            VUsxeHVFTEx3Z0RQTUxoblkwWkQ1YkFyUVM0CmpkNis2UHZNY2dSVXZGNXV1b0RX
            cmpjQ0UrZEFNRmtrZmtQY3J3NktDcmcKLS0tIDZlL2xZbEVGVHNKcGRDRUZoSHc5
            dm5TYVdHSWZDanZZSWpBWjcrV3RYalEK7HmfrFpzfiElZ0N2AehsRAmPoBi20Yg9
            r0XWYHdfL6aQ3Xxn+EoA2LshrH5j1Sig6bfrliAzS6Uv3RI29P1mgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T07:48:51Z"
    mac: ENC[AES256_GCM,data:aIjSpFG2hi3ebQJtqiD/WnqIwf0K110PYAJD0u/mFPlwivr3lehYKVaTmPDbL+6FbTYUwCxG/uJq97jZLUbE2WpVeffdxl9Cc0lWfipcmbY7V5rBltRQjYtPncilgptkF+A7Z9mGPxLbeN42lijjJYvMWWvJXN76QC0MYbm4c48=,iv:RRaJEbOVHLh3LS9lN695ubLczYG6FIBiAQN9afN5cY4=,tag:7OGQd5D+1qnc+ME8lK4BVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
