apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:xnd7ihF4V7FkadIGdt+uX6KnkZN4xQa6WCup6T4ziW664SMX8djaEA==,iv:vSlz86n4BQgwTCI6LfUXa6J2kuNclEHDWLy9VWmH4KY=,tag:/iOpAhE+TSL3tNiin+emHQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ekdlU0dmb0U3WlJyeFNW
            eDlJSmRkajBqSVJwdXBOVlk0eVBXS1hIbkhBCnRjR1YxUDBPR0dTNlhMVFdjbGFX
            enJybTE5REtsT1pCc0NHdERMTVZGQ1kKLS0tIDZGaDZMcW5US25tMTkydlBFT1Nl
            c2I0NmVSNW5seER0UkVnK2lGRXJmVDgK+xMtjoYdSBxC6YRTVI25AXoGOPlsn09j
            DtWYYxmeuPkeUavdZpgGEoOkDbqdNqrVjgPB55nEbNJr/pONvapByA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T19:40:41Z"
    mac: ENC[AES256_GCM,data:14Hgd1juI7Ki6PEhof4abiYVIqifbM2SY0fvG7SQCdTnSkA2BUD1h67z8QFH39SG+MIM5+3EIZhPxyD8S0pmZNzyDdMik6BRVO+lnZ1DFEDIbURCet6OHVNCpGz9MEViZwHQiHBXbROfRBlbgxMqKzvXiOD4R9huZ15QjhiEaTE=,iv:rMRYuDsrO8u+VqQmeL6+teum7NQ7VemVeVFxHoOej4A=,tag:UQCv8vIdUJIBh3UhGWBhpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
