apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:IRSNc9BE2fusf3wngzrkmQxEcsPHoEQ+FvbYQ5gd+Z3jEpKhvnOJLg==,iv:JTSA1um7ouXGYP2HAXP707i4oDBL89OxMNRBHFJGvQc=,tag:VNDE+BueezTK+LiLGXkKfQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YlNNeVFjS1lsREJCZDNz
            d1dUUVNFNTRoZG9zb0l4SXNSZ3A0V0o1VVNBCnN1RkxXRzlRZXFaanVFU0x3Q01v
            dHFTa3pwdGtHdzhBdWhJUjBmMElLY3MKLS0tIExVbHp6blhvTzlRemR2S21WcWRm
            eXhKUkp4K1lIUk5yRDlkRHRjYjdTeEUKJuYF0Zt30XNwl9YRA46GAgIg+xrmBlbH
            YJvnf8uMjiSJCixd9xEqze9L9byoRB/uRbh1rmFQJJr69LN/8ZddKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T08:03:02Z"
    mac: ENC[AES256_GCM,data:1LILCzfJwuS80HVHbmVW6zL8ycaE8Lx45m8k++O+6QifjUIGSUltjCcuxDbkzXvzy39TDSP5T1mEwvdWfiyX2lAMSe8e+DtY1x5UUC7AV/mJWC+CgaQAq9o1WC0g7KyvoQenLqtrOzKBYei6ar0tueGVBB8LdBdDFWT+XanLplM=,iv:EFw2/QNcxeHAOoaGPuKvvDQNiOV/2e5TX+FdlhZpwQ8=,tag:h5znhuRoMsY6Xll7H+yzag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
