apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1MGupe/zLtAKp+QiQtL7bYO21Xj9KpsAJVQltulNHaFxAr9br4LwcA==,iv:bRhvg3CIfYearr9mmd8YlOI6WITEXLteAi+jHs0N5rk=,tag:RC/ndzyHLn5Zopb+8NCr4Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU3YyTSsvNStST1k2TUJI
            WGFKU203NXUvZGpPcll1RFR3cnNubDVZQXdrCnhPcWJrck5sLzFtSnhvVDRlV0VK
            cUxtVTEyYjRyaHUzTTVXQjR0VWpvOFEKLS0tIENtVVliY3NPU1VGYnc0elZiaGxq
            ZkpzeFZlelpLUUIrT3hrL3VMVTFCNkEK0drJD9ztl+C7L225MvepEKL9TtiY2G8d
            BIb9pH2kkGY+ef9FOpZnJVAFNrnX4XVa+R9BkzVzoAWNvuAP6Q5POw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T11:47:15Z"
    mac: ENC[AES256_GCM,data:etZX7gCL3HTsEuMMRhbGc8TFc9r+7lDjZojUBMy+a27CVq2wYBJ8jkiWYBdep2j0M9RJ5uexuhxxit7ILsQxgpt84TX3RCiL5u5s1nHqLgDf3TP1l3/S9rIF/3Cu+Yjg+ssfKiDqdqftLjULWVReZ+TRo7O2Ka11zJdCkBXWzXU=,iv:kUxgHXT50RvymVZGTSwFFhA1KfDGBBnf0NqTk2LFML8=,tag:85hAxCIHvpx0aUFXcJTyLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
