apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:vTaimzCbOG7H3Zwmy0gw9sZOebxb8NsA3Eiwy3mL6wq4kxmklQSoIg==,iv:jNRk3P4xf+cxszxskDsh7dECXfIj2md+LIY7jd1xTkg=,tag:P6/dF4UO3xjNjbzbKkkp8A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcmtUcXY1eWovRm1XWkN3
            bmRpdVhzQ3FtZmVjWUkwYjBSM093WXFXVlNFCnZpczJRbkRRaU9EMU5jNGJWQlZh
            T25WU0NsV3gyZnNYN1hXdmxveEl3ak0KLS0tIHdLblJtcUpMTkFHRjNqVVJhd2ds
            WFRiYkdvK2kvYVRZSmN0bDZJRmxCcmcKtZw4qvr5WhaUv57GflS90GT3Zv8Y9weP
            Sd+HZbsGHrEXktJPJ3tEihjhNuoN2XrkSjSQqXn63VfG2lceAoYseg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T11:27:11Z"
    mac: ENC[AES256_GCM,data:YBlSQnkT4k1KOGZl+2aa6UrLezbRcjVT0oSN7aDdG5j04JMxDQNd0mtW08b03VHGRnuR0aPrl2KQstNtieSEE6wSndYgPT3cj2c8POGpGmhj2zKUyjDOU1+1zp9AOE8qM5P112UMrnd4o0BR7qK65E/PmAGIN+OwVR4lU1AyC+c=,iv:bqT+o+ElYpMsHIFav/ZgjovQgWprxIsJrhUdKx3Zzvw=,tag:9DTrdWvgMZs/FWSQKrOJwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
