apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:5T9Ab+2pTJ9KetYtkeURFmClxa7fYaOMu7UcckUy69D6O4DBCkbwiQ==,iv:4skLIQwjUBkhebHM1+DRV5fXJXEcuoBsDUD2wygr+OQ=,tag:3vBGnHbfb9ajjG0KG+NEXA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadUpkbUVmT3dNd05ySUU3
            R05nbXl6MURFdzVqUFFTNC9yMUp6MWQ5QXhVCmZIRktNalhML2dqaGVxSy9zUGpP
            dkNFdzZhZENNWDQzdzd6MFR1L0k3dmMKLS0tIE1zZ3d2YzZrQ3NDai9NaWxGZzRi
            V0lpdVNFMnNPdTZhaDNZYXBqREtUTW8KmahpUkLVoF3xMPXft33ETOZFHePLUQeu
            a2e7na+K2QpzDco9zp3tGtCnORHIuO2aTXiwBCAJnNDFXtQLMnN10w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T09:08:15Z"
    mac: ENC[AES256_GCM,data:XY/nAfSieeKpmVUflPVq9Sa8INDq35zA6TnlALBgh7yHMK1paOU1Mjtc6JeRFoW3kPSxl+eG07jMYPk28XYB0xMpXNnq3SbblvzWWjC3bomTzVdvXGYO8P8nKzByMQdYmzaZCo5mNlapqQxPNrZ9wRmuGMu+qWpW9g3VfU+/EAw=,iv:GMktufAHzoh+dKc3cKhkytHD33o7peH23JSoBDb9Oqo=,tag:Oc40v2q6cGxj5QMkrGcvYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
