apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:U2WjH97FBAd30m0ppMo7IxnF7RFpYqnc1dwmdYKgtC6h2gDbVdc5xQ==,iv:1CG7NsnhtgeAcxoMFaneRTPyCOIfmqxytSfV4hq6/vw=,tag:veyESCbozl2lawPp6Svyjw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRnhjNWRJSkJQUEFOTkR2
            SmF3VE4ySHVtMG5Jak5MQ0JXWG8rZ0I3T0MwCk55Uk50VitWdENBQXVGQzUwOURU
            M2lSQ0JDeWlWdUlNajJ2UU5yQnA2TUUKLS0tIEZlRkRLQlBVbzJoNHNqYWlYazdz
            d0MySG5xSkQ1TXJUZTFoRGp5NzcwQUkKCRRQD/MYDK13vfv/fnEQpCeTgDfqcIGE
            cc7C5OsifqeuEXilniIALuPMdRTfZgAXZBVji+XyxAcXFdkuTPekFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T10:07:11Z"
    mac: ENC[AES256_GCM,data:X2X/tBoi/YJ3w18nFJ28n6g5hK1OiPdJkgPsYWCXzMQ1wdzws//fANUlhVdMBdJwEgxreaXrZXW+9HfiksAz93BzX6txLBBRdJ+CtgTwCbi9c692UdanV6IUba+XbuuboPYfV009L2pqufy0UVa6BjqK3kXySi3JHdIDqbnIbDM=,iv:PYc2NTNK8Mr36hr/8maMoN2ynGDZ2fjkDpz3oA3tlVA=,tag:mE/Vgfg+rewRRdfn80wCng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
