apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AD8Q6a+rQm3P6WW7xH0to3bb+aY+cC5kNuwM5w5+XP1oe7vtGNbq3Q==,iv:7U0hwO7CfK8tXyHaCc2+8e3onPdlQe6SBG7ePCl0umg=,tag:ktKgFGpe1qoxWp2Ux3Vedw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdVU0NjJyS2ovWGRRaEZa
            c3VYU01uWkVtZEc0ZVBlMFZCVTNOMU5YVWtvCmlXM213NkkvTzUxUHpLOFZtUFh4
            YWlVcDhNUVRoZ2xxYW1jNTVQQmg4QW8KLS0tIGJDNGl6bU1qUHZZaWwwQUhTR1JE
            VGNSYVNrYW9UaU9GdVF5SkNUK09VTEEKuMMn+esxwBDTbim+XTdNf47MbJM/W57r
            8+aIV/CiripJoUTWtjPH/vMJ0BnJaJ1hTuwslITZh1LZSTfjBj+9+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T11:27:11Z"
    mac: ENC[AES256_GCM,data:Q4IkUp7nqRsHlb/4rX6v2RZ+AIg7g5JfzY54WDWIlZPjmOJkhleZL9FBsf0d7Cg/JuTM6p0akEBhbIJjiEecDY7dy7MyYM7iQBWd5Za1K/EwcE72RFKGyB1IZzagEXEHhM6aD2tSxWoW0Ji86K0GvCn9OH/UBxj5QgwrxORxguw=,iv:MWfwS5NxSW1XdTXkOcspuUL+r3EgkOQcSCTkJqHkDxU=,tag:vsYgqZ+XbDKGdj2es3ugFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
