apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9vvsTAZI9fgDeWIxhUc2gpG49i1bqQ4/yvNl5N9oFrYVto+TmU1K4g==,iv:C15s8yGXom8WpfF7IW7enYwJOFOG5G/afPjBgsc4FdY=,tag:VIgXSXdwGukYlEQLUpxRSA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaazYrV01Ya3Z0MTQ3OFBZ
            ZW1hOURFUmxubFJaendYT09MRFhpZGlHSmo4CjNUaHhXU3BTZEVRamhOa3d3bThG
            Ung4a3Q0MTcyUnlMZGdKamlYa1VaZEEKLS0tIHhvbm9BR1J1WVVXNWJySmxZTHM5
            NnFadTV4SitJVGlhYmRtTEtKVFBkYm8K1j41eVrQWMI7EmtsXiPpIZS2Zqfda5ba
            /PcpcckgZuV2+nCvSd6rBaygwib/k7guMKDz/w+MI0o/kLB62TuFYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T09:03:50Z"
    mac: ENC[AES256_GCM,data:ovLSxa/wsDADZ17sWq0BxGgzOd9QJIhQPkyIqEMLHZG7kwU8jq+sl9FDVFyANYaXcgNwgZWXXy3avlMLDmYsGJztGL79scGES1f06PInzqS0IXgab8QJqmkK+ck9UjYSj7rxSIL1YZ7XhgycRTiav8i0KimHM1+7j0jCyZNFwNU=,iv:mYpmcPf2CHyOQ2OChM7J8xD4aOF9QLXfb11iUky5FV8=,tag:lIb22Gciu8Ex2RHgHqCeHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
