apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:85Ek0vFq/0YOSgQ/vyFXy/KMb50xRrZJLKwPTiYPVCS/rCuFmDIozA==,iv:gGZ5eVBvE0J7zxiD4tnVxvlRAGmLBLiOfm79sgugn/E=,tag:jnR5g9kqNW/uLEZB4W9+tQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5b0VkVjdncFh3QkI5aDNL
            Sll4VlFhM01BanlpbEdDTHlmN29VR0hOdGpNCkQ3TTBOenhpM0N6K1hDYytZTmpu
            QjVhWnNwYjFBcEVaKzZod3I4OVZwcEkKLS0tIGIwSXlLSnFQUGpvdCs0NHBUNThL
            M0VGdnFQdnI3dXgraXplRVVwcnYxYWsKnNMpIlz8xOCpF9oQpxB3z4EuJowurBAA
            LUC1waOM9eGvRE5QPPt+2Wlnr+GF/5TyO9TyW0nsDGFyQ5P6o/Iqag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T02:33:45Z"
    mac: ENC[AES256_GCM,data:Xk4KlqVngYs5VlAYqNuq2tZWTrY+dYpPTyGPr9Jpo8f+mEkViAO8WEa6HeByEo59ih+zyyisybHYik3p/uJXQpYV57kg/WjH6cogNoJ6w90790rpLJSBAxnYBF0L5dE3RQE9dtgXgzCMn4X98dFDvlr6V5bq1vZnXgtN2ADGRdg=,iv:0oUpY5ETbAy8hyuU7EPNG0Y7YhivWu6ZUetVQ1kXOJg=,tag:HUalZu8IFlBqDzr9t9V6pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
