apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cEsH8dnTLmmys6YnXfSHzuS2rtusIy8ZOjoNNo+Wd8flgPEgtcJ7ag==,iv:SQ+Z+GxOmp2oBCQckJucBNPnimVAeBu2B59Vqa4Kjoc=,tag:uVi/pGACCX0DgiFX7XWbTQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUW1IeDJyMzRicC9WUTZO
            WEd0bTJlU0VZQVhpVGtxYkREOVZWZzdKTndrCmlDUUYxUHNnVkUrRGRYYjFlR2FC
            YjZBc2M2OXVtSitZVnNkQlM4VklUaUUKLS0tIHUxeHV4MVcrQUJFWldjc0JjK0p5
            VlI4bjU4K2tjb285alM5bGxncGgycG8KU80o6+J44pRTLbwBInRjCPOyFq7E3+7v
            SQD8rI7OLfNtbxLPeNwq/FZ4DLjk4J++YjIcuftbZokP8U3pMk+N5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T04:57:28Z"
    mac: ENC[AES256_GCM,data:qZ+LhK5a9aSjo6lus6tf+FkHUfg5FaS4ls2xRuniuxwEObATlVpGaGok2ILPOfUxXoq4ZGK9UT9xpXz9f0hxDJpS9SxOHAkdqD5zIUU3hzRGqlMpvr+BtoDpXhXVdLK1PREaDZ6FG9EB6fRh+JtzmVLubAyaAxHm7IxOhaYjLoM=,iv:5IVPAhPY/5cJZ06EVsfktV0fplJeBonr33lWKWcPhA8=,tag:R4o3utjCavmQPhfexsnJkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
