apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:w/lZKIbu514G19EHw0hnHq0K2XiTkCV9OC7PEzzgk0VuPYsdV17zPQ==,iv:1UPrVsVINK+RjAvQQ6CenJyejuxFGvCY4w8GQkUwX6k=,tag:cSCJs69LKbaQo1HWcbNZLQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RVhqek9MblcwVFc4S1VZ
            TFJzbVlTMWVmSWtHUHNZdlE5dG9FOGduUFZRCjFZV21SRm1sTW04dkNqWThNNE9r
            NnRnOE1nVDVnN3hubWdoOWU1RTVkWGcKLS0tIGNDWkR5Zk9ZQldGYldaWksvNkgx
            OXorNnRGaERKWFhxcXM4Tk5aZkRSZEUKF/IqjiJYIK21mivn179PNmmOQkiZd8E/
            PsJb6iU7B5N5THeR2N9wkHP1tDj1OLIcgGgsEAUQJnQ5MPqko44BOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T09:08:48Z"
    mac: ENC[AES256_GCM,data:jDmVHGZm5Bgs4dYT8XunRBKH7J70ExjOiKa2m2xq5s/Xd55fOJaoFb8gq9Npq65qXfNdSOvQ5xzLi3rCIu+J6KOfXjFgHsZoOadItXP/9Fbg8KQWHoh3bCQ3cBZJIO6BG+MkVrxZXNBXdOo/gO0+UYNFq4VaftvlqtqQCcBJs5o=,iv:5LiZxad7pHjOojZLshZOmVxTe30Bd6Jw2uPkiXhvVoE=,tag:84rY4g0YRvV6y7kXrUe4Yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
