apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6NrIw7L6oPxm1tR7mKhQXnuiVumqLXcDSvDBnNr2sKXLcyojlJHSfw==,iv:CffpGfxMFJ5Q/LcMt/bkLx5o9cnSabSWcPq0CI/epqc=,tag:2/665RMl1qVIpRoAaandVQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXVRZzFhbGZUNk9xVWlj
            K24rZFFhWm92ck9vWDh0TVBYYkdCaTQ1YWhJCjFLSnk3alF1RmxWVGQ1ZXFvYWZl
            Q3Avblk2N01HWW9LQ1U5dDBOK1hINFUKLS0tIFNNRHJxU0RjQ2ZyWFl1dndSL1Rn
            eDNJM1RQeDlCWndaUXZEQ2xocStSVG8Kc6TwW3wcKZgtIaHmuPtA3t22dSLn7OlG
            KAp325tEVNsGyNnG8PkbzhcB79J9Q1DWXVmJfksxxTGD3ID0rsOkMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T11:07:35Z"
    mac: ENC[AES256_GCM,data:uhpxj82k2DEGtUmW2Q1HrUMcjc+xYzkFrROvmEWacTJfSQpYk9CTGv1PnRv78EUZw1obcLBBmYE8ZYyQ0uHZIk/ixt6q7bj1MX9jZqpSxkLxB3Mjuz2AcirXWszAr9nhIpOHVFpCSZL0lQtj1zowNxdl1DQpvUgA7Md0h7BhFZc=,iv:WuVCdMn1rrF8LaAc4sTCb6JmZ1AbxMBfmAoqZgGQiY4=,tag:C1RcOWVlpkH7wzsyQVAkUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
