apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:SfRAIe+Z8RbhwY2zfjjrbcsv7jsNcq5RNU2iXE9tRfGynFWIRwsssA==,iv:+VvhzRry6FJB2VwbE+lxYs8jaFnWfXE80JPcV9Oav4s=,tag:pclSf4a2U2CHhCGD/68LHg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdDQ1TzA3NFdDaGs5TU9W
            OVMvWS9zdVpZbmNRU2ZjY3RZV0FndHREMVZrCjN0T3hZOFNTcnJrMkZZb3dlTUg4
            V3c4UWs2LzJyQndHMG9CNnhqdjJ4MEkKLS0tIGJOZHZ4TkNWRzY4Q0tMemN3K3k2
            aGQ3UDhzcDloQzdRSTFNZ0FyUlZUVEUK17YBWrW7t3qRP6LB4BeS2LulqcYwm+JY
            vyCncduBDDysygIRv59Tsh4/Up2C/+EOAgcNqgUIhkdEhoIfdQE0SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T19:35:01Z"
    mac: ENC[AES256_GCM,data:fE0jSp8j1q7HOlz1/rgylhqRxe0OMrjDLjNt1O5kyzsDd3mhbefdgdKBnMFffYsTC+CflhnaBQitE453CUt0yRpkMahB7nOstRXuRVJe04Nfdh63Wwym32PHuh8K/CIpuPnh1lZqyr+O5oQ487xWRMKEiYc7z2NrUPaU21CVulY=,iv:hyDzXa0tGsPt+5bmyPzGvEQU9+Wg7P5l2ghyLRT0Acw=,tag:PxUtBL7+N3GCn+falAkRiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
