apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:vJhC7ZMcJy6f9q5H9c3FK/yOXl8puZ6h6N8N9fyh7yZfmqhbbI5bHg==,iv:CpvoEAQMOJUy716XQZeiHGGxuBMnWDQJIwTjQOr4cAE=,tag:xB+Qj96vBzYTknshv6O0vQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbDA5M2duWVlvNUdINE1D
            bnJYOHBZeTVuekhIa0Y3VkJFekZrVXJtUEhNCkordGxwVVBSUFNsSXplaWRqZkFM
            RDJRdkpETDFteW9JU2ZrWWpnL3k2anMKLS0tIDgrVDM0MmR2T1BoVjZLODE5UzJ3
            NDk3cXpCNmZid0g2a3pyNDRLcTQwVXcKZ7dj79KN4h/9zTvORB+o7sYBrunbCL1s
            oFslZvlyPl+mo+jFX91JI1UwejwYQsUeXgRPnXLQWB+U0vEYalZ0cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T08:11:41Z"
    mac: ENC[AES256_GCM,data:3Dm1EzXvNiM2WyL4tjOl8RW1V+B9brIVGiVIuwIzlWl3iZ5X8whxIReNSnFF4M7MhkfKQ6PemarnRYebG9CoVIKH5uji1z0ymE5oNhksMJbyHt4oFhsjcwHKt4E1fEze7d4bRbsalAjCoUZZCcvtHgEkFU/soMJZEnlbsF+bEdU=,iv:z/wx/wDRcbEJacHxkzD7AXQuywJIgfDWImQiU+YJ3G4=,tag:Nz9/VDKrKgdpPo4tu3JetA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
