apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:59tyaUsZl8teKdH6kAku7iEPK0HWrNjRW1g9mB8XEitzrsONYkK4vA==,iv:gsCd4CF3LQBEefdTj1/6+yog6Xu5ndqHq1EnZ2hfMpM=,tag:el7lCtsGiBSQ/2xhZillAA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSLzdLb2JpWTZHaXBCZW42
            WUt0dXZ5YThiWW9HTklrdzNhYU44S2Z6SVRvCmhKOGsvL01TeVNtekE1ZjNteFo0
            cmQyNjREN0xZVFc1SElEdWVmYTRqd1UKLS0tIEtRUWVOYlkxRWd2UnBEaUdlMGlG
            VkZGZTM0MUN3ZG8xcnIwM1E1ODFVU2cKWSXsq7xi6eyqJ+ZaImGIDBy/WKQOMF9T
            hU0qWWvWvTbq7FkzYavdAf4otZl5aGF0EUKbOmCX9T20RpvQOj01oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T07:06:06Z"
    mac: ENC[AES256_GCM,data:lqIM82Vbu/kFsEm901WcEOcJINPr8pUK9IPwg+vjGmLMQLR15p0IV30YIuq3nJMYs9BP1Naw7Cb5M2Gh37E6h/zdhNvVEVmVLabXJWkV2hM3jhPMQTULGU6ZHLnrPXuhgybJFsgNTXcC5I22/sLQ4ij6HTOtinX/7WS20L5NNOU=,iv:JfB1g97FXO6N4d11HgR7nBaRAJTnhxV0m+JHFzCA7Lg=,tag:B39Q5HC2nPsCFVO9NXSm0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
