apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:p3C45vGb8jjemwVwLs7M/qmKcCPAy+a53fzmb7e2IeKhk54vGFiSEA==,iv:FbmQnXg8C4grPigQcufvDwisvVCEJmLXaUc39XUPUWI=,tag:s0bH/Y35zm/ZdPK01jG/GA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZGg3MGt5YzRWSjhPRXVQ
            bENkUnVoMGlhaWRXQnVWN3N5VVdiYTd6M2tZClhNNVpJOTV2QmJ2SGlrenRHdDhN
            bXk1UHBISzNvSHlTbi9SNERuaVRhbE0KLS0tIGNkOUhjNmdMeXRsaUM0VVIzVURN
            QUVGWkJPSzJmVjhFdUtSMGp1cDRCaDAKBsDnkGpFdFOz7kTzxWJTxO6iuO+xGb6p
            JbPcsJdhQ6rUDP39d9kwJhQliYCWNhxJdhzvqeMZPO4RdrcxAFFvYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T09:43:54Z"
    mac: ENC[AES256_GCM,data:LZ03WPTrvajTW7HbDjakTNPHbpfvVHSUsB+wWnd9YW/8FiKfNgQ7ICawCghRgd5Gyvf36UOcZJuk3faYw9NhOWFmIqEi1N2vvSsEWc9I1uNWwYF/6UivoqSBQPwz9/NNw+l9FxGoobQjMRl6deGvteFzRiUN7VXaP38KW0Aqqjo=,iv:JkZ9fl8fhG1QBqEpSGK7b71Yg37P1fWOwTiwJSZFiU4=,tag:Ev5wUHViNxzuSF7rVeiXcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
