apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6j11cu6rFR8AVJvLkS5FzwhsJ0zBq3I0RjQrE/7XIl3SaxZDOZTBoQ==,iv:Zv3+b9DFIsrJUVLyYBoxxU8nVKWLem56951WDbGJhRM=,tag:WdXo8RHsJeTuau1dEuIxxg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3N4aTJtZVFYWTFwclQz
            blBtUlFDOXVYMHhRcm1BZ2g0dTg5OVo1Q0E4CkQ5NDdFYXlFWC9hRjM4cy9jeDZP
            YytUUE9zODJBbUp6K1l5RHc1cWdxQjAKLS0tIFh3dkJ0ckdYVUxYb0ZiaUh0WTd5
            Mm5VQWJMNThQUm5mbUxYV044N2JiTEUKRDMwrFkHnljC3/zrA6VeiI7bRmMbdezu
            JYcUqx55EiKo6cDkpgkU2qYG3T8aTpKh5c6YgvFg2Kdk+jIi6ChvcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T09:55:32Z"
    mac: ENC[AES256_GCM,data:EBsZyJf8APTpLbsKSJNGm1pgH2EpsCouh1aPIEhLvOvjzVHPQTEbRGJOmz1SJ1Yjrbsd7Pewz8hTBK9NbRmHxjF28CoOdD5qDPRwmM43DTgoSWUPrfSc+VHsJdl73qME/duGYpOPWL8XFXzOjR5OQr1OCv55sSiQqbreHS/6Sis=,iv:FjCU09M9HPZuuRxXdnmUKdAXlj46xarTa428PblEhCc=,tag:0gVVM6897FGT3XqgBuaEpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
