apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:iVIKduY1kz+iAsEkik7tzN+JoPuOscxQ4kiueNqSDSH484OAUV/55w==,iv:JOlcH2E1P/jLvlrbgb4DvahzwkNnxYp6zrRzOI6ma4g=,tag:tfWHbghYe0nX2yFmmfOBRw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzQydjdSZTlldm9JYWxa
            azg1ZU9SbUlmOUVHMGZGQythSXpkQzBzNHhFCitGWDRJWVRGVk01NjZyNUs5K1p1
            TC83M0RWNG52RGNXdlN1cmt6ZERHeFUKLS0tIFg3RFlCanVYSjNvZDVjdlR5WDZL
            dC9CUXBJRTV5ZDZ4NEoxL2xsaUc5UjgKlicMUM3VUkFJVuQC4mOWyRkgbLlyzSmq
            zHPWKuvu6gXm9W5wQnERE6Y8sdT0onbAn/a+IsS6ou8+SqYXN5jspg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:25:19Z"
    mac: ENC[AES256_GCM,data:H7cobzizqyHWwhQwepDIOi6o/6tk54DAa0XqWwnhokxwzp55iyjmnARX0aGZ2bSWZXSJhM9eztuTsyzWW4b6xYdVThS551G3/f+ii1wo/ZPHziYR4CIWfqvjgTZoz27XUsknc9D6QmR1xHFh1eCUbBr3ldkLg/oYImJujVNY+3c=,iv:SJ4B0j1J2m2UlVWR2Qbp7jvyTTfE0o01GBUbzduQwX0=,tag:fqgTLDeqw/vzf2iUGXNx2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
