apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+Z/Pz0hhHAnAztHsX3xfF+8jW7Oixy6PtT8ZzalPbX4q7DlqFTCO7w==,iv:XdtA+8GPsi7tvisiT/1spyTrnkmhYn4UJPpPUPOnoIs=,tag:Cr7IZrWWiqgWgj0HVQEFJg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WEppNXBtZmpoY1pwampF
            YWFnU3ZyOVVNS1BOR0kraW9GR2pHYW9XRmhZCjR0NzI1RzhZM2t5cGYxaCtBakpJ
            M0I4WUlDemVsbFFOczRJdXlhRnlIbTQKLS0tIDJnQ3NKYWNJdmZHeTYzRGE0YStE
            Rks4TXpqTXRBVDhIclNXb1hXK3RwTmcKVCr57D9FrtrpU75cbsRrQdwaq2vjqAa3
            UFadfnZx5f4tSUjm166ejSSb6PhafGDa9xdDhILlOdPXvfR4LdA1yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T10:31:21Z"
    mac: ENC[AES256_GCM,data:TRBDcxpIzm0jr+ab40IuLHBBUJH8aEuvgRPdd178uO+9LWw3Yd9U8p2j6JQeNKQr/KSTdeokSjGofIoShDkmlhclP8K/jx1T9/03VIzyicOV1fa2WGPGgmqw19t0LWAbnRmHhpXqtL16H0zELKs6vcDCglxtElnC7oZ6c4HR1cY=,iv:HDmSB/ojlgSS0azmxulDJdXN1B4D1y9Q3gk5mh12fY0=,tag:7qkS0bl0E30D1n09FnUQOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
