apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7f/J1HKCEk4h8Q5i5zEuFFC+je3maHbciQxOWi30UMZukeSFsqdKiw==,iv:Ry3Qk1dGkMz7Tokd5GoMvejJutPxN18CXpmGsiSyzxM=,tag:+xReLgBzJ5UC80Ep99iHkw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjc2ZXajI2N3o1SEdFcUxB
            em12K21UbEk5TG8yRHR1em5EVU9nVk52bnpZCjhCaGppYnBEMzh0UUEyc292V3JL
            WGIrTTUyNWdLMjFHZEo3djBQbGlWblUKLS0tIGxjdllOK0QyQk5UOTFKWG1rSWNt
            L3FkYTZwajZxczJHMzlJL2FWNU4rVTgK4Xk/vZkjZM0MqE6hFWIbliDhyoaVzylR
            pIuXH8tq5u9SWMAWBtNP2ynm0ExGlzqy5u9qrhk3Q2VnRq1dBl2thw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T07:14:52Z"
    mac: ENC[AES256_GCM,data:J8urzVFNN4KccgnZVL5jJo1wSr2rk7CWp3lKSjZSvp7Jj2ERXVgY1GhMNjqfXxGSiIZkYBuOCVXiQUDIMbFg40R+yQ/FyvLlevvEtF2J/i+8Cr/Lx2ax2Um2HjF1/0MVoaeOMC/dDxez23DXaIdP7OzygVz7TBEoN60YqlycejY=,iv:Qwr4J2CopHjUDJiLvxwst3GaCYnBPZvD8KwKLsvin6Q=,tag:xNbIkTPsHUH4NWxVZ7vKwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
