apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:L8tQcLFSrY65gliGz4vyyoinVs1kE+LGLj3Ke3Q+Yf0xPye73fb9Kg==,iv:Up1tUKvPxZ7xUDnh9Y/LTuh2yy15L12ZguxB61Rsmwc=,tag:sqgn6dDvSXPSBmeXEgaNaA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSlZXWGRlQjJ2UHV0TDZJ
            YzFqSC9SSHJ0Zm52elhPU2xMZjUyOFJhYlJVCmtiUFlwZEFOL2syYWtmWmNMU1Mr
            UUM4ZCtRbXRKdUVOajV4NkpiOWxvK1UKLS0tIHY4b3BIb2NSWWlHMTF4Zko4ZVUr
            ckxNK0l0Tk9FWGZZODlPUktuNDNWQncKJS8lEzqtiYQhtl9o2YMNNENUawF/qWEc
            ukAFbizIn/RWCTU5sTWVExCW4/IcGvRZMVRa4egyUOz7Go/FrXkyrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T08:43:09Z"
    mac: ENC[AES256_GCM,data:2wkmH3h/1QZ+q6vBzMyaT7j2Tfw/SN3ySs1P4mT9ZleSUugepQ9aOrHCNaY3Jm2N59p3yhD6zAuucnQ8yGtt3sKxHleH3BKd2SYNC8RgMZYjGmbyaWWo1JaZmUlGCSDiLZFfMNq679Y0d7itCcVKJVzMblqZR8TlocbNK01/Qhk=,iv:3tWf82NH4WFQE4wWGXIaBfxGSiEkrGL/a9/Z+4PHrqo=,tag:CrjDMfFMBrJwRgmy/gmfJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
