apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:MOjlDo7Uz79ZTp6foNn0vXovfL2uDJbrSZQIa1bA8lyzEtdJiOKmsw==,iv:6i94gZjQP5pgeSb8fPQbz2/jSV1CpKXVYQdKH78YTRo=,tag:HkF0Zwx9XTbnYcMrqlTxgA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZUJXWTdaZGo5Ri91eWpm
            TXE4dnc0cUZ3b2ZkbUFFLzBsZ1lWVWZVR21zCjhNSC8wYlBudFozbzJ4RzNqb2Zx
            MkhqdzNwdnlMMlJqR0VJZTdzRnZiV2sKLS0tIFpnTC9NU0VJT09oUmdWUXhZbThW
            eE1QVU5CRDdLYW9NdE9yZDBuR20ycUEKoaR0NPCb2cyiJWqDV4sStXyn6DcKW1s7
            CerPJEng39x3VFl3OwF4sT/zQ+ZO3reLFY3PkH7SbcWH0AMm4Ez13w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T10:03:01Z"
    mac: ENC[AES256_GCM,data:L6SABjzs4Px3MXZHlvOTS1nri6CNPzvi3N1tU41VjY1JHjG1hWnNELhzUt6ystb19P1xi/Fumr5QZsztwDLG3Jo1j/y1Hmob0blqN54rcgJ34dyRd30KpDmhIWBy7VymectQX788tgdYXtiHznJNDOE3PQ2Uz0569JQM3sQc4CI=,iv:MFnsvJBE7rjJ5jESPnckHuAe42+MwxEr84iHQ3bKtNI=,tag:X+X9b5Kqbtvu3tAqZKm70A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
