apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:E68vj7esBWF9jjKIwxYGYINEc/KhQ/AyW5hid24laMN5bt44EqCuoQ==,iv:8IoQWAfwZzmraRzGbhtL5ms8mgcFKS42kBO5AquZco4=,tag:lHvG7HwxjudrGZOWVDRKvQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcXY3dTZ3THN3NkFnYWxs
            dnZQblljYjdrNnhkcmg5WHhzajZid21rSkRBCnJHZHRveEV0Y0wyT1ZWTFFXemJa
            RWNDeWtJbzNtMldudDVNbnVNeDNDZUEKLS0tIDYyRjRiRWlsQXNoRHBFQ3BoTnBQ
            TThvRDlnQkNzUnFTdDlvVUtWdFB5NWcKCKow8yFRjwLwCAO+J70WnMTP1i//+h1q
            aCFIn7ThyygO8cuw9LdqS8T9D8wPgR5H+KeMD8zGR3N3L5oQmo4oxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T09:59:49Z"
    mac: ENC[AES256_GCM,data:bi6dMEjL9bLZmQImU07mCs6NQamKsdcScQNu+feR6gzeYNi8TVomEokBB2JmZNNZLGmrw22rVptx0yAS40oEIPQYI27Z8avtKa0WDkTxLOSNrrCEtfjHimawMFvlr37jdg0jq1e1SHQnsXzi6TSe3nUble0okE46G57Nj47zrP0=,iv:9RjVh9DqvhdkNBQBBCAKULA8QiOb8c4EIoOYPEhEzB0=,tag:OKtos5stMfqJ/+mYMnOQLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
