apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:452WLJSQB8YrNX9CV0QSKaxRlPNUAueBil7yqglF1n3zVyb+IrvUog==,iv:qP7JED9xdsd4O/3vq8iuOs0jC/XyOScME1otZ+4zOzA=,tag:FDUIwaUNrbOeIuD/rqWV4A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZmY5SUZ1TnhlbVYzZUo3
            dUJSSnJROExuM2k0SWxlTDZDZnpVRDdQS0R3CmZOZE13NElnUWE0OU1WcmxsbkxQ
            eTVVK0hjMmZXNy9tUW45Ky9Ea21XWXcKLS0tIG1UdGFCQ2xLWG5oTDIvOGdlMmlp
            d05ocVZPMU1ucjJldEw2U2JMT0JYeU0KnO0ADHY55VZCW4P6r9vD5IUN7qMTWKVT
            N0QlN7SYPl2F/3sOT6RaOPUruoupz7yQ+qKd37e5hfsGk7q+/qJgmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T07:48:07Z"
    mac: ENC[AES256_GCM,data:5E9Ou1UIkAl6b9dnuyNk0xV9EjtzFgHnpENGTQmdHHMpmmmtt4vjVSqB8ftPg3pb3HYiP5PvhWZc1r1OmHGdcICDL8RsBTt4H3jZUXq7abvPln0aWh1YFRd/nSKmOrsYqyrTkeJtjIfbZeHlhq7enIBkIh0Jiyea9Wyg5o9e5nk=,iv:LhgzHc8LKLDCKg/SddvRQ/CYD/X/kaytD872ehrAgW4=,tag:37Q1NuwBJBQzSpKAoWJ3mA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
