apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:S1F5cikN3QJ5yY6wXdTdjQhAMepdkH+y6U4tEh1xd3g5+R6sP0iyTg==,iv:Y45A2c7wyhy95LETSLdLaaVLN5XCSvblIo+rBuiRnq4=,tag:XDHByz0YOjm7DA+NytUuhA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySXA3Um1IdmVRVGZsSDND
            U3YzcitUd1dVT29KRU5mV1ZWRlhRamdBcURrCmd2OU5UTjRPaytheGoveDFDamR1
            UUpKM1Y1dzRITVhwZDFZUzFyYTAvOXcKLS0tIHdwQVQyVks2QWVzZGZrM25qakZE
            NnJpUHgzY2NIQ2NITXJuZG9pM04rUGcKNkYKGKvZNxIg/Sa2buMtqzAbOg/5KEkE
            dUAh+fQGiKlcnfsmFH5cZF1TM8T6nd2hsbaCDqKIlA1Cswpc+i8t+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:57:46Z"
    mac: ENC[AES256_GCM,data:8z0c7BBmPfjK+ZYT5eq6XptIRGTR4LmgPelgRKA2VZTz5wHX1ZPUq/qRk+W0MmZI2CAuWS19plRAYIIgZeYDP9BJKBdXYOSW7Iu6UWklvYe9Gq4COXMV0ZE6LeeMm4HBC3ZDViXrMr94ZytbT/+BS5nColwFWP/aKnQ3bvc2d2E=,iv:Sn9AeMRDen0d7Pj7wmZ44Xf+1jM+xZpQ/cQbjbiRLAU=,tag:d0xWvQDRIktNeclVO5LJAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
