apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:KIjAS4NRrOn5UUiBWZg6dbJOnTEti2IdHJUXHvGycyQRYP6KO/aSHg==,iv:H0Pe1qRBR8Cgly2EK3S8C0gZWeR8h14JUpQt81+5zSo=,tag:gxYVZKoVip08OuxkhQ12Mg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlK0pTK3g2clBJQUV5a3J5
            Rkw0RUZHSXVta014c2xGM29sMnBUY2hJcUdrCk9zZWtXY3NlT1RWUHBST0tLdStN
            VWt2Nk52RkNJNCtWeHdRdDYvYlVTN0EKLS0tIC9UK3p2bjQ4RjU3UXVldDJ0UFZP
            bEU1aUREcTZzV3VMNXRxV3JscTUzQVUKfgcDMVyrmDAr4BbDZFBUVRi5B+FgC3CO
            ES+JKAbWXRoJhM+rlkNf0CVYt78vei2SwxVR1VbAWmf8o8Gh4kJQ6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T08:31:15Z"
    mac: ENC[AES256_GCM,data:oNOfavE6oWmF/4DmtBwd7Wf103j8gcvtQm2WhNv8O0iplJi+p5SzKfQ5CQx1huMOhRHrkcirJo2075V9yul9HuOLA1mi8vHBsHBRk5jLiTqaGs1LMnVq2LVi7Cvwhw7FhgZnolus2BUPDMX7pD9kYx3jnv54CyMKCWgjl9B4WF0=,iv:IH1UPuuCFxlznkMg71fnpsO0v6zMzuzIs/72t0yN1iM=,tag:YrCkqhRKDZeLfP3ClIs5Vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
