apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:s1zuQ35Yc54J7b+fxEfIYtFRlNrZl1J0iP/i4RMt0nzUEhVV5U+4kQ==,iv:luuK7INac+hsNuk/aehffH2SryBvIyHaSdQ7hmaRsrc=,tag:hSmACqdJe7lv4mHdAg27pw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMk9CTkczd202YmdUYU0y
            dlQ3Z05mWjcyS3dKK0dsdnd4dUhRRjByY1ZjCmRUSE05dTFNdmxISlppLzNjSUVE
            VXJVanlHQU5tUFNVNzBVWmdlOU1NNDgKLS0tIEZtQWw4TGNmeVhWNzRuSmlMWUU4
            ckI2bEc4TndpTXZnTStQd2lscWJCU1UK2oq5fYBv/IXNDPcJQjnV2VGQoest9qj9
            8Owp/2Z0i5odl00i34opiAFA49ldyJrvkdj2e9Bc69wOSqebIJAtyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T10:07:08Z"
    mac: ENC[AES256_GCM,data:r3xIoKuWdRdLsVqptyPbAxoyFZAIKsYA3gMpUW0AoAuFb+YR5Mo5jasXEIgSCHxw0yWnFdh7MeBgG8T2LJ8gEpjsXslVaxZtcseZxqdw0X+2waalzUUDCPlMS0enSS++S6MxhuJxKlKjLQDqASVDiR6POSRF2kmzR89WN873J5M=,iv:nignz7QMzIqjh5CLkWwKHqNsNPTgIL05ZXB2Cvekdr4=,tag:823O7X9OAyyM/XAviZBPlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
