apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:zDjiprUfr746ONHJnkyHStUtYEuDAdlQUp3mgseVEDqEDZkKECwICw==,iv:wHST65nOLwJjHdoA2ZPIXsariQ0RizBohegC5GbJMZw=,tag:+08GWMwOzJx7VdzKuX00uw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OGd0UUJyT3Y1QXhxZmxV
            VGlScjFBR29ndGxabUU2aCtOeE5qT3A4eFhzCnFvUHRabnFETlF4SVVjaDgyLzFP
            TXp0Y0ZmaTVjMkpqWm5YcldmNnh3a00KLS0tIG5PMklJcGwvOVB4ZUFlOUJldjVJ
            UFVrcE9FelQ3QkppMGdaeVl5SFRCUHcKMS4AJ+seEiS/N5hAy8cb7DtUG7yJ0Li1
            24a3kNYPWSVoykPaqr9S9i6dS3exSqhFjZIPhrfAdfbWxZs/n+bzOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T07:11:23Z"
    mac: ENC[AES256_GCM,data:0VR4s4lwZQDnm5YiOkgcDth2VIsXpuMgO+Pl46Re/7w6UtDLxuaG4RXuHJeCiMT7SFBcFQ4LatC1YBIZFFDv1jLr8Xe8XaT790WeRfaC0horvhQaQM1DpAHvertoQh/o1jgwieWHHnvQ+ROcUHLNpwRFqJooNbInL1fh/CjD7GM=,iv:kZQj5c3qBM1bqyd24o+lA2EnvHbFtMnuwq4w5UT9gnU=,tag:qVr31rZ5tDVeCCkX3aoKWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
