apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+aN4szCJI5xboYEkt980FcvaHK/TUQtlmJk2NedD1h9ovsw+KqNdgA==,iv:u0LMoeYyrZjxSgcSl/OcztWgUnu0P+V9WI5NR9hZL98=,tag:ccV+X42zRi5MT8WciflHaQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMlhPMHUrakp1RGNNSDJa
            MVFLZG4wb0VOVEVYMmJVUThrSnJMcUZLMXpjCi9vdzVjRlAzeGRPWUNzYUwxc3Bn
            TlV3Sk9DMkRNOHJGY3NFbWlZN09xdWMKLS0tIEFlNVBQWEtPNTNOMUJkVXdOSmw1
            NkhLVXBJdnJQZ0kvVTNzOWhMM28wd0kKwvicuM7Zs6vrdAGDRyD+hIL/JDX4lVz1
            od2ZhE8ZIMPnxbQxmJNheDybvwph7CLX6GO5iQ+CCq9hs3QTQck90Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T09:06:56Z"
    mac: ENC[AES256_GCM,data:RUzk0nLGF8BO/cCHOEwasbPprcH/lapVNPSGR/SYxWg+VVR9opmXl1jhSSZ7bfTSp6YoJOq1agYyz+PwS75jg8IgEYDRJIfYcuDzee9YM0RqDtmmge61yJT/azEeFBQa/Xb1GmikeYBlAyz8Mnd5eg6U/beGbWr0uSOTYQTDEzM=,iv:oH1UTGcRzzgRryXpbGCdM7Wm6A5lG7nfXg77QqWbdXQ=,tag:IfpVD+/fo5gc7OBqKqIf+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
