apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tzBRqkh4DZv0pUWqutZ5Jxe0VpO+6ULHHrmJw9ipEqWYPrrNXKjFGQ==,iv:UE9S6oL2IIX5Hr6gPDFX2dbubu/2ArXsXulTfXWZhn4=,tag:JHDndkUdhZIdLPmq3z9rZg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtY3hWQnhSNXZySzFLSngz
            SHJnY1RwVTgzdmZGODJsWWRjaHNRa2QvdkVnClRRUVpWVGEyZUQvU1U1MW5JNXM1
            Uml4S05jZXpPQ09ER1k3S3BNaG9KaGcKLS0tIDlKODR3RThpcnZoK21lUm53Mm9P
            S01LVkFwQ2FyM3lHdTRVMmpQZkl3c3MKIxJX5LWsQ8AtGAyVpZvw3o2TSLnsgDdc
            T/G9RkfmwzJ9NiUnkTtUvkrLXZSkwAr/3zxPjozV4cjB5r2vCsQIVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T09:36:58Z"
    mac: ENC[AES256_GCM,data:nOk9cg1k3gSRXTcvygd++5hlwkU2CwNPmDMo/ddnaE+WmvfYmDtNMX8aHOeRQbE0PW+rI0JVzAo4KOTfTeYd/MlgrjoT5rQu7OEXHRitgK7wZ+RQE5/LiKdcI0mJtJ+o+68FZeI+NSXm6Qgs6FyfWTBSrV4UCJQb6PofTdeteMI=,iv:tf972lfxQx+b6o+zt9gLM1/ZOVmP1KV/XgaGK2dMr6w=,tag:Dq5rTnXzQC7GDuOClxv46Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
