apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Gmj2PdBVrg592DAvz9rVRrzxqFN/8IeiIodt+idZADrnX4Cb1XUUDA==,iv:n4eETjfedg7QzeJZMdeITaJ0PnLivRL/fe4gB6XIQ8I=,tag:VQRax6whA9Z6QK0nMtR4EA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVzNEbk1mVXY0TG96TG5P
            R2szYkp5LytUbTdYRXZQd29OZStNdjZDc0JzCk5PcWgrVjRwMVFoanYzZm1uak9X
            WklnMHdHa3NSZEllTXhBUGhkenV6ZkkKLS0tIE4rTEhqd1V2SnZXMlFxeUVOOUN0
            QzhVQVlVT2VyNEFzRko5enJhNWZzQTAKYB99YuTmVQrN/w+UWjKMB2+2GVLlIdwA
            2EABTYB+tHMD61b4dnqANW0UHI+WeNbMdNa8yMfduehRX7XYhf8pWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T11:06:09Z"
    mac: ENC[AES256_GCM,data:531mRc+M7QYOPaCtBPjlEwTEMXbEFw26q14v/WxsX1G3OhrYMuqSkvjO3heEXq5xGoBovzOZkx2L/8OgmLcjm5rs3rAzb87YAnHlHd6BZkQ84O9SVELeg74Y7edTMVIRJwUgGUfMAiwn8LHx1wadXhBJsAenBItlzaUVGQuVxnY=,iv:aWm0k7epVsii9gv+9ycB4p4XxuP9ulgHWjSuwomna6M=,tag:fxTx/dBs7hDZwZzq+rfsGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
