apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:psivz0igSzDfAtfK4UAmagfpzS4ZKEeyAed2+tLW9AZgmC3+WPRCJA==,iv:+ub8LPSQalcM6Hw/+xq91DwAcTTHWAVY5VxJe+SNgQs=,tag:p4SdeRrf6QSp/a9Jk2l53w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbThhKzVpbnNTNDZleFJH
            aU1VbjdTVzZEUm1pb1grOVlIWUhkSkRDQ0JFCnFSczZQVUExa0tOa24vYTJpQXpL
            MXp3MjV6N0xWSlJUenFZSnJ6dEIrZGcKLS0tIEs1dnBOYTkzeENSOWhQZlRkRmx1
            SHFxRXJHR1NxNlZ0VkZvTU91eDJMQ3cK/JJRT2M2aIeTt7yor9jQ5xUEy3A6raRh
            DtaOIeZvY+FAs/os8lgoTT6o2MWxBdZTX92eOSBmlWhdS+z+m6p8LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T09:17:46Z"
    mac: ENC[AES256_GCM,data:k0scWfziPyN/4P2z5CeWRXxZ4LOm5PW7Y0La9x4jJ88w/PeT8OT0L5n8bF5C7UmOW53UpTk9O6m6kA4VGoiByibbX+UxX0dVfTpBQsAC0lKIloWLDz6TpG4PVZRP6hPgDVrFX1B2JtH1lXWVQdR6OkUyAvf7Drhm7QkvP54HUAM=,iv:NCCt1MyPU0+oJp978pnT1f4O59XnSMYvbYdsYY75R5Y=,tag:4LmIWAg+UPnTIAcAYx8sKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
