apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6Pnj3EKUe2nlEeNKXslPsc8hh+1rGjvQ/QRbjgt1dog3nQiciY8BsA==,iv:cEWFrSoiD6Y9vMVmg2s5/BniyJ94OcF6IOHNu/PAVXo=,tag:KIfkXt0anRqoi7O+nHf2Ww==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WDcvbzd0WjNab3YvZElH
            OFhFWTNLTkhhZG1EQ0JMNFNpVXc2aXVXSWdrCkl6TXB4TVgwV1A0Y1dZMm92Q3BX
            ekQ1NGFNellRaklnOHlWNkxWK21NdEUKLS0tIFJ0NjdpYWtzaXgxQ0I0ZTg1N1pT
            dk1pSW1rcEE3UlVNN1V0YUZzNjd2MTgKMSuX/c3eiPU36AWS5cxYzMTzhVUiu85y
            SqNk0D9/jVIBrbj5KHB8egB4D220SF+nlfaAbaK3DykPlb45DFk9ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T10:24:49Z"
    mac: ENC[AES256_GCM,data:jZTRW4x+PeUXPeTaKHb3O56dPj9POMYg1jVwFWgGfOzmsobGEyASFPFZ+MnAm+NaPYAH9fGMqV4OCbmybvmXvR6ePTX/fQxyFKVyEZpWYKc2vf5pxgGJgCcWCsBDe247zhiwB5QDf6E2VVdv79PlwmsxFG7/tdtJBox3GTGH9Qw=,iv:1sn2VcH4YmM0M0RSgVF7qJeNiUr19fMEQ3mileCw4jY=,tag:qGRZa7ZDdun5TyFFAPLkXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
