apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+Yoj63NqN8I3KQ1u84PHh3fWy+4DN0BCneryVM/HJJSSDejxRQYYKQ==,iv:xsts6ekqWlDnBV2MnNEWO7iWD6ZdGWHDgcHdAyJ/6hc=,tag:uCAH8u4IiXCCiChioBL7ig==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaG51ZU9mN0NYbW5nZGVa
            dSs1djAweWJpaFVsNWRzWmptTVVXeVNBUUNZCnAzdGVIamlGVTlQWlZqcmZXNG1X
            QnFkQmpJU3ZYYVRFWEY2aUx6R3lBRWsKLS0tICt6SHAwYS80Z0tvTUhoeG1XQW1Y
            aHEyUzMraGpWcE1ab0xTTzAxZVBUV00KIe7WHxxk8DPxb3XQcsxaSZBRaS3y5BoF
            K60Hwqzd0pE1JlZZBq++Rnq9ZM89HdE1MxbO6yFd1tzkTAltEhph7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T10:30:19Z"
    mac: ENC[AES256_GCM,data:yTbhiCNgNIE+u+BLmXRpEEq1l4I4HiF6qz7UWKNDlb2kHP89NPtw4gVn7YuwKGcHdRj4L7KIoVNzcRODSt/EIw7lRKOj5UwEmtuIGoMBo7fdUHQNXsdOwWjjvU7dawef4HgVXUOi40w7hgopw0fSJXJU0nc/vD1C6UUQ3hCT34Y=,iv:dpchQktiBZe3xIYtzjoGT4SAL/fb32tK3MU57JCkKjs=,tag:gpIBKRZboXFXpjKE3yRuMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
