apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:SWmiCyQJjgVd6GSixI5yRi9YRsQcj3dz/jX/yVGQNoUQPYvDJseDEA==,iv:EbctrI1wsLHXj+/y8HP5FWeAiWOozJZl8Tfwr20fn3I=,tag:7FWNiOYRLhNX/yLe1fgLkA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SnlkNWhQb1N4czIwR2VQ
            Y1l0NzhKVlVYSkFmMkwwZitERWtncEZMNWhzCm9abVExRldneFYzNjVBcERLc21k
            d3VyOGlramNsdkZwNHkvWGJGS0QvbTAKLS0tIEtsUHFzMUEvQU05QUpwTGR3TWdl
            eVpGN1h5NHlwc25kZ0k4U1NyOGx5dncKJtWz+upHyuSjWfKNb2bZWvaW9GhPO29T
            yGQXZ4w2Lqik6eJQx6MvtkfyPIA+MVG0/34ddVWIfGubGpcPGY9vmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T09:19:03Z"
    mac: ENC[AES256_GCM,data:w8V6nU8Ov4OjNQIng2QFg/f8kxY2JaP2qx2LsxvE7suXxvkkriK/c45NnIhCmDe5AeDrLe9+PbUdpZ5Jucng8CZra/OcypX33Q354xzM9aQqlsg1ewj8Run0BMW6eyrY8h5hwD1fcR0UENxcQTHkuj9Hi0iTuetkjUYd8nBiT50=,iv:xgJ+v1DkVHl547c+xEM7n2fAFmQYlA9TSomxqhcPsdo=,tag:8AJfwfkhiStwJcf2Doj7xQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
