apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:YWCCbNR3qtCHpIceqPZacK9+YpmWBDfzKk7IgfJlE5tMq2jQLAqxXw==,iv:6CXSCcGLBnLfHmad9OStPL0ILUyoJhGDGS3Jy8r3V2k=,tag:IizTbnUm5eROvCE0pqM8yw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUGVGVktLRWRCTnIzMkw2
            a3l5OTZkZTNibnpia05DcjFlRFlaclBDZlNvCnZYSm1DQ3RtM3ZINnN0WGdDMVFp
            MjYrajN3bE5BdHV1YkdtbUcxSmdtTjgKLS0tIHFlNkd2dnQycmFzQjFHWmRMVkh4
            SHpWM2lIeGgwUWJkZDJPb0VYa2ttWXMKj0yPQE6w773pL/kHaAunoGQ/jnR2pHJC
            7c3fkLcn5E9yuOJaJqLqa9dZmdV4WDIyyf33QCXEFULLgGDBsbknsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T09:30:24Z"
    mac: ENC[AES256_GCM,data:XXJCX1KDN5m7BmSsnENrKCOwdbDJqEg1u1kBC0QXDza6g9YBvxanMZntZrKbXATeODGdqhAet7Y7SIHVLCpl5DckETRlEJ116hXBXCjiynmZCiGc9z9rX8Ci2f2o+2HU/ZpIb7fcZ3FRGXRTUkavz2lAJ0zQljQu3XzIW6va40Y=,iv:7nceRTqjUVY0Rzpt+jxHvIL+0Kv7qyblA0yqcREp9lo=,tag:DK18vdt1H2u89UDSU2m+HQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
