apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:T8LUIf140JhC6okqIDmzDGEGR/BLjSAp5CVY0lp8d/0fnYNysY87Lw==,iv:GW2AfUbvw4HSNsoSG6zPml4wm4t8Ek6vQluFBB4ho6Y=,tag:T9WPOf+VB7vgPcgvPxt6sw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOW1kdEVia0U4d1Yxb3Zt
            di8xK242bEtHWFlrcm5wVWZQSXo2NjkrcnhBClROVnZGSnVjUXk1WlRVNUI5c3Vo
            RWFQZFpNTmYxazBwWkRWRldkVnBUSTgKLS0tIHRTSW96QTBwcDJaMXdmcDBpd1cr
            d3JVWVFRNy9EOTRaOU9uTFZ5aHdtNTAKhze4xLMJcjg6YY6mwTapWaMWc0MHOWaX
            Et3psuz3k92pVUArASBeUz4W0RKxOo37dS/TYyzUzlDpH/5LWdMoxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T09:25:22Z"
    mac: ENC[AES256_GCM,data:6i9+zESUjmBELMy8PwRhViHdHa7EDiseOPg990ERCDuuLHpnpvHnSB+PSIQQL2wJNAhYHEnzOhH2mRLeEd1XQ7y7f42jGRREHN/6/SvgJwPu7bLeM9ishZ1OUHOkyzoIi/CLNoTa5AsS5kzowX2FoQIWtXfb6J1s4KqhdSen3oM=,iv:JnE6hb/W7wr8ylrg3B3b4k4sFSejLxyJq0t1abgSsis=,tag:74QRgqXy1VYTtrKuD7KIQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
