apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZEqLZmWGju22QNhGOD3WLBaGd1+/9ZR6vmFjLe/IeXLILPrGy9hseQ==,iv:4vDnYrf2oGjcB+Q40GmE7LKc7Oa2ExBTC5IR0L4ZrJU=,tag:JC8016KfXAWwz0lRuhTllQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVDdqdjZiYSs1dTVTMkgr
            MWdDdGs5aUhpZzl4TWF0TXNQQTRyVVFwTnpvCmt2VE9qWVMvaEF6R21vb2tjTzVP
            VVpKSDlVUm1KRlp4Z1dTVldmSkluZm8KLS0tIEdPWTc5ektETnFKcFA4cDNLbUVW
            WFprOVBUZWtpY3VoS3VsYjdJa3pwY0UKzVgzPYKvU2tEZ1ho6DxCKVo5cxDxSmPY
            HJgGLKK/692zQXUNMcfEe127DeV/bawuRLBfp5xbY3ynqKUj/kcYLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T08:54:46Z"
    mac: ENC[AES256_GCM,data:iaWWDHRVTgbe1eRzLAkJuwXLF0Y2TNYcGEJr0dREX0Trg07pWytjwft/FjlQmp+sZ/fR4b1LFNkNdUwlwLlbdDqFy+wnrePCNhROF8Z92R/S6ACQfunBHh7c1Bj83DwlL+uDEOCVx+D9DZR7DPIAS67v2KeGs8z0jWRavr9hTiM=,iv:oK1B6reLPIIax2f8NfG6VIpOE1iBrX4LtC9HuNFxpVU=,tag:Lq5q6lfzAmAreu2//iFPuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
