apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:l9ibWq2k9o5iWDI1bnRBqxlJ3v6qGlVzHFtgfyT7+30MYcXrD1+uCw==,iv:iChaJBg6LviKggyabqUhxVNvJwr7Y73s7Ga/Wi7Ofws=,tag:9uogxOAI1RWVoNaqEulXXQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOUl5VWc2Si8vS3BsblRE
            RGQzbldrWjh1cTh3RXBDb1pFWTJTMlhVaVFBCmF4MUFzRk82YmJJSGJ4dk9QVkFU
            dXZlZDBoMzhubU1iNjYvdVdCNUlDRW8KLS0tIEhVcGRLc1dET29uQnFFZ1pKZ0JB
            a3BYWmh2VEVSbVJhTHAyYUgvc3dFcjQKvsbSlS4JSAQWT0aqJlTIK2ejjPTW3Q0j
            uildZBuTE9rkfCo2hK3LGwYy+e6vhi+VhC+vDBdu/iTB8c8+PLTJXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T08:36:25Z"
    mac: ENC[AES256_GCM,data:sBmeg3dgha6AQy4xZKokrksemi36oLv8R1p/VRG1D9aXPgWX5ppWHse7vPJf5MlqZYXiiiWJ3uuDzJCI4MLbJZ6IhOqY766DNsB9gw0tenqI04r1k4M5thCVNXFuD24HHCoFyKNlgZErMTfWk8Bj/5l76N8Tob1piDVOl9M1AXw=,iv:pApLfbXkcd2EL63el9Qr/sPayN+NjunYeL8YI5Cf/9w=,tag:hrgplCYgxJ6mlSnckpCQjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
