apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+RHCG3gPXCUs6aCV0MAiTwoqLCYKuZE3vCVvLzhA0ZDgRldo5da/SQ==,iv:kmWe0BlDI5OTMRDK1fH8FF4kvcJGn3qxnBfPdjtR6h0=,tag:hWPtafrT/XzkTM4M3Pu+Jw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL0hjY2pNWVRGcThPdnlp
            aExkMHVqZnJMaWZyOU1hTWlyeFR2T2VXQlJBCjdQQlFaaEdEdEpHY2JGRWFUYkU4
            Zk5vMk4wMm1WRnJxb0ZMRVV3VUJzRmsKLS0tIG00K3VTRDdVVW84bFRCdFNuejhu
            cFV3ZWZHaXZSNW5SNEl4OXArNGQyZXcKRvVlvIFopZLfX7LOBgOiFB1sIN/2hdBv
            1/7rD8wRBO4EkPuV8jZg4nGzbD6c85nmEUXK/ClYSrYOtUAJl+aOKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T19:51:34Z"
    mac: ENC[AES256_GCM,data:oq6X4DPuqnOlU1tpGklm1feI1kjOQxB+74Yq2hj8Xn/4dKjBqwMLuLRDSuGyynAG/fdUMZ1wi9BKlg49P4S/4Cuu00wQ2tLRDu2BgDnMKp1XE6oHatTE9UyJ7wp3BNy3oNf0yBU/0D99qfguhWGNi8Wzxz3vDSQyG2eD1EztX7Q=,iv:qJhY44R/H+vQLNKwsB8dMFi+Tm7LlVwtd/w6C1tbicI=,tag:Eu3r+6/RuHW8B20x3SSFjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
