apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eYfvLRffvgB3IluZC2o0bAMGGpGpSxm+rPmlT/h0h+MZLfDiMS3ptg==,iv:V35YN/QQM34dC3SfrSPFoCgMupjrbLqqpIa+xGPvn28=,tag:T8AXc8P8sxYCI4TotQCUXQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWVlQeTh1dVdFVk5MWDhF
            YUJCQzM0a2VCbEJjQzRqcWZXT0ZjQUZ1Y21vCkdFSTFxZkxWRjI3bFE0MVgySW0v
            VHNHZ1piYjVDbEFNRDQzYk1BN2Jrc1UKLS0tIGZ4bHZIbU9hbFlxbFlSWFpuZGhQ
            L25JMTMwZ2R6UmV5UmhCTjl3SVJMSTgKVULtsIy8+sD2qMFIc3v+wJMXMyYAY7i4
            42g7vjXBxZAfjhCzfzJmk0nuRabiMl+QpSijSiMO5xcjpv/pXUfc3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T09:33:53Z"
    mac: ENC[AES256_GCM,data:AtkpSWPkCO3io5+uqqND6YZ9NlLtpm3X0dlifqI6MA7anrZCxozo8oGFxUTXDTxHBryHY+VC1+s/pMlYVUNfcr/2rCKYBmVgShkeCOPWeNzjVGTfRJEE+1Hm3v1PcaHKzX1JrIe1dkOb4yHjxLYV/iGxK3Qz4ou+hMqhv1jrsso=,iv:M8UKRpTR0rx23U/4hySbp736W65LStOoTc7zrKcbdGc=,tag:bKgp21jw4xeLpQL4FJ72DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
