apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0iChnaC6lYTcqRQS7Deku5G+VTkvHFitue40MNXA9Rs6yWiMwj9Z6g==,iv:U/SlGfZgP/NXBxnkbs88eUWaakd99UHVetcIJWuJO5s=,tag:JzpY3lxPyksNsAKcLxYxqg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbW9ySDlqclpHNXVkVnRE
            WmFYTU01eURrTk1jd2QybWdaVWtDdnRSb2trCkc3WnlTdHNaVVFIQXhTQitJclVX
            SXBoSitieXlrblJlZWFDMVQvWlVlY1UKLS0tIGEvZ3l3amc2Vlh1SHQrNlhtNUs2
            WHhHWTVTcXJyUVhhVlhscnBzbGVMNm8K003/9nZc6kA9hgQ8y1ly/Gtwy1B72zxt
            20RcSsjqMbfwRLAfis3X1hzOW9jVDR10IoqkneVbyXaoTayO6h7n8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T07:41:41Z"
    mac: ENC[AES256_GCM,data:nh6M6m0LoglfefNrn1znctYzb52RShROKMoH2SYYqku+lJvJr/7nnMq839+LBfMwgr2pOBR1TqnX7ZqK10Jjq6MAOHKri8W+JAF9vR4Lgzh2fyH05+2WPAu3WoTpRLYN39h9MoYqRacUjoFhbm9A9ySTxZwPcISlyvZW8Nt3A9k=,iv:9jFkPNLuDS8EIVaka5cYpM2I2Yy0D1KlclT/uuJURmM=,tag:5ipsqE/H3IWrIaj2YgEFlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
