apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:l+xoSiGTbc+JbL2p0zRcaIiyzSKs2piX1DszDLwRrE6vUT/kTBtovw==,iv:S66SjlmwGnLYQerE8g344DYCLjFhC9vDuVAbeYFci3I=,tag:x7S2rn+QI/HurCl7tSDz/Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWUdqcmc1d2RhRndDcFVu
            MTZHcjgvSkpMa1FwcXZpQlVmODU0WDR2UTFjCmNCajlIVmw0V09nQ2Y1MXR6cTdO
            bld1a3VSZ2lvNFVHODhyUS9ObGhtMmsKLS0tIDg1VFdpTStwb3F6N1lYZzh0cU5W
            aFJYU0xWZk5QOU5lUUFxYUNxWXNuenMKvu0g2K4cCqnpZHvWUZPY0oEe7J5kmBhA
            hmQjVa9QjkZNlL08icD8KISxUSxPKICreI/+WlAcllIjmXPb1rKoMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T07:41:59Z"
    mac: ENC[AES256_GCM,data:UNVvaIi86xDpNjGws1Sx22WDkUSFpdiYumfghNqEKOinwaXnppFcrg8W0bHEVCE9CHoCHxgi1yFMtGha6Gn16P6TX15Dbo0Qh7Ys83dE5xluNnrkKWDNTx7FrKNuaVDhsSr4jLhhBhxnBJVcwrAKdklCSsDLuyCLw2j6nLvbzvE=,iv:EH88/M4OImTplMqaIFK60wPeY4DHA0YZOfLfI3S4IQE=,tag:tQEdB6EgmjtdLy8Wn5d3eQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
