apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2MKxrQFh9Mvjg3NoxHbNbB67E0+pEhcorhJr5Bm/nEwzhVQpjiyDJw==,iv:M0k6rg9GVnCnIzs9wSdpDiftm6KzBna5iF+QXfaQClw=,tag:r5aMKRbmUshn2FDi8gwWRQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeW5Ra0tNdmhvclhaUGRE
            VjhTN2prWUZvWTlvOWRKUE1RV1Fla0NwazJjCmVMa3h6SytIc1o1bDVRZDhmK3JV
            Ni9vTGhJUlV1YlhhVmpxSVM1MlJOdUUKLS0tIFFoS29wN1IrL3lWRzVNUU5Sek9x
            VXZDMlFVTlVyZEl6RXR3a3huanFhVkkKxDjKZ4YIgkW0LHyDR5ij9ad60kk/szfW
            ScB8NQPd84aT1wpRWa57SvnkqRlLzMumAfpw3f26KHV9OJsgME2KoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T10:49:53Z"
    mac: ENC[AES256_GCM,data:x2/PAlqYXdr81wWYxnM+awaLREeIO5N1KiiSgFttDnRjno+5NTqpVebQ+U0dgKNsx5a85VuUoEh/THjsAhO9LJKhSRam93Mc2Sd+CSZW/kd6CyDAcDrq12AvLHui04Jv0c+f3E17TgVpdBLeHtrgZZU0ejOj6QZNvzIlWI6Ndk8=,iv:pwIu3QlE1m1M65hF+v4q7CLAO6BKsRO4YWPnMhm99R0=,tag:7c5SRerOX5PGynZidInnvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
