apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:gcdus/epRFrOu1K/lB15AQLccGUMU4Ic3NKhHVL/WLCoXZXkbObiBQ==,iv:4f2TTDgiv9Q+ZZNivwY4oDYrRF+jirgY5QpFrqkNlT0=,tag:x4iNp2tR1b7Uhzn2we8AHg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MG4xdjVKRlExS0pYbGJ4
            cThpbWNwUC9RZlAyOW1vc29JVmlBOVVpQ0drCmNqTUlkVVY0ZzYzUUNYR3IyV3o5
            OWZ5d09oRUxrd2VNaXBpWDRyeWg1dWsKLS0tIERvZXdzU25LUU1WSkxGb2dQdklI
            RkxPVUhDc0hURzIzRnR0d2xNaGJJS2cKbKDPaNxH+b85LZvJEw1OdNwgcc2elHIB
            e7PwgqKQmiEVEm7j9Ma/rHWGMgYcI9gQKCDD7TcCIfpkIDZn8XQocA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T09:07:01Z"
    mac: ENC[AES256_GCM,data:YjZtFok7te1XWtb0m7LigsFBfg9iIGhwhkzyRFCR8sINYjZwdn+zk2ZevyjsYzRO3MvsFMaCeU8G6tYmVE9Ylmdwo0xGdgKb7lfIcU3R/P27dqK+YqyQK5/sQpk+8TlA2UmrBCOiLSu50EDUgy2i6Ohj6YqghhCDCuvBR6fR+7A=,iv:GX+G4wSByfNygEYGI1OWJV1B5SJakQNk9Z2SHfWsQMw=,tag:L+4KTsshEe0XxtFsw2viGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
