apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DgzFidznHMkucczrcz0Do3Fki3HekLa8/bJXnecAT3EyVOCnHGF7nQ==,iv:AMM3DA02O17LMG9XvvdUfrbWFFZKwGXpBnbowPZcmHk=,tag:zgZpKUXizabh+A9SwtybpQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1elFmNkgwWGZTQmYza3oz
            REFLYjc5dEFFa25yMEhjWVhuTnNyTThaM3pnCmlSWmNDbkI2K3pGTHhlWkJxd0VU
            d0pYZGg4N1hhOGJOTFpGNnBPc0Q2ZHcKLS0tIEFoMnJvcUZWbFJGckRHZEFYUE9j
            MFU1eHR2Q3ZKaklxNXJMSlhQSk9ZNFkKNTIXcWT0x40nLMD0kdz4v5/wf3YFBnaw
            SoCC5CJ8ysDJ28QMrMUvWGYMPFxLnYEsfCdfSIs/ASsaPb1mIKWc6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T07:58:58Z"
    mac: ENC[AES256_GCM,data:xLNcNBQYua+JYGqkta/k0YIxbgtrQ3mieQcHbuFSSWVKijgdeoOWDkCluXkdYYxI2wtV6bCtLPW/6mGFG+s6kkPOUcGrOz6qoN8sSiwfNCO+0F1jY9WqDv3no40kDtZMqIcoX20HRaMxJUTDra8FOylDgIsNkfxC/pamGjG2bHA=,iv:gqoPgc34x3dMIYWgX9QfTO+X3aAdH+SvsCWM30R8v9E=,tag:IT6uoxGWnt0iIpJNpTWheg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
