apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Va9X3d0nfTo4vG2BsspmRB5ol/hNRAQj28gyb31+QjikZUspj0VK3A==,iv:ijn/zfk8WNkCrKnctcLuIBStKIsDF1y27wHT3G7vQAs=,tag:Ahhwd7TWTdimewwWHezv/w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZDJvSFl1U2w4MDk3Zng2
            MDFtU2RXdTYxbzJwY2YvTUlhZVBHTUljekZnCnhMQVZTZlROeTRQUXdlU2N3MlZj
            SVgrdDNBekl3cGtVQnRlUWdpbkdJckEKLS0tIDl5QUI3d01Ya1J3dy93Kyt3ZFVG
            RGNVYU9uMmNNa3g4UjVWTjZBYXlmNEEKKtajsxClVctmc+uTdf3ERrfAWPWkSt/3
            VmTXGYZ/xFclrrRhJKniB6hZ+Fr1+OYK8mVUynWQtG7PmQxWu+XUrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T07:29:19Z"
    mac: ENC[AES256_GCM,data:wMVJ0RS1lGSXfn6cBbh0S2Zsuu++LGIkuQbMWgUB/TphKonp7mAxyB2yAP23D60bwQPCkCdlKLH072oL2fernJ0qu+Ir2P94MgrxqkZ0OHzWrqDwiLDu+85qfZnjRkzzWAaGajVYsPOrcTVdTrfgORy6SlhEiFeUOPXzrTjgquM=,iv:vPr/y0RqFVj8RVXnGYLZdtcJFVEKISxG7t0KBwogzdc=,tag:NsxvPTe2jLf22nyJz/yWdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
