apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:BNW0GM04T1eTKvcqKb1ZRmd1RsjJkSI5EGWrkaxLXQhqzHAdTkf/wA==,iv:dnzR+XjT6+FQJDfm8H3dkO+yCSNJZwS/iwAftuYxKHU=,tag:fI8/tdcRB2iPO8Z326GFuA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraGhUa1NQbmVja2ZzRzd0
            Q2h5MXVIMVBNTkhob3AxY2FoMUxVemtJeVUwCndkUWtaSjJEZXFTK0dKdm5pVGpt
            aWVYdnUrRnlVSjIrREtOdGdHNGFKY2MKLS0tIGgzYUdNSHZ5NmdUUlArdHdUUVpP
            TVNrbWNYc1FNNFh5SXRaWVZLUWFYVzQKh3uBcO3Lw4uj38mMEJsC7ruRjjR8AejK
            r/y3g4nrdGcIq+x4gsuBtLttOEyYTTeAnehoGzHYsHo7E1GHGTpfqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T05:25:19Z"
    mac: ENC[AES256_GCM,data:Te3pqbfRKCrGEJc23vMbsmfSKx80plWR+iF58R39ciklIX9q2ZnwoRnk1e/somRP1ExzxUTDsQl2wd5hQz00b3wex4hiMkofmmVb7fdj3+2Smk8M1E1DCW3NilSv5HUJvopft4qU0hR9/rcyWf4JSofSxp8AfbfE+gM3usJyRNo=,iv:C/SPkNjmpbZB+oM3jtcoRgLmmMxyIO1jvDQdDoLAlTs=,tag:fjGpVCWGodP6HVlEyRxfgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
