apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:8mxSKYYa4MNyQ0bM/pDTtREMn86JprXYnZpyW3EV1MRHkVZIqqXTaw==,iv:1TH0Ny85XG+4izMHQ8DhO5mEVZ0Nt/7bSQnW0ewsSSI=,tag:ZX8Jd++lVbMo8TTBxtR97Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBM1ltQ01nd1dsN1FmTk9h
            cnRDdGg5eXY3WjFnSEFieWthZDUzS1dRbG1zClpXOXhVOFBxNmxiSS85YWpRamdW
            clF5dlJVZmQ3UVdNVVhQdzRUSXFGeXcKLS0tIDBGZTlxa0VHM3ZqTmVxQStiZE8w
            ZUhWWnRVaGFWMkNpZEZjbWsvK1VLbjAK4BrJD1S2O3xOmfOmuUq2mDJRkui6yt2Y
            zFyRiZcT/VCitu9ZXPN/VE5LQDJgzuiZR9Lwz88ac7TKm37wrtA+3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T10:30:47Z"
    mac: ENC[AES256_GCM,data:j18m8NTx6Oy6wefghZY/wGwSKDhHkmaqmopf3kveAmeArWDtX3Aqx5qGk94/4rx7r7KBVc/nXoteKYgfuDxl2Fo0QPToNqmmPd/xGWV8WrSjDCaQ0OeUGK95jzMyGdAtzLqr+/RPedj2zsv1R5j7uf3kN7Vq3HapfWpbd28OATQ=,iv:0wZizGqweuI8ETr+khLD7QWg+/b3zJ1xOegoyLHp6BI=,tag:gDFvX3R82IIy/uUB0a4CsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
