apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:lS5R6xu7CUIc8JDCwTfG73AfKEIABJOsrAJav1xsiYOErmwmUc3wSQ==,iv:VtYI55Uc8OFvlt5s666kNGW2/JOZ3vp+lXWxW7jcs6g=,tag:Z6cNti6928w5GsK2ybz4Pg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YVFFbUZNbHhkVDFLY2ZZ
            OU8zY3pVRTViaWhQZGVLUklFa0l5eTdWdTBBCklhaHNqVkdvRjN5TE5SSzdpWW4z
            MitBYVdZOGVsWVFEb0FobjRNUit1TkEKLS0tIHFhcmd5VkhwUkdtWGVvSXIzWnQx
            T0NocDhVcmNDZXIzajdMRWZhYWZ4RzgKakv2g6VKGyT+U2POGrM3eraxrN65yTtR
            FKDiIKAlw7cIWYDd3o8y5sHgBNsoCZUtKvurYoGUMotmT64TCpiGzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T10:31:15Z"
    mac: ENC[AES256_GCM,data:0pvTWd+AFo/M1HCPP61g85F0x0DTk0FO9HHBiguIK+7putYhybV+OrsG4cG3JLS2xvPvjfXGo9odo0vV/w981IojNG1IQyxbh4VquG7v7OyQ1edyuY9+D6goT90JgtiQ2vHWx9iOisqG7Z4OwR5yAkgy6VMIrqRMZquX2YHK7dg=,iv:xmSHjn5qhbTl7FnMwir19w/CnzlKeCyfIUMq5g021Dc=,tag:ghOfQ/gHQFz1TuoNWX/6RQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
